### PR TITLE
Llmga diffusers

### PR DESCRIPTION
**Pull request by jmikedupont2**
# What does this PR do?

This is a copy of the llma diffusers code rebased onto 0.24 when they copied it over. 

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by ultranity** [comment]
what's the purpose of this PR?

**Comment by ParagEkbote** [comment]
Hi, @jmikedupont2. Is this an accidental PR merge request from your fork of diffusers?

https://github.com/meta-introspector/diffusers/tree/LLMGA_diffusers

**Comment by jmikedupont2** [comment]
I dont need this currently. lets close it for now.

**Comment by jmikedupont2** [comment]
I created this at the time to help answer some question about a rebase.

**Comment by jmikedupont2** [comment]
I remember now, This is a copy of the llma diffusers code rebased onto 0.24 when they copied it over. So that is for creating an accurate diff and attribution

**Pull request closed without merging**
