### PR TITLE
Fix SVD bug (shape of `time_context`)

### PR DESCRIPTION
**Pull request by KimbingNg**
# What does this PR do?

Fixes issue

The data arrangements in [this line](https://github.com/huggingface/diffusers/blob/916d9812a8753c0114ffa7f641da264c3b47fc31/src/diffusers/models/transformers/transformer_temporal.py#L317) and  [this line](https://github.com/huggingface/diffusers/blob/165af7edd3d5d35a77463b399a9d5257af3761db/src/diffusers/models/attention.py#L502)  are inconsistent, which could cause data mismatch during the cross-attention operation in  [this line](https://github.com/huggingface/diffusers/blob/916d9812a8753c0114ffa7f641da264c3b47fc31/src/diffusers/models/transformers/transformer_temporal.py#L359) when `batch_size` > 1.

Thus, it should be `(b h w) n c` instead of `(h w b) n c`. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sayakpaul** [comment]
@DN6 a gentle ping here.

**Comment by DN6** [comment]
@KimbingNg Sorry, but I'm not quite sure what this is solving? The tensor shapes do match?

**Comment by KimbingNg** [comment]
> @KimbingNg Sorry, but I'm not quite sure what this is solving? The tensor shapes do match? Are you referring to the ordering of the elements inside the tensor?

@DN6 Yes, I am referring to the ordering issue.  The data arrangements in [this line](https://github.com/huggingface/diffusers/blob/916d9812a8753c0114ffa7f641da264c3b47fc31/src/diffusers/models/transformers/transformer_temporal.py#L317) and  [this line](https://github.com/huggingface/diffusers/blob/165af7edd3d5d35a77463b399a9d5257af3761db/src/diffusers/models/attention.py#L502)  are inconsistent, which could cause data mismatch during the cross-attention operation in  [this line](https://github.com/huggingface/diffusers/blob/916d9812a8753c0114ffa7f641da264c3b47fc31/src/diffusers/models/transformers/transformer_temporal.py#L359) when `batch_size` > 1

**Comment by DN6** [comment]
Ah I see. Looks okay to merge to me. cc @patil-suraj for visibility. Could you run `make style && make quality` so that the quality checks pass.

**Pull request merged**
