### PR TITLE
[Tests] Improve transformers model test suite coverage - Lumina

### PR DESCRIPTION
**Pull request by saqlain2204**
# What does this PR do?

Improves test suite coverage for Lumina
Part of https://github.com/huggingface/diffusers/issues/8907

@DN6 @sayakpaul

Not all of my tests are passing
I am facing dimension issues:

image

Can someone help me with it please.
Thanks

### CODE REVIEW

**Comment by sayakpaul** [comment]
Sorry, for tests, you have to dive deep a little to fix.

**Comment by saqlain2204** [comment]
Fixed failing tests

**Comment by saqlain2204** [comment]
@sayakpaul . Fixed the dimension issue. Please review the PR and let me know if I should make any changes.
Thanks :)

**Comment by yiyixuxu** [comment]
it seems all the tests are passing now cc @sayakpaul

**Comment by sayakpaul** [comment]
Sorry for the late reply!

**Comment by saqlain2204** [comment]
> Sorry for the late reply!

Sure, not an issue :)

**Pull request merged**
