### PR TITLE
storing original images from dataset

### PR DESCRIPTION
**Pull request by lukovnikov**
Script to store original images from unconditional training datasets as a collection of images. This script can be used before computing FID scores with tools like torch-fidelity.

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
Ok for me to add this, I let you decide though @anton-l !

**Comment by patrickvonplaten** [comment]
Re-ping @anton-l here

**Comment by anton-l** [comment]
Hi @lukovnikov, sorry for the late reply and thank you for adding the example! Just so that we don't leave the script undocumented, could you please add a couple of lines to the unconditional generation README, showing how it can be used in combination with the FID script? :pray:

**Comment by lukovnikov** [comment]
@anton-l yes, will do!

**Pull request closed without merging**
