### PR TITLE
tensor format ort bug fix

### PR DESCRIPTION
**Pull request by prathikr**
Fixes the following error:

```
Traceback (most recent call last):
  File "/workspace/diffusers/examples/unconditional_image_generation/train_unconditional_ort.py", line 276, in <module>
    main(args)
  File "/workspace/diffusers/examples/unconditional_image_generation/train_unconditional_ort.py", line 76, in main
    noise_scheduler = DDPMScheduler(num_train_timesteps=1000, tensor_format="pt")
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/diffusers-0.10.0.dev0-py3.8.egg/diffusers/configuration_utils.py", line 567, in inner_init
    init(self, *args, **init_kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/diffusers-0.10.0.dev0-py3.8.egg/diffusers/schedulers/scheduling_ddpm.py", line 129, in __init__
    predict_epsilon = deprecate("predict_epsilon", "0.11.0", message, take_from=kwargs)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/diffusers-0.10.0.dev0-py3.8.egg/diffusers/utils/deprecation_utils.py", line 43, in deprecate
    raise TypeError(f"{function} in {filename} line {line_number-1} got an unexpected keyword argument `{key}`")
TypeError: __init__ in /opt/conda/envs/ptca/lib/python3.8/site-packages/diffusers-0.10.0.dev0-py3.8.egg/diffusers/schedulers/scheduling_ddpm.py line 128 got an unexpected keyword argument `tensor_format`
```

### CODE REVIEW

**Comment by prathikr** [comment]
@patrickvonplaten @anton-l could I please get a review on this quick bug fix?

**Comment by prathikr** [comment]
@JingyaHuang could you please review this as well?

**Comment by anton-l** [comment]
Hi @prathikr, thanks for the fix! Happy to merge once you reaolve that merge conflict :)

**Review by JingyaHuang — APPROVED** [review]
LGTM!

**Pull request merged**
