### PR TITLE
fix min-snr implementation

### PR DESCRIPTION
**Pull request by ethansmith2000**
# What does this PR do?

Fixes the implementation of min-snr training for v-prediction models

Based on implementation seen here.
https://github.com/kohya-ss/sd-scripts/blob/main/library/custom_train_functions.py#L66

These two graphs show the weight scheme based on timestep from the kohya implementation.
epssnr
v-predsnr

the current implementation in diffusers takes the eps weight and increases everything by + 1, it appears that the +1 should be relocated to the denominator

- Schedulers: @yiyixuxu 
- Training examples: @sayakpaul

### CODE REVIEW

**Review by sayakpaul — COMMENTED** [review]
Thanks for the fix!

Do you want to apply it to the other scripts too?

**Comment by sayakpaul** [comment]
@ethansmith2000 a gentle ping :)

**Comment by yiyixuxu** [comment]
@ethansmith2000 
would you be able to `make style`?  will merge once CI is green and we will ask the community to apply the same change

**Comment by sayakpaul** [comment]
Will merge after the CI is green.

**Review by sayakpaul — APPROVED** [review]

**Pull request merged**
