### PR TITLE
Document magic number

### PR DESCRIPTION
**Pull request by Ghost---Shadow**
I was about to remove the weird number, until I tried to google it.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
I think we should move this configuration variable actually fully to the VAE config (as discussed with @patil-suraj) 

@patil-suraj, would you like to open a PR for it or should I go ahead?

**Comment by patrickvonplaten** [comment]
@Ghost---Shadow it'd be super nice to add your text to the docstring then :-)

**Comment by patil-suraj** [comment]
@patrickvonplaten will open a PR today.

**Comment by patil-suraj** [comment]
@patrickvonplaten PR is here #1860

**Comment by Ghost---Shadow** [comment]
Please close this PR if it is not needed.

**Comment by pcuenca** [comment]
Thanks a lot @Ghost---Shadow! I've added a comment to the other PR so we don't forget to include an explanation similar to yours to the docstring, as Patrick suggested.

**Pull request closed without merging**
