### PR TITLE
[docs] Add safetensors flag

### PR DESCRIPTION
**Pull request by stevhliu**
Based on this internal Slack [discussion](https://huggingface.slack.com/archives/C03HBN1C8CW/p1689947608968689), I think it'd be nice to update existing code samples in the docs with the `use_safetensors=True` flag.

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
Think we also need to check here whether it works for all models or not - are we sure it works for all models (note that not all models have `safetensors` at the moment)

**Comment by sayakpaul** [comment]
> Think we also need to check here whether it works for all models or not - are we sure it works for all models (note that not all models have `safetensors` at the moment)

If not the case, we can leverage the `fp16_safetensors` command to automatically generate the safetensors variants and create pull requests. Guidance on how to use the command is available here: https://github.com/huggingface/diffusers/blob/5ef6b8fa53e78b440abfe5d766a6b99d05a6f29c/src/diffusers/commands/fp16_safetensors.py#L17C19-L17C35. 

@stevhliu let me know if you need any help in checking this.

**Comment by stevhliu** [comment]
Thanks! I've identified several models that don't have `safetensors` so I'll work on converting those :)

**Comment by stevhliu** [comment]
All models used in the code snippets in the docs should have `safetensors` weights now! Any idea how to get the last remaining tests to pass @sayakpaul or @yiyixuxu? I've already tried running `make style` but it didn't help.

**Comment by sayakpaul** [comment]
Hmm, the styling chekcs are popping up at a couple of other places too. These for example: https://github.com/huggingface/diffusers/pull/4441, https://github.com/huggingface/diffusers/pull/4536. 

Same for the scheduler tests too. 

Let me check this internally. 

Cc: @DN6

**Comment by stevhliu** [comment]
Rebased and all tests are passing now! ✨ Should be ready to merge @sayakpaul

**Comment by sayakpaul** [comment]
Let's go then!

**Pull request merged**
