### PR TITLE
[LoRA SD3] add support for lora fusion in sd3

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Fixes https://github.com/huggingface/diffusers/issues/8615

Tested on the PixelArt LoRA too:

```python
from diffusers import DiffusionPipeline
import torch

pipeline = DiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-3-medium-diffusers", torch_dtype=torch.float16
).to("cuda")
pipeline.load_lora_weights(
    "nerijs/pixel-art-medium-128-v0.1",
    weight_name="pixel-art-medium-128-v0.1.safetensors",
    adapter_name="pixel",
)
pipeline.fuse_lora(lora_scale=1.0, safe_fusing=True)

image = pipeline(
    prompt="portrait of a cute happy corgi wearing a party hat, pastel color background, pixel art style",
    negative_prompt="realistic, 3d render, photo",
    num_inference_steps=28,
    guidance_scale=5.0
).images[0]
image.save("sd3_fusion.png")
```

The pup looks cute:

sd3_fusion

Cc: @apolinario

### CODE REVIEW

**Comment by yiyixuxu** [comment]
should we support `set_adapter` here too? https://github.com/huggingface/diffusers/issues/8565

**Comment by sayakpaul** [comment]
@yiyixuxu I can, but I want to tackle that differently by refactoring our LoRA utilities to promote more modularity and reusability. This is something I am planning on starting to work on next from tomorrow itself. Would that be okay? Because adding `set_adapters()` would also require us to add methods like `delete_adapters()` which would largely be copy-pastes. I want to eliminate that in my refactor.,

**Comment by apolinario** [comment]
Maybe we can get `fuse_lora` in and `set_adapter` in another PR?

**Comment by sayakpaul** [comment]
Yeah that is basically I was suggesting.

**Comment by asomoza** [comment]
I didn't test this a lot before, but is it normal that the results are different when the lora is fused and when not?

|loaded|fused|
|---|---|
|||

Other than that, LGTM.

**Review by asomoza — APPROVED** [review]

**Comment by sayakpaul** [comment]
Hmm, weird. Does this happen when you fix the precision to FP32?

**Comment by asomoza** [comment]
can't test with the T5 in FP32, but it doesn't happen in FP32, the results are exactly the same with just loading and with fuse.

**Comment by sayakpaul** [comment]
Then it is expected (and confirms the functional correctness, too) as we have seen in other SDXL LoRAs too.

**Review by yiyixuxu — APPROVED** [review]

**Comment by sayakpaul** [comment]
Okay just realized that the test was already here: `test_simple_inference_with_transformer_fused_with_no_fusion()`. 

https://github.com/huggingface/diffusers/blob/2b945b0a2f1fbdb960ad045f9fd32ab057afb7ab/tests/lora/test_lora_layers_sd3.py#L257

**Pull request merged**
