### PR TITLE
 renamed variable to input_ and output_

### PR DESCRIPTION
**Pull request by vikasmech**
fixing first 2 of this [issues](https://github.com/huggingface/diffusers/issues/198#issuecomment-1262272521)

https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/resnet.py#L37
https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/resnet.py#L54

@patil-suraj Please have a look thanks.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Looks good to me - thanks @vikasmech !

**Review by patrickvonplaten — APPROVED** [review]

**Review by sayakpaul — APPROVED** [review]
LGTM!

Why append the `_`?

**Comment by vikasmech** [comment]
input is also a method, so just to be explicit. and for output_ just maintaining the convention.

**Comment by sayakpaul** [comment]
Not trying to overthink, but maybe `inputs` and `outputs` are a better combination?

**Comment by vikasmech** [comment]
we have one input and output tensor that's why i thought inputs and outputs might not be appropriate. but if it works for i can change it inputs and outputs.

**Comment by vikasmech** [comment]
@ sayakpaul should i change it to, inputs and outputs ?

**Comment by sayakpaul** [comment]
> @sayakpaul should i change it to, inputs and outputs ?

Yes, I think that would be nice.

**Comment by vikasmech** [comment]
@sayakpaul done

**Pull request merged**
