### PR TITLE
Added input pretubation

### PR DESCRIPTION
**Pull request by isamu-isozaki**
I made the issue [here](https://github.com/huggingface/diffusers/issues/3293)

### CODE REVIEW

**Comment by isamu-isozaki** [comment]
Code implementation can be found [here](https://github.com/forever208/DDPM-IP) too.

**Comment by isamu-isozaki** [comment]
My finding with input perturbations:
It makes the model learns general concepts better but can lose some of the details. I haven't done a long-term training so will need to investigate more.

**Comment by isamu-isozaki** [comment]
Honestly, this will be more experimental but gradually decreasing input perturbation as training goes on might be good

**Review by sayakpaul — APPROVED** [review]
LGTM. Do you have any results to share with us? Preliminary results are also fine.

**Comment by isamu-isozaki** [comment]
@sayakpaul Thanks! And, kind of! I mainly tested out my research project to generate images from input images to diffusion models but from the feedback I'm getting in Laion Discord the general sentiment is similar.  My overall thought is it has a hard time with details(because the noise can straight up hide it) but it can be good for the general idea. I can show some results with this +snr which ended up being pretty good

Some examples:

Success case:
Given:


media_images_validation_3028_05efbf5c680acacc4463

input pertubation 0.1:

media_images_validation_3028_a1ae4bb1e743aac76877


input pertubation 0.05:

media_images_validation_3028_a0c977ab93f6a18de704

no input pertubation:

media_images_validation_3028_00893408c64e691cff6e


Failure case:

Given:
media_images_validation_2927_632d10f078c4d6c033fd

input pertubation 0.1:

media_images_validation_2927_4cf038340bfda5bda996

input pertubation 0.05:

media_images_validation_2927_03da91a302e20555302a

no input pertubation:

media_images_validation_2927_d21d70202d679e9cb7ab

**Comment by sayakpaul** [comment]
Thanks a lot for providing those! Also, really glad to know that SNR is working well <3 

I think I have enough to merge this 🚀

**Comment by isamu-isozaki** [comment]
@sayakpaul np! And thanks

**Comment by dathudeptrai** [comment]
@sayakpaul @isamu-isozaki wonder if [LossSecondMomentResampler](https://github.com/forever208/DDPM-IP/blob/30b334a8ea0a1ee1c3978247afcb3ddc59e3f1f9/guided_diffusion/resample.py#L124) is neccessary to reproduce the results ?. For me, `LossSecondMomentResampler` seems more natural compared to `SNR`.

**Comment by isamu-isozaki** [comment]
@dathudeptrai thanks for the comment! Can you give some intuition behind that code?

**Comment by dathudeptrai** [comment]
@isamu-isozaki the idea is quite simple, we will track the history loss corresponding to each timestep, and based on the mean/variance of the history loss, we will adjust the sampling probability of timesteps. So basically, the model will focus more on hard timesteps.

**Comment by dathudeptrai** [comment]
FYI, I have tried my codebase and diffusion models. Mostly this framework and the codebase from guided diffusion. The codebase from guided diffusion gave me better results, especially in the sense of text-image alignment. Seems like the `learned_range` variance type is important. And `diffusers` not yet support `variance_bound` loss.

**Comment by isamu-isozaki** [comment]
@dathudeptrai very cool! I think it'll def be a great addition. Feel free to make a pr for it. I think it's def valuable. Happy to make one too if you are busy!

**Pull request merged**
