### PR TITLE
fix cogvideox autoencoder decode

### PR DESCRIPTION
**Pull request by Xiang-cd**
# What does this PR do?

fix bug of https://github.com/huggingface/diffusers/issues/9568

Fixes # (issue)
it is a simple fix with a line code change.
cogvideox train with mixsure of image and video, so the vae must support reconstruction of image, I fix the image case.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
any one who familiar with vae.
@sayakpaul @DN6 @yiyixuxu

Core library:

- Schedulers: @yiyixuxu
- Pipelines and pipeline callbacks: @yiyixuxu and @asomoza
- Training examples: @sayakpaul
- Docs: @stevhliu and @sayakpaul
- JAX and MPS: @pcuenca
- Audio: @sanchit-gandhi
- General functionalities: @sayakpaul @yiyixuxu @DN6

Integrations:

- deepspeed: HF Trainer/Accelerate: @SunMarc
- PEFT: @sayakpaul @BenjaminBossan

HF projects:

- accelerate: [different repo](https://github.com/huggingface/accelerate)
- datasets: [different repo](https://github.com/huggingface/datasets)
- transformers: [different repo](https://github.com/huggingface/transformers)
- safetensors: [different repo](https://github.com/huggingface/safetensors)

-->

### CODE REVIEW

**Review by a-r-r-o-w — APPROVED** [review]
thank you, this looks correct!

**Comment by a-r-r-o-w** [comment]
The commit was to resolve the merge conflict with the following `conv_cache` line

**Comment by sayakpaul** [comment]
@a-r-r-o-w could we have caught it with some tests? Or not really? In the former case, let's also add a test?

**Comment by a-r-r-o-w** [comment]
> could we have caught it with some tests? Or not really? In the former case, let's also add a test?

Previously, we did not need to decode 1-frame video so this was not required, so testing for this case was not necessary. For Image-to-Video training, however, we need to be able to encode single frames (which is already supported). I think having decode work for a single frame is good to have too, since it could help with debugging.

**Comment by sayakpaul** [comment]
Cool. If you want to feel free to support a test.

**Comment by Xiang-cd** [comment]
thank you, the support of image decode is useful for image-video mix tasks and further research, and this was my first pr to huggingface, hope it could merge. :)

**Comment by yiyixuxu** [comment]
thanks for your PR!! @Xiang-cd

**Pull request merged**
