### PR TITLE
`trained_betas` ignored in some schedulers

### PR DESCRIPTION
**Pull request by vishnu-anirudh**
Hello

I was going through the code repo and I observed how the `self.betas` is being assigned. I don't know if what I observed is correct, so I wanted to raise this PR to clarify this.

Without the changes made in this PR, it seems the following code is not useful 
```
if trained_betas is not None:
    self.betas = np.asarray(trained_betas)
```

This is because `self.betas` is assigned again as part of the if-statement below. And if `beta_schedule` doesn't exist then an error is raised. So it doesn't matter if `self.betas` is assigned to `trained_betas`.

As a note, certain schedulers such as [FlaxDDIMScheduler](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddim_flax.py#L124), [DDPMScheduler](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm.py#L120) and [FlaxDDPMScheduler](https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_ddpm_flax.py#L117) seem to have the right implementation.

If you think this is not right, I am happy to close this PR.

### CODE REVIEW

**Comment by pcuenca** [comment]
This does look like a bug to me, when `trained_betas` is used instead of one of the beta schedules. I updated the title, I hope that's ok with you @vishnu-anirudh.

Requesting review from others in case I'm missing something.

**Comment by kashif** [comment]
@vishnu-anirudh nice catch!

**Review by pcuenca — APPROVED** [review]

**Comment by kashif** [comment]
Although the issue still remains if trained betas and schedule type is passed no?

**Comment by vishnu-anirudh** [comment]
> Although the issue still remains if trained betas and schedule type is passed no?

From the code, it seems we choose `trained_betas` by default. Otherwise, we initialise `self.betas` based on `beta_schedule`.

**Comment by patrickvonplaten** [comment]
I think we are intertwining two things here:
- The warning message, which actually already has been downgraded to an info message here: https://github.com/huggingface/diffusers/blob/c070e5f0c57037c879a8ec25f870f97246183212/src/diffusers/configuration_utils.py#L315
- This PR which is nice in itself! 

This PR looks good to me :-)

**Review by patrickvonplaten — APPROVED** [review]

**Comment by vishnu-anirudh** [comment]
Hello (cc @patrickvonplaten)
Can this be merged if there are no more changes (as I don't have the rights to do it).

Thanks in advance.

**Pull request merged**
