### PR TITLE
[SDXL DreamBooth LoRA] improve test image quality

### PR DESCRIPTION
**Pull request by Xargonus**
# What does this PR do?

This PR fixes poor quality of test images, generated at the end of the SDXL DreamBooth LoRA training example script.

At the end of SDXL DreamBooth LoRA training, the script generates sample test images. The number of inference steps for this generation is currently set to 25, which is too low for the used DDPMScheduler, resulting in poor-quality images.

The validation images that are generated every n-th epoch use the same DDPMScheduler and the default number of 50 inference steps, which results in a better image quality. This PR makes the change to also use the default number of 50 inference steps during test time.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul @patrickvonplaten

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
I don't really think this is necessary - one can always manually run validation if necessary

**Comment by Xargonus** [comment]
Yes, one can always manually run validation after training finishes.

Why not make it easier for the users of this script and generate good-quality images during the final inference, just like we do during training for validation images?

**Comment by patrickvonplaten** [comment]
> Yes, one can always manually run validation after training finishes.
> 
> Why not make it easier for the users of this script and generate good-quality images during the final inference, just like we do during training for validation images?
> 
> Another solution is to just remove the final inference altogether. The fact that there is a noticeable difference in the quality of validation and test images is also confusing. Users might attribute it to overfitting, when in fact the difference in inference arguments is at fault.

I hear your point - I would prefer though to put a big disclaimer on the README instead of overengineering the example scripts (after all they stay example scripts and are build to be easy to follow/understand)

**Comment by Xargonus** [comment]
I agree that the script shouldn't be overengineered. It should be a good example of how to DreamBooth.

The proposed change makes the script simpler and in my opinion, fixes a bug. The final inference has inappropriately chosen parameters.

**Comment by Xargonus** [comment]
Why not merge this? The proposed change makes the script simpler, easier to understand and in my opinion, fixes a bug.

**Comment by bghira** [comment]
let's move these to parse_args and have sensible defaults for `--validation_num_inference_steps` and even `--validation_guidance_scale`, because most likely these will be different for any given tuning style.

for example, the default cfg of 7.5 is much too high for Epsilon models after dreambooth.

The default cfg of 7.5 is too low for v_prediction models after dreambooth.

additionally, it's not clear why we use DDPM for sampling when that isn't even the same scheduler in the model's config.

**Pull request closed without merging**
