### PR TITLE
 Notebooks for Community Scripts Examples

### PR DESCRIPTION
**Pull request by ParagEkbote**
# What does this PR do?
I've added 3 new Jupyter notebooks for IP Adapter Negative Noise, Asymmetric Tiling and Prompting Scheduling Callback. Additionally, I have improved the Prompting Scheduling Callback Script by a tiny bit. Are any more required changes?

Please let me know, and I will make the necessary changes as required.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [  ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.

- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [  ] Did you write any new necessary tests?

## Who can review?

Core library:

- Training examples: @sayakpaul
- Docs: @stevhliu and @sayakpaul

### CODE REVIEW

**Comment by sayakpaul** [comment]
Thanks for your work but I think the notebooks should go to: https://github.com/huggingface/notebooks

Cc: @stevhliu

**Comment by ParagEkbote** [comment]
@sayakpaul I have created the 3 notebooks in this repository because I believe there is scope mentioned for them here: https://github.com/huggingface/diffusers/blob/main/examples/community/README_community_scripts.md

Also, if I wanted to contribute notebooks to additional community examples mentioned below, where can I add them:
https://github.com/huggingface/diffusers/blob/main/examples/community/README.md

**Comment by stevhliu** [comment]
Yeah I think it'd be best to keep the notebooks in https://github.com/huggingface/notebooks and add a link in the Colab column for them from there (likewise for the additional community notebook examples).

**Comment by ParagEkbote** [comment]
I'll add the notebooks on the mentioned repo and update the branch accordingly.

cc: @stevhliu

**Comment by ParagEkbote** [comment]
I have updated the ReadMe as per the given feedback.

Could you please review?

cc: @stevhliu

**Review by stevhliu — APPROVED** [review]
Cool, thanks again for your contribution!

**Comment by ParagEkbote** [comment]
I have updated the ReadMe as per the given feedback.

Could you please review?

cc: @sayakpaul

**Comment by yiyixuxu** [comment]
thanks very much for your contribution! @ParagEkbote

**Pull request merged**
