### PR TITLE
[Alpha-VLLM Team] Feat: added fused qkv and chunked ffn

### PR DESCRIPTION
**Pull request by PommesPeter**
# What does this PR do?

Fixes #8652 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by yiyixuxu** [comment]
so I think you will actually need to wrap your feedforward layers inside `_chunked_feed_forward` in order for it to work https://github.com/huggingface/diffusers/blob/673eb60f1c4d971e1a577bed767053e50578b461/src/diffusers/models/attention.py#L182
(sorry I think it is our fault, I think the example PR we gave you did not do this either) 

i see very little memory saving though with this method cc @sayakpaul

**Comment by sayakpaul** [comment]
> i see very little memory saving though with this method

Yeah, it was very expected. It was probably because of parameter-flop patterns. For other models like SDXL, Stable Video, etc., where transformer blocks are used alongside conv blocks, we see quite nice memory savings with chunked feedforward. What is even more interesting is that during my initial studies with the 800M SD3 variant, the savings were evident but they diminished with the 2B variant. 

@PommesPeter have you played around with the `dim` and `chunk_size` parameters of `enable_forward_chunking()`? Usually, setting `dim` to 1 is necessary to achieve more memory savings. 

For the QKV fusion, let's maybe wait for https://github.com/huggingface/diffusers/pull/8829/ to get merged?

**Comment by PommesPeter** [comment]
> > i see very little memory saving though with this method
> 
> Yeah, it was very expected. It was probably because of parameter-flop patterns. For other models like SDXL, Stable Video, etc., where transformer blocks are used alongside conv blocks, we see quite nice memory savings with chunked feedforward. What is even more interesting is that during my initial studies with the 800M SD3 variant, the savings were evident but they diminished with the 2B variant.
> 
> @PommesPeter have you played around with the `dim` and `chunk_size` parameters of `enable_forward_chunking()`? Usually, setting `dim` to 1 is necessary to achieve more memory savings.
> 
> For the QKV fusion, let's maybe wait for #8829 to get merged?
> 
> Apologies for the fault on our part.

I haven't tried chunked ffn before. I should play it with different parameters.

For qkv fused:
I would like to wait the #8829 when it has been merged.

**Comment by sayakpaul** [comment]
@PommesPeter hey there :) 

https://github.com/huggingface/diffusers/pull/8829 is now merged. Would you like to revive this PR again?

**Comment by PommesPeter** [comment]
> @PommesPeter hey there :)
> 
> #8829 is now merged. Would you like to revive this PR again?

Okay, I will revive this PR.

**Comment by yiyixuxu** [comment]
closing this since these techniques are not particularly effective here

**Pull request closed without merging**
