### PR TITLE
Enable Intel optimizations for textual inversion with IPEX

### PR DESCRIPTION
**Pull request by hshen14**
In this PR, Intel optimizations for textual inversion are enabled through IPEX. It can support both single and multi-node distributed training. It also supports BF16 if the example runs with 4th gen Intel Xeon Scalable Processor.

### CODE REVIEW

**Comment by hshen14** [comment]
Hi @anton-l @patrickvonplaten please review. Thanks.

**Review by anton-l — COMMENTED** [review]
Hi @hshen14, thank you for the example! Could you add some benchmark results for training with `ipex` vs `pytorch+accelerate`? Distributed training on CPUs is quite an exotic use case for Textual Inversion, so I'm also curious how much it would benefit single-node training :)  
Would be great if the speedup can be achieved on AWS/GCP/Azure VMs and consumer hardware! 

Also I see that you only optimize the text encoder, is there a reason to focus on it instead of the denoising UNet?

cc @mfuntowicz @echarlaix @patil-suraj

**Comment by hshen14** [comment]
> Hi @hshen14, thank you for the example! Could you add some benchmark results for training with `ipex` vs `pytorch+accelerate`? Distributed training on CPUs is quite an exotic use case for Textual Inversion, so I'm also curious how much it would benefit single-node training :) Would be great if the speedup can be achieved on AWS/GCP/Azure VMs and consumer hardware!
> 
> Also I see that you only optimize the text encoder, is there a reason to focus on it instead of the denoising UNet?
> 
> cc @mfuntowicz @echarlaix @patil-suraj

Thanks @anton-l for your review. Yes, I will combine accelerate and IPEX to maximize the potential optimizations. Enabling IPEX optimization for text encoder is my first step and I plan to enable UNET and vae later to get additional speedup at least for forward and backward by data.

**Comment by patil-suraj** [comment]
Thanks a lot for the PR @hshen14 , pretty much the same comment as @anton-l , would be nice to see some benchmarks.

**Comment by patrickvonplaten** [comment]
Hey @hshen14,

After some discussion we decided that we cannot maintain all such training scripts in the core examples. Could you please instead move the example script to the `examples/research_folder` with a README stating that the script is maintained by you maybe? :-) 

Sadly, we're simply not able to dive into IPEX code at the moment. I hope that this is ok for you!

**Comment by hshen14** [comment]
> Hey @hshen14,
> 
> After some discussion we decided that we cannot maintain all such training scripts in the core examples. Could you please instead move the example script to the `examples/research_folder` with a README stating that the script is maintained by you maybe? :-)
> 
> Sadly, we're simply not able to dive into IPEX code at the moment. I hope that this is ok for you!

Sounds good. Thanks for letting me know. Let me try this.

**Comment by hshen14** [comment]
Close this one and open https://github.com/huggingface/diffusers/pull/1579 per comments.

**Pull request closed without merging**
