### PR TITLE
offload the optional module `image_encoder`

### PR DESCRIPTION
**Pull request by yiyixuxu**
add `image_encoder` to `model_cpu_offload_seq` for all relevant pipelinees

### CODE REVIEW

**Comment by charchit7** [comment]
@yiyixuxu any more such edit's left? Happy to help!

**Review by patrickvonplaten — APPROVED** [review]
Nice job! This also works just fine in case `image_encoder` is not defined. Can we maybe add one test?

**Comment by yiyixuxu** [comment]
@patrickvonplaten 
The case where `image_encoder` is not defined is already tested with `test_model_cpu_offload_forward_pass`
I added a IP-adaper test for the case where image_encoder is defined

**Comment by yiyixuxu** [comment]
cc @sayakpaul for a final review

**Review by sayakpaul — APPROVED** [review]
Thank you!

**Comment by patrickvonplaten** [comment]
Good to merge once merge conflicts are resolved here

**Pull request merged**
