### PR TITLE
[Community Pipeline] SDXL T2I Adapter Inpainting

### LINKED ISSUE #5481: SDXL T2I Adapter Inpainting Support
### Model/Pipeline/Scheduler description

Greetings contributors!

I was wondering if `diffusers` currently supports inpainting with T2I adapters (with SDXL in my case)? If not, would a new pipeline be required to achieve this functionality, or is it not technically possible?

Thanks!

### PR DESCRIPTION
**Pull request by jakebabbidge**
# What does this PR do?
Fixes #5481 ✅

Adds a custom pipeline "stable_diffusion_xl_adapter_inpaint" (StableDiffusionXLAdapterInpaintPipeline) which adds support for inpainting with T2I Adapters and the base SDXL model. 👷

Not sure if the community pipeline will work with the `diffusers` `custom_pipeline` fetching system built in, as i'm making updates to the `t2iadapterxl` branch. Would love clarity on how we can get this pipeline usable by others 😄

Thanks in advance!

Example snippet taken from my pipeline's docs:
```py
>>> import torch
>>> from diffusers import DiffusionPipeline, T2IAdapter
>>> from diffusers.utils import load_image
>>> from PIL import Image

>>> adapter = T2IAdapter.from_pretrained(
... 	"TencentARC/t2i-adapter-sketch-sdxl-1.0", torch_dtype=torch.float16, variant="fp16"
... ).to("cuda")

>>> pipe = DiffusionPipeline.from_pretrained(
... 	"stabilityai/stable-diffusion-xl-base-1.0",
... 	torch_dtype=torch.float16,
... 	variant="fp16",
... 	use_safetensors=True,
... 	custom_pipeline="stable_diffusion_xl_adapter_inpaint",
... 	adapter=adapter
... ).to("cuda")

>>> image = Image.open(image_path).convert("RGB")
>>> mask = Image.open(mask_path).convert("RGB")
>>> adapter_sketch = Image.open(adapter_sketch_path).convert("RGB")

>>> result_image = pipe(
... 	image=image,
... 	mask_image=mask,
... 	adapter_image=adapter_sketch,
... 	prompt="a photo of a dog in real world, high quality",
... 	negative_prompt="extra digit, fewer digits, cropped, worst quality, low quality",
...	num_inference_steps=50
... ).images[0]
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

Pipelines:  @patrickvonplaten and @sayakpaul

### CODE REVIEW

**Comment by jakebabbidge** [comment]
If we can't find a way to allow other users to use this pipeline via the repo's `examples/community`, please let me know, and i can take the HuggingFace model repo approach instead 😄

**Comment by sayakpaul** [comment]
Thanks for your PR! Could you also share some results you achieved with this pipeline? This might spark a lot of interest in the community.

**Comment by jakebabbidge** [comment]
Sure thing!

Here's a basic demo i was able to quickly create. In this instance the controlnet sketch image is quite poorly made as it doesn't include any background elements, but you can see it still did a pretty good job!

example

Cheers!

**Comment by sayakpaul** [comment]
> Here's a basic demo i was able to quickly create. In this instance the controlnet sketch image is quite poorly made as it doesn't include any background elements, but you can see it still did a pretty good job!

Sorry, I didn't understand. Confused why ControlNet is mentioned and "it still did a pretty good job" is said at the same time. I can clearly see that the RHS image is quite nice and has all the background features preserved. Could you please clarify?

**Comment by jakebabbidge** [comment]
🤦 Sorry, i totally meant "adapter sketch image" not "controlnet sketch image".

I was also referring to the fact that the adapter sketch image (the black and white guidance dog sketch) does not include any background details like the back of the chair etc, and the model still did a great job preserving the background details 😄

**Comment by sayakpaul** [comment]
Wow. Ccing @patrickvonplaten @patil-suraj here. 

I think it could make sense to have it as a core pipeline no? The results are quite nice!

**Comment by jakebabbidge** [comment]
I have also just added this pipeline to HuggingFace under `jakebabbidge/sdxl-adapter-inpaint` if we can't solve a way to get this merged into `main` 😄

**Comment by canache** [comment]
I tried using this model, but it threw errors when I tried to load a LORA.
The error message said: "AttributeError: 'ModuleList' object has no attribute '4'."

Do you think it might have something to do with this:
https://github.com/huggingface/diffusers/pull/4512

Thanks for the great work, by the way!

**Comment by jakebabbidge** [comment]
Sorry @canache... i didn't test it with a LORA! I feel that i'm not expert enough to tackle that one, and luckily my use case didn't require that 😅

**Review by patrickvonplaten — COMMENTED** [review]
Can we also add a short description to https://github.com/huggingface/diffusers/blob/main/examples/community/README.md?

**Pull request closed without merging**
