### PR TITLE
Added `diffusers` to conda-forge and updated README for installation instruction

### LINKED ISSUE #126: Add a `conda` install option for `diffusers`
It will be helpful to have `diffusers` added `conda-forge` channel and install with conda.

:point_right: I have started the work on it already.

- https://github.com/conda-forge/staged-recipes/pull/19751

Once the PR is merged, the library can be installed as:

```sh
conda install -c conda-forge diffusers
```

### PR DESCRIPTION
**Pull request by sugatoray**
Since adding a package to conda-forge cannot be done from this repository, it was taken care of by the following PR.

- https://github.com/conda-forge/staged-recipes/pull/19751

This PR updates the README to add conda install instruction.

Closes #126

### CODE REVIEW

**Comment by sugatoray** [comment]
- Feedstock: https://github.com/conda-forge/diffusers-feedstock
- Conda: https://anaconda.org/conda-forge/diffusers

It is available on conda-forge now!

```sh
$ conda search -c conda-forge diffusers
Loading channels: done
# Name                       Version           Build  Channel             
diffusers                      0.1.2    pyhd8ed1ab_0  conda-forge 
```

**Comment by sugatoray** [comment]
cc: @StoneCypher @patrickvonplaten

**Comment by natolambert** [comment]
(Accidentally ran the checks on my phone poking around l, though this looks like a useful addition) 🤦‍♂️

**Comment by sugatoray** [comment]
Hi @natolambert,

I am not clear on if I have any actionable before this PR could be merged. Please let me know. Thank you.

**Comment by natolambert** [comment]
I think @patrickvonplaten will look this week, or I can look then too. It was a really big push before the initial release, but I think this should be merged in shortly :)

**Comment by patrickvonplaten** [comment]
Thanks a lot for your PR @sugatoray - @anton-l @patil-suraj can you maybe handle this? Also cc @LysandreJik

**Comment by anton-l** [comment]
Hi @sugatoray, sorry for the late reply! One request before we update the links: could you please add me and @patrickvonplaten to the maintainers list? That way we'll be able to trigger the conda package update right after we release a new version on PyPi (e.g. there's a 0.1.3 already). Thank you!

**Comment by sugatoray** [comment]
@anton-l Sure. Will add both of you as co-maintainers. 

👉 Typically, there is a conda-forge bot that picks up new PyPI versions and pushes PR to the repository. There's also another bot that automerges when the conda-forge builds pass successfully. 

👉 The only time you would need to manually intervene is when the listed dependencies on the conda-forge feedstock recipe are incomplete or need some manual tweaking/updating.

**Comment by anton-l** [comment]
Awesome, thank you! :hugs:

**Comment by sugatoray** [comment]
This PR will add you as co-maintainers.

- https://github.com/conda-forge/diffusers-feedstock/pull/4

**Pull request merged**
