### PR TITLE
[WIP] Add Pipeline.push_to_hub

### PR DESCRIPTION
**Pull request by anton-l**
Adds a hub mixin for models and pipelines

### CODE REVIEW

**Comment by anton-l** [comment]
Closing as a non-essential proposal for now, but feel free to reopen/reuse!

**Comment by patrickvonplaten** [comment]
Let's keep this alive. It's really important IMO to be able to push the pipeline to the Hub for things like "in-training" evaluations via the Hub inference API.

**Comment by ParagEkbote** [comment]
Since this feature already has been implemented in diffusers, can this PR be closed to declutter?

Link: https://huggingface.co/docs/diffusers/main/en/using-diffusers/push_to_hub#push-files-to-the-hub

image

cc: @yiyixuxu

**Comment by yiyixuxu** [comment]
thanks @ParagEkbote 
yes closing!

**Pull request closed without merging**
