### PR TITLE
[Community Pipeline] Checkpoint Merger based on Automatic1111

### PR DESCRIPTION
**Pull request by Abhinay1997**
The checkpoint merger pipeline based on the discussion at #877.

Tested the checkpoint merger for the case with two checkpoints.

### CODE REVIEW

**Comment by Abhinay1997** [comment]
@patrickvonplaten could you have a look at this once you're free ?

**Comment by patrickvonplaten** [comment]
This looks very cool! Could you add an entry to the table here and also add a section of how to use your community pipeline? :-) 

https://github.com/huggingface/diffusers/blob/main/examples/community/README.md#community-examples

**Comment by hafriedlander** [comment]
@Abhinay1997 is this a clean redevelopment, or does it use code from the Automatic1111 repository?

Unfortunately Automatic1111 (deliberately) does not have a license for his code, and it can't be legally used in other projects.

**Comment by Abhinay1997** [comment]
@hafriedlander, only the interpolation functions are from Automatic1111 but they are originally from Wikipedia. Last I checked, Automatic1111 had changed their code in the current version.

**Comment by Abhinay1997** [comment]
Meanwhile, I have added the docs in the README

**Comment by patrickvonplaten** [comment]
Thanks!

**Pull request merged**
