### PR TITLE
fix the parameter naming in `self.downsamplers`

### PR DESCRIPTION
**Pull request by chenguolin**
It has been discussed in issue #943.

### CODE REVIEW

**Comment by geekinglcq** [comment]
Thanks for fixing it~ Just found the same bug when I tried to train a model with `layers_per_block=1`. The naming bug will cause the shape mismatch problem.

**Comment by patrickvonplaten** [comment]
Thanks a lot for the PR - I'll quickly have to run the slow tests on this one to make sure it doesn't break anything

**Comment by chenguolin** [comment]
Hi @patrickvonplaten, just a reminder to merge this PR if it doesn't break anything :)

**Comment by patrickvonplaten** [comment]
Hey @chenguolin,

I'm very sorry to have been so slow here - please feel free to revert the deletion of your branch - this PR is still very much relevant :-)

**Comment by chenguolin** [comment]
Hi @patrickvonplaten,

I'm sorry that I deleted my branch of this PR by mistake (I'm not really familiar with the operations in GitHub) :(. I've opened another duplicate PR #1108. Thanks.

**Pull request closed without merging**
