### PR TITLE
[Flax] from_flax help ⛑

### PR DESCRIPTION
**Pull request by camenduru**
I trained plushies with tpu and now I need convert to pytorch I tried this [code ](https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_flax_pytorch_utils.py#L242-L352)from transformers but I failed 🤪 help 🚑
also https://github.com/huggingface/diffusers/issues/1161

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @camenduru,

Good point this is definitely a feature we should add. I might find some time by end of next week. Maybe also cc @pcuenca

**Comment by jorahn** [comment]
Don't want to step on anyones toes, just to make sure that time is allocated efficiently. I've created a PR #1241 from my local progress, that takes this a bit further. We should try to align our efforts.

**Comment by camenduru** [comment]
thanks @jorahn ❤ your PR looks better 🤩

**Comment by jorahn** [comment]
Appreciated :) let me know if you have any ideas to get my PR to work for the full pipeline.

**Comment by camenduru** [comment]
📑 https://github.com/google/flax/blob/main/docs/advanced_topics/convert_pytorch_to_flax.rst

**Comment by camenduru** [comment]
maybe we need adapt `load_flax_weights_in_pytorch_model` for each msgpack I don't know how 🙄 @jorahn do you have any idea?

https://github.com/huggingface/diffusers/blob/89c969b14bfc80c2043d86761c1cf305c6d35262/src/diffusers/modeling_pytorch_flax_utils.py#L103-L107

all different 🧩

unet
```
('conv_in', 'bias')
('conv_in', 'kernel')
('conv_norm_out', 'bias')
('conv_norm_out', 'scale')
('conv_out', 'bias')
('conv_out', 'kernel')
```
vae
```
('decoder', 'conv_in', 'bias')
('decoder', 'conv_in', 'kernel')
('decoder', 'conv_norm_out', 'bias')
('decoder', 'conv_norm_out', 'scale')
('decoder', 'conv_out', 'bias')
('decoder', 'conv_out', 'kernel')
```
text_encoder
```
('text_model', 'embeddings', 'token_embedding', 'embedding')
('text_model', 'embeddings', 'position_embedding', 'embedding')
('text_model', 'encoder', 'layers', '0', 'self_attn', 'k_proj', 'kernel')
('text_model', 'encoder', 'layers', '0', 'self_attn', 'k_proj', 'bias')
```

**Comment by patrickvonplaten** [comment]
@camenduru should we focus on #1241 and maybe close this one?

**Comment by camenduru** [comment]
download

**Pull request closed without merging**
