### PR TITLE
[Tests] Speed up panorama tests

### PR DESCRIPTION
**Pull request by sayakpaul**
Summary of the changes: 

* Reduced the kinds of batch sizes for testing methods like `test_inference_batch_consistent()`, `test_inference_batch_single_identical()`.
* Reduced the size of the UNet.
* Reduced the number of inference steps.

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
Great!

**Comment by patrickvonplaten** [comment]
Some tests seem to be missing the `batch_size` argument

**Comment by sayakpaul** [comment]
> Some tests seem to be missing the `batch_size` argument

The latest changes should fix that.

**Comment by sayakpaul** [comment]
@patrickvonplaten seems to have been fixed :)

**Pull request merged**
