### PR TITLE
changed positional parameters to named parameters like in docs

### PR DESCRIPTION
**Pull request by patrykbart**
## Description

Now this conversion script has named parameters like in documentation at the top of the file.

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul @linoytsaban @apolinario

### CODE REVIEW

**Comment by sayakpaul** [comment]
@linoytsaban could you give this a look?

**Review by linoytsaban — COMMENTED** [review]
looks alright to me :)
I think replacing `narge="?"` with `required=False` is pretty equivalent, since there is no specified default value, no? 🤔

**Comment by patrykbart** [comment]
> looks alright to me :) I think replacing `narge="?"` with `required=False` is pretty equivalent, since there is no specified default value, no? 🤔

I think so, In my opinion it's just more readable and consistent :)

**Review by linoytsaban — APPROVED** [review]
LGTM @sayakpaul :)

**Pull request merged**
