### PR TITLE
[`IP-Adapter`] Fix IP-Adapter Support and Refactor Callback for `StableDiffusionPanoramaPipeline`

### LINKED ISSUE #7064: [ip-adapter]fix IP-adapter support for SAG, panorama pipeline
We have added a `IPAdapterTexterMixin` https://github.com/huggingface/diffusers/pull/6862. However, we have discovered that the IP adapter support was not implemented correctly in the following pipelines: 

- StableDiffusionSAGPipeline
- StableDiffusionPanoramaPipeline

If anyone is interested in fixing the IP-adapter support for these pipelines, please feel free to give it a try!

cc @a-r-r-o-w here, let me know if I missed any pipeline here

### PR DESCRIPTION
**Pull request by standardAI**
Fixes #7064 for `StableDiffusionPanoramaPipeline`.
It looks like most of the work has already been done. `StableDiffusionPanoramaPipeline` class seems to pass the tests of `IPAdapterTesterMixin` in my local setup.

Thanks for this opportunity!
@yiyixuxu

### CODE REVIEW

**Review by yiyixuxu — COMMENTED** [review]
oh thanks!
we also need to dd the `callback_on_step_end` like how it's done here https://github.com/huggingface/diffusers/pull/7149

**Comment by standardAI** [comment]
Hi @a-r-r-o-w! When I set `device="cuda"` at [here](https://github.com/huggingface/diffusers/blob/5dd8e04d4b5ff57dde63a6cb080f936fdfb56a96/tests/pipelines/test_pipelines_common.py#L232), this PR passes the tests; but we need to use CPU for these fast tests to pass. Thus, [the PR cannot pass the tests](https://github.com/huggingface/diffusers/actions/runs/8215907149/job/22495801364?pr=7262#step:6:13147). If the problem is on my side, just say so; I try to find what it is.

**Comment by standardAI** [comment]
Hi @a-r-r-o-w! When I set `device="cuda"` at [here](https://github.com/huggingface/diffusers/blob/5dd8e04d4b5ff57dde63a6cb080f936fdfb56a96/tests/pipelines/test_pipelines_common.py#L232), this PR passes the tests; but we need to use CPU for these fast tests to pass. Thus, [the PR cannot pass the tests](https://github.com/huggingface/diffusers/actions/runs/8215907149/job/22495801364?pr=7262#step:6:13147). If the problem is on my side, just say so; I try to find what it is.

**Comment by standardAI** [comment]
`StableDiffusionPanoramaPipeline` class passes the tests of `IPAdapterTesterMixin` when I set `device="cuda").to(torch_device)` [here](https://github.com/huggingface/diffusers/blob/5dd8e04d4b5ff57dde63a6cb080f936fdfb56a96/tests/pipelines/test_pipelines_common.py#L232). But when `device="cpu"` as expected for fast CPU tests, it cannot pass. I am currently working on this.

**Comment by standardAI** [comment]
The last commit seems to resolve the issue.

**Comment by standardAI** [comment]
@yiyixuxu Here is ready for a review.

**Comment by yiyixuxu** [comment]
can you make sure the quality tests pass?

**Comment by standardAI** [comment]
Done.

**Comment by standardAI** [comment]
Done!

**Comment by standardAI** [comment]
There were 2 errors. One went away when I merged with the main branch and the other seems irrelevant to me in terms of this PR.

**Comment by standardAI** [comment]
Thanks for merging!

**Pull request merged**
