### PR TITLE
ort integration

### PR DESCRIPTION
**Pull request by prathikr**
Integrated ORTModule into examples/unconditional_image_generation/train_unconditional.py

Note: We required a change to unet_2d.py to return a raw tensor as output of the model instead of a dataclass. I verified that the changes to remove this dataclass do not affect baseline execution. 

test command: 
```
accelerate launch train_unconditional.py \
  --dataset_name="huggan/flowers-102-categories" \
  --resolution=64 \
  --output_dir="ddpm-ema-flowers-64" \
  --train_batch_size=16 \
  --num_epochs=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-4 \
  --lr_warmup_steps=500 \
  --mixed_precision=no \
  --ort
  ```

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Leaving it up to @anton-l , maybe you could take a look whenever you find some time :-)

**Comment by prathikr** [comment]
Hi @anton-l, I've tried rebasing off main a couple times to get the CI tests running but for some reason it says I need to resolve conflicts in tests/test_models_unet.py even though I believe it is merge-able. Could you please let me know what I am doing wrong? Thank you.

**Comment by patrickvonplaten** [comment]
Hey @prathikr,

Thanks a lot for the PR. We are trying to keep our examples as easy to understand as possible and I think we don't want to mix ORT and PyTorch in the same training example to keep the PyTorch simple and independent from ORT.

Could we maybe instead add a ORT compatible as its own standalone script?

Cc @anton-l

**Comment by prathikr** [comment]
Hi @patrickvonplaten ,

Absolutely, I just made the changes but the CI still seems to have issues with tests/test_models_unet.py. I'd like to highlight my changes to the unet_2d.py class. Is this safe to do? I've done my best to verify that removing the dataclass for the output of forward() doesn't affect downstream operators if .sample is removed, but it might be best to have someone more familiar with the codebase confirm.

Thanks again,
Prathik

**Comment by prathikr** [comment]
@JingyaHuang could you please take a look at this PR?

**Review by patrickvonplaten — COMMENTED** [review]
This looks good to me - @anton-l what do you think?

**Comment by patrickvonplaten** [comment]
@prathikr however it seems like the commit history of this PR is a bit messed up - could you maybe open a new PR with the intended changes :sweat_smile: - thanks!

**Comment by prathikr** [comment]
@patrickvonplaten I've created a new PR and tagged you three #1110

**Pull request closed without merging**
