### PR TITLE
resolve an error when floats are provided for resolution values

### PR DESCRIPTION
**Pull request by bghira**
# What does this PR do?

Inside prepare_latents, it will crash if a float was inadvertently passed to the pipeline.

This will cast the input values to integers, allowing these situations to proceed.

```
TypeError: randn(): argument 'size' failed to unpack the object at pos 3 with error "type must be tuple of ints,but got float"
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by DN6** [comment]
@bghira The quality checks are likely failing because the `prepare_latents` method is copied in other pipelines. One option is to apply casting before passing to `prepare_latents` or change the affected pipelines to cast inside the method. You can run `python utils/check_copies.py` to find the affected files. 

CI message should have been more helpful here. Will take a look into it.

**Comment by bghira** [comment]
@DN6 thanks usually i push a proposed change to get feedback before i copy to the rest. that's done now

**Review by DN6 — COMMENTED** [review]
LGTM. Good to merge once tests pass.

**Comment by DN6** [comment]
@bghira I think some extra files got added here? The examples directory wasn't in the PR earlier?

**Comment by bghira** [comment]
you said to run make quality

**Comment by yiyixuxu** [comment]
should we update the dependencies
i.e. `pip install -e ".[quality]"` again?

**Comment by bghira** [comment]
i don't think there's an issue with those deps per se it's just that the main branch doesn't have the formatting the way it wanted.

**Comment by DN6** [comment]
@bghira What version of `ruff` do you have installed?

**Comment by bghira** [comment]
0.3.4

**Comment by DN6** [comment]
Ah, diffusers `ruff` is currently pinned 
https://github.com/huggingface/diffusers/blob/cf6e0407e051467b480830d3ed97d2873b5019d3/setup.py#L124

Could you downgrade and run `make style && make quality` that should take care of the tests.

**Comment by bghira** [comment]
nope... that doesn't fix it. it adds even more changes

**Comment by bghira** [comment]
thank god we tried to fix that one formatting issue, or else this PR wouldn't have 66 files with open changes :)

**Comment by DN6** [comment]
@bghira Just a couple of pipelines that also need to be updated with the int casting. 

If you run `make fix-copies` those should be handled. 

```
Traceback (most recent call last):
  File "utils/check_copies.py", line 222, in <module>
    check_copies(args.fix_and_overwrite)
  File "utils/check_copies.py", line [20](https://github.com/huggingface/diffusers/actions/runs/8690950165/job/23832556622?pr=7537#step:5:21)6, in check_copies
    raise Exception(
Exception: Found the following copy inconsistencies:
- src/diffusers/pipelines/audioldm2/pipeline_audioldm2.py: copy does not match pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline.prepare_latents at line 789
- src/diffusers/pipelines/audioldm/pipeline_audioldm.py: copy does not match pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline.prepare_latents at line 329
Run `make fix-copies` or `python utils/check_copies.py --fix_and_overwrite` to fix them.
```

**Comment by DN6** [comment]
@bghira If it's cool with you can I open a separate PR to get this update in and tag you as the author? There are some merge conflicts with your branch because of some recent changes to main.

**Comment by bghira** [comment]
sure

**Comment by yiyixuxu** [comment]
completed in  #7691

**Pull request closed without merging**
