### PR TITLE
Fix lpw stable diffusion pipeline compatibility

### PR DESCRIPTION
**Pull request by SkyTNT**
Make it works on diffusers < 0.10.0

Fixes: #1604 , #1616

### CODE REVIEW

**Comment by SkyTNT** [comment]
@patrickvonplaten , Can you take a look?

**Comment by patrickvonplaten** [comment]
Awesome!

**Comment by adhikjoshi** [comment]
@patrickvonplaten as diffusers become more stable and widely used, we need to make sure all updates are compatible at least with few past versions.

Can we have some checks for this for all merged requests?

**Comment by kovtcharov** [comment]
Thank you for fixing this so quickly, much appreciated!

**Comment by anton-l** [comment]
> run highly used community pipelines as nightly tests
Thought about that too, added a reminder in https://github.com/huggingface/diffusers/issues/1679

**Comment by patrickvonplaten** [comment]
Fixing here: https://github.com/huggingface/diffusers/pull/1680

**Pull request merged**
