### PR TITLE
fix bugs for sd3 controlnet training

### PR DESCRIPTION
**Pull request by xduzhangjiayu**
# What does this PR do?
This PR is for fix some bugs for sd3 controlnet training
1. fix issue for multi-gpu training (examples\controlnet\train_controlnet_sd3.py)
2. fix issue for enabling `--gradient_checkpointing` in training process (src\diffusers\models\controlnet_sd3.py)

## Who can review?
@yiyixuxu @sayakpaul @asomoza

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks, looks good to me. 

In a future PR, I will add a few more tests related to gradient checkpointing.

**Comment by xduzhangjiayu** [comment]
Hi, any comment on this PR ? @yiyixuxu

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by tobiasfshr** [comment]
Hi, I have a question on 1: Is having unused parameters expected behavior? The following parameters seem to be unused:
```
transformer_blocks.11.ff_context.net.2.bias, transformer_blocks.11.ff_context.net.2.weight, transformer_blocks.11.ff_context.net.0.proj.bias, transformer_blocks.11.ff_context.net.0.proj.weight, transformer_blocks.11.attn.to_add_out.bias, transformer_blocks.11.attn.to_add_out.weight
```

**Comment by Zheng-Fang-CH** [comment]
> sformer_blo

Hi, I meet the same error, do you solve it now?

**Comment by xduzhangjiayu** [comment]
> > sformer_blo
> 
> Hi, I meet the same error, do you solve it now?
Hi, I have never met this error, could you please decribe in detail, thanks!

**Comment by Zheng-Fang-CH** [comment]
> Hi, I have never met this error, could you please describe in detail, thanks!

error
Hi, I didn't change the code in diffusers, but the weight parameters in controlnets seem not be used to compute the final loss, but obviously, these weights have been initialized.

**Comment by xduzhangjiayu** [comment]
> > Hi, I have never met this error, could you please describe in detail, thanks!
> 
> error Hi, I didn't change the code in diffusers, but the weight parameters in controlnets seem not be used to compute the final loss, but obviously, these weights have been initialized.

Seems maybe I have met before, but I'm not sure, could you please contact me with email: xduzhangjiayu@163.com for further discussion ?

**Pull request merged**
