### PR TITLE
Update scheduling_euler_discrete.py

### PR DESCRIPTION
**Pull request by Senume**
# What does this PR do?

Fixes # 
Type Error fix. During the tensor type conversion, it expects for NumPy array, which fails when tensor array is passed. 
Solution: Check the type before conversion.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by yiyixuxu — COMMENTED** [review]
(1) can we instead create sigmas as a numpy array here (with `np.linspace`), and make sure all the tests still pass 
```python
        elif self.config.interpolation_type == "log_linear":
            sigmas = torch.linspace(np.log(sigmas[-1]), np.log(sigmas[0]), num_inference_steps + 1).exp()
```
(2) can we go through all the schedulers to see if there is another schedulers with same issue

thanks!

**Comment by yiyixuxu** [comment]
fix https://github.com/huggingface/diffusers/issues/6054

**Comment by Senume** [comment]
> (1) can we instead create sigmas as a numpy array here (with `np.linspace`), and make sure all the tests still pass
> 
> ```python
>         elif self.config.interpolation_type == "log_linear":
>             sigmas = torch.linspace(np.log(sigmas[-1]), np.log(sigmas[0]), num_inference_steps + 1).exp()
> ```
> 
> (2) can we go through all the schedulers to see if there is another schedulers with same issue
> 
> thanks!

I have changed the code accordingly, to option (1) requirement. If it's good, I will look through schedulers for same issues

**Comment by yiyixuxu** [comment]
looks good :)

> I have changed the code accordingly, to option (1) requirement. If it's good, I will look through schedulers for same issues

**Comment by Senume** [comment]
Went through the schedulers, I have noticed few variations from, 

At scheduling_ddpm_wuerstchen.py 
imag1

At scheduling_ipndm.py 
imag2

These directly does operation on tensor array, instead of making a numpy array, doing operation on it, finally converting to tensor array and assigning to class attributes.  But it seems to work without any issue. 

Similarly,

At scheduling_k_dpm_2_ancestral_discrete.py 
imag3

It seems to change location from GPU to CPU memory without changing tensor array to numpy array (underlined in blue), but class function 'sigma_to_t' accepts a numpy array as input (underlined in red). This may possess an issue. 
It was also found seen 

At scheduling_k_dpm_2_discrete.py 
imag4

**Pull request closed without merging**
