### PR TITLE
Add ZipLora 

### LINKED ISSUE #5925: Add ZipLora to enhance multi-lora inference
**Is your feature request related to a problem? Please describe.**
Refer to https://ziplora.github.io/

**Describe the solution you'd like.**
When multiple LoRAs are passed to the model, you should have the ability to use ziplora to merge them.

**Additional context.**
arxiv paper: https://arxiv.org/abs/2311.13600

### PR DESCRIPTION
**Pull request by shauray8**
# What does this PR do?

Adds [ZipLoRA: Any Subject in Any Style by Effectively Merging LoRAs](https://ziplora.github.io/)

Fixes #5925

- [X] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [X] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [X] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).

## Who can review?
@sanchit-gandhi @patrickvonplaten 

@AmericanPresidentJimmyCarter

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Should we maybe try to directly add this to PEFT cc @younesbelkada @pacman100 @say

**Comment by sayakpaul** [comment]
Adding to `peft` sounds good to me. But for training, I think we should encourage the community to use the scripts developed by @mkshing here: https://github.com/mkshing/ziplora-pytorch. They're quite elegant and are fully diffusers compatible.

**Comment by shauray8** [comment]
The training script by @mkshing is pretty neat actually, I'm not sure if you want this to be an inference-only addition to ```PEFT``` or if it is something else.

**Comment by younesbelkada** [comment]
Yes it would make sense to add ZipLora directly in PEFT and use it in diffusers. You can take a look at a similar PR here: https://github.com/huggingface/peft/pull/1160
How does that to you @shauray8 ?

**Comment by shauray8** [comment]
Sounds good, I might need a little help moving forward @younesbelkada. Closing this and opening up a PR in PEFT.

**Pull request closed without merging**
