### PR TITLE
parameterize pass single args through tuple

### PR DESCRIPTION
**Pull request by williamberman**
I was getting an error here locally when running tests.

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Weird. Probably surfaces from PyTorch 2.0? Previously it didn't fail with PT 1.13.1.

**Comment by williamberman** [comment]
> Weird. Probably surfaces from PyTorch 2.0? Previously it didn't fail with PT 1.13.1.

Think it's more likely a testing dependency version discrepancy but yeah fersure weird

**Comment by pcuenca** [comment]
I also encountered this, worked after upgrading to the latest version of `parameterize`.

**Comment by sayakpaul** [comment]
> I also encountered this, worked after upgrading to the latest version of parameterize.

Does this mean we should update the version of `parameterize` when installing `pip install -e .[test]`? @pcuenca

**Comment by pcuenca** [comment]
Not sure, I was testing locally, saw the issue, updated and it worked. I think if you install in a fresh environment with `.[test]` it should work and bring the latest version.

**Pull request merged**
