### PR TITLE
fix(DDIM scheduler): use correct dtype for noise

### PR DESCRIPTION
**Pull request by keturn**
Otherwise, it crashes when eta > 0 with float16.

Follow-up to #511.

### CODE REVIEW

**Comment by keturn** [comment]
Should we add a `randn_like` function somewhere that accepts `generator`? (because it doesn't exist yet upstream:  https://github.com/pytorch/pytorch/issues/27072 )

right now the different calls to randn are subtly inconsistent in whether and how they pass dtype or device. Having a single implementation would provide one place for those fiddly details, especially if there are things that have to be different on certain platforms like `mps`.

**Comment by keturn** [comment]
> All done! ✨ 🍰 ✨
> 123 files would be left unchanged.
> Traceback (most recent call last):
>  File "/opt/hostedtoolcache/Python/3.7.14/x64/bin/doc-builder", line 8, in <module>
>    sys.exit(main())
>  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/doc_builder/commands/doc_builder_cli.py", line 47, in main
>    args.func(args)
>  File "/opt/hostedtoolcache/Python/3.7.14/x64/lib/python3.7/site-packages/doc_builder/commands/style.py", line 28, in style_command
>     raise ValueError(f"{len(changed)} files should be restyled!")
> ValueError: 1 files should be restyled!

a) this is not an informative failure message.
b) I ran `make style` and it changed some file that was not in this PR.

sod off, stylebot.

**Review by pcuenca — APPROVED** [review]
Good catch!

**Comment by pcuenca** [comment]
> Should we add a `randn_like` function somewhere that accepts `generator`? (because it doesn't exist yet upstream: [pytorch/pytorch#27072](https://github.com/pytorch/pytorch/issues/27072) )

I think that makes sense, and we should ensure that all calls use the generator. If @patrickvonplaten and @anton-l agree we can follow up in a new PR :)

**Comment by kashif** [comment]
I think this fix can potentially be applied to sde-ve and sde-vp schedules too

**Review by patrickvonplaten — APPROVED** [review]
Great fix! Thanks!

**Pull request merged**
