### PR TITLE
fix from_transformer() with extra conditioning channels

### PR DESCRIPTION
**Pull request by xduzhangjiayu**
# What does this PR do?
Hi, 
This PR is for training a SD3 controlnet model with extra conditioning channels (e.g. sd3 controlnet inpainting)
So for `from_transformer()` function, I added a parameter `num_extra_conditioning_channels` to specify the extra channels before controlnet copy the channels from transfomer.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@yiyixuxu @sayakpaul 
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by yiyixuxu** [comment]
hi @xduzhangjiayu 
thanks for the PR! but I'm not sure I understand how it works, `extra_conditioning_channels` is not a config in sd3 controlnet,no?

**Comment by xduzhangjiayu** [comment]
> hi @xduzhangjiayu thanks for the PR! ~but I'm not sure I understand how it works, `extra_conditioning_channels` is not a config in sd3 controlnet,no?~
> 
> nevermind, I think it makes sense! can you fix the quality test (run `make style` and `make fix-copies`?)

Hi,
Could you tell me how to run `make style` on Windows (Currently I don't have a Linux environment)? Because I always got `bash: make: command not found` on Windows. Thanks so much!

**Comment by xduzhangjiayu** [comment]
Hi, 
Now I can run `make style` and `make fix-copies`, but up to 40 files will be changed (not include controlnet_sd3.py), so what should I do next? Thanks! @yiyixuxu

**Comment by asomoza** [comment]
on windows, in my experience, the only way to run the `make style` and `make fix-copies` without them changing a lot of files because of the formatting is to use WSL and run it inside of it.

You can run it and just commit the files that you changed and discard the rest though.

**Comment by yiyixuxu** [comment]
@xduzhangjiayu 
let me know if what @asomoza suggested work for you! 
we can help if not!

**Comment by xduzhangjiayu** [comment]
> @xduzhangjiayu let me know if what @asomoza suggested work for you! we can help if not!
Hi, I have tried with a lot of time, but still cannot work. Could you please help fix that if you have time? Thanks so much!

**Comment by xduzhangjiayu** [comment]
Hi, any update on this PR~ :) @yiyixuxu

**Review by yiyixuxu — APPROVED** [review]

**Comment by xduzhangjiayu** [comment]
Thanks so much for all the helps! @yiyixuxu @asomoza

**Comment by Mo-Junyang** [comment]
> Thanks so much for all the helps! @yiyixuxu @asomoza

Hi,I have some question running SD3Controlnet with `num_extra_conditioning_channels`
Here is a part of code from https://github.com/huggingface/diffusers/blob/main/examples/controlnet/train_controlnet_sd3.py
``` python
                # controlnet(s) inference
                controlnet_image = batch["conditioning_pixel_values"].to(dtype=weight_dtype)
                controlnet_image = vae.encode(controlnet_image).latent_dist.sample()
                controlnet_image = controlnet_image * vae.config.scaling_factor

                control_block_res_samples = controlnet(
                    hidden_states=noisy_model_input,
                    timestep=timesteps,
                    encoder_hidden_states=prompt_embeds,
                    pooled_projections=pooled_prompt_embeds,
                    controlnet_cond=controlnet_image,
                    return_dict=False,
                )[0]
```

After vae, `controlnet_image` should be 16 channels. 
But with default, SD3ControlNetModel expects `16 + 1 (num_extra_conditioning_channels)`
So what is the extra channel here? Should there be another cond_img to input controlnet? 

An additional question, I noticed that SD3controlnet is different from other controlnet, no conv_in, but with cond_img after vae. Would you mind explaining why it is different?

**Comment by xduzhangjiayu** [comment]
Hi, @Mo-Junyang 
For controlnet like canny, depth, SD3 controlnet needs 16 channels (only canny or depth map)
For controlnet like inpainting, SD3 controlnet needs 17 channels (masked_image (16) + mask (1))
For the last question, I don't know why the SD3 controlnet author use vae to replace conv_in, but as far as I know, a paper 'BrushNet' using the same strategy, and you can refer to this paper.

**Comment by Mo-Junyang** [comment]
@xduzhangjiayu 
Thank you so much for your patient explanation!

**Pull request merged**
