### PR TITLE
Feature/colossalai

### PR DESCRIPTION
**Pull request by Fazziekey**
- support ColossalAI Dream blooth training
- add README for Train ColossalAI Dream blooth

### CODE REVIEW

**Comment by isamu-isozaki** [comment]
Nice! dreambooth with 6gb gpu is pretty impressive. How fast is it to train on a 6gb card?

**Comment by patrickvonplaten** [comment]
Hey @Fazziekey,

Could you run `make style` here to fix the final failing tests? :-) 

Also, could we maybe to begin with put this under the research examples as we don't (yet) have that much experience with ColossalAI, e.g. could you maybe create a directory:

`examples/research_projects/colossalai_dreambooth` here: https://github.com/huggingface/diffusers/tree/main/examples/research_projects with a nice README stating that it is maintained by you? :-) 

Apart from this the PR looks very nice to me! @patil-suraj what do you think?

**Comment by Fazziekey** [comment]
> Hey @Fazziekey,
> 
> Could you run `make style` here to fix the final failing tests? :-)
> 
> Also, could we maybe to begin with put this under the research examples as we don't (yet) have that much experience with ColossalAI, e.g. could you maybe create a directory:
> 
> `examples/research_projects/colossalai_dreambooth` here: https://github.com/huggingface/diffusers/tree/main/examples/research_projects with a nice README stating that it is maintained by you? :-)
> 
> Apart from this the PR looks very nice to me! @patil-suraj what do you think?

ok, I will fix the style bug

**Comment by Fazziekey** [comment]
@patrickvonplaten @isamu-isozaki  I have fixed the format bug, is it ok to be merged or I'd better move it to https://github.com/huggingface/diffusers/tree/main/examples/research_projects

**Comment by Fazziekey** [comment]
- cpu mode :4GB
image

- auto mode 5.6GB:
image

- cuda mode 10GB:
image

**Comment by patil-suraj** [comment]
Hey @Fazziekey , this is very cool; thanks a lot for working on this! 

As Patrick said, could you please put the script under https://github.com/huggingface/diffusers/tree/main/examples/research_projects ? We could create a `dir` called `colossalai` and put the script under it. Then it should be good to merge.

**Comment by Fazziekey** [comment]
@patrickvonplaten can you merge the PR

**Comment by patrickvonplaten** [comment]
Perfect, thank you :-)

**Pull request merged**
