### PR TITLE
[training] fix training resuming problem for fp16 (SD LoRA DreamBooth)

### PR DESCRIPTION
**Pull request by a-r-r-o-w**
# What does this PR do?

Part of #6552.

I'm yet to test it on a training run. I think Sayak mentioned he'll be opening a follow-up PR to add a utility function that removes the duplicated code.

First run:

```bash
CUDA_VISIBLE_DEVICES=0 accelerate launch train_dreambooth_lora.py \
  --pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5 \
  --instance_data_dir="dog" \
  --mixed_precision="fp16" \
  --instance_prompt="a photo of sks dog" \
  --output_dir="lora-dog-sd" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=4 --checkpointing_steps=2 --checkpoints_total_limit=2 \
  --use_8bit_adam \
  --seed="42"
```

Resume training:

```bash
CUDA_VISIBLE_DEVICES=0 accelerate launch train_dreambooth_lora.py \
  --pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5 \
  --instance_data_dir="dog" \
  --mixed_precision="fp16" \
  --instance_prompt="a photo of sks dog" \
  --output_dir="lora-dog-sd" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=1e-4 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=4 --checkpointing_steps=2 --checkpoints_total_limit=2 \
  --resume_from_checkpoint="latest" \
  --use_8bit_adam \
  --seed="42"
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@sayakpaul

### CODE REVIEW

**Comment by sayakpaul** [comment]
Super fast! I have updated the description of https://github.com/huggingface/diffusers/issues/6552. It should be clear now.

**Comment by sayakpaul** [comment]
@a-r-r-o-w let me know if I can test it.

**Comment by a-r-r-o-w** [comment]
Hi Sayak, this is ready for testing I believe, and seems to be working well. Here are my logs:

image

**Comment by sayakpaul** [comment]
Just tested. Seems to be working well! Thank you!

**Pull request merged**
