### PR TITLE
Fix multi-prompt inference

### PR DESCRIPTION
**Pull request by nikitabalabin**
Fix generation of multiple images with multiple prompts, e.g len(prompts)>1, num_images_per_prompt>1

# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sayakpaul** [comment]
Can you show an example of where the current code (without the changes in this PR) fails?

**Comment by nikitabalabin** [comment]
```
from diffusers import PixArtAlphaPipeline, Transformer2DModel
import torch

pipe = PixArtAlphaPipeline.from_pretrained("PixArt-alpha/PixArt-XL-2-1024-MS", 
                                           torch_dtype=torch.float16).to('cuda')
prompts = ["a man", "cat riding a bike in the forest, watercolor style"]   
images = pipe(prompt=prompts, num_images_per_prompt=2).images
```

images[1] and images[2] will be generated with wrong prompt_attention_mask.

**Comment by sayakpaul** [comment]
Thanks! Could we add a fast test for this as well?

**Comment by yiyixuxu** [comment]
hi @nikitabalabin 
thanks for the PR! let us know if you're still interested in finishing it:)

**Comment by yiyixuxu** [comment]
can we run `make style` too?

**Comment by sayakpaul** [comment]
@hlky was the close expected?

**Comment by hlky** [comment]
Rebase to fix conflict went wrong 😅

**Pull request closed without merging**
