### PR TITLE
Update colab notebook to be under DDPM

### PR DESCRIPTION
**Pull request by tmabraham**
The link in the docs suggest that the training example is for DDIM when in fact it is for DDPM.

### CODE REVIEW

**Comment by pcuenca** [comment]
Hi @tmabraham!

You are right, the notebook uses DDPM and not DDIM. In addition, I believe it's not in the right section at all, as it is a _training_ notebook and not an example of how to use the pipeline as the others in the same table.

I think I'd just remove it from that table and leave it in the [training page](https://huggingface.co/docs/diffusers/training/overview) that already links to it.

Any other suggestions @patrickvonplaten @anton-l ?

**Comment by tmabraham** [comment]
@pcuenca I can close this PR and make another one just removing it from that page... does that work?

**Comment by pcuenca** [comment]
Cool, that's fine by me :)

**Comment by patrickvonplaten** [comment]
Agree that we should remove it @tmabraham would you like to update your PR?

**Pull request closed without merging**
