### PR TITLE
Fix a bug of pano when not doing CFG

### PR DESCRIPTION
**Pull request by ernestchu**

### CODE REVIEW

**Comment by sayakpaul** [comment]
Thanks for your PR. Could you rebase from `main` and ensure the code quality tests pass? 

Also tagging @omerbt for a review.

**Comment by ernestchu** [comment]
Hi, sorry I'm kind of new to the community. I afraid I have difficulty to follow your workflow. Feel free to modify my commit!

**Comment by sayakpaul** [comment]
Our instructions are here: https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md#how-to-open-a-pr

I would suggest following them. If you find any difficulties, let us know. We're more than happy to help.

**Comment by omerbt** [comment]
Thanks, looks good!

**Comment by ernestchu** [comment]
@omerbt Hi, great work on MultiDiffusion. BTW, I want to ask have you tried aggregation schemes other than averaging? For example, overwriting the overlapped area, or keeping only one of values at the overlapped area.

I'm wondering if averaging smooths out the noise during diffusion sampling.

**Comment by omerbt** [comment]
Hi @ernestchu thanks! The averaging is aimed to 'fuse' the generation paths of different regions in the panorama, reconciling them 
in the Least-Square sense. Intuitively, we steer the diffusion process into a path that suits all of the panorama crops. More details and derivation are provided in our paper https://arxiv.org/pdf/2302.08113.pdf

**Comment by patrickvonplaten** [comment]
Good job @ernestchu & thanks for fixing the style @sayakpaul !

**Comment by ernestchu** [comment]
@omerbt thanks for your reply, but my concerns persist. Let's say, what if we initialize the noise latent with MultiDiffusion step. That is to say, the init latent has the shape (#view, N, 4, 64, 64), and we fuse these views into panorama by either averaging or overwriting (c.f. `use_avg`), as implemented below.

https://github.com/huggingface/diffusers/blob/e748b3c6e163ce9a61965eb456704a83b855ccc3/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py#L601-L604
```python
# 6.5. Take the MultiDiffusion step at the initialization of noise latents
use_avg = True
latent_views = self.prepare_latents(
    len(views) * batch_size * num_images_per_prompt,
    num_channels_latents,
    512, 512,
    prompt_embeds.dtype,
    device,
    generator,
)
latent_views = latent_views.view(len(views), -1, *latent_views.shape[1:])
for (h_start, h_end, w_start, w_end), latent_view in zip(views, latent_views):
    value[:, :, h_start:h_end, w_start:w_end] = (
        value[:, :, h_start:h_end, w_start:w_end] if use_avg else 0) + latent_view
    count[:, :, h_start:h_end, w_start:w_end] += 1

latents = torch.where(count > 0, value / count, value) if use_avg else value.clone()
```
https://github.com/huggingface/diffusers/blob/e748b3c6e163ce9a61965eb456704a83b855ccc3/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_panorama.py#L606-L607

---

With `use_avg = True`, we obtain failed result like this
asdf

With  `use_avg = False`, i.e. overwriting, we obtain expected result like this
Unknown-1

With  `use_avg = False` throughout the diffusion process, i.e. using overwriting not only at initialization but every step, we obtain suboptimal result like this
Unknown

---

From my point of view, I think averaging do smooth out the noise and fail the SD. It's something similar to smoothing with Gaussian kernel in spatial domain. However, when we set `num_inference_steps = 50` and do the MultiDiffusion step after the first denoising step, the latent being averaged contains significantly less noise, and thus my concerns are not prominent. To verify this, I use the original MultiDiffusion with `num_inference_steps = 999` to obtain the following image
Unknown-3


In addition, we can also tell that using averaging during diffusion sampling can boost the diversity and mitigate the boundary effect. This is intuitive since averaging provides novel pixel values and helps LS optimization.

Please let me know your comments. It's an amazing work nevertheless!

**Comment by omerbt** [comment]
Thanks @ernestchu ! 
First, the MultiDiffusion process averages the per-crop **denoising suggestions** of SD. MultiDiffusion is only defined in terms of these denoising steps. In fact, we assume that each crop in the panorama is distributed `N(0,I)` (see the proposition in the paper which serves as the main motivation), hence it is important not to average the initial noise itself (otherwise the inital noise has non-unit variance)

For the sake of simplicity, we focused on the case of number of denoising steps that is commonly used in practice (e.g., 50). However, you can also define the MultiDiffusion updates in a more general manner, for example by setting the per-pixel weights (Eq. 4 in the paper) to be time dependent, and tradeoff differently the different denoising suggestions to prevent divergence in the extreme case of large timesteps near`t=999` (a private case is setting the weights to infinity as you suggested). Adapting the per-pixel weights can also be interesting in other scenarios where you would like to control the 'harmonization' of the panorama using more sophisticated strategies (i.e., how information propagates across the panorama).

Hope that helps!

**Pull request merged**
