### PR TITLE
Re-structure the repository

### PR DESCRIPTION
**Pull request by ydshieh**
Re-structure the repository

### CODE REVIEW

**Comment by patil-suraj** [comment]
Thanks a lot for the PR ! Is there any specific reason/advantage of this restructuring ? It would be nice to keep the repo structure as flat as possible initially, this makes it easier to browse and work with the repo.  This can be done later if the current structure is becoming  inflexible. 
cc @anton-l @patrickvonplaten

**Comment by ydshieh** [comment]
Hi @patil-suraj I just tried to make the structure similar to `transformers` in an earlier stage, as it would be more tedious to change once the repo. become large enough. Although I don't know the details, but guess there are some good reasons for `transformers` to have this structure, so might be good to do the same here.

Regarding browsing the repo, with an IDE, it is fine. But maybe you guys prefer using commandline tools?

**Comment by patil-suraj** [comment]
That's a good point! But the repo is not aimed to be similar to `transformers` in structure. `transformers` also had a flat structure initially which made it very easy to browse and contribute. `transformers` only switched to this when the flat structure started to get a bit out of hands. 

`diffusers` is not as big as `transformers` so I don't see why this re-structure will help. Having a flat structure will also help the community to better browse the repo, as they can just land on github and browse through it with few clicks rather than having to go through multiple subdirectories. I'm not in favour of this change at this stage of lib.

But we could for sure revisit this once in future when `diffusers` has grown. Thanks a lot :)

**Comment by ydshieh** [comment]
Also, you are working on Flax version, no? And as far as I know, eventually we would like to include that work into this repo..? Guess it's almost the time to re-structure the reop for different frameworks.

**Comment by ydshieh** [comment]
OK for me to close this PR, but let's have opinions from @anton-l and @patrickvonplaten  first 🙏 .

**Comment by patil-suraj** [comment]
>Also, you are working on Flax version, no?

Right but this is only for the stable-diffusion model. There is no immediate plan to support flax and or any other framework. And even if we support flax now, the repo is as big to warrant a re-strucrtre IMO.

**Comment by ydshieh** [comment]
Got it!

Although I agree that `transformers` was initially flat too + quick browsing is good, I also think using that structure in an early stage could avoid unnecessary larger amount of work (to change) in the future. For `transformers`, it was normal that we have a change to current structure. But now we have experience learned from it.

One more argument is that people (mostly the contributors) could get familiar with the same structure (while it is small). It would be more difficult for them to get used to the new structure in the future if we change it later.

**Comment by pcuenca** [comment]
I agree with @patil-suraj here. I'm new to the code base, and so far I've found it very easy to browse, navigate and generally find things. I use IDEs when actively working on the code, if I'm just using the library I prefer to take a quick look in github or even in the command-line, depending on what I'm doing.  A flat structure has the advantage that you see everything in a folder at once, and I think it's less intimidating, even with an IDE. Reading the names of a few files gives you a very clear idea of what's in there. 

@ydshieh's points are good, but I'd rather wait until we feel we need more structure. 

That's just my opinion from a newcomer's point of view, happy to hear other perspectives.

**Comment by patil-suraj** [comment]
Those are good point @ydshieh !

Let me clarify some differences between `diffusers` and `transformers`:

- `transformers` is model's repo and has hundreds of models . That's not the case with `diffusers`, it's not  a models repo, while we have some models it's unlikely that it will have hundreds of models like in transformers.

- in  `transformers` a model has multiple related modules like `tokenizer`, `config`, `feature_extractor` so it makes sense to create a package for individual models. But in diffusers `models` and `schedulers` are very well separated so it's not one model tied with one scheduler. So most likely models will be single file and what is the advantage  of  creating a package for a single file ?

- Same case with `schedulers` those are self-contained , single file and not tied with any specific models. Same question as above. What is the advantage  of  creating a package for a single scheduler file ?

Considering this, at this point IMO it's not necessary to have a package structure like in `transformers`.

**Comment by ydshieh** [comment]
Thanks @patil-suraj Good points on single files per model/scheduler.

Actually, my initial motivation is to contribute in TF, and for different frameworks, I just decide to use the same structure in `transformers`.

**Comment by patil-suraj** [comment]
No worries at all :) 

In future let's all discuss things on issues first before doing any changes. It will save all of us some time :)

**Comment by ydshieh** [comment]
Close this PR - leave it in the future 🔥

**Pull request closed without merging**
