### PR TITLE
Update xFormers docs

### LINKED ISSUE #1731: Update xformers installation docs when xformers `0.0.16` is released
The wheels will have PyTorch pinned to the latest stable version:
https://github.com/facebookresearch/xformers/issues/533#issuecomment-1355162407

For older versions, we can recommend to install from source.

### PR DESCRIPTION
**Pull request by pcuenca**
Fixes #1731

### CODE REVIEW

**Review by kashif — APPROVED** [review]
LGTM! Thanks! Do we want to add it to the setup.py?

**Comment by pcuenca** [comment]
> LGTM! Thanks! Do we want to add it to the setup.py?

As an `extra`? I'm not sure we should, it's more of an user preference for me. Happy to submit a commit if you think it's important/useful.

**Comment by kashif** [comment]
no its ok! It might cause more issues (especially since it is so tied in with the pytorch version...)

**Review by patrickvonplaten — APPROVED** [review]
Thanks!

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
