### PR TITLE
[Community] RAVE Video Editing

### LINKED ISSUE #6325: RAVE
### Model/Pipeline/Scheduler description

RAVE (Randomized Noise Shuffling for Fast and Consistent Video Editing with Diffusion Models) is a fast text-guided video editing framework. It supports editing videos of any length while preserving motion and semantic structure. From some very basic testing, I really like the quality and it'd be great to have diffusers support it.

<table>
<tr>
  <td>Input</td>
  <td>Egyptian Pharaoh</td>
  <td>Medieval Knight</td>
  <td>Zombie</td>
</tr>
<tr>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/5dc6ce64-d2be-49dd-89b3-1589cd9195bb" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/0eeaa1e4-4b8d-42d0-b5cb-e427e562da37" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/2425ff0b-3e00-4bff-8afb-fa4f00019e8e" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/f1c9bc21-6ce3-4a4e-b761-7ea906a3bdf6" /></td>
</tr>
<tr>
  <td>Input</td>
  <td>Blue Crystal</td>
  <td>Crotchet boxes</td>
</tr>
<tr>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/02a51a97-15e2-416b-83ee-f1d25bbbf220" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/7e450029-6816-495b-b990-b3b15b39f791" /></td>
  <td><video src="https://github.com/huggingface/diffusers/assets/72266394/2217dc3e-6459-4483-8e67-72b57190cbed" /></td>
</tr>
</table>

### Open source status

- [X] The model implementation is available.
- [X] The model weights are available (Only relevant if addition is not a scheduler).

### Provide useful links for the implementation

[Paper](https://arxiv.org/abs/2312.04524)
[Project Page](https://rave-video.github.io/)
[Code](https://github.com/rehg-lab/RAVE/)
[Demo](https://huggingface.co/spaces/ozgurkara/RAVE)

Authors: @ozgurkara99 @bariscankurtkaya @yesiltepe-hidir [James M. Rehg](https://scholar.google.co.in/citations?user=8kA3eDwAAAAJ&hl=en) @pinaryanardag

Thank you for your amazing work!

@sayakpaul @DN6 @patrickvonplaten

### PR DESCRIPTION
**Pull request by a-r-r-o-w**
# What does this PR do?

Adds RAVE (Randomized Noise Shuffling for Fast and Consistent Video Editing with Diffusion Models) support in community pipelines.

Some results can be found in the [Colab](https://drive.google.com/file/d/1yhRG6md-QXS1YaRC1CdpL_q0ahvPyflk/view?usp=sharing) notebook.

Fixes #6325.

[Paper](https://arxiv.org/abs/2312.04524)
[Project Page](https://rave-video.github.io/)
[Code](https://github.com/rehg-lab/RAVE/)
[Demo](https://huggingface.co/spaces/ozgurkara/RAVE)

GPU support generously provided by [ModelsLab](https://modelslab.com/).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@sayakpaul @DN6 @ozgurkara99 @bariscankurtkaya @yesiltepe-hidir

### CODE REVIEW

**Comment by a-r-r-o-w** [comment]
Short summary of the paper:
- Input video is split into frames and placed into grids of user-defined size (widely known in the community as the "Grid Trick")
- Controlnet preprocessors are used to obtain control video, which is also placed into grids
- Noise shuffling of latents between grids is employed (at every denoising timestep) which greatly improves results as it allows for consistent styling across different grids by encouraging spatio-temporal interaction between each video frame. Self attention ensures that features in each patch are influenced by other frames at each step of the denoising process.
- Denoising is performed and obtained latents are decoded and reorganized to undo the shuffling, thereby resulting in the edited video.
- Does not require any extra memory or compute as such, and can be employed to edit videos of any length.

So far, I've added the grid trick and noise shuffling to the pipeline. I'm yet to add DDIM inversion which greatly improves generation quality because I haven't found an easy way to do it yet...

**Comment by ozgurkara99** [comment]
Thank you for your contributions @a-r-r-o-w , my suggestion is that DDIM inversion also plays an important role, so it’d be beneficial if that is included in the pipeline, what problem did you encounter while implementing it?

**Comment by a-r-r-o-w** [comment]
> Thank you for your contributions @a-r-r-o-w , my suggestion is that DDIM inversion also plays an important role, so it’d be beneficial if that is included in the pipeline, what problem did you encounter while implementing it?

I'm a little inexperienced with using inversion tbh. I will work on it and finish adding it when I'm awake next :) Apart from inversion, I'd like to know your thoughts about the remaining implementation and if I've captured the ideas highlighted in the paper, and your code, correctly in the implementation.

**Comment by a-r-r-o-w** [comment]
Hi @ozgurkara99. So I've added support for DDIM inversion locally and will be pushing it in a bit. I had a question though:

In the original codebase, I notice that when performing the inversion, you use the original video frames instead of the grid concatenated video frames to obtain the latents. Have you experimented with which provides better results after inversion? Because, in the original codebase, I see that you're doing something equivalent to:

```python
latents = split_grid_to_frames(grid_latents)
latents = ddim_inversion(latents)
latents = create_grid_from_frames(latents)
```

I believe it might work without needing to split/create grids. I haven't experimented yet but I will do so in a short while. Asking because maybe this could have already been looked into by you.

**Comment by a-r-r-o-w** [comment]
I see. Yes, I guess that would be a good way of handing control to the user on what to perform the inversion on. I'll hopefully be able to find time to test soon and push.

**Comment by a-r-r-o-w** [comment]
Hi @ozgurkara99 @bariscankurtkaya. Here's a [Drive link](https://drive.google.com/drive/folders/1-myWDQNhgp0X2izt4wMMA-t38oPLfMgD?usp=sharing) to some of the generations. Unfortunately, even after adding inversion, I haven't been able to replicate the demonstrated quality on your project site. I believe I might be doing something incorrectly. Would you be able to review the code once if you're able to find time? I will try to do the same.

There are a few features yet to be added: `denoise_batch_size` support, multiple controlnet and a few other smaller things, but as such the pipeline is ready (except a few bugs).

I don't think there is anything incorrect with the LoC related to grid and shuffling. Inverse scheduling also uses all parameters correctly I believe. Here's the [notebook](https://drive.google.com/file/d/1yhRG6md-QXS1YaRC1CdpL_q0ahvPyflk/view?usp=sharing) I've used for testing.

**Comment by ozgurkara99** [comment]
hmm, i checked the videos and it might be about the parameters of the models + the type of control that was used. But I am going to check the notebook code and the pipeline soon, thanks for the implementation @a-r-r-o-w

**Comment by ozgurkara99** [comment]
hey @a-r-r-o-w , I hope you are doing well. Sorry for my late reply, I now become able to find a suitable time to check the pipeline as I had a tight schedule for the last month. Let's keep in touch if you are available this week and let's finish this integration. Thanks.

**Comment by a-r-r-o-w** [comment]
Hi @ozgurkara99, thanks for being patient and apologies for the delay. I've been a little busy with work and trying out other ideas and papers. I'd definitely like to finish this and create a better implementation from what we have here. By the end of this week, I'll rewrite this in a better way and allow multicontrolnet support and try investigating the bad results. Hopefully we can do a review then.

**Comment by a-r-r-o-w** [comment]
@ozgurkara99 I have uploaded the results after using multicontrolnet [here](https://drive.google.com/drive/folders/1-myWDQNhgp0X2izt4wMMA-t38oPLfMgD?usp=drive_link). I still seem to be having troubles replicating the results with the following settings (depth_leres and canny, 50 inversion steps, 50 inference steps):

<details>
<summary> Code </summary>

```py
import imageio
from diffusers.utils import export_to_gif
from IPython.display import Image as ImageDisplay
from PIL import Image

def load_video(file_path):
    images = []
    vid = imageio.get_reader(file_path)
    for i, frame in enumerate(vid):
        pil_image = Image.fromarray(frame)
        images.append(pil_image)
    return images

from typing import List
from PIL import Image
from diffusers.utils import export_to_gif

def image_grid(images: List[Image.Image], rows: int, cols: int) -> Image.Image:
    if len(images) > rows * cols:
        raise ValueError(
            f"Number of images ({len(images)}) exceeds grid size ({rows}x{cols})."
        )
    w, h = images[0].size
    grid = Image.new("RGB", size=(cols * w, rows * h))
    for i, image in enumerate(images):
        grid.paste(image, box=(i % cols * w, i // cols * h))
    return grid

def gif_grid(gifs: List[List[Image.Image]], rows: int, cols: int) -> Image.Image:
    if all(len(x) != len(gifs[0]) for x in gifs):
        raise ValueError("All gifs must have same length")
    frames = []
    for x in zip(*gifs):
        frame = image_grid(x, rows, cols)
        frames.append(frame)
    return frames

num_frames = 16
data = {
    "1.mp4": "A shiny silver robotic wolf, futuristic, metallic, with some golden features, high quality render",
    "2.mp4": "A train moving on the railway track in autumn, maple leaves, high quality, photorealistic, artistic detail",
    "3.mp4": "Swarovski blue crystal stones, high quality",
}
video = [load_video(x)[:num_frames] for x in data.keys()]
prompt = data.values()
video_grid = gif_grid(video, 1, 3)
export_to_gif(video_grid, "input.gif")

ImageDisplay("input.gif", embed=True)

from controlnet_aux.processor import Processor
p1 = Processor("depth_leres")
control_video_1 = [[p1(frame) for frame in vid] for vid in video]
p2 = Processor("canny")
control_video_2 = [[p2(frame) for frame in vid] for vid in video]

control_video_1 = [[frame.resize(video[index][0].size) for frame in vid] for index, vid in enumerate(control_video_1)]
control_video_2 = [[frame.resize(video[index][0].size) for frame in vid] for index, vid in enumerate(control_video_2)]
control_video = list(zip(control_video_1, control_video_2))

control_video_grid = gif_grid([*control_video_1, *control_video_2], 2, 3)
export_to_gif(control_video_grid, "control.gif")
ImageDisplay("control.gif", embed=True)

experiment_params = [
    dict(
        strength=0.5,
        grid_size=2,
        use_shuffling=False,
    ),
    dict(
        strength=0.5,
        grid_size=2,
        use_shuffling=True
    ),
    dict(
        grid_size=2,
        use_shuffling=True,
        num_inversion_steps=50,
        inversion_prompt="",
        apply_inversion_on_grid=False,
    ),
    dict(
        grid_size=2,
        use_shuffling=True,
        num_inversion_steps=50,
        inversion_prompt="",
        apply_inversion_on_grid=True,
    ),
    dict(
        grid_size=3,
        use_shuffling=True,
        num_inversion_steps=50,
        inversion_prompt="",
        apply_inversion_on_grid=False,
    ),
    dict(
        grid_size=3,
        use_shuffling=True,
        num_inversion_steps=50,
        inversion_prompt="",
        apply_inversion_on_grid=True,
    ),
]

controlnet_1 = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-depth", torch_dtype=torch.float16, cache_dir=".")
controlnet_2 = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16, cache_dir=".")

pipe = RAVEPipeline.from_pretrained(
    "SG161222/Realistic_Vision_V5.1_noVAE",
    controlnet=[controlnet_1, controlnet_2],
    torch_dtype=torch.float16,
    cache_dir=".",
).to("cuda")
pipe.enable_vae_slicing()

for param in experiment_params:
    for index, (video_, control_video_, prompt_) in enumerate(zip(video, control_video, prompt)):
        filename = f"rave_{index}_{'_'.join('{}-{}'.format(key, value) for key, value in param.items())}.gif"
        print(filename)
        video_ = video_
        control_video_ = [cv for cv in control_video_]
        output = pipe(
            video=video_,
            control_video=control_video_,
            prompt=prompt_,
            negative_prompt="worst quality, normal quality, low quality, low res, blurry, text, watermark, logo, banner, extra digits, cropped, jpeg artifacts, signature, username, error, sketch ,duplicate, ugly, monochrome, horror, geometry, mutation, disgusting",
            width=video_[0].size[0],
            height=video_[0].size[1],
            num_inference_steps=50,
            **param,
        )
        export_to_gif(output.frames, filename)
```
</details>

I have a feeling that there might be an issue with the DDIMInverseScheduler. I remember taking a look at the latents after the inversion was done, and it did not look as noisy as I expected. It definitely retained some aspects of the original image without completely turning into noise and I believe this is what's causing the weird outputs.

**Pull request closed without merging**
