### PR TITLE
[Pipeline] Enhancements to `AutoPipeline`

### PR DESCRIPTION
**Pull request by suzukimain**
# What does this PR do?

This PR adds the ability to automatically search for models from `civitai` and `huggingface` in AutoPipeline and enables the loading of single file checkpoints.

From #9986

> Example:
```python
pip install git+https://github.com/suzukimain/diffusers.git@Update_AutoPipeline
```

```python
# Search for Civitai
from diffusers import AutoPipelineForText2Image
pipe = AutoPipelineForText2Image.from_civitai("any").to("cuda")
image = pipe("cat").images[0]
image.save("cat.png")
```

```python
# Search for Huggingface
from diffusers import AutoPipelineForText2Image
pipe = AutoPipelineForText2Image.from_huggingface("any").to("cuda")
img = pipe("cat").images[0]
img.save("cat.png")
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@yiyixuxu @asomoza @bghira

### CODE REVIEW

**Comment by bghira** [comment]
cc @vladmandic check this out 😹 oh god @suzukimain you genius. thank you.

**Comment by vladmandic** [comment]
> cc @vladmandic check this out 😹 oh god @suzukimain you genius. thank you.

i have something similar, but this is pretty clean!

needs a bit of cleanup to actually use params - e.g., instead of
> model_path = f"/root/.cache/Civitai/{repo_id}/{version_id}/{file_name}"
use actual `cache_dir` param to construct path.
also, download resume-on-error is almost a necessity given the size of the models and how unreliable civitai can be at the times.

**Comment by yiyixuxu** [comment]
hi @suzukimain 

If you make this tool as separate repo, we are happy to add it to our doc and help promote it!

**Comment by suzukimain** [comment]
> hi @suzukimain
> 
> If you make this tool as separate repo, we are happy to add it to our doc and help promote it!


Originally, this PR was incorporated into `AutoPipeline` based on the repository below, so it is possible. 
However, since it was created as a hobby project, it might be necessary to implement the changes and organize the entire repository, as well as change the license.

github:  https://github.com/suzukimain/auto_diffusers

pypi:  https://pypi.org/project/auto-diffusers/

**Comment by bghira** [comment]
assuming huggingface doesnt want to support a competitor even if it benefits the user or this project. bummer

**Comment by suzukimain** [comment]
> assuming huggingface doesnt want to support a competitor even if it benefits the user or this project. bummer

Sorry. What do you mean by competitors?

**Comment by bghira** [comment]
CivitAI as a model hosting provider

**Comment by suzukimain** [comment]
Oh, I see

**Comment by yiyixuxu** [comment]
@suzukimain feel free to dress it up and write a nice introduction about it!
cc @asomoza here too! maybe we can use it to make diffusers node:)

**Comment by suzukimain** [comment]
> @suzukimain this is cool and I agree that it would work a lot better as an external tool with your library. Do you have plans for something similar with loras?

The functions `search_huggingface` and `search_civitai`, which search for hubs, are designed to support multiple tasks. 
Thus, you can support different tasks by simply changing the `model_type` argument.
However, `baseModel` and `types` are not yet supported by the Hugging Face API at this time and could not be implemented.


<a id="error_example"></a>
<details close>

By the way, the `baseModels` should be in [hf_api.model_info](https://github.com/huggingface/huggingface_hub/blob/7dc41b1b3e9769c57162728826bbe72e2e0dcbbb/src/huggingface_hub/hf_api.py#L2534), but I get an error.
```python
from huggingface_hub import hf_api

info = hf_api.model_info(
    "stable-diffusion-v1-5/stable-diffusion-v1-5",
    expand=["baseModels"]
)

print(info.baseModels)
# AttributeError: 'ModelInfo' object has no attribute 'baseModels'
```

</details>

https://github.com/huggingface/diffusers/blob/dbe8fcbd99f1d79fa977408b17160b4d3492a367/src/diffusers/pipelines/auto_pipeline.py#L783-L791


```python
from diffusers.pipelines.auto_pipeline import (
    search_huggingface,
    search_civitai,
) 

# Search Lora
Lora = search_civitai(
    "Keyword_to_search_Lora",
    model_type="LORA",
    base_model = "SD 1.5",
    download=True,
    )
# Load Lora into the pipeline.
pipeline.load_lora_weights(Lora)


# Search TextualInversion
TextualInversion = search_civitai(
    "EasyNegative",
    model_type="TextualInversion",
    base_model = "SD 1.5",
    download=True
)
# Load TextualInversion into the pipeline.
pipeline.load_textual_inversion(TextualInversion, token="EasyNegative")
```

**Comment by yiyixuxu** [comment]
cc @stevhliu, where should this go if we want to add a doc page about it (as an external library)?

**Comment by suzukimain** [comment]
Made it available for use as an external tool.  
The main changes are as follows:  
- Changed the license to `Apache-2.0`, the same as Diffusers.  
- Updated the downloader to `huggingface_hub.http_get` to support `resume-on-error`.
- Cache directory is now obtained by `os.path.expanduser`.

Made it as usable as possible in the same way as a pull request.

```python
pip install --quiet auto_diffusers

from auto_diffusers import EasyPipelineForText2Image

# Search for Huggingface
pipe = EasyPipelineForText2Image.from_huggingface("any").to("cuda")
img = pipe("cat").images[0]
img.save("cat.png")


# Search for Civitai
pipe = EasyPipelineForText2Image.from_civitai("any").to("cuda")
image = pipe("cat").images[0]
image.save("cat.png")

```
@yiyixuxu, @stevhliu, @bghira

**Comment by stevhliu** [comment]
I think you can add your project [here](https://huggingface.co/docs/diffusers/community_projects) and then link to the docs you're making in #9986

**Comment by suzukimain** [comment]
> I think you can add your project [here](https://huggingface.co/docs/diffusers/community_projects) and then link to the docs you're making in #9986

Based on [this advice](https://github.com/huggingface/diffusers/pull/10006#issuecomment-2499615649), I have made some revisions [here](https://github.com/suzukimain/auto_diffusers/blob/master/src/auto_diffusers/pipeline_easy.py). Is it okay to apply these changes?
I apologize for the inconvenience.

**Comment by suzukimain** [comment]
> > I think you can add your project [here](https://huggingface.co/docs/diffusers/community_projects) and then link to the docs you're making in #9986
> 
> Based on [this advice](https://github.com/huggingface/diffusers/pull/10006#issuecomment-2499615649), I have made some revisions [here](https://github.com/suzukimain/auto_diffusers/blob/master/src/auto_diffusers/pipeline_easy.py). Is it okay to apply these changes? I apologize for the inconvenience.

I intend to apply the changes in [this way](https://github.com/suzukimain/diffusers/blob/EasyPipeline/examples/model_search/README.md).

**Comment by suzukimain** [comment]
hi @stevhliu , What should I do with this PR?

**Comment by stevhliu** [comment]
I think this can be closed since we your project is here https://github.com/huggingface/diffusers/tree/main/examples/model_search now :)

**Comment by suzukimain** [comment]
hello @stevhliu 
Understood. Also, if possible, I would appreciate it if you could let me know how this matter will turn out.
> I think you can add your project [here](https://huggingface.co/docs/diffusers/community_projects) and then link to the docs you're making in #9986

**Comment by suzukimain** [comment]
Add this functionality to [auto_diffusers](https://pypi.org/project/auto-diffusers/) and close this as #9986 and #10358 have been merged. thank you!

**Pull request closed without merging**
