### PR TITLE
add reshape to fix use_memory_efficient_attention in flax

### LINKED ISSUE #7895: Flax's use_memory_efficient_attention is broken
### Describe the bug

I accidentally introduced a bug in this [PR](https://github.com/huggingface/diffusers/pull/5181) by making a condition on [this line](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/attention_flax.py#L238), which is needed when `use_memory_efficient_attention=True`.

Adding this bug to remind myself to put in a fix.

### Reproduction

Using [this example](https://github.com/huggingface/diffusers/blob/main/examples/research_projects/sdxl_flax/sdxl_single.py) but adding use_memory_efficient_attention=True in from_pretrained.

### Logs

_No response_

### System Info

N/A

### Who can help?

@pcuenca

### PR DESCRIPTION
**Pull request by entrpn**
# What does this PR do?

Fixes #7895

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [X] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@pcuenca

### CODE REVIEW

**Comment by sayakpaul** [comment]
@pcuenca a gentle ping here.

**Comment by a-r-r-o-w** [comment]
Gentle ping @pcuenca

**Review by pcuenca — APPROVED** [review]
Makes sense! Sorry for the super late review!

**Comment by pcuenca** [comment]
Failing tests are unrelated, merging.

**Comment by entrpn** [comment]
Thank you @pcuenca!

**Pull request merged**
