### PR TITLE
Fix os.path.join() to Path(..).as_posix() for Windows support

### PR DESCRIPTION
**Pull request by Bhavay-2001**
# What does this PR do?

Fixes #6585

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, is this correct now?

**Comment by yiyixuxu** [comment]
you need to import `Path`

**Comment by Bhavay-2001** [comment]
Hi @yiyixuxu , thanks for letting me know. I have updated the file again. Please review it once.
Also, should I make these changes in all the files in the diffusers repository?
Thanks

**Comment by Bhavay-2001** [comment]
Hi @yiyixuxu, can you please confirm me this once? I'll update the files accordingly. 
Thanks

**Comment by sayakpaul** [comment]
We need the code quality to pass before we can merge the PR.

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, can you please let me know how to improve upon that? I have made the necessary changes but don't have a clue on code quality. 
Thanks

**Comment by sayakpaul** [comment]
@Bhavay-2001 the logs from the CI make it quite clear why the tests are failing.

```
E   RuntimeError: Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
E   Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
E   No module named 'Path'
```

I would suggest taking a look and fixing them accordingly. 

But also do read https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md, it should already make you aware of the code quality issues and what to do with them.

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, I updated the file. How can I check for tests?

**Comment by sayakpaul** [comment]
The thing is that Unet concerned in this PR is already updated now. So, I suggest you target a separate file

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, so the file is updated now? Is this PR merged or are the changes done by some other contributor itself?

**Comment by sayakpaul** [comment]
Yeah `src/diffusers/loaders/unet.py` is updated now.

**Comment by sayakpaul** [comment]
Closing this as it has been already resolved.

**Comment by Bhavay-2001** [comment]
Hi @sayakpaul, some of my PRs are pending. Can you please merge them. They have been mentioned in the issue.

**Pull request closed without merging**
