### PR TITLE
Fix key error for dictionary with randomized order in convert_ldm_unet_checkpoint

### PR DESCRIPTION
**Pull request by yunseongcho**
# What does this PR do?

I found that for some model weights, the key values in the dictionary are not applied in order, and this can cause a potential KeyError.

For example, on line 560 of convert_from_ckpy.py, the key value of ["conv.bias", "conv.weight"] in output_block_list is "2", but if the order is first ({"2": ["conv.bias", "conv.weight"], "0": [...], ...}), then on line 563 the index is "0" instead of "2". This causes a key error. 

Because we get the value of unet_state_dict through index, not the key, a KeyError occur if the order of the output_block_list and index do not match.

To prevent this from happening, this PR ensures that index and key are in the same order.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@sayakpaul @yiyixuxu @DN6

### CODE REVIEW

**Comment by DN6** [comment]
@yunseongcho Would you mind sharing a checkpoint we could use to test with?

**Comment by yunseongcho** [comment]
I tried the PastelMix model 
https://civitai.com/models/5414/pastel-mix-stylized-anime-model

**Comment by yunseongcho** [comment]
This is not an error that happens all the time, it happens in some cases and not in others.

**Comment by aycaecemgul** [comment]
I have the same problem while I try to use [this model](https://civitai.com/models/85953/pixelstyleckpt) and this in img2img pipeline

**Comment by yunseongcho** [comment]
@DN6 
Hello,
Could I get your feedback? I'd love to hear your feedback

**Review by DN6 — APPROVED** [review]

**Comment by DN6** [comment]
Hi @yunseongcho sorry for the delay. Yes I'm okay to merge this.

**Pull request merged**
