### PR TITLE
Accept pooled_prompt_embeds in the SDXL Controlnet pipeline. Fixes an error if prompt_embeds are passed.

### PR DESCRIPTION
**Pull request by cmdr2**
Hi,

The SDXL Controlnet pipeline would fail to run if `prompt_embeds` was passed (instead of `prompt`), because the implementation wouldn't create the pooled embeds (and would fail later with a `NoneType does not have repeat method` error).

This copies the code from the other SDXL pipelines.

Thanks!

@sayakpaul @patrickvonplaten

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Cool!

**Review by patrickvonplaten — APPROVED** [review]

**Review by bghira — APPROVED** [review]

**Review by sayakpaul — APPROVED** [review]
Excellent. Do you think it might be worth to also add a test for this?

**Comment by cmdr2** [comment]
@sayakpaul Thanks. I've added a test, by copying the test from `test_stable_diffusion_xl.py`.

**Review by sayakpaul — APPROVED** [review]
Amazing!

**Comment by cmdr2** [comment]
Thanks! :)

**Pull request merged**
