### PR TITLE
[Dockerfiles] add: a workflow to check if docker containers can be built in case of modifications

### PR DESCRIPTION
**Pull request by sayakpaul**

### CODE REVIEW

**Comment by DN6** [comment]
What exactly would we be testing here? That the build completes?

**Comment by sayakpaul** [comment]
Yeah.

**Comment by DN6** [comment]
Can't we just run the existing workflow? Or just update the docker build workflow to run on change? Why add another workflow?

**Comment by sayakpaul** [comment]
> Can't we just run the existing workflow?

Integrating a change after ensuring it successfully passes is what I would like to keep in mind here. 

> Or just update the docker build workflow to run on change? Why add another workflow?

I can look into this.

**Comment by sayakpaul** [comment]
@DN6 turns out the workflow doesn't show up on the PR strangely, but you can see it here: https://github.com/huggingface/diffusers/actions/runs/8144706116/job/22259379215. I have also made the code simpler and a bit more explicit. So, would appreciate another review.

I explicitly changed a Dockerfile to test things out but will remove that change once you approve the PR.

**Comment by sayakpaul** [comment]
@DN6 good to merge?

**Pull request merged**
