### PR TITLE
[WIP] Remove unnecessary subclasses

### PR DESCRIPTION
**Pull request by sayakpaul**
This PR attempts to remove the subclasses which are not known to be used alongside the classes inheriting from them. Otherwise, it might confuse users. Let me give a couple of examples:

* `StableDiffusionControlNetPipeline` and its derivatives subclass from `LoraLoaderMixin` and `TextualInversionLoaderMixin`. But AFAIK no one really uses ControlNets with LoRA or textual inversion. 
* If we keep the classes this way, the documentation reflects them and readers might think how can ControlNets be leveraged with something like LoRA, textual inversion. 

Opening this PR to get quick thoughts. If there's a consensus, happy to extend it further.

### CODE REVIEW

**Comment by DN6** [comment]
Using Textual Inversion and LoRA with ControlNets are valid workflows right? 

 Are there any benefits to not having these inheritances present in the ControlNet pipeline? IMO, just because there is low usage at the moment, doesn't necessarily mean this will always be the case. I think if it isn't actively hurting the pipeline to have these in there, then we might want to consider keeping as is.

**Comment by sayakpaul** [comment]
Valid workflows yes. In retrospect, I concur with your thoughts. Can revisit if the community reports anything otherwise.

**Review by patrickvonplaten — COMMENTED** [review]
Nice thanks!

**Comment by sayakpaul** [comment]
@patrickvonplaten I closed the PR. Just double-checking if you saw https://github.com/huggingface/diffusers/pull/4577#issuecomment-1679931136 correctly.

**Comment by patrickvonplaten** [comment]
Cool!

**Pull request closed without merging**
