### PR TITLE
Device to use (e.g. cpu, cuda:0, cuda:1, etc.)

### PR DESCRIPTION
**Pull request by camenduru**

### CODE REVIEW

**Comment by camenduru** [comment]
fixes `"Error: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU." `https://huggingface.co/spaces/diffusers/convert-sd-ckpt/discussions/2

**Comment by camenduru** [comment]
I am also getting this for `make style`
```
@camenduru ➜ /workspaces/diffusers (map_location ✗) $ make style
black --preview examples scripts src tests utils
reformatted examples/textual_inversion/textual_inversion.py
reformatted examples/research_projects/intel_opts/textual_inversion/textual_inversion_bf16.py
reformatted examples/textual_inversion/textual_inversion_flax.py
reformatted scripts/convert_kakao_brain_unclip_to_diffusers.py
reformatted src/diffusers/modeling_flax_pytorch_utils.py
reformatted src/diffusers/models/cross_attention.py
reformatted src/diffusers/models/attention.py
reformatted src/diffusers/schedulers/scheduling_euler_ancestral_discrete.py
reformatted src/diffusers/schedulers/scheduling_euler_discrete.py
reformatted utils/custom_init_isort.py
reformatted tests/test_scheduler.py

All done! ✨ 🍰 ✨
11 files reformatted, 273 files left unchanged.
isort examples scripts src tests utils
make: isort: Command not found
make: *** [Makefile:59: style] Error 127
@camenduru ➜ /workspaces/diffusers (map_location ✗) $ 
```

**Review by patil-suraj — APPROVED** [review]
Thanks a lot for the PR, looks good!

**Comment by patil-suraj** [comment]
@camenduru think this is because the quality deps are not installed. You can install diffusers using 

`pip install -e ".[dev]"` which will take of installing all dev related deps.

**Comment by camenduru** [comment]
thanks @patil-suraj ❤

**Pull request merged**
