### PR TITLE
[lora] Allow finetuning text encoder with lora

### PR DESCRIPTION
**Pull request by orenwang**
Fine-tuning `text_encoder` along with `unet` can bring us much more fidelity in the results when training Dreambooth. With LoRA, my personal experiments have shown that this conclusion holds true. Hence this PR: 
- Passing `--train_text_encoder` to fine-tune model's `text_encoder` entirely
- Passing both `--train_text_encoder` and `--lora_text_encoder_only` only trains injected text encoder lora layers

For inference:
```python
pipe = DiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    text_encoder=CLIPTextModel.from_pretrained("path-to-output/text_encoder"),
    torch_dtype=torch.float16,
)
```

OR lora layers only:
```python
from train_dreambooth_lora import inject_lora_text_encoder_params

inject_lora_text_encoder_params(pipe.text_encoder, "path-to-output/pytorch_lora.text_encoder_weights.bin")
```

I do have a few noob questions left, and it would be appreciated if anyone can explain anything to me:
- I saw in [train_dreambooth.py](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth.py) that when training `text_encoder` should be always in full-precision. Why? Although in this PR I implemented it in full-precision to make it work, but I don't really understand what's going on to be honest.
- Currently I wrote everything in [train_dreambooth_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py) but it is not as beautiful as the `CrossAttnProcessor`. But to implement something like that, I would need to change library `transformers`... Is there a better way for this, or is current implementation alright (as an example)?

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
Thanks for the PR. 

I'm really not a fan of hijacking methods with `inject_lora_text_encoder_params` because one cannot cleanly load such weights afterwards and it opens the door for too much hacking IMO 

@patil-suraj wdyt?

**Comment by orenwang** [comment]
> I'm really not a fan of hijacking methods with `inject_lora_text_encoder_params` because one cannot cleanly load such weights afterwards and it opens the door for too much hacking IMO

Or maybe it makes sense to only allow training the whole `text_encoder` for now, which does not need any "hijacking"? Actually my personal use cases benefit most from this way anyway.

**Comment by patil-suraj** [comment]
Agree with Patrick, maybe we could try to see if PEFT can be used for this to do it cleanly https://github.com/huggingface/peft

**Comment by orenwang** [comment]
PEFT looks cool. I just tested its [train_dreambooth.py](https://github.com/huggingface/peft/blob/main/examples/lora_dreambooth/train_dreambooth.py) with `--train_text_encoder` and it actually gave me better results...

However, using PEFT means we have to use `set_peft_model_state_dict` to "inject" lora anyway during inference, not sure if this is any better:
```python
from peft import LoraModel, LoraConfig, set_peft_model_state_dict

lora_checkpoint_sd = torch.load("path-to-output")
text_encoder_lora_ds = {k.replace("text_encoder_", ""):v for k,v in lora_checkpoint_sd.items() if "text_encoder_" in k}
text_encoder_config = LoraConfig(**lora_config["text_encoder_peft_config"])
pipe.text_encoder = LoraModel(text_encoder_config, pipe.text_encoder)
set_peft_model_state_dict(pipe.text_encoder, text_encoder_lora_ds)
```

**Comment by patil-suraj** [comment]
Yes, the inference would be a bit hacky now , for example see https://huggingface.co/spaces/smangrul/peft-lora-sd-dreambooth/blob/main/inference.py

**Comment by sayakpaul** [comment]
The inference part has improved a bit in PEFT. This [example](https://github.com/huggingface/peft/blob/main/examples/image_classification/image_classification_peft_lora.ipynb) shows an end to end workflow. Does it provide sufficient entrypoints for you to adapt your changes such that it's less hacky? 

Thanks a lot btw, for your PR :)

**Comment by orenwang** [comment]
> The inference part has improved a bit in PEFT. This [example](https://github.com/huggingface/peft/blob/main/examples/image_classification/image_classification_peft_lora.ipynb) shows an end to end workflow. Does it provide sufficient entrypoints for you to adapt your changes such that it's less hacky?

I think the current problem is that PEFT itself is also hacky. Don't know if it would be sufficient enough for this PR to be merged by adapting PEFT's entrypoints.

> Thanks a lot btw, for your PR :)

You're too kind @sayakpaul

**Comment by sayakpaul** [comment]
Ccimg @pacman100 here.

**Comment by pacman100** [comment]
Hello, for more context, I considered following things but ended up making no changes to the PEFT LoRA example yet.

The new hf hub utils support for PEFT methods allows one to do: `unet.save_pretrained()` and `text_encoder.save_pretrained` but then on hub there will be 2 repos for single Dreambooth model with tiny weights. Hence, I ended up reverting to the current example wherein lora checkpoints for unet and text_encoder are combined so as to get only single checkpoint and single config for both the tuned unet and text_encoder which I think is more portable.

Below is the example of using newly added hub utils:
1. Saving
```
if accelerator.is_main_process:
        if args.use_lora:
            unet.peft_config.base_model_name_or_path = args.pretrained_model_name_or_path
            unet.save_pretrained(os.path.join(args.output_dir, "unet"), state_dict=accelerator.get_state_dict(unet))
            if args.train_text_encoder:
                text_encoder.peft_config.base_model_name_or_path = args.pretrained_model_name_or_path
                text_encoder.save_pretrained(os.path.join(args.output_dir, "text_encoder"),
                                             state_dict=accelerator.get_state_dict(text_encoder))
```

2. loading:
```
def load_and_set_lora_ckpt(peft_model_id, device, dtype):
    config = PeftConfig.from_pretrained(os.path.join(peft_model_id, "unet"))
    pipe = StableDiffusionPipeline.from_pretrained(config.base_model_name_or_path, torch_dtype=dtype).to(device)

    # Load the U-Net LoRA model
    pipe.unet = PeftModel.from_pretrained(pipe.unet, os.path.join(peft_model_id, "unet"))
    
    if len(os.listdir(peft_model_id))>1:
        #load the text encoder LoRA model
        pipe.text_encoder = PeftModel.from_pretrained(pipe.text_encoder, os.path.join(peft_model_id, "text_encoder"))
    
    if dtype in (torch.float16, torch.bfloat16):
        pipe.unet.half()
        pipe.text_encoder.half()
    
    pipe.to(device) 
    return pipe

pipe = load_and_set_lora_ckpt(peft_model_id, "cuda", torch.float16)
```

**Comment by orenwang** [comment]
> @orenwang, what are your thoughts on this, i.e., using hf hub utils to save the unet and text_encoders separately and then loading them back instead of having them be available in single ckpt and config (the current example version)?

Agree. "... unet and text_encoders separately and then loading them back..." sounds better! @pacman100

**Comment by pacman100** [comment]
but my only concern is that it would lead to 2 repos per dreambooth training (1 unet + 1 text_encoder) on HF hub and hence I haven't changed anything yet for dreambooth example.

https://huggingface.co/smangrul/text_encoder 
https://huggingface.co/smangrul/unet

@orenwang,  feel free to raise PR on PEFT if you find a better way of serializing both unet and text_encoder so that they are part of single hf hub repo, I think one might have to mici the way pipeline saves multiple models in a given folder/hf hub repo

**Comment by evancasey** [comment]
This would really be a great addition to the library since without fine-tuning the text encoder it's quite difficult to do human faces well with LoRA.

I've tried the PR and it works, but now I want to change alpha for the text encoder...any ideas on how to add support for this?

**Comment by patrickvonplaten** [comment]
Hmm this is really difficult because text encoder resides in `transformers` and we cannot really hack into it. 
How does pivotal tuning compare to LoRA with text encoder? See point 3. here for explanation on pivotal tuning: https://github.com/cloneofsimo/lora#lengthy-introduction

**Comment by patrickvonplaten** [comment]
Otherwise we could instead add this script to the research folder: https://github.com/huggingface/diffusers/tree/main/examples/research_projects but I'm not in favor of putting training scripts that inject layers like this into the official examples

**Comment by orenwang** [comment]
Closing this for now because I can't see a solution that is good enough here.

**Pull request closed without merging**
