### PR TITLE
Fix save_path bug in textual inversion training script

### PR DESCRIPTION
**Pull request by Yead**
# What does this PR do?
fix the bug of model save_path in `safe_serialization=True` mode in textual inversion training
otherwise, when you trained with `args.no_safe_serialization=False` but saved with ".bin" file,  it will conflict with pipe loading strategy.
 
## Details:
After training with `diffusers/examples/textual_inversion/textual_inversion.py` with `args.no_safe_serialization=False`, you will get a file named  `learned_embeds.bin`

when you want to load your embedding into your pipe:
```
pipe.load_textual_inversion(save_dir, weight_name="learned_embeds.bin", use_safetensors=True)
```
 the name "learned_embeds.bin" will get stuck judging on this condition [weight_name.endswith(".safetensors")](https://github.com/huggingface/diffusers/blob/main/src/diffusers/loaders.py#L795) then caused `UnpicklingError: Memo value not found at index 0`

if you already got several `learned_embeds*.bin` using previous code, `cp learned_embeds.bin learned_embeds.safetensors` can work as a temporary solution but is inelegant.
```
pipe.load_textual_inversion(save_dir, weight_name="learned_embeds.safetensors", use_safetensors=True)
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by DN6** [comment]
Thanks for flagging @Yead. I'll take a look at this.

**Review by patrickvonplaten — APPROVED** [review]
Nice `safetensors` is indeed supported for loading and in this case we should rename it just like done here. Great job @Yead !

**Comment by patrickvonplaten** [comment]
We probably just need to update the failing example test here - could you take a look @Yead ? :-)

**Comment by Yead** [comment]
Oh sorry I missed the test part, and just update them

**Review by DN6 — APPROVED** [review]
LGTM 👍🏽

**Pull request merged**
