### PR TITLE
[Docs] fix docstring for issue #709

### LINKED ISSUE #709: [Documentation] "r" as method docstring for forward
### Describe the bug

As seen [here](https://github.com/huggingface/diffusers/blame/688031c592a08832387761971f1e6ca504a5900b/src/diffusers/models/unet_2d.py#L173), the forward docstrings of the UNet classes have "r" as the method description. Why is this?

https://github.com/huggingface/diffusers/blob/688031c592a08832387761971f1e6ca504a5900b/src/diffusers/models/unet_2d.py#L173-L180

I think @kashif you added these?

### Reproduction

_No response_

### Logs

_No response_

### System Info

Not needed, documentation issue.

### PR DESCRIPTION
**Pull request by kashif**
fixes #709

### CODE REVIEW

**Comment by natolambert** [comment]
Oh interesting. What does the `r` before do?

**Comment by kashif** [comment]
@natolambert I believe it makes a python raw string...

**Comment by natolambert** [comment]
@kashif, while we are here, is this line right too?

https://github.com/huggingface/diffusers/blob/688031c592a08832387761971f1e6ca504a5900b/src/diffusers/models/unet_2d.py#L180-L183

Not sure what that or statement is.

**Review by patrickvonplaten — APPROVED** [review]
Thanks! 

Feel free to merge @kashif :-)

**Pull request merged**
