### PR TITLE
[Lora] fix lora fuse unfuse

### PR DESCRIPTION
**Pull request by patrickvonplaten**
Fixes sequentially fusing & unfusing LoRAs.
Fixes: https://github.com/huggingface/diffusers/issues/5000

### CODE REVIEW

**Comment by apolinario** [comment]
It works!

**Comment by apolinario** [comment]
Found another case where it fails: 
```py
pipe.load_lora_weights("Pclanglais/TintinIA")
pipe.fuse_lora()
pipe.unfuse_lora()
pipe.unload_lora_weights()

pipe.load_lora_weights("ProomptEngineer/pe-balloon-diffusion-style")
pipe.fuse_lora()
pipe.unload_lora_weights()
pipe.unfuse_lora()

pipe.load_lora_weights("ostris/crayon_style_lora_sdxl")
pipe.fuse_lora()
pipe.unload_lora_weights()
pipe.unfuse_lora()
```

This time with this error 
```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-5-545257b7c3f8>](https://localhost:8080/#) in <cell line: 14>()
     12 pipe.fuse_lora()
     13 pipe.unload_lora_weights()
---> 14 pipe.unfuse_lora()

2 frames
[/usr/local/lib/python3.10/dist-packages/diffusers/loaders.py](https://localhost:8080/#) in _unfuse_lora(self)
    127         dtype, device = fused_weight.dtype, fused_weight.device
    128 
--> 129         w_up = self.w_up.to(device=device).float()
    130         w_down = self.w_down.to(device).float()
    131 

AttributeError: 'NoneType' object has no attribute 'to'
```

**Comment by patrickvonplaten** [comment]
Sweet this seems to be fixed no? I'll add a quick test and then we can merge this I think

**Comment by apolinario** [comment]
Yes I added the same fix to `loaders.py` and I think that made it

**Comment by patrickvonplaten** [comment]
Cool, this one should be good to merge then

**Pull request merged**
