### PR TITLE
[addresses issue #1642] add add_noise to scheduling-sde-ve 

### PR DESCRIPTION
**Pull request by aengusng8**
This PR adds `add_noise` method to `scheduling_sde_vp.py` (addresses issues https://github.com/huggingface/diffusers/issues/1642)

My implementation is derived from the below author's codebase 
https://github.com/yang-song/score_sde_pytorch/blob/ef5cb679a4897a40d20e94d8d0e2124c3a48fb8c/losses.py#L109-L117

### CODE REVIEW

**Comment by 42Shawn** [comment]
Wow! The add_noise function is very helpful for me, could you share this part of code with me? I will be really appreciative!

**Comment by aengusng8** [comment]
Hi @42Shawn , just go to **_Files changed_** tab and copy the code.

**Review by patrickvonplaten — APPROVED** [review]
Thanks!

**Comment by 42Shawn** [comment]
Hi @aengusng8, another question is about how to utilize the add_noise in scheduling-sde-ve. In the examples/unconditional_generation, I have changed the scheduler and pipeline into ve_sde, and used this add_noise in this line: 
https://github.com/huggingface/diffusers/blob/2533f92532b4d48723df7cd5d1de67b53b7fffe5/examples/unconditional_image_generation/train_unconditional.py#L422 . 

But the generated images are completed noise. Should I transfer the noisy_images into another form and then feed them into the loss function?

**Comment by aengusng8** [comment]
Hi @PKURio and @42Shawn, I already tested and visualized this method before opening this PR, and it works smoothly. Sorry for your problem, I will double-check and reply to you.

**Comment by 42Shawn** [comment]
Hi, Thanks @aengusng8! I think the noise_images directly by your add_niose module are correct, but there are some gaps between  score function in ve-sde and noise estimator in ddpm. If you @PKURio  want, we can discuss more on WeChat (mine is: shangyuzhang).

**Comment by aengusng8** [comment]
@42Shawn Note that the `timesteps` of ScoreSdeVeScheduler range from `1` to **very small** `9.9998e-6` which is different from other schedulers in Diffuser (the range is usually from 1 to 1000). 

I am not sure if this is related to your problem, but it might help.

**Comment by 42Shawn** [comment]
Thanks again for your kind reply @aengusng8 , but I am confused. I mean in the add_noise module, sigma is indexed with sigmas = self.discrete_sigmas.to(original_samples.device)[timesteps]. If timesteps are not integers, how can we realize that?

**Comment by PKURio** [comment]
> Hi, Thanks @aengusng8! I think the noise_images directly by your add_niose module are correct, but there are some gaps between score function in ve-sde and noise estimator in ddpm. If you @PKURio want, we can discuss more on WeChat (mine is: shangyuzhang).

Thanks :-) I have added you.

**Comment by PKURio** [comment]
> 

Yes. That's the difference. _Timesteps_ in DDPM is more like index, while in ScoreSDE is more like the real time between [eps, 1]. I have changed the code according to [https://colab.research.google.com/drive/120kYYBOVa1i0TD85RjlEkFjaWDxSFUx3?usp=sharing#scrollTo=YyQtV7155Nht](url) but still get noise image.
Could you share the training & sampling test code? It will be easier to follow your idea :-)

**Pull request merged**
