### PR TITLE
Update train_text_to_image_lora.py

### PR DESCRIPTION
**Pull request by haofanwang**
This PR fixes https://github.com/huggingface/diffusers/issues/2459.

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks much!

**Comment by sayakpaul** [comment]
@haofanwang could you check following https://github.com/huggingface/diffusers/issues/2460#issuecomment-1441145756 helps with the code quality check being failed?

**Comment by haofanwang** [comment]
Done. @sayakpaul

**Review by yiyixuxu — APPROVED** [review]
Thanks!

**Pull request merged**
