### PR TITLE
refactor(scripts): `params` and `conv_shortcut`

### PR DESCRIPTION
**Pull request by ryanrussell**
Signed-off-by: Ryan Russell <git@ryanrussell.org>

This one has functional implications.

@pcuenca -- I don't believe either of these `scripts` were doing what they were intended to do. 
- `create_ldm_bert_config()` -- Was calling a bad object path...
- Please let me know if the replace was intentionally mis-spelled and I'm missing context.

Best,
Ryan

### CODE REVIEW

**Comment by ryanrussell** [comment]
Also, should

```pytthon
        new_item = new_item.replace("conv_shortcut", "conv1")
        new_item = new_item.replace("in_shortcut", "conv_shortcut")
```

be 

```python
        new_item = new_item.replace("in_shortcut", "conv_shortcut")
        new_item = new_item.replace("conv_shortcut", "conv1")
```


instead? (Should `in_shortcut` end up as `conv_shortcut` or `conv1`)?

**Comment by pcuenca** [comment]
Hi @anton-l could you please take a look here? :)

**Comment by anton-l** [comment]
Hi @ryanrussell! The naming here really depends on the structure of the original checkpoints. I'm off this week, but would you like to investigate and try to convert the original [DDPM](https://heibox.uni-heidelberg.de/d/01207c3f6b8441779abf/) and SD checkpoints with and without your changes? :)

**Review by patil-suraj — COMMENTED** [review]
The changes stable diffusion script look good to me. For the DDPM part would be awesome if you could try converting the checkpoint.

**Comment by ryanrussell** [comment]
Hey @patil-suraj .. Sorry for being a bit slow on this. I'm on the road this week, it is on my todo list. 

One question -- do you know where I could locate a sample config?

```bash
python scripts/convert_ddpm_original_checkpoint_to_diffusers.py  --checkpoint_path models/diffusion_cifar10_model/model-790000.ckpt 
usage: convert_ddpm_original_checkpoint_to_diffusers.py [-h] --checkpoint_path CHECKPOINT_PATH --config_file CONFIG_FILE --dump_path DUMP_PATH
convert_ddpm_original_checkpoint_to_diffusers.py: error: the following arguments are required: --config_file, --dump_path

```

There are some references to a `config.json` that I'm unable to find.

```bash
src/diffusers/utils/__init__.py:CONFIG_NAME = "config.json"
```
It looks like this is config has number of variables if you check the codebase for `grep -r ' config.get'`

**Comment by patrickvonplaten** [comment]
Here is a sample config if you still need one :-) 
https://huggingface.co/google/ddpm-bedroom-256/blob/main/config.json

**Pull request closed without merging**
