### PR TITLE
Fix `num_images_per_prompt>1` with Skip Guidance Layers in `StableDiffusion3Pipeline`

### LINKED ISSUE #10085: RuntimeError with LyCORIS, Batch Inference and skip_guidance_layers
### Describe the bug

A `RuntimeError` occurs when using the following combination:

* SD3 
* Batch inference (`num_images_per_prompt > 1`)
* LyCORIS 
* `skip_guidance_layers` is set

The error message is: `"RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0"`

It seems that batch inference (`num_images_per_prompt > 1`) does not work in conjunction with `skip_guidance_layers`.

### Reproduction

This code snippet produces the error:

```python
self.pipe = StableDiffusion3Pipeline.from_pretrained(
    "stabilityai/stable-diffusion-3-medium-diffusers", 
    torch_dtype=torch.bfloat16
    )

self.pipe.scheduler = FlowMatchEulerDiscreteScheduler.from_config(
    self.pipe.scheduler.config,
    timestep_spacing="trailing",
    shift=3.0
    )
self.pipe.to("cuda")

lora_scale = 1.0
wrapper, _ = create_lycoris_from_weights(lora_scale, my_lora, self.pipe.transformer)
wrapper.merge_to()

image = self.pipe(
    prompt=request.prompt,
    num_inference_steps=request.num_inference_steps,
    num_images_per_prompt=2,  # Batch inference
    output_type="pil",
    generator=torch.Generator(device="cuda").manual_seed(42),
    guidance_scale=request.guidance_scale,
    width=request.width,
    height=request.height,
    skip_guidance_layers=[7, 8, 9],  # Doesn't seem to work with batching
).images[0]
```

Commenting out `skip_guidance_layers` resolves the error.

**Expected behavior**

Batch inference should work correctly even when `skip_guidance_layers` is used with LyCORIS.

### Logs

_No response_

### System Info

**Environment**

*  CUDA Version: 12.4
*  Python version: 3.12.1 (main, Jan 11 2024, 10:22:40) [GCC 10.2.1 20210110]
*  Diffusers version: https://github.com/huggingface/diffusers.git@99c0483b67427de467f11aa35d54678fd36a7ea2
*  The specific LyCORIS model and inference method used from Bghira: https://huggingface.co/bghira/sd35m-photo-mixedres-cL-sS3-noOverride?not-for-all-audiences=true

### Who can help?

@sayakpaul

### PR DESCRIPTION
**Pull request by hlky**
# What does this PR do?

https://github.com/huggingface/diffusers/issues/10085#issuecomment-2511977629 for some further details.

Fixes #10085

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

cc @sayakpaul @japppie

### CODE REVIEW

**Comment by hlky** [comment]
Note there is some small visual difference between `num_images_per_prompt=1` and `num_images_per_prompt=2`:

num_images_per_prompt=1
minimal_1
num_images_per_prompt=2
minimal

This also occurs without `skip_guidance_layers`:

num_images_per_prompt=1
minimal_no
num_images_per_prompt=2
minimal_no_2

**Review by yiyixuxu — APPROVED** [review]
thanks a lot for the fix! @hlky 
so the implementation was wrong before and just happen to got broadcasted inside one of the AdaLayerNorm

**Comment by yiyixuxu** [comment]
can we add more tests here https://github.com/huggingface/diffusers/blob/cd344393e20f321ccb569fb893b227caf7d28235/tests/pipelines/stable_diffusion_3/test_pipeline_stable_diffusion_3.py#L123
to test num_images_per_prompt =2  for SLG with and without CFG

**Comment by yiyixuxu** [comment]
feel free to merge once tested is add (or you can add test in a separate PR!)

**Comment by hlky** [comment]
Yes it's easily missed, important to check batch support for new models etc. going forward.

Looks like tests for `num_images_per_prompt` are missing from some other pipelines like Flux as well so I'll add them all in another PR.

**Comment by sayakpaul** [comment]
> Looks like tests for num_images_per_prompt are missing from some other pipelines like Flux as well so I'll add them all in another PR.

@hlky 

I think it would make sense to introduce/revisit the pipeline tester mixin to see how we can make it more general so that this is tested by default without us having to write it for every pipeline/model test suite. WDYT? 

Feel free to ping me and @DN6 if you need further ideas here.

**Pull request merged**
