### PR TITLE
Control SDXL classifier-free guidance scale with step granularity

### PR DESCRIPTION
**Pull request by jamarju**
# What does this PR do?

Please consider this PR that allows step-wise granular control of `StableDiffusionXLPipeline`'s classifier-free guidance scale by passing a list of `num_inference_steps` floats instead of a single float in the `guidance_scale` argument.

image

image

image

By allowing granular control over CFG scales you can, for example, disable CFG on the last denoising steps and save a considerable amount of compute without a noticeable degradation of the image in most of the cases, as depicted above.

The above images were generated with SDXL conditioned on 3 different prompts over 30 denoising steps. On each column, CFG was set to 6.0 during the first S steps and then to 0.0 during the last 30-S steps for S in (0, 5, 10, 15, 20, 25, 30) by passing `guidance_scale = [6.0] * S + [0.0] * (30-S)`.

Every 5 steps in which CFG is turned off cut generation time down by 7% on A100 hardware so, as an example, if you disable CFG for the last 15 steps, you save 21% of compute.

@patrickvonplaten  @sayakpaul

### CODE REVIEW

**Comment by vladmandic** [comment]
this would also be a no-op if my suggestion of having pipeline state passed back as reference in per-step callback so callback could modify such values as it deemed fit.

**Comment by patrickvonplaten** [comment]
This should also be solved by: https://github.com/huggingface/diffusers/issues/4778 

@yiyixuxu can you try to prioritize this a bit?

**Comment by patrickvonplaten** [comment]
Fully agree that we need better support for a schedule-type of design

**Comment by vladmandic** [comment]
i think this should now be resolved.

**Comment by yiyixuxu** [comment]
you can achieve this with callback now - checkout our doc here https://huggingface.co/docs/diffusers/main/en/using-diffusers/callback

**Pull request closed without merging**
