### PR TITLE
[Fix] added case for text_encoder_projection_dim to handle the default None

### LINKED ISSUE #5824: Problematic default value for `text_encoder_projection_dim` in `get_add_time_ids()` method of `StableDiffusionXLPipeline`
### Describe the bug

The `get_add_time_ids()` method of `StableDiffusionXLPipline` currently has the following defaults defined in line 573 of `stable_diffusion_xl/pipeline_stable_diffusion_xl.py`:
```
def _get_add_time_ids(
        self, original_size, crops_coords_top_left, target_size, dtype, text_encoder_projection_dim=None
    ):
```

The problem is in line 579:
```
self.unet.config.addition_time_embed_dim * len(add_time_ids) + text_encoder_projection_dim
```
If `text_encoder_projection_dim` assumes the default value of `None`, then you end up adding an `int` to a `None`, which is an undefined operation resulting in a `TypeError`

### Reproduction

```
import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16
)
pipe = pipe.to("cuda")

with torch.no_grad():
    time_ids = pipe._get_add_time_ids([512, 512], [0,0], [512,512], dtype=torch.float16)
```

### Logs

```shell
File "/home/textual_inversion_xl.py", line 765, in main
    time_ids = pipe._get_add_time_ids([512, 512],[0,0],[512,512],dtype=unet.dtype).to(unet.device)
  File "/opt/conda/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py", line 579, in _get_add_time_ids
    self.unet.config.addition_time_embed_dim * len(add_time_ids) + text_encoder_projection_dim
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```
```


### System Info

```
- `diffusers` version: 0.23.0
- Platform: Linux-5.15.0-88-generic-x86_64-with-glibc2.31
- Python version: 3.10.13
- PyTorch version (GPU?): 2.1.0 (True)
- Huggingface_hub version: 0.17.3
- Transformers version: 4.35.1
- Accelerate version: 0.24.1
- xFormers version: 0.0.22.post7
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No
- ```

### Who can help?

@yiyixuxu @sayakpaul @DN6 @patrickvonplaten

### PR DESCRIPTION
**Pull request by charchit7**
# What does this PR do?
This PR adds a case for **text_encoder_projection_dim** to handle the default None value

Fixes #5824
text_encoder_projection_dim default case

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by charchit7** [comment]
Fixes : #5824

**Review by yiyixuxu — APPROVED** [review]
thank you!

**Comment by yiyixuxu** [comment]
ohh can you run `make quality` so that quality test passes?

**Comment by charchit7** [comment]
@yiyixuxu sorry missed it. Started checks again.

**Comment by yiyixuxu** [comment]
`make fix-copies` too

**Comment by charchit7** [comment]
Hey @DN6 please review it.

**Review by yiyixuxu — APPROVED** [review]

**Comment by patrickvonplaten** [comment]
Sorry I don't understand the PR here exactly, why do we need to support this use case? Note that `text_encoder_projection_dim` should never be "not-None" for SDXL and the function `_get_add_time_ids` is private, so I don't fully understand why we should change it? Or is there a common use case in which this function should be called? 

Also cc @tyler-tomita

**Comment by charchit7** [comment]
Hey @patrickvonplaten ,

As per @tyler-tomita The issue #5824 arises when the text_encoder_projection_dim parameter is left as its default value of None in the _get_add_time_ids method. In this scenario, the expression self.unet.config.addition_time_embed_dim * len(add_time_ids) + text_encoder_projection_dim results in a TypeError, as it attempts to add an integer to None.

While I understand that the _get_add_time_ids method is private, this issue surfaces when using the StableDiffusionXLPipeline in certain configurations, as demonstrated in the provided reproduction steps in the issue. The proposed change by @yiyixuxu aims to handle this specific scenario, ensuring that the function works as expected even when the text_encoder_projection_dim is not explicitly provided.

**Comment by yiyixuxu** [comment]
@charchit7 I

I think what @patrickvonplaten want to find out here is is there any reason we would call `_get_add_time_ids` with `text_encoder_projection_dim = None`  

However if `text_encoder_projection_dim` should never be "not-None" for SDXL, it doe not make sense to default it to `None` no? maybe make it a required argument instead?

**Comment by charchit7** [comment]
Got it @patrickvonplaten , @yiyixuxu, thank you :) 
Shall I update the code to make it required argument?

**Comment by yiyixuxu** [comment]
@charchit7 

I would wait for @patrickvonplaten feedbacks, I'm not sure why it is set to be the default None value to begin with

**Comment by charchit7** [comment]
Got it. Thanks @yiyixuxu. 
Hey @patrickvonplaten please let me know. If no changes required I'll close the PR.

**Comment by charchit7** [comment]
Hello @patrickvonplaten, could you please guide me on what to do here? I apologize for any haste; this is my first pull request, and I'm quite excited about it. :)

**Comment by patrickvonplaten** [comment]
Hey @charchit7,

Could we maybe close this PR and try to move to another one - I think the commit history is sadly borked here and I also don't think the change is necessary really :-)

**Comment by charchit7** [comment]
I'll close this. @patrickvonplaten . No worries!

**Pull request closed without merging**
