### PR TITLE
TST Fix LoRA test that fails with PEFT >= 0.7.0

### LINKED ISSUE #6185: [LoRA fusion tests] SDXL LoRA tests with fusion when using `peft`
Currently, the following test is failing:

```bash
RUN_SLOW=1 pytest tests/lora/test_lora_layers_peft.py::LoraSDXLIntegrationTests::test_sdxl_1_0_fuse_unfuse_all
```

Error:

```bash

self = <test_lora_layers_peft.LoraSDXLIntegrationTests testMethod=test_sdxl_1_0_fuse_unfuse_all>

    def test_sdxl_1_0_fuse_unfuse_all(self):
        pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=torch.float16)
        text_encoder_1_sd = copy.deepcopy(pipe.text_encoder.state_dict())
        text_encoder_2_sd = copy.deepcopy(pipe.text_encoder_2.state_dict())
        unet_sd = copy.deepcopy(pipe.unet.state_dict())
    
        pipe.load_lora_weights(
            "davizca87/sun-flower", weight_name="snfw3rXL-000004.safetensors", torch_dtype=torch.float16
        )
    
        fused_te_state_dict = pipe.text_encoder.state_dict()
        fused_te_2_state_dict = pipe.text_encoder_2.state_dict()
        unet_state_dict = pipe.unet.state_dict()
    
        for key, value in text_encoder_1_sd.items():
>           self.assertTrue(torch.allclose(fused_te_state_dict[key], value))
E           KeyError: 'text_model.encoder.layers.0.self_attn.k_proj.weight'
```

When I investigated `fused_te_state_dict` with the following:

```python
targeted_layers = list(filter(lambda x: "text_model.encoder.layers.0.self_attn" in x, fused_te_state_dict.keys()))
print(targeted_layers)
```

I got:

```bash
['text_model.encoder.layers.0.self_attn.k_proj.base_layer.weight', 'text_model.encoder.layers.0.self_attn.k_proj.base_layer.bias', 'text_model.encoder.layers.0.self_attn.k_proj.lora_A.default_0.weight', 'text_model.encoder.layers.0.self_attn.k_proj.lora_B.default_0.weight', 'text_model.encoder.layers.0.self_attn.v_proj.base_layer.weight', 'text_model.encoder.layers.0.self_attn.v_proj.base_layer.bias', 'text_model.encoder.layers.0.self_attn.v_proj.lora_A.default_0.weight', 'text_model.encoder.layers.0.self_attn.v_proj.lora_B.default_0.weight', 'text_model.encoder.layers.0.self_attn.q_proj.base_layer.weight', 'text_model.encoder.layers.0.self_attn.q_proj.base_layer.bias', 'text_model.encoder.layers.0.self_attn.q_proj.lora_A.default_0.weight', 'text_model.encoder.layers.0.self_attn.q_proj.lora_B.default_0.weight', 'text_model.encoder.layers.0.self_attn.out_proj.base_layer.weight', 'text_model.encoder.layers.0.self_attn.out_proj.base_layer.bias', 'text_model.encoder.layers.0.self_attn.out_proj.lora_A.default_0.weight', 'text_model.encoder.layers.0.self_attn.out_proj.lora_B.default_0.weight']
```

So the error makes sense to me. @BenjaminBossan @younesbelkada could you take a look here?

### PR DESCRIPTION
**Pull request by BenjaminBossan**
# What does this PR do?

Resolves #6185 (LoRA test failing with PEFT >= 0.7.0).

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks much! Works for me in light of https://github.com/huggingface/diffusers/issues/6185#issuecomment-1861519806.

**Comment by BenjaminBossan** [comment]
@sayakpaul Not sure what the norms for for diffusers. Shall I (squash and) merge this PR or do I wait for a diffusers core maintainer to do that?

**Comment by sayakpaul** [comment]
@patrickvonplaten's https://github.com/huggingface/diffusers/issues/6185#issuecomment-1861277283

**Comment by sayakpaul** [comment]
@patrickvonplaten a gentle ping here.

**Review by patrickvonplaten — APPROVED** [review]
Thanks!

**Pull request merged**
