### PR TITLE
Manually move UNet to cuda/cpu

### PR DESCRIPTION
**Pull request by pcuenca**
Temporary hack for #2266, meant for discussion.

Note memory consumption is higher than when using the previous method through `accelerate`. I'm not sure if this is because all inner modules are being loaded/unloaded as inference progresses.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@pcuenca can you show some memory stats before / after the PR as well as the code snippet you use?

**Comment by pcuenca** [comment]
The code is based on the one @keturn posted in the issue:

```Python
import torch
from diffusers import StableDiffusionPipeline
from timeit import timeit

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    revision="fp16", torch_dtype=torch.float16,
)
pipe.enable_sequential_cpu_offload()

reps = 3
print(timeit(lambda: pipe("a jockey riding a dragon on mars"), number=reps) / reps)
```

I'm checking memory simply looking at the plot from `nvtop`. These are my observations:

|                 | Peak GPU RAM | Inference Time |
|-----------------|:------------:|---------------:|
| Without this PR |    3.6 GB    |         21.42s |
| With this PR    |    5.2 GB    |          4.34s |
| No offloading   |    6.2 GB    |          3.18s |

**Comment by patrickvonplaten** [comment]
Ok yeah actually that makes sense since `cpu_offload` also moves all submodules to CPU. So I think we probably shouldn't make that change. Instead we should add a new function:

```python
enable_model_offload
```

That is a trade-off between cpu_offload and no offload?

**Comment by pcuenca** [comment]
> Ok yeah actually that makes sense since `cpu_offload` also moves all submodules to CPU. So I think we probably shouldn't make that change. Instead we should add a new function:
> 
> ```python
> enable_model_offload
> ```
> 
> That is a trade-off between cpu_offload and no offload?

I'm not sure I follow, do you mean having two functions:

- `enable_sequential_cpu_offload` (same as we already had)
- `enable_model_offload` that does not use accelerate, but manually moves between CPU and CUDA depending on the pipeline stage
?

**Comment by patrickvonplaten** [comment]
@pcuenca, yes I think the best solution here is to keep `enable_sequential_cpu_offload` exactly the way it is and then add a new `enable_model_cpu_offload` method that keeps much more speed performance but pays in VRAM memory usage. I think for `enable_model_cpu_offload` we can directly make use of the new accelerate PR here: https://github.com/huggingface/accelerate/pull/1045 . Think the new `enable_model_cpu_offload` in combination with `enable_attention_slicing` or xformers will at least free 1 GB for users while being still very fast. 

As @sgugger said "pure" cpu_offload should be kept for extreme use cases where we try to save maximum GPU memory and thus leave it the way it is . 


Wdyt?

**Comment by pcuenca** [comment]
@patrickvonplaten I agree! I'll finalize it tomorrow morning.

**Pull request closed without merging**
