### PR TITLE
Allow Flax model to save as pytorch (If converted from pytorch)

### PR DESCRIPTION
**Pull request by Lime-Cakes**
Allows saving mapping_dict when loading pytorch model through from_pretrained(from_pt=True), which can be used to save flax model in pytorch bin format. 

Add new option `return_mapping_dict` to from_pretrained. When set to True (default False), mapping_dict will be returned as well. The mapping_dict can be passed to new method `save_as_pytorch_bin`, allowing fax params dict to be converted and saved as pytorch bin.

Currently config isn't saved, as current config loading for flax seemed outdated, as FutureWarning is triggered. I'll see if I can implement saving config as well, after flax models got config loading updated.

### CODE REVIEW

**Comment by camenduru** [comment]
(If converted from pytorch) oh no 🥺

**Comment by Lime-Cakes** [comment]
The same mapping dict could probably be use to convert any flax model back to pytorch. I only tested with unet. But all model converted through 'convert_pytorch_state_dict_to_flax' could be reversed.

The same model class should generate the same mapping_dict, so old models can be converted back as well. But for native pytorch loading flax model, check pull#1241

**Comment by camenduru** [comment]
@patrickvonplaten knows the [code](https://github.com/huggingface/transformers/blame/main/src/transformers/modeling_flax_pytorch_utils.py#L224-L352) how transformers can do? why diffusers need mapping_dict but transformers not also every human being on this planet is waiting for [this ](https://huggingface.co/camenduru/plushies) model to be converted to pytorch 😋 @patrickvonplaten help!

**Comment by averad** [comment]
Use `from_flax=True` to load this model from those weights.

**Comment by Lime-Cakes** [comment]
> `from_flax=True` https://huggingface.co/docs/transformers/main_classes/model#transformers.PreTrainedModel.from_pretrained

Thanks! I didn't know it was implemented. Does from_flax work with diffusers?

**Comment by camenduru** [comment]
@averad `from_flax=True` for transformers we need diffusers 😋

**Comment by averad** [comment]
> @averad `from_flax=True` for transformers we need diffusers 😋

Just providing documentation for when @pcuenca inevitably pops in here.

**Comment by patrickvonplaten** [comment]
Maybe also cc @yiyixuxu here :-)

**Comment by camenduru** [comment]
hi @Lime-Cakes please change the title people not reading the `(If converted from pytorch)` part like me I also not read that part and I realized I need mapping_dict when I setup everything 😋 maybe like "🚨 If converted from pytorch 🚨 Allow Flax model to save as pytorch"

**Comment by camenduru** [comment]
download

**Comment by Lime-Cakes** [comment]
No longer needed after #1900 merge. Closing. Use from_pretrained(from_flax=True) instead.

**Pull request closed without merging**
