### PR TITLE
fix/doc-code: Updating to the latest version parameters

### PR DESCRIPTION
**Pull request by Aisuko**
# What does this PR do?

Fixes # (issue)

Same issue with https://github.com/huggingface/accelerate/issues/1559 in the basic training tutorial. So, we need to update the parameter to the `project_dir`.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by pcuenca — APPROVED** [review]
Looks good to me! Double-checking with @muellerzr just in case.

@muellerzr I see that the property is called `project_dir` now, but `logging_dir` still exists: https://github.com/huggingface/accelerate/blob/main/src/accelerate/utils/dataclasses.py#L367, https://github.com/huggingface/accelerate/blob/main/src/accelerate/accelerator.py#L487 and is referenced in the docs: https://github.com/huggingface/accelerate/blob/main/docs/source/usage_guides/tracking.md?plain=1#L89-L94

Since instantiating `Accelerator` with `logging_dir` is no longer supported, are there still use cases that require both `project_dir` and `logging_dir`? If so, what would be the recommended way to set them up?

**Comment by muellerzr** [comment]
@pedrogengo the `logging_dir` is setup for a case where your whole project is stored in `my_dir` but your logs should be saved in `my_dir/logs` (such as `tensorboard`) but because it's more fine-grained, we reduced it to `project_dir` and you set this in the `ProjectConfiguration`

**Comment by muellerzr** [comment]
E.g. see https://github.com/huggingface/diffusers/pull/3714/files, while this solution _can_ be right, there's a better way setting it with `ProjectConfiguration`

(Otheriwse I'm OOO until Tuesday and I can look closer then 😉 )

**Comment by pcuenca** [comment]
oops, sorry! Thank you, enjoy your time off :)

**Comment by pcuenca** [comment]
I think it should be safe to merge this PR, as the current docs won't work, but then maybe create a new PR to document the better process demonstrated in the PR Zach pointed out: https://github.com/huggingface/diffusers/pull/3714/files. In my opinion we should also slightly update the accelerate docs when they refer to tensorboard (https://github.com/huggingface/accelerate/blob/main/docs/source/usage_guides/tracking.md?plain=1#L89-L94). I can work on those tasks later.

Copying @patrickvonplaten too for visibility.

**Comment by patrickvonplaten** [comment]
Sounds good! Agree that updating the docs would be best here. Also cc @stevhliu

**Pull request merged**
