### PR TITLE
[Kandinsky tests] add `is_flaky` to test_model_cpu_offload_forward_pass 

### PR DESCRIPTION
**Pull request by sayakpaul**
Check https://huggingface.slack.com/archives/C065E480NN9/p1706602235715929

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]

**Comment by sayakpaul** [comment]
Failing test is unrelated. See; https://huggingface.slack.com/archives/C04L3MWLE6B/p1706601893641009

**Comment by sayakpaul** [comment]
Nope `is_flaky` didn't solve it either :/

**Review by yiyixuxu — COMMENTED** [review]
do we still want this knowing that it did not fix the test? this slows down the tests, no?

**Comment by DN6** [comment]
I think just bump up the precision to 8e-4

**Pull request merged**
