### PR TITLE
IP-Adapter for StableDiffusionControlNetImg2ImgPipeline

### PR DESCRIPTION
**Pull request by charchit7**
# What does this PR do?

Part of #5884 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?
@yiyixuxu @patrickvonplaten

### CODE REVIEW

**Comment by charchit7** [comment]
Working Code : 

```
from diffusers import StableDiffusionControlNetImg2ImgPipeline, ControlNetModel,LCMScheduler
import torch
from diffusers.utils import load_image
from PIL import Image
import cv2
import numpy as np
from transformers import CLIPVisionModelWithProjection, CLIPImageProcessor

image_encoder = CLIPVisionModelWithProjection.from_pretrained(
    "h94/IP-Adapter", 
    subfolder="models/image_encoder",
    torch_dtype=torch.float16,
).to("cuda")

controlnet_model_path = "lllyasviel/control_v11f1p_sd15_depth"
controlnet = ControlNetModel.from_pretrained(controlnet_model_path, torch_dtype=torch.float16)

pipeline = StableDiffusionControlNetImg2ImgPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",controlnet=controlnet,
    image_encoder = image_encoder, torch_dtype=torch.float16, safety_checker=None)
pipeline.to("cuda")

image = load_image("https://instagram.flko7-1.fna.fbcdn.net/v/t51.2885-15/300237810_757670065344305_1728511144050236696_n.jpg?stp=dst-jpg_e15&efg=eyJ2ZW5jb2RlX3RhZyI6ImltYWdlX3VybGdlbi4xMDgweDEzNDkuc2RyIn0&_nc_ht=instagram.flko7-1.fna.fbcdn.net&_nc_cat=105&_nc_ohc=6Nh4KFTgb24AX9V2UQ3&edm=ACWDqb8BAAAA&ccb=7-5&ig_cache_key=MjkwNzY2MzIyMDYzMTYxNTExMQ%3D%3D.2-ccb7-5&oh=00_AfD5b5LzEVpCvS_YJHi_nwCd2DF7s1vbEHvhx5tzMe9Jtg&oe=656458D2&_nc_sid=ee9879")
cn_image = load_image("https://huggingface.co/datasets/YiYiXu/testing-images/resolve/main/depth.png")
ip_image = load_image("https://huggingface.co/datasets/YiYiXu/testing-images/resolve/main/girl.png")

#Load images
# Resize images
image = image.resize((512, 768))
ip_image = ip_image.resize((512, 768))
cn_image = cn_image.resize((512, 768))

# Load ip-adapter
pipeline.load_ip_adapter("h94/IP-Adapter", subfolder="models", weight_name="ip-adapter_sd15.bin")

# Generate image
generator = torch.Generator(device="cpu").manual_seed(33)
images = pipeline(
    prompt='best quality, high quality', 
    image = image,
    control_image=cn_image,
    ip_adapter_image=ip_image,
    negative_prompt="monochrome, lowres, bad anatomy, worst quality, low quality", 
    num_images_per_prompt=1, 
    num_inference_steps=50,
    generator=generator,
    strength=0.5,
    controlnet_conditioning_scale=0.5,
).images
images[0].save("charchit_test.png")
```
---
Resulted Image : 
image

Reference Image ( Which I Drew 🤗 )
image

IP-Image : 
image

depth-Image : 
`depth_map = load_image("https://huggingface.co/datasets/YiYiXu/testing-images/resolve/main/depth.png")`

**Comment by charchit7** [comment]
Adapters are fun :)

**Comment by yiyixuxu** [comment]
@charchit7 

I updated your example code and left a comment there (I hope it is ok) 😁
2 feedbacks:
1. we do not need to load image_encoder manually if it is in the ip-adapter weight folder, it will be loaded automatically
2. I think for this controlnet img2img example to work, it makes more sense and will work better to have your `control_image` to be the the condition extracted from the `image`. let's give it a try? 

PS. I love your drawings!!

**Comment by charchit7** [comment]
Hey @yiyixuxu Thank you so much :) 
I'll add this in 3 days. I hope that's okay.

**Comment by charchit7** [comment]
Hi @yiyixuxu thank you for the comment It really improves the image. 

---
Here's a test 2 with different image I tried : 

| Final Result                        | Ip-Image                           | Image which i drew :)                      |
| ----------------------------------- | ------------------------------------------------- | --------------------------------------------------- |
| image | image |
image |

**Comment by yiyixuxu** [comment]
@charchit7 can we run `make fix-copies` so the quality test pass? 
we merged 2 PRs that will affect yours too

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by yiyixuxu** [comment]
cc @sayakpaul for a final review

**Review by sayakpaul — APPROVED** [review]
Works for me! Have you tried using IP-Adapters for ControlNet img2img? Would be curious to see results 👁️

**Comment by charchit7** [comment]
Hey @sayakpaul  which one? Even I want to test more results. Seems a good direction for research too.

**Comment by sayakpaul** [comment]
The pipeline affected in this PR where you added IP-Adapters to?

**Comment by sayakpaul** [comment]
Ah I see the results above. Nevermind.

**Comment by charchit7** [comment]
Yeah, no problem.

**Comment by charchit7** [comment]
Thanks @yiyixuxu @sayakpaul one more PR done!

**Pull request merged**
