### PR TITLE
Add vae_roundtrip.py example

### PR DESCRIPTION
**Pull request by thomaseding**
# What does this PR do?

Adds `examples/inference/vae_roundtrip.py` to demonstrate VAE inference without any other models or pipelines.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

This just introduces a new demo example file. No need to update documents or update tests.

### CODE REVIEW

**Comment by yiyixuxu** [comment]
why do we need this?

cc @sayakpaul

**Comment by thomaseding** [comment]
You dont need it. If you think this is not a worthwhile example script, we can just close the ticket. I just submitted this because it took me a while to figure out how to use the VAE due to its non-tensor return values. And I already wrote the script in the first place to evaluate VAE how good/bad the standard SD VAEs are with heavily aliased images.

**Comment by sayakpaul** [comment]
> I just submitted this because it took me a while to figure out how to use the VAE due to its non-tensor return values. 

You can mitigate that by specifying `return_dict=False` in your VAE call. 

I am okay accommodating this script under the `research_projects` folder, if you're down.

**Comment by thomaseding** [comment]
> I am okay accommodating this script under the `research_projects` folder, if you're down.
Sure why not. Alternatively there is also `examples/community` if that is better than placing under `examples/research_projects/vae`

**Comment by sayakpaul** [comment]
`examples/community` are for pipelines that can be loaded with the "custom_pipeline" argument. So, I think `research_projects` is a better location.

**Comment by sayakpaul** [comment]
Will merge after the CI is green. Sorry for the delay.

**Comment by sayakpaul** [comment]
We need to make sure the code quality test passes.

**Comment by sayakpaul** [comment]
@asomoza WDYT about this example?

**Comment by asomoza** [comment]
I like the idea but maybe focus it to a more practical use case? 

This is used a lot to store the embeddings of the images, so probably a `encode and save` and a `decode` functionality would help the community more.

But I also think it's fine as an example if people struggle on how to do this, since we now have the community scripts, maybe this can be simplified and put there?

**Comment by sayakpaul** [comment]
> But I also think it's fine as an example if people struggle on how to do this, since we now have the community scripts, maybe this can be simplified and put there?

Yes exactly. I wouldn't mind having it under `research_projects` really. 

@thomaseding, apologies for the delay on our side. Could you maybe fix the styling problems so that we can merge this?

**Comment by thomaseding** [comment]
I can't figure out why the style linter is complaining about unsorted imports.

**Comment by sayakpaul** [comment]
You can either search for the solutions and use them for the codes provided there "F403", for example. Or you can do "no qa" like done here:

https://github.com/huggingface/diffusers/blob/7bfc1ee1b2cb0961ff111f50a9d096816e4dd921/benchmarks/base_classes.py#L24

**Comment by sayakpaul** [comment]
@asomoza could you give this a final review and merge?

**Review by asomoza — APPROVED** [review]

**Comment by asomoza** [comment]
Thanks a lot!

**Pull request merged**
