### PR TITLE
[Typo] Update md files

### PR DESCRIPTION
**Pull request by luchaoqi**
fix hyperlink error/typo

# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by stevhliu — APPROVED** [review]
Thanks for the fix! There are a couple other [files](https://github.com/search?q=repo:huggingface/diffusers%20../../using-diffusers/schedulers.md&type=code) with this error, would you like to also fix those in this PR?

**Comment by luchaoqi** [comment]
@stevhliu thanks! All fixed, feel free to let me know if you have any other suggestions.

**Comment by stevhliu** [comment]
Sorry I wasn't clear before, but the `.md` at the end needs to be removed otherwise the link won't work. The link in InstructPix2Pix should work, but if you take a look at the files [here](https://github.com/search?q=repo:huggingface/diffusers%20../../using-diffusers/schedulers.md&type=code), they won't work.

**Comment by luchaoqi** [comment]
Yes, `.md` should be removed at the end of links

**Pull request merged**
