### PR TITLE
Fix unipc use_karras_sigmas exception - fixes huggingface/diffusers#4580

### LINKED ISSUE #4580: unipc schedule throws exception when use_karras_sigmas=True
### Describe the bug

unipc scheduler throws exception when use_karras_sigmas=True

File "/usr/local/src/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 642, in __call__
    self.scheduler.set_timesteps(num_inference_steps, device=device)
  File "/usr/local/src/diffusers/src/diffusers/schedulers/scheduling_unipc_multistep.py", line 239, in set_timesteps
    sigmas = self._convert_to_karras(in_sigmas=sigmas, num_inference_steps=num_inference_steps)
  File "/usr/local/src/diffusers/src/diffusers/configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'UniPCMultistepScheduler' object has no attribute '_convert_to_karras'

Its just missing the _convert_to_karras and _sigma_to_t functions.
I will submit a pull request shortly

### Reproduction

specify use_karras_sigmas=True when creating unipc scheduler, then use scheduler

### Logs

_No response_

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-5.10.0-23-amd64-x86_64-with-glibc2.35
- Python version: 3.10.6
- PyTorch version (GPU?): 2.1.0a0+b5021ba (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.32.0.dev0
- Accelerate version: 0.22.0.dev0
- xFormers version: 0.0.21+db0e439.d20230810
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

_No response_

### PR DESCRIPTION
**Pull request by reimager**
# What does this PR do?

Fixes an exception when using the unipc scheduler with use_karras_sigmas=True
Fixes #4580

Core library:

- Schedulers: @williamberman and @patrickvonplaten

### CODE REVIEW

**Comment by sayakpaul** [comment]
Could you also add a test for covering this scenario?

**Review by sayakpaul — APPROVED** [review]
Sweet! 

@williamberman could you give this a look too?

**Review by williamberman — APPROVED** [review]
neato!

**Comment by sayakpaul** [comment]
Thanks for your contributions!

**Pull request merged**
