### PR TITLE
Fix Flax flip_sin_to_cos

### PR DESCRIPTION
**Pull request by akashgokul**
Adding flip_sin_to_cos arg for FlaxTimesteps and passing it to get_sinusodial_embeddings.

Currently, FlaxTimesteps hardcodes the order of the sin and cosine embeddings ([1](https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/embeddings_flax.py#L92)). However, in the UNet2DConditionModel the order is an argument (set to True when loaded from StableDiffusion pretrained ckpt/config) which is currently not supported in Flax.

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
This looks good to me! @kashif @pcuenca could you take a look as well?

**Comment by kashif** [comment]
thank you @akashgokul I actually had a look at this and it's good from my end! Unet is the only place where the sin/cos is flipped so that is also fine. Let me update the branch and run the tests.

**Review by kashif — APPROVED** [review]
LGTM!

**Review by pcuenca — APPROVED** [review]
LGTM!

**Pull request merged**
