### PR TITLE
img2img.multiple.controlnets.pipeline

### PR DESCRIPTION
**Pull request by mikegarts**

### CODE REVIEW

**Comment by mikegarts** [comment]
Regression for single controlnet use case: 
https://colab.research.google.com/drive/1CfJO2rNKDPMJeLrTXVi7e03-QE0VruwE?usp=sharing

Multiple controlnets use case:
https://colab.research.google.com/drive/1e-yLAoLFUlGBSQqcGGHaMjiaOOdTlw3L?usp=sharing


image

:)

**Comment by mikegarts** [comment]
This is not the ideal way to handle the controlnet_guidance_{start,stop} (addition by @hyowon-ha). 
Right now they control the start/stop cond globally and one can't pass a list to control each controlnet separately.

Ideally, imho, - it would be cool to be able to pass them (as lists) to MultiControlNetModel imho (the same way controlnet_conditioning_scale is handled) - but this requires a modification of the MultiControlNetModel.

**Comment by mikegarts** [comment]
@williamberman since you reviewed a similar pr of mine, tagging you (sorry in advance if you are not the person)

**Review by patrickvonplaten — APPROVED** [review]
Looks good to me!

**Comment by mikegarts** [comment]
> @mikegarts could you take a quick look as well? :-)

Sure, but since I proposed the pr in the first place I might be a little biased here :-)

**Pull request merged**
