### PR TITLE
[WIP] Add Latent Consistency Model Img2Img Pipeline

### PR DESCRIPTION
**Pull request by dg845**
# What does this PR do?

This PR adds `LatentConsistencyModelImg2ImgPipeline`, a text-guided image-to-image version of `LatentConsistencyModelPipeline` based on the [community pipeline](https://github.com/huggingface/diffusers/blob/main/examples/community/latent_consistency_img2img.py) by @nagolinc.

Based on PR #5477, which was originally in response to issue #5462.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten
@sayakpaul
@nagolinc
@luosiallen

### CODE REVIEW

**Comment by nagolinc** [comment]
Did you do any experiments before changing this line?

https://github.com/huggingface/diffusers/blob/main/examples/community/latent_consistency_img2img.py#L326

https://github.com/huggingface/diffusers/pull/5559/files#diff-205b2ad5eac653752af8760192d8315263a5aec4203451d38f3b1db2b20551b9R672


The reason why I am passing the strength to set_timesteps (and using a custom scheduler) is that I found for very small number of timesteps the method here (https://gist.github.com/nagolinc/6e0d3960a81714d13b821e3694d673d6) does not work well.

**Comment by dg845** [comment]
Thanks for the info @nagolinc! I haven't done any experiments yet. I will try to see if I can handle the `strength` logic within the pipeline code itself to avoid passing it to `set_timesteps` (which I think would modify the scheduler API). I guess this might require changes to how `LatentConsistencyModelImg2ImgPipeline.get_timesteps` and `LCMScheduler.set_timesteps` are implemented.

> The reason why I am passing the strength to set_timesteps (and using a custom scheduler) is that I found for very small number of timesteps (n=4) the method here (https://gist.github.com/nagolinc/6e0d3960a81714d13b821e3694d673d6) does not work well.

Just to clarify, does "not work well" mean that the code runs into errors, or that the generated images are low quality? I'm running into some errors when testing on different timesteps with the code in [86adad0](https://github.com/huggingface/diffusers/pull/5559/commits/86adad02051c399417cf2c52c3259819dcf563d6), but it might be because there are still some other bugs that I haven't found yet.

**Comment by nagolinc** [comment]
The images look bad:

using 1st method (https://gist.github.com/nagolinc/6e0d3960a81714d13b821e3694d673d6)



lcm_0Untitled


using 2nd method (https://gist.github.com/nagolinc/53c395d8cd70a852b03fca4eb273923f)
lcm_1Untitled

here's a notebook I was using to test out the two methods

https://github.com/nagolinc/notebooks/blob/main/lcm%20img2img.ipynb

**Comment by dg845** [comment]
Hi @patrickvonplaten, since #5632 has been merged, does this PR still make sense?

**Comment by sayakpaul** [comment]
Yeah, I think we can safely close it.

**Comment by dg845** [comment]
Closing due to #5632 being merged.

**Pull request closed without merging**
