### PR TITLE
Ext analytic dpm

### PR DESCRIPTION
**Pull request by kashif**

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
+ also it'd be nice to add a pipeline test

**Comment by kashif** [comment]
yes exactly @patrickvonplaten I will next try it out... perhaps I should mark this WIP till then?

**Comment by patil-suraj** [comment]
Hey @kashif , sorry to only come to this now. Let us know if you need any help with tests :)

**Comment by patrickvonplaten** [comment]
Could we move this to: https://github.com/huggingface/diffusers/tree/main/src/diffusers/experimental and add some links to the original paper?

**Comment by kashif** [comment]
yes sure! let me close this and make a new PR if that is ok?

**Comment by patrickvonplaten** [comment]
Sure btw also totally fine to drop this one or do you think it's very important?

**Comment by kashif** [comment]
yes, let's drop it as better schedulers are already in.

**Pull request closed without merging**
