### PR TITLE
Fix an error when DPM Solver Single Step contains duplicate timesteps

### PR DESCRIPTION
**Pull request by cmdr2**
Uses the de-duplication logic applied to the other samplers in https://github.com/huggingface/diffusers/pull/2969

I think this sampler got missed?

This change fixes an error when duplicate timesteps are created with the karras flag: `ValueError: only one element tensors can be converted to Python scalars`

@patrickvonplaten @sayakpaul 

Thanks!

### CODE REVIEW

**Comment by cmdr2** [comment]
I'm really not sure how to fix the non-passing test. It seems to be due to the order_list, which causes the order to stay at 2 (instead of 1), which results in the `sample` not getting assigned to `self.sample`.

**Comment by patrickvonplaten** [comment]
I think this is related: https://github.com/huggingface/diffusers/pull/4187

Could you take a look @yiyixuxu ?

**Comment by yiyixuxu** [comment]
Thanks for your PR @cmdr2 :)

We are trying to see if we can move away from the de-duplicate logic altogether in this PR https://github.com/huggingface/diffusers/pull/4187 

will keep you updated! 

YiYi

**Comment by cmdr2** [comment]
Thanks @yiyixuxu! Sounds good, looks like a better path. I noticed the index_counter approach in DPM Solver SDE as well.

**Comment by cmdr2** [comment]
This error has not been resolved, and the other PR hasn't been closed either (it's been marked as stale).

**Comment by yiyixuxu** [comment]
fixed in https://github.com/huggingface/diffusers/pull/4986

**Pull request closed without merging**
