### PR TITLE
Added --save_every option in dreambooth script.

### PR DESCRIPTION
**Pull request by lukovnikov**
Added --save_every option to the dreambooth training script. In contast to --checkpointing_steps, it saves the model where the final model will be stored and does so independently of checkpointing settings. It is intended to make sure the model is saved at smaller intervals than checkpointing.
This behavior cannot be replicated with existing options afaik, if you set a small checkpoint interval, you'll end up with many copies (each ~4GB), so you'll have to set a limit on the number of checkpoints, which will prevent you from recovering deeper checkpoints. So I think this additional option is a nice simple way to make sure the model is saved more regularly. Personally, I'm using this to trigger a generation server to generate images in a separate process using `watchdog` in order to not slow down the trainer.

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
Cool looks good to me :-) 

@williamberman mind taking a look here as well?

**Comment by patrickvonplaten** [comment]
@williamberman gentle ping here

**Comment by patrickvonplaten** [comment]
@williamberman @sayakpaul can you take a look here?

**Comment by williamberman** [comment]
Appreciate this! But actually, the recommended way of limiting the number of saved checkpoints should be with the `--checkpoints_total_limit` flag

**Comment by sayakpaul** [comment]
> Appreciate this! But actually, the recommended way of limiting the number of saved checkpoints should be with the `--checkpoints_total_limit` flag

But it still doesn't work expected, no? See: https://github.com/huggingface/diffusers/issues/2466

**Pull request closed without merging**
