### PR TITLE
[Community Pipelines] Update lpw_stable_diffusion pipeline

### LINKED ISSUE #3008: lpw_stable_diffusion community pipeline passes invalid combination of arguments to torch.randn
### Describe the bug

When using `lpw_stable_diffusion` pipeline, it passes an invalid combination of arguments into `torch.randn`. Problem still persists while using `cpu`.

### Reproduction
```py
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained('Linaqruf/anything-v3.0', custom_pipeline="lpw_stable_diffusion").to("mps")
image = pipe(
    prompt='test',
    width=512,
    height=512,
    num_inference_steps=10,
    num_images_per_prompt=3,
    generator=[torch.Generator(device="mps").manual_seed(i) for i in range(3)]
).images[0]
```
### Logs

```shell
File "/Users/test/.cache/huggingface/modules/diffusers_modules/git/lpw_stable_diffusion.py", line 638, in prepare_latents
    latents = torch.randn(shape, generator=generator, device="cpu", dtype=dtype).to(device)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: randn() received an invalid combination of arguments - got (tuple, dtype=torch.dtype, device=str, generator=list), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```

### System Info

diffusers 0.14.0, pytorch 2.0.0, MacOS M1, python 3.11.2

### PR DESCRIPTION
**Pull request by SkyTNT**
Adapt to the latest version of diffusers and fixes #3008

### CODE REVIEW

**Comment by SkyTNT** [comment]
fixes #3182

**Comment by patrickvonplaten** [comment]
Great - thanks for the fix!

**Comment by ghunkins** [comment]
Hi, @patrickvonplaten this broke active `diffusers`, can you roll back please? Active services are breaking.

**Comment by williamberman** [comment]
Hey @SkyTNT sorry have to briefly revert this PR. I think because of how community pipelines get installed, we have to maintain compatibility with previous diffusers versions. Either that or we have to better document what the expectations are for installing then _or_ pin the installed version.

We'll be able to re-merge this PR once we pin those down :) 

https://github.com/huggingface/diffusers/issues/3199#issuecomment-1518739355

**Comment by bubooK90** [comment]
> Adapt to the latest version of diffusers and fixes #3008

FANTASTIC!

**Pull request merged**
