### PR TITLE
fix: enable unet_3d_condition to support time_cond_proj_dim

### PR DESCRIPTION
**Pull request by yhZhai**
# What does this PR do?

This PR adds an argument `time_cond_proj_dim` to UNet3DConditionModel (the same as UNet2DConditionModel), and thus it enables the time_embedding module to create a cond_proj module.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by yhZhai** [comment]
> Thanks for the PR. Is this for a use case? Just curious.

Hi, I encountered this problem when trying to replace the UNet2DConditionModel with UNet3DConditionModel in [consistency model training example](https://github.com/huggingface/diffusers/blob/main/examples/consistency_distillation/train_lcm_distill_sd_wds.py). In the original code, `time_cond_proj_dim` is [passed to the 2D UNet](https://github.com/huggingface/diffusers/blob/4330a747d457ff2af1ba89e94c57a6e19efffdb9/examples/consistency_distillation/train_lcm_distill_sd_wds.py#L935), and is used to create a new linear layer [here](https://github.com/huggingface/diffusers/blob/4330a747d457ff2af1ba89e94c57a6e19efffdb9/src/diffusers/models/unets/unet_2d_condition.py#L268). In this way, the 2D consistency model can takes the guidance scale as a conditional input.

This PR enables the consistency model training example to support 3D Unet.

**Review by sayakpaul — APPROVED** [review]
I am okay with the change. Thanks!

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Review by DN6 — APPROVED** [review]

**Comment by sayakpaul** [comment]
@yhZhai please ping us once the CI run is complete.

**Comment by sayakpaul** [comment]
Sorry this needs to be run again because previously, the CI was broken (for an internal mistake). Should hopefully be fixed 🤞

**Comment by yhZhai** [comment]
@sayakpaul Hi, could you please take a look at the CI test result? Thanks!

**Comment by sayakpaul** [comment]
Thank you for your contributions!

**Pull request merged**
