### PR TITLE
Add bit diffusion [WIP]

### PR DESCRIPTION
**Pull request by kingstut**

### CODE REVIEW

**Comment by kingstut** [comment]
Run fast tests / MPS tests on Apple M1 (pull_request) succeed locally but not on GitHub Actions

**Comment by patrickvonplaten** [comment]
Hey @kingstut sorry for being so slow here? Is this PR ready for a final review? :-) 

Could you maybe delete the folders that were accidentally created during testing? Also could you add some example code to: https://github.com/huggingface/diffusers/blob/main/examples/community/README.md ? :-)

**Comment by kingstut** [comment]
@patrickvonplaten Yes, deleted test folders and added to README

**Review by patrickvonplaten — APPROVED** [review]
Perfect thanks a lot for the PR :-)

**Pull request merged**
