### PR TITLE
Set datasets temporary upper version 2.20.0

### PR DESCRIPTION
**Pull request by albertvillanova**
# What does this PR do?

This PR sets `datasets` temporary upper version to 2.20.0, so that the CI is fixed and it does not block other PRs.

Note that in the latest `datasets` release, a breaking change was introduced for security reasons: https://github.com/huggingface/datasets/releases/tag/2.20.0
> Datasets with a Python loading script now require passing `trust_remote_code=True` to be used
- See discussion in: https://github.com/huggingface/diffusers/pull/8528#issuecomment-2172360584

This PR should be reverted once, the underlying issue (mandatory passing of `trust_remote_code=True`) is addressed.

CC: @sayakpaul 

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sayakpaul** [comment]
Cc: @asomoza @yiyixuxu

**Comment by albertvillanova** [comment]
Note that the CI error is unrelated: it is due to the release of `numpy` 2.0.0 made yesterday.

**Comment by lhoestq** [comment]
I merged https://huggingface.co/datasets/hf-internal-testing/fill10/discussions/1 to fix the CI, I believe we can close this PR

**Comment by sayakpaul** [comment]
Thanks

**Pull request closed without merging**
