### PR TITLE
Fixed incorrect width/height assignment in StableDiffusionDepth2ImgPi…

### PR DESCRIPTION
**Pull request by antoche**
…peline when passing in tensor

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@patil-suraj could you check this?

**Review by patrickvonplaten — COMMENTED** [review]
@antoche can you give a bit more background why this change, I'm a bit surprised that we need this. Usually `height` and `width` are in the same order whether it's PIL or not

**Comment by antoche** [comment]
Hi Patrick, the image layout on torch tensors is BxCxHxW, so ``image[0].shape[-2:]`` is in the order ``height, width``, not ``width, height``. On the other hand, ``PIL.Image.size`` returns 2-tuple ``(width, height)``. So the previous code was incorrectly mixing up width and height (which would only be noticed when passing in non-square tensors as input).

This change fixes this bug and makes the code consistent with the rest of the diffusers, see for example
- https://github.com/huggingface/diffusers/blob/3231712b7da66f9c1b160f2d5363b186b03daafe/src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion_superresolution.py#L112
- https://github.com/huggingface/diffusers/blob/e4c356d3f62158936d8031a74a8793d5162f7bb4/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py#L283

**Comment by patrickvonplaten** [comment]
Hey @antoche,

Thanks a lot for explaining further - you're 100% right! 

For future reference, in `diffusers` we should always have the `... H x W ...` layout for PyTorch and Numpy and always have `... W x H ... ` for PIL. This can also be seen by PIL automatically flipping the axis e.g.:

```py
import numpy as np
import PIL.Image

height = 384
width = 512
image_np = np.ones(height, width, 3)

image = PIL.Image.fromarray(image_np)
image.sive
# gives (512, 384) => (width, height)
```

Thanks a lot for the PR @antoche !

**Pull request merged**
