### PR TITLE
fix link in the docs

### PR DESCRIPTION
**Pull request by coding-famer**
# What does this PR do?

Fix a link in the docs, which used to be `hf.co/docs/datasets` and will be directed to `https://huggingface.co/docs/diffusers/main/en/training/hf.co/docs/datasets`.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@stevhliu @sayakpaul

### CODE REVIEW

**Review by hlky — COMMENTED** [review]
@coding-famer Thanks for spotting this! Looks like there are some other links with the [same issue](https://github.com/search?q=repo%3Ahuggingface%2Fdiffusers+path%3A%2F%5Edocs%2F+%2F%5C%5D%5C%28%5Ba-z%5D%2B%5C.%5Ba-z%5D%2B%2F&type=code) that we can address here or with a follow up PR.

**Comment by coding-famer** [comment]
> @coding-famer Thanks for spotting this! Looks like there are some other links with the [same issue](https://github.com/search?q=repo%3Ahuggingface%2Fdiffusers+path%3A%2F%5Edocs%2F+%2F%5C%5D%5C%28%5Ba-z%5D%2B%5C.%5Ba-z%5D%2B%2F&type=code) that we can address here or with a follow up PR.

@hlky fixed.

**Review by hlky — APPROVED** [review]
Awesome! The additional fixes are greatly appreciated 🤗

**Review by stevhliu — APPROVED** [review]
Thanks!

**Pull request merged**
