### PR TITLE
fix: flagged_images implementation

### PR DESCRIPTION
**Pull request by justinmerrell**
Flagged images would be set to the blank image instead of the original image that contained the NSF concept for optional viewing. #845

### CODE REVIEW

**Comment by justinmerrell** [comment]
For the action that failed, I have no clue what `1 file would be reformatted, 301 files would be left unchanged.` is indicating as the error.

**Comment by patrickvonplaten** [comment]
@manuelbrack could you by any chance give this PR a review? :-)

**Comment by manuelbrack** [comment]
@patrickvonplaten Yes I can give a review. I'll try to finish it within the week.

**Comment by manuelbrack** [comment]
Sorry for the late reply. 
PR looks could to me and should be ready to merge.

**Comment by manuelbrack** [comment]
@justinmerrell Regarding your question on the failed check.
Please have a look at the contribution guidelines:  https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md#start-contributing-pull-requests

I guess you just forgot to run ```make style``` before committing your changes.

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
