### PR TITLE
EulerAncestral add `rescale_betas_zero_snr`

### PR DESCRIPTION
**Pull request by Beinsezii**
Implements the `rescale_betas_zero_snr` field on EulerAncestralDiscreteScheduler, using the same implementation as regular euler seen in #6024.

Once again I upcast the samples for the duration of `step()` as it significantly improves the output quality at no performance cost. I leave the ancestral noise as the model's dtype to preserve existing seeds, but this could be changed to float32 as well to make seeds mostly deterministic across model dtypes.

`#Copy from` points to DDIM again, and the UT is the same as established ddim/euler.

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]
thank you!

**Comment by sayakpaul** [comment]
@yiyixuxu is this good to be merged?

**Comment by yiyixuxu** [comment]
@sayakpaul LGTM!

**Comment by sayakpaul** [comment]
Thank you for your contributions!

**Pull request merged**
