### PR TITLE
Add multiple conditions to StableDiffusionControlNetInpaintPipeline

### PR DESCRIPTION
**Pull request by timegate**
Discussed in https://github.com/huggingface/diffusers/issues/3104, this following draft works with the following code.
This pull request adds multiple conditions to `StableDiffusionControlNetInpaintPipeline`.

```
from stable_diffusion_controlnet_inpaint import StableDiffusionControlNetInpaintPipeline 
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel, UniPCMultistepScheduler
import torch
controlnet = [
    ControlNetModel.from_pretrained("fusing/stable-diffusion-v1-5-controlnet-depth", torch_dtype=torch.float16),
    ControlNetModel.from_pretrained("fusing/stable-diffusion-v1-5-controlnet-seg", torch_dtype=torch.float16),
]
pipe = StableDiffusionControlNetInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting", controlnet=controlnet, torch_dtype=torch.float16
)
pipe.scheduler = UniPCMultistepScheduler.from_config(pipe.scheduler.config)
pipe.enable_xformers_memory_efficient_attention()
pipe.enable_model_cpu_offload()
```

I appreciate your consideration of this contribution. I look forward to your feedback and any required modifications.

### CODE REVIEW

**Comment by ghpkishore** [comment]
@timegate can you check if this yields the same results as the sd-controlnet-webui extension (https://github.com/Mikubill/sd-webui-controlnet/) . That way you will be able to figure out if the multi-control inpainting does work.

**Comment by timegate** [comment]
> @timegate can you check if this yields the same results as the sd-controlnet-webui extension (https://github.com/Mikubill/sd-webui-controlnet/) . That way you will be able to figure out if the multi-control inpainting does work.

It seems difficult to draw a mask accurately on the web. It is probably possible to compare using the API, but it will take some time. I'll try when I have some time to do it.

**Review by williamberman — APPROVED** [review]
Nice, thanks! Note that we don't have tests for these as they aren't officially maintained. Eyeballing it, it looks good

**Comment by reimager** [comment]
I believe this only works with a batch_size of 1. If you have a batch_size of 4 (and for example 2 control images) you will get:
ValueError: If image batch size is not 1, image batch size must be same as prompt batch size. image batch size: 2, prompt batch size: 4

I believe we need something like this from the official pipeline:
https://github.com/huggingface/diffusers/blob/f92253015cc27557d78af62f7c62038dd8afd6f4/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_controlnet.py#LL612C41-L612C42

I hesitate to open a new issues since this is just a community pipeline

**Pull request merged**
