### PR TITLE
[Sana]add 2K related model for Sana

### PR DESCRIPTION
**Pull request by lawrence-cj**
# What does this PR do?

We release 2K model of Sana. So I add the ckpt and 2K related code into the conversion script.

Cc: @a-r-r-o-w @sayakpaul

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]
thanks @lawrence-cj !

**Comment by vladmandic** [comment]
thanks @lawrence-cj! a bit off-topic, do you have plans for img2img sana pipeline?

**Comment by lawrence-cj** [comment]
We do. Will release controllnet code and model later. Any suggestion on other img2img pipeline?

**Comment by vladmandic** [comment]
i was thinking about having pure `SanaImg2ImgPipeline` using existing model,  
should be possible by encoding input image and then using it while initializing latents in `prepare_latents`?
but of course controlnet is more than welcome!

**Comment by lawrence-cj** [comment]
OK, I think it's ok to have a `SanaImg2ImgPipeline` with the current model. Just my bandwidth has been full recently. If you or anyone else is willing to help with the development, I will try my best to help.
@vladmandic

**Pull request merged**
