### PR TITLE
Support different strength for Stable Diffusion TensorRT Inpainting pipeline

### PR DESCRIPTION
**Pull request by jinwonkim93**
# What does this PR do?

This PR support examples/community/stable_diffusion_tensorrt_inpaint.py to run in different strength (0~1).

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@patrickvonplaten

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@asfiyab-nvidia could you have a look here? :-)

**Comment by asfiyab-nvidia** [comment]
Thanks for the ping - I can drop some review comments in the next few days

**Comment by asfiyab-nvidia** [comment]
LGTM. Thanks for the contribution @jinwonkim93 
@patrickvonplaten approving these changes

**Comment by patrickvonplaten** [comment]
Thanks @asfiyab-nvidia

**Pull request merged**
