### PR TITLE
Jax infer support negative prompt

### PR DESCRIPTION
**Pull request by entrpn**
Added negative prompt support to jax pipeline.

For example.

prompt : `a colorful photo of a castle in the middle of a forest with trees and bushes, by Ismail Inceoglu, shadows, high contrast, dynamic shading, hdr, detailed vegetation, digital painting, digital drawing, detailed painting, a detailed digital painting, gothic art, featured on deviantart`

output (3)

With negative prompt: `fog, grainy, purple`

output (4)

### CODE REVIEW

**Review by pcuenca — APPROVED** [review]
Looks good!

**Comment by pcuenca** [comment]
Works fine for me, thanks a lot @entrpn!

@patil-suraj can you maybe take a quick look?

**Comment by camenduru** [comment]
thanks @entrpn ❤

**Comment by entrpn** [comment]
@camenduru that looks right.

**Pull request merged**
