### PR TITLE
Use parameters + buffers when deciding upscale_dtype

### PR DESCRIPTION
**Pull request by universome**
Sometimes, the decoder might lack parameters and only buffers (e.g., this happens when we manually need to convert all the parameters to buffers — e.g. to avoid packing fp16 and fp32 parameters with FSDP)

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sayakpaul** [comment]
Could you maybe elaborate a bit more where this is useful?

**Comment by sayakpaul** [comment]
@universome a gentle ping

**Review by DN6 — APPROVED** [review]

**Comment by DN6** [comment]
@universome Would it be possible to handle the merge conflict? We can merge this after.

**Comment by universome** [comment]
Hi @DN6 , sorry for the late reply. Basically, my use-case is the following.
I'm training a video latent diffusion model with the CogVideoX autoencoder with FSDP wrapping.
I instantiate the autoencoder inside the base model class, wrap the base model in FSDP, and now I need to make sure that it does not get FSDP-wrapped (to avoid extra syncs for it since it's quite small in terms of the parameter counts anyway).
One way to do this is to simply convert AE parameters to buffers (which would cause the error above). The other is to add changes to FSDP wrap policy to make sure it's not wrapped. I felt that the conversion to buffers is simpler since in this case I also do not need to bother about setting requires_grad to False for them.

**Pull request merged**
