### PR TITLE
Migrate the BrownianTree to BrownianInterval in DPM solver

### PR DESCRIPTION
**Pull request by dianyo**
# What does this PR do?

Dealing with  #8728 

In the original issue, I observed that using `BrownianInterval` could provide a slight speedup in the diffusion loop. However, the performance gain was primarily due to not setting `halfway_tree=True` in the arguments, which caused the results to differ from the original implementation.

To maintain deterministic results before and after using `BrownianInterval`, it’s not feasible to accelerate the implementation in this way. Nonetheless, I still believe it’s worthwhile to migrate from `BrownianTree` to `BrownianInterval` since `BrownianTree` is noted as a legacy class in the torchsde documentation.

## Test Settings
I test the numeric and image output using following script on an A100 GPU device with OS `20.04.1-Ubuntu`
```
import torch
from diffusers.pipelines.stable_diffusion_xl import StableDiffusionXLPipeline
from diffusers.schedulers.scheduling_dpmsolver_sde import DPMSolverSDEScheduler
from PIL import Image

pipe = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0")
scheduler = DPMSolverSDEScheduler()
pipe.scheduler = scheduler
pipe = pipe.to("cuda")

generator = torch.manual_seed(1996)
prompt = "A cat"
out = pipe(prompt, generator=generator)  # Run the model for 10 timesteps
out.images[0].save("output_tree.png")
```

## Test Output
Using BrownianTree
output_tree

Using BrownianInterval
output_interval

SHA result
```
sha256sum output_tree.png output_interval.png
55215252f7488ee788ce2932a9f305aa9880cf6e42ed9251e0f81eeaf1ea3879  output_tree.png
55215252f7488ee788ce2932a9f305aa9880cf6e42ed9251e0f81eeaf1ea3879  output_interval.png
``` 
## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [X] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [X] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? issue #8728 
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@yiyixuxu

### CODE REVIEW

**Comment by yiyixuxu** [comment]
thank you!

**Comment by yiyixuxu** [comment]
thanks for the PR! It looks good to me
would you be able to test out an example for stable audio too? (they also use browniantree!) https://huggingface.co/docs/diffusers/api/pipelines/stable_audio

**Comment by dianyo** [comment]
Hi @yiyixuxu,
I've run the test using the following script and the results are the same!
```
import torch
from diffusers import StableAudioPipeline
from PIL import Image
import soundfile as sf

repo_id = "stabilityai/stable-audio-open-1.0"
pipe = StableAudioPipeline.from_pretrained(repo_id, torch_dtype=torch.float16)
pipe = pipe.to("cuda")

# define the prompts
prompt = "The sound of a hammer hitting a wooden surface."
negative_prompt = "Low quality."

# set the seed for generator
generator = torch.Generator("cuda").manual_seed(0)

audio = pipe(
    prompt,
    negative_prompt=negative_prompt,
    num_inference_steps=200,
    audio_end_in_s=10.0,
    num_waveforms_per_prompt=3,
    generator=generator,
).audios

output = audio[0].T.float().cpu().numpy()
sf.write("output_tree.wav", output, pipe.vae.sampling_rate)
```

Here's the sha256 results
```
# sha256sum output_interval.wav 
21e8033448080a52c0519b8df3c17ff1ce70eb5a235b0fb41293a6803e05ae2a  output_interval.wav
# sha256sum output_tree.wav 
21e8033448080a52c0519b8df3c17ff1ce70eb5a235b0fb41293a6803e05ae2a  output_tree.wav
```

**Review by yiyixuxu — APPROVED** [review]
thank you!

**Pull request merged**
