### PR TITLE
Dreambooth docs: minor fixes

### PR DESCRIPTION
**Pull request by pcuenca**
Add missing section headers. README links to docs section about running inference using a saved checkpoint.

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]

**Review by yiyixuxu — APPROVED** [review]
are we missing a `train_dreambooth_inpaint.py` in the folder?

**Comment by patrickvonplaten** [comment]
That'd be nice @pcuenca - let's indeed put it in the research_folder :-)

**Comment by pcuenca** [comment]
@yiyixuxu can you take a final look? :)

**Review by yiyixuxu — APPROVED** [review]
looking great!

**Pull request merged**
