### PR TITLE
Fix unable to save_pretrained when using pathlib

### PR DESCRIPTION
**Pull request by Cyberes**
I was getting an error when saving a model via `save_pretrained()` that was loaded with `from_pretrained()` using a variable that was of type `pathlib.path`. This is a simple fix to convert the `Path` object to a string.

Full traceback:
```
  File "/home/paperspace/.stablediffusion/infra/infrastructure/LocalMachine/trainer/text_to_image/train_text_to_image.py", line 280, in save_ckpt                                                                  
    pipeline.save_pretrained(temp)                                                                                                                                                                      
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/pipelines/pipeline_utils.py", line 249, in save_pretrained                                                                                  
    save_method(                                                                                                                                                                                                   
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 267, in save_pretrained                                                                                     
    model_to_save.save_config(save_directory)                                                                                                                                                                      
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 137, in save_config                                                                                           
    self.to_json_file(output_config_file)                                                                                                                                                                          
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 525, in to_json_file                                                                                          
    writer.write(self.to_json_string())                                                                                                                                                                            
  File "/home/paperspace/.local/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 514, in to_json_string                                                                                            return json.dumps(config_dict, indent=2, sort_keys=True) + "\n"                                                                                                                                                
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps                                        
    **kw).encode(obj)                                                                                                                                                                                                File "/usr/lib/python3.10/json/encoder.py", line 201, in encode                                                                                                                                                  
    chunks = list(chunks)                                                                                                                                                                                          
  File "/usr/lib/python3.10/json/encoder.py", line 431, in _iterencode                                                                                                                                             
    yield from _iterencode_dict(o, _current_indent_level)                                                                                                                                                          
  File "/usr/lib/python3.10/json/encoder.py", line 405, in _iterencode_dict                                                                                                                                        
    yield from chunks                                                                                                                                                                                              
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode                                   
    o = _default(o)                                                                                                                                                                                                
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default                                       
    raise TypeError(f'Object of type {o.__class__.__name__} '                                            
TypeError: Object of type PosixPath is not JSON serializable  
```

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Thanks a lot for the PR @Cyberes ! 

Do you think we could add a simple test to make sure this feature is maintained.
You could add the test here: https://github.com/huggingface/diffusers/blob/7f0eb35af379def05c111806e12f3ef50a94a54b/tests/test_config.py#L63 for example by creating a new config class that has a PosixPath as a variable.

**Comment by Cyberes** [comment]
Will do.

**Review by patrickvonplaten — APPROVED** [review]
Thanks @Cyberes

**Comment by Cyberes** [comment]
Do you still need that test? I've been a little busy recently so haven't been able to write that yet.

**Comment by patrickvonplaten** [comment]
Would be nice to add it, but don't worry if you're busy

**Pull request merged**
