### PR TITLE
Remove unnecessary lines

### PR DESCRIPTION
**Pull request by tolgacangoz**
They are unnecessary lines, aren't they? Self-assigned vars have been found with [PLW0127](https://docs.astral.sh/ruff/rules/self-assigning-variable/).

@yiyixuxu @DN6

### CODE REVIEW

**Review by a-r-r-o-w — APPROVED** [review]
thank you for removing the unnecessary lines! i do not know the reasoning behind the duplicate assignments but if it's just a mistake, these changes look good to me. CI looks good as well (failing test seems unrelated)

**Comment by tolgacangoz** [comment]
> thank you for removing the unnecessary lines! i do not know the reasoning behind the duplicate assignments but if it's just a mistake, these changes look good to me. CI looks good as well (failing test seems unrelated)

Thanks for the review Hugging Face member!

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by tolgacangoz** [comment]
Thanks for merging!

**Pull request merged**
