### PR TITLE
fix a small bug in sdxl

### PR DESCRIPTION
**Pull request by xiaohu2015**
fix a bug

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by pcuenca — APPROVED** [review]
I think this is correct!

We may have to correct the same in `pipeline_stable_diffusion_upscale.py` cc @patrickvonplaten @sayakpaul @williamberman

**Comment by pcuenca** [comment]
Just one thing, @xiaohu2015, could you please run "make style" in your checkout to format the files? If you can't, let us know and I'll do it.

**Comment by xiaohu2015** [comment]
> Just one thing, @xiaohu2015, could you please run "make style" in your checkout to format the files? If you can't, let us know and I'll do it.

thanks, you can help do that

**Comment by pcuenca** [comment]
Thanks @xiaohu2015 for your contribution! Merged in #4019 :)

**Pull request closed without merging**
