### PR TITLE
[WIP] Add DDGAN Pipeline and Scheduler

### PR DESCRIPTION
**Pull request by dg845**
# What does this PR do?

This PR adds a pipeline and scheduler for the denoising diffusion GAN (DDGAN) model ([paper](https://arxiv.org/pdf/2112.07804.pdf), [code](https://github.com/NVlabs/denoising-diffusion-gan)). The GAN discriminator is not implemented in this PR.

Partially addresses #5905.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten
@sayakpaul
@JunbongJang

### CODE REVIEW

**Comment by dg845** [comment]
I'm not sure if adding a new pipeline and scheduler to support DDGAN is strictly necessary - I believe `DDGANPipeline` + `DDGANScheduler` is very similar to `DDPMPipeline` + `DDPMScheduler`, with the following possible issues: 

- The GAN generator denoising model might not be expressible as a `UNet2DModel`; the [original DDGAN paper](https://arxiv.org/pdf/2112.07804.pdf) uses a variant of  the NCSN++ architecture (see Appendix C.1).
- The original paper uses a different definition of `beta_start` and `beta_end`: I believe it gives these quantities in terms of what `diffusers` calls `1.0 - self.alphas_cumprod` (and what the [original DDPM paper](https://arxiv.org/pdf/2006.11239.pdf) would call $`1 - \bar\alpha_t`$, which is the variance of $`q(x_t \mid x_0)`$ rather than of $`q(x_t \mid x_{t - 1})`$). Accordingly, it implements different variance schedules ([geometric](https://github.com/NVlabs/denoising-diffusion-gan/blob/6818ded6443e10ab69c7864745457ce391d4d883/test_ddgan.py#L23-L24) and [variance preserving](https://github.com/NVlabs/denoising-diffusion-gan/blob/6818ded6443e10ab69c7864745457ce391d4d883/test_ddgan.py#L18-L21)). I haven't figured out yet if these variance schedules are equivalent to beta schedules already implemented in `DDPMScheduler`. 

I think if these issues could be resolved (possibly with some additions to `DDPMScheduler`) we could use existing pipelines and schedulers for DDGAN checkpoints.

**Comment by dg845** [comment]
@patil-suraj I haven't looked into implementing DDGAN training yet, this PR so far only implements a pipeline and scheduler for DDGAN inference.

Happy to look at/help with a DDGAN training script if that sounds good to you :).

**Comment by patil-suraj** [comment]
cool I will share the script with you (or push in this PR) later today.

**Comment by patil-suraj** [comment]
Oh actually I meant I have the script for https://arxiv.org/abs/2311.09257 which is formulated slightly differently than DDGAN

**Comment by dg845** [comment]
I am also planning to open a PR for a UFOGen scheduler (and pipeline if necessary) in light of #5905 but decided to work on a DDGAN pipeline and scheduler first since there is official code and checkpoints available (unlike for UFOGen, unless I'm missing something).

Would still be happy to take a look at the UFOGen training script :).

**Comment by XiaXin-Aloys** [comment]
> [patil-suraj](/patil-suraj)
Dear @patil-suraj @dg845,

I saw your mention of having a script for the UFOGen model. I'm studying text-to-image generation and your script could be incredibly helpful. I assure you it'll be used responsibly for my research. Could you consider sharing it? I appreciate your help.

**Pull request closed without merging**
