### PR TITLE
instruct pix2pix pipeline: remove sigma scaling when computing classifier free guidance

### PR DESCRIPTION
**Pull request by erliding**
Fixes (https://github.com/huggingface/diffusers/issues/6981)

instruct pix2pix pipeline scale model prediction to sigma space before computing classifier free guidance and scale back when done for schedulers operating in sigma space, which seems unnecessary, especially when `rescale_betas_zero_snr ` is enabled for those schedulers, this scaling can result in fp16 overflow with high rates and generating black images

for example `(noise_pred - latents)` below can goes beyond -65504 and result in `-inf` for fp16 (for this specific case reorganize rhs of the assignment to `latents / sigma - noise_pred / sigma` should also work) https://github.com/huggingface/diffusers/blob/3a7e481611bc299416aaeed4207086d9ddca5852/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_instruct_pix2pix.py#L439

@yiyixuxu @sayakpaul

### CODE REVIEW

**Comment by sayakpaul** [comment]
@erliding do you have some results for us to verify things here? 

Cc: @patil-suraj here as well.

**Comment by yiyixuxu** [comment]
can you maybe run the docstring example with fixed seed from main branch and this branch and see if they are identical? 
(I think math is the same)

**Comment by erliding** [comment]
> @erliding do you have some results for us to verify things here?
> 
> Cc: @patil-suraj here as well.

yeah, so i tested with `EulerDiscreteScheduler` and `EulerAncestralDiscreteScheduler` for both eps and v_prediction with `StableDiffusionInstructPix2PixPipeline`, removing sigma scaling doesn't seem to have noticeable impact on generated images, and setting `rescale_betas_zero_snr=True` won't cause generating black images for fp16 inference anymore

**Comment by erliding** [comment]
i ran the example below on main branch and this branch, it use `EulerAncestralDiscreteScheduler`
https://github.com/huggingface/diffusers/tree/main/examples/instruct_pix2pix#inference
attached the edited images, first from main, second from this branch
edited_image-main
edited_image-branch

**Comment by sayakpaul** [comment]
Alright, thanks. But I varely see any qualitative difference though.

**Comment by erliding** [comment]
> Alright, thanks. But I varely see any qualitative difference though.

it shouldn't, it is to show sigma scaling can be removed without introducing difference

**Comment by sayakpaul** [comment]
Alright, yes, that makes sense!

**Comment by yiyixuxu** [comment]
gentle pin @patil-suraj

**Review by patil-suraj — APPROVED** [review]
Great find! This was done to mimic the original code but actually shouldn't make difference here. Thanks a lot for the PR.

**Pull request merged**
