### PR TITLE
🤫 Quiet IP Adapter Mask Warning

### PR DESCRIPTION
**Pull request by ghunkins**
# What does this PR do?

Fixes [**#7033**](https://github.com/huggingface/diffusers/issues/7033) and duplicate issue [**#7695**](https://github.com/huggingface/diffusers/issues/7695)

For testing, please follow the IP adapter masking section of the docs [**here**](https://huggingface.co/docs/diffusers/main/en/using-diffusers/ip_adapter?tasks=Text-to-image#ip-adapter-masking). You will no longer see the warning message spam the console.

@sayakpaul @yiyixuxu @DN6 requesting review, thank you!

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]
i like this
thank you!

**Review by asomoza — APPROVED** [review]
Nice, we had this pending for some time. Thanks

**Comment by sayakpaul** [comment]
Very cool.

**Comment by sayakpaul** [comment]
Will merge once the CI is done. There might be a single unrelated test failure which can be safely ignored.

**Comment by ghunkins** [comment]
Sounds good, will follow your lead @sayakpaul , thanks!

**Pull request merged**
