### PR TITLE
sketch inpaint from a1111 for non-inpaint models

### PR DESCRIPTION
**Pull request by noskill**
# What does this PR do?

sketch inpaint from a1111 for non-inpaint models.

Pipleline takes an image and a mask as inputs. It does inpainting by doing this step on each iteration

latent = latent * mask + image_latent * (1 - mask)

that is we replace latent code for non-masked parts of images with latents from the encoding of the image

code in a1111 works with both: inpainting and non-inpainting models. The pipeline from this pr will work only with non-inpaint ones

### CODE REVIEW

**Comment by adhikjoshi** [comment]
There is lots of things from auto1111 if we can port. Like highres fix.

**Comment by patrickvonplaten** [comment]
Cool!

**Comment by deepconv** [comment]
Without a specially trained inpainting model, does this trick really work? My experiment is that the inpainted area does not respect the context well.

**Comment by noskill** [comment]
@deepconv yes, it works:

result6

result4

result3

I used this model https://civitai.com/models/28059?modelVersionId=89464 for tests.

**Pull request merged**
