### PR TITLE
Fix gmflow_dir

### PR DESCRIPTION
**Pull request by pravdomil**
# What does this PR do?

users cannot change `gmflow_dir`
since every time
custom pipeline gets downloaded
and overrides user changes
this fixes that

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@SingleZombie

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]
oh thanks!

**Comment by yiyixuxu** [comment]
can you resolve the conflicts and fix the quality test?

**Comment by yiyixuxu** [comment]
what other PRs?

**Comment by pravdomil** [comment]
https://github.com/huggingface/diffusers/pulls/pravdomil

**Comment by pravdomil** [comment]
ready

**Comment by pravdomil** [comment]
ready

**Pull request merged**
