### PR TITLE
add support for pre-calculated prompt embeds to Stable Diffusion ONNX pipelines

### PR DESCRIPTION
**Pull request by ssube**
## Motivation

I would like to calculate the prompt and negative prompt embeds ahead of time using my own logic and pass them into the ONNX version of the SD pipeline, which is supported by the regular non-ONNX pipeline, https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L571, but not available for ONNX. This should bring parity between the two for the `prompt_embeds` and `negative_prompt_embeds` parameters.

~~If this change is acceptable, I would like to do the same to the other ONNX pipelines. I can add those changes to this same PR or make another one, whatever works, I know you all have limited time for the ONNX stuff.~~ Looks like the build requires the change to be copied out to the other pipelines, so that's in this PR as well. 

## Example

```python
prompt = "an astronaut eating a hamburger"
steps = 50

pipe = OnnxStableDiffusionPipeline.from_pretrained(self.hub_checkpoint, provider="CPUExecutionProvider")

tokens = pipe.tokenizer(
    prompt,
    padding="max_length",
    max_length=pipe.tokenizer.model_max_length,
    truncation=True,
    return_tensors="np",
)
embeds = pipe.text_encoder(input_ids=tokens.input_ids.astype(np.int32))[0]

image = pipe(
    num_inference_steps=steps,
    prompt_embeds=embeds,
).images[0]
```

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
Looks very clean to me and makes sens! Thanks a lot - @anton-l could you take a quick look here?

**Comment by ssube** [comment]
This is still useful to me (and hopefully others). I got sidetracked for a little bit, but I've rebased the branch and the existing tests look good - happy to add more if you'd like, or make any other changes.

This will be really helpful for custom prompt parsing, like weights and group and expansion stuff.

**Comment by patrickvonplaten** [comment]
Sorry for taking so long here @ssube - merging!

**Comment by ssube** [comment]
No worries, thank you! Always happy to add more tests or make changes, I don't want to break things for anyone, especially my own project :smile:

**Pull request merged**
