### PR TITLE
add: support for notifying maintainers about the nightly test status

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Cc: @younesbelkada 

I have added a temporary workflow to validate things. You can check a sample message here: https://huggingface.slack.com/archives/C06LR0CSR6H/p1709043893377739. Will delete the temporary workflow after the PR is approved and before merging.

### CODE REVIEW

**Comment by sayakpaul** [comment]
Need to investigate a bit why this is not posting the notifs. Will get back to it tomorrow.

**Comment by sayakpaul** [comment]
The PR is ready for review @yiyixuxu @DN6 :)

**Comment by sayakpaul** [comment]
@yiyixuxu @DN6 another gentle ping here.

**Review by DN6 — APPROVED** [review]
👍🏽

**Pull request merged**
