### PR TITLE
[LoRA] make LoRAs trained with `peft` loadable when `peft` isn't installed

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Reported by @apolinario. Internal thread: https://huggingface.slack.com/archives/C05GX934Z98/p1703334768186119. 

Currently, our LoRA trainers use `peft`. To load those LoRAs you need `peft` to be installed. However, we want those LoRAs to be loadable without `peft` too (or so I'd think?). 

This PR fixes that. 

* Colab to train a dummy LoRA with `peft`: https://colab.research.google.com/gist/sayakpaul/cc0886ada3ecdd5c3b305cf9862d2c72/scratchpad.ipynb
* Colab to load the dummy LoRA where `peft` isn't installed: https://colab.research.google.com/gist/sayakpaul/41c60a6bfb921108faf572508bc15469/scratchpad.ipynb

@apolinario does this work for you? 

## TODO

- [ ] Propagate to the other scripts.

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Makes sense, thanks! DO we need the same for other training scripts as well? Can you confirm the slow tests pass on a V100 instance?

**Comment by sayakpaul** [comment]
> DO we need the same for other training scripts as well?

@younesbelkada hence the TODO here: https://github.com/huggingface/diffusers/pull/6306#issue-2055028706.

> Can you confirm the slow tests pass on a V100 instance?

Which ones? Can you pinpoint?

**Comment by sayakpaul** [comment]
> Can you confirm the slow tests pass on a V100 instance?

Ran

```bash
RUN_SLOW=1 pytest tests/lora/test_lora_layers_peft.py
```

Works.

**Comment by sayakpaul** [comment]
@pacman100 could you also give it a look?

**Comment by patrickvonplaten** [comment]
Makes sense! As a general guideline, for now let's try to always have the exact same serialization format that we had before using PEFT in the example scritps

**Review by patrickvonplaten — APPROVED** [review]

**Pull request merged**
