### PR TITLE
#7535 Update FloatTensor type hints to Tensor

### LINKED ISSUE #7535: FloatTensor type hint is incompatible with Tensor
### Describe the bug

At present, the `torch.FloatTensor` type hint is commonly employed in the codebase. However, if one were to pass a `torch.Tensor`, Pyright would raise complaints about the inconsistency between these two types. Furthermore, based on information from [this thread](https://discuss.pytorch.org/t/type-checking-types-tensor-and-tensorfloat-incompatible/118654), it appears that `torch.FloatTensor` has been deprecated.

### Reproduction

```
import torch
from diffusers.schedulers.scheduling_ddim import DDIMScheduler

scheduler = DDIMScheduler()
a = torch.randn(1, 3, 64, 64)
scheduler.scale_model_input(a)
```

Output of Pyright:
```
$ pyright test.py
test.py
  test.py:6:29 - error: Argument of type "Tensor" cannot be assigned to parameter "sample" of type "FloatTensor" in function "scale_model_input"
  __"Tensor" is incompatible with "FloatTensor" (reportArgumentType)
1 error, 0 warnings, 0 informations
```

### Logs

_No response_

### System Info

- `pyright` version: 1.1.356
- `diffusers` version: 0.27.2
- Platform: Linux-5.4.210-4-velinux1-amd64-x86_64-with-glibc2.31
- Python version: 3.12.2
- PyTorch version (GPU?): 2.2.1 (True)
- Huggingface_hub version: 0.22.0
- Transformers version: not installed
- Accelerate version: 0.28.0
- xFormers version: not installed
- Using GPU in script?: no
- Using distributed or parallel set-up in script?: no

### Who can help?

_No response_

### PR DESCRIPTION
**Pull request by vanakema**
# What does this PR do?

Updates all references to torch.FloatTensor to torch.Tensor. This is because FloatTensor is essentially deprecated and all Tensor types are actually just Tensors now. FloatTensor was kept to be backwards compatible as noted [here](https://discuss.pytorch.org/t/type-checking-types-tensor-and-tensorfloat-incompatible/118654/2).

This allows type hints to not yell when a user uses the canonical Tensor type

Fixes #7535 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by vanakema** [comment]
@DN6 Can you approve this for a pipeline run? Due to the number of files this touches, I was trying to run the full suite on my laptop but it was taking over an hour, and I see it takes way less than an hr (around 20m) for people's tests to run in the CI pipeline.

**Comment by yiyixuxu** [comment]
cc @standardAI here :)

**Review by yiyixuxu — APPROVED** [review]
thank you so much for doing this!!

**Comment by yiyixuxu** [comment]
I think we need to manually update this too (a test currently fails) https://github.com/huggingface/diffusers/blob/8edaf3b79c564a56fbffb003ee74ac92e9162a73/tests/others/test_check_copies.py#L31C1-L31C15

**Comment by vanakema** [comment]
Yep! On it. Thanks for the review!

**Comment by vanakema** [comment]
Do you think it makes sense to update the examples too? Just realized I missed those

**Review by stevhliu — APPROVED** [review]
Thanks so much for updating! 👏 

What examples are you referring to?

**Comment by vanakema** [comment]
I really meant all of them that reference or use FloatTensor. I decided to update them. I'm running the tests on my server right now instead of my laptop, but they're still going pretty slow. Do one of you mind approving the workflow again?

**Comment by vanakema** [comment]
How long should the full suite of tests take to run? I started a full run last night on my home server and as of this morning, they're still running. I'm curious to hear what's the typical dev flow for situations like this for those of you at HF. It seems super weird for it to take this long. Maybe the 32 worker threads it spun up was too many and my box is getting bottlenecked somewhere? Would it run faster if I passed my GPU to it? On my Mac, the pipelines never were this slow (but they were only running 8 threads since there were only 8 "cores"), but on my much more powerful server it is typical to see numbers like "159s/it".

**Comment by vanakema** [comment]
An update on the test that failed: I believe the one that caused the failed pipeline was a fluke as it passes consistently on my box. I think it just needs a retry.

Looking forward at other tests that have yet to run in the pipeline, I am consistently having issues with one of the determinism tests: `tests/models/unets/test_models_unet_spatiotemporal.py::UNetSpatioTemporalConditionModelTests::test_set_attn_processor_for_determinism`

I see that elsewhere the precision required for the determinism test was reduced to `10^2` down from `10^3`. When I apply this to the `base_precision` in the `ModelTesterMixin` in `test_modeling_common.py`, the determinism test that was regularly failing on my box now passes. I am curious to hear y'all's thoughts on this, and why you think this might be happening. Every (almost every) change in this PR is only changes to the type hints and documentation. I trawled through every potentially relevant file (and a lot of files that were irrelevant), and I could not find any instance of actual object instantiation that would affect this. It's strange though because I don't understand how typehints would change the behavior of the determinism test.

Admittedly determinsim is definitely something that's a little out of my wheelhouse, so it's totally possible I missed something, and I would love to hear any ideas y'all may have. In the meantime, I'll continue investigating tomorrow in my free time. I'm totally down to hop on a call to talk about it if any of you at HF are open to it! But I know you guys are probably really busy, so I also completely understand if that's not something of interest. I'll hop on the Discord though

Thanks in advance!

**Comment by standardAI** [comment]
Thanks for updating type hints!
The failed pipeline test can be passed on my local PC too. `test_set_attn_processor_for_determinism` can also be passed on my local PC. This is my setup:
```
❯ diffusers-cli env
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- 🤗 Diffusers version: 0.28.0.dev0
- Platform: Ubuntu 24.04 LTS - Linux-6.8.0-31-generic-x86_64-with-glibc2.39
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.10.14
- PyTorch version (GPU?): 2.3.0+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): 0.8.3 (cpu)
- Jax version: 0.4.26
- JaxLib version: 0.4.26
- Huggingface_hub version: 0.23.0
- Transformers version: 4.40.2
- Accelerate version: 0.30.0
- PEFT version: 0.10.0
- Bitsandbytes version: 0.43.1
- Safetensors version: 0.4.3
- xFormers version: not installed
- Accelerator: NVIDIA GeForce GTX 1650, 4096 MiB VRAM
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>
```

**Comment by vanakema** [comment]
Oh awesome, thanks for testing that out Tolga! Ok maybe it just needs a retry then? I'll rebase on main and then can @yiyixuxu or @stevhliu approve the pipeline run?

**Comment by vanakema** [comment]
Pipeline passed, woohoo, let's go! Does someone with permissions mind merging?

**Comment by yiyixuxu** [comment]
thank you!
thank @standardAI for your help too :)

**Comment by vanakema** [comment]
Amazing, thank you all! Super stoked to have my first contribution merged in :)

**Pull request merged**
