### PR TITLE
Update train_text_to_image_lora.py

### PR DESCRIPTION
**Pull request by haofanwang**
Fix a typo as suggested in [file](https://github.com/huggingface/diffusers/blob/1d686bac8146037e97f3fd8c56e4063230f71751/examples/research_projects/lora/train_text_to_image_lora.py#L907)

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Good point - we need to indeed by sure that the model is unwrapped here. Did we ever test the new example scripts on multi-GPU? cc @sayakpaul

**Review by younesbelkada — APPROVED** [review]
Makes sense to me, thanks!

**Comment by sayakpaul** [comment]
> Good point - we need to indeed by sure that the model is unwrapped here. Did we ever test the new example scripts on multi-GPU? 

Most of these updates are made in bulk and it's quite cumbersome to test them for multi-GPU. So, fixing them ad-hoc is more preferable IMO. It's quite rare for the community to use a node of GPUs for LoRA training.

**Review by BenjaminBossan — APPROVED** [review]
Good catch, thanks for fixing.

I wonder if we could call `extract_model_from_parallel` from accelerate automatically in  `get_peft_model_state_dict` or if there could be use cases where this is not desired.

**Review by younesbelkada — APPROVED** [review]
Thanks again ! After testing all scripts under multi-gpu regime I can confirm this PR fixes the bug with respect to multi-gpu training for the text_to_image_lora.py file :

Find the scripts that I used to test below:

<details>
<summary> `examples/text_to_image/train_text_to_image_lora.py` </summary>

```bash
accelerate launch examples/text_to_image/train_text_to_image_lora.py --pretrained_model_name_or_path hf-internal-testing/tiny-stable-diffusion-pipe --dataset_name hf-internal-testing/dummy_image_text_data --resolution 64 --center_crop --random_flip --train_batch_size 1 --gradient_accumulation_steps 1 --max_train_steps 9 --learning_rate 5.0e-04 --scale_lr --lr_scheduler constant --lr_warmup_steps 0 --output_dir /tmp/tmpgqu8nxzx --checkpointing_steps=2 --seed=0 --num_validation_images=0
```

</details>


<details>
<summary> `examples/text_to_image/train_text_to_image_lora_sdxl.py` </summary>

```bash
accelerate launch examples/text_to_image/train_text_to_image_lora_sdxl.py --pretrained_model_name_or_path hf-internal-testing/tiny-stable-diffusion-xl-pipe --dataset_name hf-internal-testing/dummy_image_text_data --resolution 64 --train_batch_size 1 --gradient_accumulation_steps 1 --max_train_steps 2 --learning_rate 5.0e-04 --scale_lr --lr_scheduler constant --lr_warmup_steps 0 --output_dir ./test-training/ --train_text_encoder
```

</details>

<details>
<summary> `examples/dreambooth/train_dreambooth_lora_sdxl.py` </summary>

```bash
accelerate launch examples/dreambooth/train_dreambooth_lora_sdxl.py --pretrained_model_name_or_path hf-internal-testing/tiny-stable-diffusion-xl-pipe --instance_data_dir docs/source/en/imgs --instance_prompt photo --resolution 64 --train_batch_size 1 --gradient_accumulation_steps 1 --max_train_steps 7 --checkpointing_steps=2 --checkpoints_total_limit=2 --learning_rate 5.0e-04 --scale_lr --lr_scheduler constant --lr_warmup_steps 0 --output_dir /tmp/tmpesqh3pdg
```

</details>

<details>
<summary> `examples/dreambooth/train_dreambooth_lora.py` </summary>


```bash
accelerate launch  examples/dreambooth/train_dreambooth_lora.py --pretrained_model_name_or_path hf-internal-testing/tiny-stable-diffusion-pipe --instance_data_dir docs/source/en/imgs --instance_prompt photo --resolution 64 --train_batch_size 1 --gradient_accumulation_steps 1 --max_train_steps 2 --learning_rate 5.0e-04 --scale_lr --lr_scheduler constant --lr_warmup_steps 0 --train_text_encoder --output_dir test-dreambooth-lora
```

</details>

**Comment by Eggwardhan** [comment]
it work for me  thanks

**Pull request merged**
