### PR TITLE
Fix for SVD "num_frames error in pipeline_stable_video_diffusion.py"

### PR DESCRIPTION
**Pull request by RajdeepBorgohain**
# What does this PR do?

Fixes # (issue)
TypeError: AutoencoderKLTemporalDecoder.decode() missing 1 required positional argument: 'num_frames'

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@patrickvonplaten, @sayakpaul

### CODE REVIEW

**Comment by sayakpaul** [comment]
Can you provide a snippet to reproduce the issue?

**Comment by RajdeepBorgohain** [comment]
Hi @sayakpaul
Here the code:
`import torch

from diffusers import StableVideoDiffusionPipeline
from diffusers.utils import load_image, export_to_video

import torch._dynamo
torch._dynamo.config.suppress_errors = True

pipe = StableVideoDiffusionPipeline.from_pretrained(
    "stabilityai/stable-video-diffusion-img2vid-xt", torch_dtype=torch.float16, variant="fp16"
)
pipe.to("cuda")

pipe.unet = torch.compile(pipe.unet,mode="reduce-overhead", fullgraph=True)
pipe.vae = torch.compile(pipe.vae,mode="reduce-overhead", fullgraph=True)
#pipe.enable_model_cpu_offload()

image = load_image("https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/diffusers/svd/rocket.png?download=true")
image = image.resize((1024, 576))

generator = torch.manual_seed(42)
frames = pipe(image, decode_chunk_size=8, generator=generator).frames[0]

export_to_video(frames, "generated.mp4", fps=7)
`

**Comment by sayakpaul** [comment]
Cc: @DN6

**Comment by patrickvonplaten** [comment]
Ah it's due to `torch.compile` here. Hey @RajdeepBorgohain, does the following fix it for you: https://github.com/huggingface/diffusers/pull/6217

**Pull request closed without merging**
