### PR TITLE
Fix scheduler inference steps error with power of 3

### PR DESCRIPTION
**Pull request by natolambert**
Discussing in #444.
More verification to do on the unclear number of iterations vs `num_inference_steps`

Solution inspired by this [discussion](https://github.com/CompVis/stable-diffusion/issues/111) in original SD repo, thanks @ryanirl.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Cool that looks good to me! Thanks a lot for the fix. @natolambert could you also add one test that shows that it can now be a power of three?

**Review by patrickvonplaten — APPROVED** [review]

**Comment by natolambert** [comment]
Okay @patrickvonplaten, so this test should cover the test needed for now.
Note that the `DDIMScheduler` did not error out with powers of 3, but rather it had a number of iterations that did not match the expected behavior.

If we update `DDIMScheduler` to have the same alpha logic as `PNDMScheduler`, we should add the power of 3 test!

**Comment by pcuenca** [comment]
We need to verify this in the Flax implementation too; it probably happens there as well: https://github.com/patil-suraj/stable-diffusion-jax/blob/main/stable_diffusion_jax/scheduling_pndm.py#L103-L105

/cc @kashif

**Comment by patrickvonplaten** [comment]
PR looks great to me!

**Review by patrickvonplaten — APPROVED** [review]

**Comment by natolambert** [comment]
I'll add a comment on the test explaining why it is there, then merge (otherwise it may be a little confusing to a reader). Great!

**Review by anton-l — APPROVED** [review]
LGTM, but there might be a case where we need to `.round()` as well, instead of just truncating the decimal with `.astype(int)`. So watch out for those issues :)

**Comment by natolambert** [comment]
@anton-l that's a good point. I'm going to check with round, I like that better (it's also less opaque).

**Pull request merged**
