### PR TITLE
[WIP][Docs] Use DiffusionPipeline Instead of Child Classes when Loading Pipeline

### PR DESCRIPTION
**Pull request by dg845**
This PR edits the docs to use `DiffusionPipeline` instead of its child classes (such as `StableDiffusionPipeline`) where possible when loading a pipeline. The rationale behind this change is that `DiffusionPipeline` should always create a pipeline of the right class when loading a checkpoint and thus should be more user friendly. See #2135 for more discussion; in particular, this PR corresponds to item 4 in [this comment](https://github.com/huggingface/diffusers/issues/2135#issuecomment-1416171179).

----
Below I've documented pages with examples that use a child class of `DiffusionPipeline` when loading a checkpoint that I've opted not to change, along with a short explanation of why I think it should stay as is.

1. `/docs/source/en/using-diffusers/loading.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/loading))

The examples here specifically discuss loading directly from the appropriate pipeline class (e.g. `StableDiffusionPipeline`).

2. `/docs/source/en/using-diffusers/schedulers.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/schedulers))

The JAX/Flax example uses `FlaxStableDiffusionPipeline`; since it deals specifically with Flax, I think it makes sense to use the more specific class.

3. `/docs/source/en/using-diffusers/img2img.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/img2img))
4. `/docs/source/en/using-diffusers/inpaint.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/inpaint))
5. `/docs/source/en/using-diffusers/depth2img.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/depth2img))

Since these pages talk about specific Stable Diffusion pipelines, I think it's appropriate to reference the specific pipeline class when loading the checkpoints.

6. `/docs/source/en/using-diffusers/reproducibility.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/reproducibility))

The running example on this page uses `DDIMPipeline`, which I think is relevant to the discussion on reproducibility. I haven't tested the numbers produced if we substitute `DiffusionPipeline` for `DDIMPipeline` (presumably, they are close if not the same).

Edit: in `0.15.0.dev0` the numbers are less important to the exposition, so it might make more sense to replace `DDIMPipeline` with `DiffusionPipeline`.

7. `/docs/source/en/using-diffusers/contribute_pipeline.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/contribute_pipeline))

I think it makes sense that there is an example that discusses loading a checkpoint explicitly from a custom pipeline (in this case, `UnetSchedulerOneForwardPipeline`).

8. `/docs/source/en/using-diffusers/using_safetensors.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/using_safetensors#why-use-safetensors))

I imagine substituting `DiffusionPipeline` for `StableDiffusionPipeline` in the loading speed example could make a difference to the final loading numbers (I don't have the required hardware to test this myself).

9. `/docs/source/en/optimization/onnx.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/optimization/onnx))

I think discussing the difference between `StableDiffusionPipeline` and `StableDiffusionOnnxPipeline` is valuable, although perhaps there could be a note about using `DiffusionPipeline` to load the checkpoint as well.

Edit: in `0.15.0.dev0` `ORTStableDiffusionPipeline` replaces `StableDiffusionPipeline`. I think the comment above remains valid, although I'm not sure if 'DiffusionPipeline` is an acceptable substitute for `ORTStableDiffusionPipeline`.

10. `/docs/source/en/optimization/habana.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/optimization/habana))

Using `GaudiStableDiffusionPipeline` here instead of the generic `DiffusionPipeline` probably makes more sense. (I'm not familiar with Habana Gaudi.)

11. `/docs/source/en/training/text_inversion.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/training/text_inversion))
12. `/docs/source/en/training/text2image.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/training/text2image))
13. `/docs/source/en/training/lora.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/training/lora))

These pages specifically discuss fine-tuning a Stable Diffusion model, so it feels weird to replace `StableDiffusionPipeline` with `DiffusionPipeline`.

(Note that for `/docs/source/en/training/dreambooth.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/training/dreambooth)), some of the code snippets use `DiffusionPipeline` and some use `StableDiffusionPipeline`, so I've changed all checkpoint loading examples to use `DiffusionPipeline`.)

14. `/docs/source/en/api/outputs.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/api/outputs))

In the pipeline loading example, we follow up a call to `from_pretrained(...)` with a call to `__call__(...)`, so I think it makes sense to use a specific pipeline such as `DDIMPipeline` rather than `DiffusionPipeline` (which doesn't implement a `__call__` method).

(Sorry for making the PR so long!)

Edit: changed the links to point to the PR docs endpoint.

### CODE REVIEW

**Comment by dg845** [comment]
Sorry, I just realized that the docs in `0.15.0.dev0` are pretty different from the docs in `0.14.0`, which I was implicitly working off of (I'm not currently able to build the docs locally due to #2803). I think some of my comments above still apply, and I will take a look at the new doc pages.

**Comment by dg845** [comment]
Looked at the docs for `0.15.0.dev0` and have the following notes:

1. `/docs/diffusers/en/using-diffusers/write_own_pipeline` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/write_own_pipeline))

Left unchanged because I think the specific pipelines (e.g. `DDPMPipeline`) used are important to the exposition.

2. `/docs/diffusers/en/using-diffusers/weighted_prompts` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/using-diffusers/weighted_prompts))

Since this page discusses the `prompt_embeds` argument of a `DiffusionPipeline`'s `__call__` method, it makes sense to use a specific child class (e.g. `StableDiffusionPipeline`) for which `prompt_embeds` is implemented.

3. `/docs/diffusers/en/training/controlnet` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/training/controlnet))
4. `/docs/diffusers/en/training/instructpix2pix` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/training/instructpix2pix))

Similarly to the other training docs, since these pages discuss specific pipelines, I think it makes sense to use them rather than the generic `DiffusionPipeline`.

5. `/docs/source/en/conceptual/evaluation.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/conceptual/evaluation))

For the first example, using `StableDiffusionPipeline` probably makes more sense than `DiffusionPipeline`, since the page specifically discusses evaluating a text-quided image generation model, and similarly for the other examples (e.g. image-conditioned text-to-image generation, etc.).

6. `/docs/source/en/api/pipelines/overview.mdx` ([link](https://moon-ci-docs.huggingface.co/docs/diffusers/pr_2809/en/api/pipelines/overview))

The examples discuss specific tasks (e.g. inpainting) so I think it makes sense to use the specific pipeline for that task (e.g. `StableDiffusionInpaintPipeline`).

**Comment by dg845** [comment]
I realize that instead of documenting specific cases where a change is or is not made, it might make more sense to use a bright line rule about when using `DiffusionPipeline.from_pretrained(...)` to load a checkpoint in the docs is preferred over a specific subclass of `DiffusionPipeline`. I think the standard I've been trying to follow is "prefer `DiffusionPipeline.from_pretrained(...)` unless the docs explicitly mention a specific pipeline, or depend upon a property of a specific pipeline".

(I would also greatly appreciate it if people could give feedback on the verbosity of this PR, so that I can improve in the future.)

**Comment by patrickvonplaten** [comment]
Thanks for the PR @dg845 - I agree with your reasoning. I think we should use `DiffusionPipeline` whenever we can. **Note** sometimes we can't e.g. when showcasing `StableDiffusionImg2Img` we can't load it from `DiffusionPipeline` because it would default to the wrong one. 

I'm in favor of merging this PR as it though, so LGTM. @yiyixuxu could you take a final look?

**Review by patrickvonplaten — APPROVED** [review]

**Review by yiyixuxu — APPROVED** [review]
LGTM!

**Pull request merged**
