### PR TITLE
Change `export_to_video` default

### PR DESCRIPTION
**Pull request by DN6**
# What does this PR do?
There's a strange issue with the `cv2` VideoWriter where setting the FPS to 8 results in a green/distorted video in Colab. Changing the default value to 10 for now so that anyone running our docs examples in Colab doesn't run into strange exports

In any case, the FPS for `export_to_gif` is set to 10 as well, so this would exports consistent.  

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sayakpaul — COMMENTED** [review]
With an FPS of 8, do you see problems locally? If not, then I think we shouldn't change the value and instead make it clear from the documentation.

**Comment by DN6** [comment]
I was able to reproduce the issue locally too.

**Comment by sayakpaul** [comment]
Holy hell 🥹

**Comment by sayakpaul** [comment]
@DN6 let's merge this.

**Pull request merged**
