### PR TITLE
Fix runtime error in dreambooth training script

### LINKED ISSUE #5932: RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 3, 512, 512] to have 4 channels, but got 3 channels instead
### Describe the bug

I'm trying to follow the Dreambooth training example and I'm getting this error: 

RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 3, 512, 512] to have 4 channels, but got 3 channels instead

This is the full window:

accelerate launch train_dreambooth.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4"  --instance_data_dir=".\dog" --output_dir=".\output" --instance_prompt="a photo of sks dog" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=5e-6 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=400
11/25/2023 22:59:47 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda

Mixed precision type: no

You are using a model of type clip_text_model to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
{'clip_sample_range', 'timestep_spacing', 'prediction_type', 'variance_type', 'thresholding', 'sample_max_value', 'dynamic_thresholding_ratio'} was not found in config. Values will be initialized to default values.
{'mid_block_only_cross_attention', 'conv_in_kernel', 'dual_cross_attention', 'resnet_time_scale_shift', 'time_embedding_type', 'transformer_layers_per_block', 'class_embed_type', 'use_linear_projection', 'cross_attention_norm', 'num_attention_heads', 'conv_out_kernel', 'encoder_hid_dim', 'projection_class_embeddings_input_dim', 'time_embedding_dim', 'addition_embed_type_num_heads', 'mid_block_type', 'class_embeddings_concat', 'upcast_attention', 'addition_time_embed_dim', 'only_cross_attention', 'encoder_hid_dim_type', 'resnet_out_scale_factor', 'dropout', 'time_embedding_act_fn', 'timestep_post_act', 'reverse_transformer_layers_per_block', 'resnet_skip_time_act', 'time_cond_proj_dim', 'attention_type', 'addition_embed_type', 'num_class_embeds'} was not found in config. Values will be initialized to default values.
11/25/2023 22:59:51 - INFO - __main__ - ***** Running training *****
11/25/2023 22:59:51 - INFO - __main__ -   Num examples = 5
11/25/2023 22:59:51 - INFO - __main__ -   Num batches each epoch = 5
11/25/2023 22:59:51 - INFO - __main__ -   Num Epochs = 80
11/25/2023 22:59:51 - INFO - __main__ -   Instantaneous batch size per device = 1
11/25/2023 22:59:51 - INFO - __main__ -   Total train batch size (w. parallel, distributed & accumulation) = 1
11/25/2023 22:59:51 - INFO - __main__ -   Gradient Accumulation steps = 1
11/25/2023 22:59:51 - INFO - __main__ -   Total optimization steps = 400
Steps:   0%|                                                                                             | 0/400 [00:00<?, ?it/s]Traceback (most recent call last):
  File "G:\dreambooth\diffusers\examples\dreambooth\train_dreambooth.py", line 1422, in <module>
    main(args)
  File "G:\dreambooth\diffusers\examples\dreambooth\train_dreambooth.py", line 1253, in main
    model_pred = unet(
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\dreambooth\diffusers\src\diffusers\models\unet_2d_condition.py", line 1035, in forward
    sample = self.conv_in(sample)
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 3, 512, 512] to have 4 channels, but got 3 channels instead
Steps:   0%|                                                                                             | 0/400 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 994, in launch_command
    simple_launcher(args)
  File "C:\Users\zPTVq\AppData\Local\Programs\Python\Python310\lib\site-packages\accelerate\commands\launch.py", line 636, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\zPTVq\\AppData\\Local\\Programs\\Python\\Python310\\python.exe', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=.\\dog', '--output_dir=.\\output', '--instance_prompt=a photo of sks dog', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=400']' returned non-zero exit status 1.

### Reproduction

accelerate launch train_dreambooth.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4"  --instance_data_dir=".\dog" --output_dir=".\output" --instance_prompt="a photo of sks dog" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=1 --learning_rate=5e-6 --lr_scheduler="constant" --lr_warmup_steps=0 --max_train_steps=400

### Logs

_No response_

### System Info

- `diffusers` version: 0.24.0.dev0
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.10.6
- PyTorch version (GPU?): 2.1.1+cu121 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.24.1
- xFormers version: not installed
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

GPU: 3090TI 24GB VRAM

### Who can help?

@sayakpaul @patrickvonplaten

### PR DESCRIPTION
**Pull request by andrewsagio**
# What does this PR do?
Fixes #5932 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
This is a fix to a training example. So: @sayakpaul and @patrickvonplaten

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sayakpaul** [comment]
@williamberman could you take a look here?

**Comment by patrickvonplaten** [comment]
Thanks for the PR @ctawong, can you explain a bit why the change is needed here? I don't understand #5932 as it's very messy and also am generally not a big fan of adding `try-error` statements

**Comment by ctawong** [comment]
The script errors out when the model to train from does not have a VAE. The original code attempted to handle it but failed. 

The same bug was in the Lora training script in the same folder, and is fixed by PR #3462.

I don’t like the try except either but applied the same fix as in #3462 for consistency.

**Comment by patrickvonplaten** [comment]
The training script is meant to be for Stable Diffusion models which always have a VAE no? I think it'd be better to raise a nice error here instead

**Comment by ctawong** [comment]
The training script is meant for Stable Diffusion models with or without a VAE. 

Model without VAE is supported, just that the VAE check failed. This PR fixes the VAE check.

**Comment by ctawong** [comment]
Can I merge this?

**Comment by sayakpaul** [comment]
> The training script is meant for Stable Diffusion models with or without a VAE.

Is not true. This training script can be used with Deepfloyd IF, too. Since this script was tested rigorously against a few combination of models, I am afraid we won't be able to consider these changes.

**Comment by ctawong** [comment]
>  this script was tested rigorously against a few combination of models

As it stands now, the script doesn't even train from the SD 1.5 model `runwayml/stable-diffusion-v1-5`

**Comment by sayakpaul** [comment]
The fast tests don't seem to tell me that. They run fine. For what combination of CLI args the script doesn't run?

**Comment by ctawong** [comment]
Tested on Windows
```
$MODEL_NAME="runwayml/stable-diffusion-v1-5"
$INSTANCE_DIR="dog"
$OUTPUT_DIR="dreambooth/model"

accelerate launch .\examples\dreambooth\train_dreambooth.py `
  --pretrained_model_name_or_path=$MODEL_NAME  `
  --instance_data_dir=$INSTANCE_DIR `
  --output_dir=$OUTPUT_DIR `
  --instance_prompt="a photo of sks dog" `
  --resolution=512 `
  --train_batch_size=1 `
  --gradient_accumulation_steps=1 `
  --learning_rate=5e-6 `
  --lr_scheduler="constant" `
  --lr_warmup_steps=0 `
  --max_train_steps=400 `
```
Error message:
```
Steps:   0%|                                                                                   | 0/400 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\XXXXXXX\git\diffusers\examples\dreambooth\train_dreambooth.py", line 1428, in <module>
    main(args)
  File "C:\Users\XXXXXXX\git\diffusers\examples\dreambooth\train_dreambooth.py", line 1258, in main
    model_pred = unet(
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\accelerate\utils\operations.py", line 680, in forward
    return model_forward(*args, **kwargs)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\accelerate\utils\operations.py", line 668, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\torch\amp\autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "C:\Users\XXXXXXX\git\diffusers\src\diffusers\models\unet_2d_condition.py", line 1072, in forward
    sample = self.conv_in(sample)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 4, 3, 3], expected input[1, 3, 512, 512] to have 4 channels, but got 3 channels instead
Steps:   0%|                                                                                   | 0/400 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\XXXXXXX\git\diffusers\venv\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\accelerate\commands\accelerate_cli.py", line 47, in main
    args.func(args)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\accelerate\commands\launch.py", line 1017, in launch_command
    simple_launcher(args)
  File "C:\Users\XXXXXXX\git\diffusers\venv\lib\site-packages\accelerate\commands\launch.py", line 637, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\XXXXXXX\\git\\diffusers\\venv\\Scripts\\python.exe', '.\\examples\\dreambooth\\train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--instance_data_dir=dog', '--output_dir=dreambooth/model', '--instance_prompt=a photo of sks dog', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=400']' returned non-zero exit status 1.
```
The training is successful with this fix, which I stole from the LoRA training script which shared many codes with this script.

**Comment by sayakpaul** [comment]
Can you try updating `huggingface_hub` and see if that solves your problem? Essentially what you're doing can be accomplished by the use of `model_info` from the Hugging Face Hub library. I would try to debug that in isolation and see if that's giving expected outputs.

**Comment by ctawong** [comment]
Hi, it is already the latest version huggingface-hub         0.20.1

**Comment by sayakpaul** [comment]
Then this still stands:

```
Essentially what you're doing can be accomplished by the use of model_info from the Hugging Face Hub library. I would try to debug that in isolation and see if that's giving expected outputs.
```

**Pull request closed without merging**
