### PR TITLE
[Wuerstchen] dreambooth lora

### PR DESCRIPTION
**Pull request by kashif**
# What does this PR do?

Lora dreambooth training scripts for Wuerstchen prior pipeline.

Example: https://wandb.ai/krasul/dreambooth-lora/runs/7ia16ohd

needs #6046

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
PR is good to go for me, but I'm really not sure if it's that important. We haven't seen much usage of Wuerstchen yet and I'm not sure if anyone is training LoRAs on it

**Comment by yiyixuxu** [comment]
cc @sayakpaul here - 
can you take a look to see if we can merge this?

**Review by sayakpaul — APPROVED** [review]
Works for me!

Does it also make sense to incorporate the changes to prevent https://github.com/huggingface/diffusers/issues/6552?

**Comment by yiyixuxu** [comment]
@sayakpaul 
yeah for sure - 
do you want to add to your list?  feel free to merge this PR if you think it's ready:)

**Comment by sayakpaul** [comment]
Sorry, I was asking @kashif about incorporating the changes.

**Comment by kashif** [comment]
Ah yes @sayakpaul  let me have a look... shouldn't be hard

**Comment by sayakpaul** [comment]
I guess this is NOT stale? @kashif

**Comment by yiyixuxu** [comment]
pin @kashif

**Comment by yiyixuxu** [comment]
@sayakpaul
I'm also ok with merging it in and opening up this to the community to help fix if @kashif does not have time

**Comment by DN6** [comment]
Should this be opened up to community then? cc: @sayakpaul @kashif?

**Comment by kashif** [comment]
yes sure!

**Comment by yiyixuxu** [comment]
cc @sayakpaul can we merge this and open the remaining task for the community?

**Comment by sayakpaul** [comment]
@kashif let's maybe move this to `examples/research_projects`? I will go ahead and merge then.

**Comment by kashif** [comment]
ok

**Comment by ParagEkbote** [comment]
Hi, can I please move the required files to examples/research_projects? 

Maybe that could close this pending PR?

cc: @sayakpaul

**Comment by sayakpaul** [comment]
Sure, that works for me. Cc: @kashif

**Comment by ParagEkbote** [comment]
I have opened a PR with the requested changes.

Could you please review?

cc: @sayakpaul

**Comment by ParagEkbote** [comment]
Thank you for @kashif for allowing me to lead the PR to its completion.

Could we please close this PR as #9935 has been merged.

cc: @sayakpaul

**Pull request closed without merging**
