### PR TITLE
Support higher dimension LoRAs

### LINKED ISSUE #4593: Unable to load Automatic1111 LoRa due rank being higher than "min(in_features, out_features)}"
### Describe the bug

Hi! I'm unable to load a LoRa as I get the following error.

`ValueError: LoRA rank 384 must be less or equal than 320`

The LoRa works perfectly if the ValueError check is removed from the code. Is it possible to override this error? I don't understand why it must be less or equal. Thanks!

### Reproduction

Run the interference script with [this](https://civitai.com/models/7227/urushi) LoRa
Get error about the LoRa rank

### Logs

```
  File "/home/wizard/pipelines/utils.py", line 465, in load_lora_weights_diffusers
    loader.load_lora_into_unet(state_dict, network_alphas=network_alphas, unet=unet)
  File "/home/wizard/lib/python3.9/site-packages/diffusers/loaders.py", line 1233, in load_lora_into_unet
    unet.load_attn_procs(state_dict, network_alphas=network_alphas)
  File "/home/wizardlib/python3.9/site-packages/diffusers/loaders.py", line 376, in load_attn_procs
    lora = LoRAConv2dLayer(
  File "/home/wizard/lib/python3.9/site-packages/diffusers/models/lora.py", line 58, in __init__
    raise ValueError(f"LoRA rank {rank} must be less or equal than {min(in_features, out_features)}")
```

### System Info

- `diffusers` version: 0.19.3
- Platform: Linux-5.15.107+-x86_64-with-glibc2.31
- Python version: 3.9.16
- PyTorch version (GPU?): 2.0.1+cu118 (True)
- Huggingface_hub version: 0.16.4
- Transformers version: 4.29.2
- Accelerate version: 0.16.0
- xFormers version: 0.0.20
- Using GPU in script?: yes
- Using distributed or parallel set-up in script?: no

### Who can help?

@williamberman @patrickvonplaten @saya

### PR DESCRIPTION
**Pull request by isidentical**
# What does this PR do?

Removes the now moot check which prevented higher rank/dimensional LoRAs used with diffusers.

Fixes #4593

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten and @sayakpaul

### CODE REVIEW

**Comment by isidentical** [comment]
@sayakpaul I looked into writing a test for this but it seems like I can't use a direct civit.ai model, so I assume I need it available on the HF's internal repo (as per this example):

https://github.com/huggingface/diffusers/blob/a7508a76f025fcbe104c28f73dd17c8e866f655b/tests/models/test_lora_layers.py#L726-L743

Could I use some of your help for it?

**Comment by sayakpaul** [comment]
@isidentical absolutely. Let me know which LoRA from civitai you were targeting. I will get it uploaded and then have the `expected_output` values for you :)

**Comment by isidentical** [comment]
> @isidentical absolutely. Let me know which LoRA from civitai you were targeting. I will get it uploaded and then have the expected_output values for you :)

The LoRA from the issue #4593 with Base SD1.5 makes sense I think, WDYT?

**Comment by sayakpaul** [comment]
Alright. Will do. I think meanwhile you would proceed as usual hosting the file on your account. Tomorrow, when I get back I can take care of hosting it on our testing repo and adjusting the assertion numbers. 

Sounds good?

**Pull request merged**
