### PR TITLE
Fix Disentangle ONNX and non-ONNX pipeline

### PR DESCRIPTION
**Pull request by DN6**
# What does this PR do?
Changes the `OnnxStableDiffusionUpscalePipeline`  in the following way

1. Removes inheritance from the `StableDiffusionUpscalePipeline` and replaces it with inheritance from `DiffusionPipeline` so that it aligns with the Diffusers design philosophy
2. Remove the use of `torch` tensors and torch based operations (generator, concatentation etc)  in favour of `numpy` arrays and operations so that this pipeline is more in line with the design of the `OnnxStableDiffusionImg2ImgPipeline` and OnnxStableDiffusionPipeline`
3. Update/cleanup tests for the Onnx Upscale Pipeline  

Fixes # (issue)
#4440

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Is this ready for a review? :-)

**Comment by DN6** [comment]
@patrickvonplaten Ready to review

**Comment by DN6** [comment]
@patrickvonplaten Following up on this

**Review by patrickvonplaten — APPROVED** [review]
Great! Feel free to merge :-)

**Pull request merged**
