### PR TITLE
Adding better way to define multiple concepts and also validation capabilities.

### PR DESCRIPTION
**Pull request by mauricio-repetto**
# What does this PR do?

It tries to enhance/fix the request from here: https://github.com/huggingface/diffusers/issues/3309. In the process together with @fededemo we have:
- Refactored code.
- Fixed typos and improved documentation.
- Added new functionality to better implement the multiple concepts.
- Added validation functionality.

Whenever you have time @sayakpaul / @patrickvonplaten please let us know what do you think about it, thanks!

Fixes # (issue)

## Before submitting
- [x ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests? At this moment I've run several tests, but all of them manually.

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by mauricio-repetto** [comment]
It seems to be only one conflict with the accelerator creation, the parameter `logging_dir` is deprecated and `project_dir` should be used instead of it, I've changed that when refactoring the code, hope that's ok.

```
    accelerator = Accelerator(
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        mixed_precision=args.mixed_precision,
        log_with=args.report_to,
<<<<<<< main
        project_dir=logging_dir,
=======
>>>>>>> main
        project_config=accelerator_project_config,
    )
```

**Comment by patrickvonplaten** [comment]
Very cool! @klopsahlong as the original author of this training script could you also take a look? Are these changes ok for you?

**Comment by mauricio-repetto** [comment]
@klopsahlong, hi! how are you? have you had the chance to review this pr? thanks in advance :)

**Comment by mauricio-repetto** [comment]
All issues are now fixed @klopsahlong.

**Comment by patrickvonplaten** [comment]
Looks good as is, let's try to merge this!

**Pull request merged**
