### PR TITLE
Fix stable diffusion initial latents in the inpainting pipeline

### LINKED ISSUE #261: Inpainting example is using data from the masked parts with strength 1
### Describe the bug

It is my understanding that if we provide `strength=1` to the inpainting pipeline, that the model would try to fill the missing parts without taking into account what was in the image before (where the mask is).

It does not appear to be the case and is really apparent when trying to zoomout of a picture.
In that case, the prediction will very often fill this area with white.

Using the following mask (open the image in a new tab to see the white border):

zoomout_mask

I create prediction first by keeping the white border in the `init_image`, then I create prediction by filling the white border with similar colors (with gimp).

keeping white border:

zoomout_white

Filling white border with gimp:

zoomout_filled

Here is my result with the white border:

white_result

Here is my result with the filled border:

filled_result

It is clear that the model is keeping data about the parts which should be cropped by the mask.

### Reproduction

The code I used to generate the grids is [here](https://gist.github.com/leszekhanusz/27052eefd0cec80a9bda6f0b6392f62e)

Add 3 images above named `zoomout_mask.png` `zoomout_white.png` `zoomout_filled.png` in the `/tmp/inpainting` folder and run the above script.

### Logs

_No response_

### System Info

```shell
diffusers version: commit 5cbed8e0d157f65d3ddc2420dfd09f2df630e978
```

### PR DESCRIPTION
**Pull request by leszekhanusz**
Applying @nagolinc proposition in #261 to the inpainting pipeline.

Should fix #261

This modification allows to do outpainting without having a white border.

### CODE REVIEW

**Comment by patil-suraj** [comment]
Thanks a lot for the PR! Do you have a colab with some examples with which we can verify this ?

**Comment by patrickvonplaten** [comment]
@patil-suraj @anton-l could we check this out maybe? Also related to: https://github.com/huggingface/diffusers/pull/328

**Comment by chengyjonathan** [comment]
I was playing around with this change, and I noticed that it would trigger this error more frequently:

if not mask.shape == init_latents.shape:
            raise ValueError("The mask and init_image should be the same size!")

Even when I explicitly resize the images like so:

initial_image = init_image["image"].convert("RGB").resize((512, 512))
mask_image = init_image["mask"].convert("RGB").resize((512, 512))

**Comment by leszekhanusz** [comment]
@chengyjonathan could you please give us an example of image and mask which causes your problem?

**Comment by chengyjonathan** [comment]
It’s a little tricky to reproduce. Since I was passing the image and mask
through a gradio interface.

**Pull request closed without merging**
