### PR TITLE
Fix duplicate variable assignments in SD3's JointAttnProcessor

### LINKED ISSUE #8515: Duplicate code: SD3 JointAttnProcessor2_0
**What API design would you like to have changed or added to the library? Why?**

SD3's JointAttnProcessor2_0. It has a duplicate code.

**What use case would this enable or better enable? Can you give us a code example?**

In 1135 of diffusers.models.attention_processor.py
https://github.com/huggingface/diffusers/blob/7f51f286a5397cb3e5c5a25693681aa4955e6241/src/diffusers/models/attention_processor.py

Before:
```python
hidden_states = hidden_states = F.scaled_dot_product_attention(
        query, key, value, dropout_p=0.0, is_causal=False
)
```

After:
```python
hidden_states = F.scaled_dot_product_attention(
        query, key, value, dropout_p=0.0, is_causal=False
)
```

### PR DESCRIPTION
**Pull request by Prgckwb**
# What does this PR do?
Duplicate codes in SD3's JointAttnProcessor have been corrected.

Fixes #8515 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@sayakpaul @yiyixuxu @DN6

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]

**Comment by yiyixuxu** [comment]
can you run `make style`?

**Comment by Prgckwb** [comment]
@yiyixuxu 
I have just committed a version with the Ruff formatter applied! 
I'd like you to check it out.

**Comment by yiyixuxu** [comment]
thank you!

**Comment by sayakpaul** [comment]
Thank you!

**Pull request merged**
