### PR TITLE
Fix SDXL finetuning arguments issue

### PR DESCRIPTION
**Pull request by sr5434**
[Forum Post](https://discuss.huggingface.co/t/sdxl-finetuning-script-not-working/65267)

# What does this PR do?
When running the script to fine-tune Stable Diffusion XL, there is an error saying that the ```args``` argument is missing. This is because Accelerate tries to run the ```main``` function without providing an ```args``` parameter(even though it shouldn't). This issue is unique to the SDXL fine-tuning scripts(both the LoRA and full fine-tune). I fixed it by running the ```parse_args``` function inside of the ```main``` function(just like the other fine-tuning scripts), rather than running ```parse_args``` outside the function and passing the outputs in as a parameter.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- (N/A) Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- (N/A) Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- (N/A) Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten
@sayakpaul

### CODE REVIEW

**Comment by sr5434** [comment]
This is the Colab: https://colab.research.google.com/drive/1TUo5wZEnY1o7Ab9QVXnukfX-XNWfwLxQ?usp=sharing

**Comment by sr5434** [comment]
But with this patch, one will have more flexibility(PyTorch vs Jax) as to which ML framework they wish to use.

**Comment by sayakpaul** [comment]
For now, we cannot be deviating here. If we decide to revisit this consideration, we will let you know.

**Comment by sr5434** [comment]
Ok.

**Pull request closed without merging**
