### PR TITLE
Add (Scheduled) Pseudo-Huber Loss training scripts to research projects

### PR DESCRIPTION
**Pull request by kabachuha**
This PR adds an option to use (Scheduled) Pseudo-Huber loss from https://arxiv.org/abs/2403.16728 for text2image and Dreambooth trainings.

Because of this feature being experimental, it's firstly needed to add it to the research projects.

See #7488 for detailed description, plots and examples

@sayakpaul @kashif @patil-suraj

### CODE REVIEW

**Comment by kabachuha** [comment]
The kohya-ss scripts have been merged after throughout testing in https://github.com/kohya-ss/sd-scripts/pull/1228. Will update the rest of this Pull Request soon and prepare for merging in Diffusers

**Comment by sayakpaul** [comment]
Sure.

**Comment by kabachuha** [comment]
@sayakpaul updated all scripts, ready for merging

**Comment by kabachuha** [comment]
Should I do anything about the code quality?

**Comment by kashif** [comment]
you can run `make style` in the root folder to fix

**Comment by kabachuha** [comment]
@kashif what is `make: ruff: No such file or directory`?

**Comment by sayakpaul** [comment]
Please ping me once the CI run is complete.

**Comment by kabachuha** [comment]
@sayakpaul CI check ran, but failed.

I'm getting exhaused 😢

**Comment by sayakpaul** [comment]
If you check https://github.com/huggingface/diffusers/actions/runs/8641181505/job/23690277573?pr=7527, it clearly says the solution:

> Run echo "Quality check failed. Please ensure the right dependency versions are installed with 'pip install -e .[quality]' and run 'make style && make quality'" >> $GITHUB_STEP_SUMMARY

Is it not helpful?

**Comment by kabachuha** [comment]
@sayakpaul Thanks for the instruction! Now I'll cross my fingers and hope it'll finally work🤞

Sorry for all these misunderstandings and extra commits 😓 (please, squash them when merging)

**Comment by sayakpaul** [comment]
Thank you for your contributions.

**Pull request merged**
