### PR TITLE
Fix "push_to_hub only create repo in consistency model lora SDXL training script"

### PR DESCRIPTION
**Pull request by aandyw**
Fix for #6093 

Added push_to_hub `upload_folder` functionality for all `consistency_distillation` scripts.

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks a lot!

**Comment by sayakpaul** [comment]
@patil-suraj if you could take a look here?

**Comment by patrickvonplaten** [comment]
@patil-suraj @williamberman can you take a look here?

**Review by patil-suraj — APPROVED** [review]
Thanks for fixing !

**Pull request merged**
