### PR TITLE
[UniDiffuser Tests] Fix some tests

### PR DESCRIPTION
**Pull request by sayakpaul**
W.r.t the UniDiffusers failing [here](https://github.com/huggingface/diffusers/actions/runs/5108261909/jobs/9181910494#step:7:11856).

This PR fixes some UniDiffuser tests. 

I first reproduced the environment in which our test suite is run following https://github.com/huggingface/diffusers/blob/main/.github/workflows/push_tests.yml. It's as simple as:

* First, run the Docker containing (`diffusers/diffusers-pytorch-cuda`).
* Clone `diffusers` from the PR branch. 
* Install the dependencies. 

Then I ran:

```bash
RUN_SLOW=1 python -m pytest -n 1 --max-worker-restart=0 --dist=loadfile tests/pipelines/unidiffuser/test_unidiffuser.py
```

On an A100, with the changes introduced in this PR all the tests from `test_unidiffuser.py` passed including the SLOW ones. 

But on a V100, it failed with:

```
FAILED tests/pipelines/unidiffuser/test_unidiffuser.py::UniDiffuserPipelineSlowTests::test_unidiffuser_default_joint_v1_fp16 - AssertionError: assert 'A living room' == 'a living room'
```

@patrickvonplaten any thoughts on how this should be handled? Since our SLOW tests are run on a V100 always, I think it's okay to switch "'a living room'" to ensure the test passes but on an A100 this would fail complaining:

```
FAILED tests/pipelines/unidiffuser/test_unidiffuser.py::UniDiffuserPipelineSlowTests::test_unidiffuser_default_joint_v1_fp16 - AssertionError: assert 'a living room' == 'A living room'
```

(Just the opposite of the failure noted earlier) 

Cc: @dg845

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
cool!

**Comment by sayakpaul** [comment]
@patrickvonplaten I think there's still an issue with one SLOW test when run on V100 as stated initially. Maybe you missed it?

**Comment by patrickvonplaten** [comment]
Ah sorry yeah, we should try to make the code work for V100 since our tests run on a V100

**Comment by sayakpaul** [comment]
> Ah sorry yeah, we should try to make the code work for V100 since our tests run on a V100

Will make the necessary changes 👍

**Pull request merged**
