### PR TITLE
make `pipelines` tests device-agnostic (part2)

### PR DESCRIPTION
**Pull request by faaany**
## What does this PR do?

Followed by [this ](https://github.com/huggingface/diffusers/pull/9399) PR

### CODE REVIEW

**Comment by IlyasMoutawwakil** [comment]
@faaany I would like to merge this PR this week keeping the momentum from the first one.

**Comment by faaany** [comment]
> @faaany I would like to merge this PR this week keeping the momentum from the first one.

thanks a lot! let me update it quickly.

**Comment by faaany** [comment]
done.

**Comment by IlyasMoutawwakil** [comment]
@DN6

**Review by DN6 — APPROVED** [review]

**Pull request merged**
