### PR TITLE
[CI] Add slow MPS tests

### PR DESCRIPTION
**Pull request by anton-l**

### CODE REVIEW

**Comment by anton-l** [comment]
cc @pcuenca for the failing tests reference, feel free to take over the PR if you get to it first :)

**Comment by pcuenca** [comment]
I fixed a couple crashes I found in #1170. I can continue here :)

**Comment by pcuenca** [comment]
I made the failing tests pass. Some where about generators not being compatible with the `mps` device, in some cases I had to increase the tolerance. But in other cases the returned slices are completely different as in other devices, I'm not sure if it's because of the "warmup" bug.

**Comment by pcuenca** [comment]
@anton-l I think this should be ready now :)

**Comment by pcuenca** [comment]
@anton-l I'll merge `main` and retest this so we can merge.

**Comment by anton-l** [comment]
@pcuenca maybe we should make these tests nightly (+ manually triggered) for now? We only have one MPS runner and the fast tests queue will get blocked by slow tests

**Comment by pcuenca** [comment]
> @pcuenca maybe we should make these tests nightly (+ manually triggered) for now? We only have one MPS runner and the fast tests queue will get blocked by slow tests

Sounds good!

**Pull request merged**
