### PR TITLE
[don't merge] allow lora checkpoint to have additional unsupprted layers 

### PR DESCRIPTION
**Pull request by yiyixuxu**
fix https://github.com/huggingface/diffusers/issues/6368

I'm not sure if we want to do this, but there are "wrong" Lora checkpoints that come with these additional and unnecessary layers. They seem to be able to be used in comfyui, we can also allow them to be used in diffusers if you just throw a warning instead of an error 

do we need to support this? is there any downside to doing this? ideally they should fix the checkpoints, no?

this works now
```python
from requests import get
from diffusers import StableDiffusionXLPipeline, LCMScheduler

sdxl_pipeline_id = "stabilityai/stable-diffusion-xl-base-1.0"
lora_url = "https://civitai.com/api/download/models/247778?type=Model&format=SafeTensor"
lora_path = "./lcm-turbo-mix.safetensors"

with open(lora_path, "wb") as fh:
  data = get(lora_url, stream=True)
  for chunk in data.iter_content(chunk_size=8192):
    fh.write(chunk)

pipe = StableDiffusionXLPipeline.from_pretrained(
  sdxl_pipeline_id,
  variant="fp16"
)


pipe.load_lora_weights(lora_path)

pipe.enable_model_cpu_offload()
image = pipe(
  prompt="a horse, highly detailed, 4k, professional",
  negative_prompt="blurry",
  num_inference_steps=8,
).images[0]
image.save("yiyi_test_out.png")
```

### CODE REVIEW

**Comment by yiyixuxu** [comment]
cc @sayakpaul

**Comment by sayakpaul** [comment]
Hmm, I think we should support it because of the ecosystem compatibility. We should throw a warning and make it clear as you mentioned. 

The only downside I can foresee with that is the risk of silent bugs. But I don’t think we can be rigorous about it from the getgo either.

**Review by sayakpaul — COMMENTED** [review]
Ah, after looking at the changes, feels like a bit too much of a burden. 

Do we have an idea on how many civitai checkpoints are like this?

**Comment by yiyixuxu** [comment]
not sure - we only have one bug report so far
I'm also in favor of not supporting this - it does not make sense to me

what should we recommend they do in this case, then?

**Comment by sayakpaul** [comment]
Hmm, I think then we're on the same page. This seems too risky to support, and we don't know what the unintended consequences might be. 

I think it might be best to recommend to the users that they should correct the checkpoints. I think this is still okay because this does seem really like a very nit edge case. If we see substantial amount of such requests, we can revisit it. 

WDYT?

**Comment by yiyixuxu** [comment]
@sayakpaul sounds good!

**Comment by CaptainStiggz** [comment]
@sayakpaul @yiyixuxu Curious how you concluded that, based on the changes (switching to a warning rather than raising an exception), this constitutes a burden. 

I also ran into this recently. I have an employee who trains loras and occasionally uses civitai and others as starting points. Even if these layers are unnecessary, it seems like a pretty low cost to support a wider slice of the ecosystem. I'm now going to just plant a similar bit of code in my app to auto-correct the checkpoints.

**Comment by sayakpaul** [comment]
Thanks for raising your question. Autocorrection might have another set of consequences we may not be fully aware of. So, we decided to go with something that the majority of our users prefer. To us, the issue being presented here is an edge case.

**Comment by CaptainStiggz** [comment]
Would it potentially be better to allows `load_lora_weights` to have an `allow_unsupported_layers` param?

**Comment by yiyixuxu** [comment]
hi @CaptainStiggz 

we provided a script here for you to remove the unsupported layers - I agree with @sayakpaul here, since it is an edge case and not really expected, it is better to be handled in the apps that use diffusers

https://github.com/huggingface/diffusers/issues/6368#issuecomment-1965993330

```python
from requests import get
from diffusers import StableDiffusionXLPipeline, LCMScheduler
import safetensors

sdxl_pipeline_id = "stabilityai/stable-diffusion-xl-base-1.0"
lora_url = "https://civitai.com/api/download/models/247778?type=Model&format=SafeTensor"
lora_path = "./lcm-turbo-mix.safetensors"

with open(lora_path, "wb") as fh:
  data = get(lora_url, stream=True)
  for chunk in data.iter_content(chunk_size=8192):
    fh.write(chunk)

state_dict = safetensors.torch.load_file(lora_path, device="cpu")
state_dict = {k: w for k, w in state_dict.items() if k in ["input_blocks", "middle_block", "output_blocks"]}


pipe = StableDiffusionXLPipeline.from_pretrained(
  sdxl_pipeline_id,
  variant="fp16"
)


pipe.load_lora_weights(state_dict)

pipe.enable_model_cpu_offload()
image = pipe(
  prompt="a horse, highly detailed, 4k, professional",
  negative_prompt="blurry",
  num_inference_steps=8,
).images[0]
```

**Comment by AbhinavGopal** [comment]
Hi @yiyixuxu, does this fix still work? When I use it, in the example you provided, the entire state_dict is emptied out. Maybe I'm configuring something incorrectly?

**Pull request closed without merging**
