### PR TITLE
Fix model offload bug when key isn't present

### PR DESCRIPTION
**Pull request by DN6**
# What does this PR do?
This PR fixes an issue with `enable_model_cpu_offload` when a key isn't present in a checkpoint on the hub 

Fixes # (issue)
#5026

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]

**Comment by patrickvonplaten** [comment]
LGTM, the use case here is the refiner mostly: https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0 which doesn't have a `text_encoder`. We really need tests for this whole pipeline class

**Review by patrickvonplaten — APPROVED** [review]

**Comment by DN6** [comment]
There's a flaky test. Will merge when CI is green.

**Comment by tin2tin** [comment]
> There's a flaky test. Will merge when CI is green.

Thank you. I'm standing by to release the Pallaidium Blender add-on with Würstchen implented, when this fix is comitted.

**Comment by tin2tin** [comment]
Thank you for the swift handling of this.

**Pull request merged**
