### PR TITLE
Update train_dreambooth_colossalai.py

### PR DESCRIPTION
**Pull request by haofanwang**
Fix a known bug in this example. From [a recent update](https://github.com/hpcaitech/ColossalAI/pull/2445) in colossalai.

### CODE REVIEW

**Comment by haofanwang** [comment]
@patrickvonplaten This update has been merged into ColossalAI, it should be fine to merge into diffusers.

**Comment by patrickvonplaten** [comment]
Hey @haofanwang,

Could you maybe run:

```
make style
```

once?

**Comment by haofanwang** [comment]
Already done. But it seems that the testing is still fail? @patrickvonplaten

**Comment by isamu-isozaki** [comment]
@haofanwang I noticed that when you run the style check it modifies the other parts of the code too which causes the tests to fail interestingly enough. So I recommend doing git add on just the colossalai part and nothing else. Then I think it should be fixed.

**Comment by haofanwang** [comment]
Thanks. Will fix this in a new PR.

**Pull request closed without merging**
