### PR TITLE
[Tests] add test suite for SD3 DreamBooth

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

SD3 training will be crucial in the coming days and we would want to ensure robustness for our canonical scripts. So, this PR adds test suites for the LoRA and non-LoRA DreamBooth scripts.

### CODE REVIEW

**Comment by sayakpaul** [comment]
Will add more tests for prior preservation too in a separate PR once I fix it (reference: https://github.com/huggingface/diffusers/issues/8589).

**Comment by sayakpaul** [comment]
@yiyixuxu @asomoza a gentle ping here.

**Review by asomoza — APPROVED** [review]

**Comment by asomoza** [comment]
Really great idea!.  Actually it helps a lot. I wanted to test it and all the tests fails for me and I know why, so I'll open a PR to fix it.

**Comment by sayakpaul** [comment]
@asomoza which tests are you referring to?

**Comment by asomoza** [comment]
Tested the lora ones:

```python
pytest examples/dreambooth/test_dreambooth_lora_sd3.py 
============================================================ test session starts =============================================================
platform linux -- Python 3.12.3, pytest-8.2.2, pluggy-1.5.0
configfile: pyproject.toml
plugins: requests-mock-1.10.0, xdist-3.6.1, timeout-2.3.1
collected 3 items                                                                                                                            

examples/dreambooth/test_dreambooth_lora_sd3.py FFF                                                                                    [100%]

========================================================== short test summary info ===========================================================
FAILED examples/dreambooth/test_dreambooth_lora_sd3.py::DreamBoothLoRASD3::test_dreambooth_lora_sd3 - test_examples_utils.SubprocessCallException: Command `accelerate launch --config_file /tmp/tmp2yatc1ok/default_config.yml examples/dreamb...
FAILED examples/dreambooth/test_dreambooth_lora_sd3.py::DreamBoothLoRASD3::test_dreambooth_lora_sd3_checkpointing_checkpoints_total_limit - test_examples_utils.SubprocessCallException: Command `accelerate launch --config_file /tmp/tmp2yatc1ok/default_config.yml examples/dreamb...
FAILED examples/dreambooth/test_dreambooth_lora_sd3.py::DreamBoothLoRASD3::test_dreambooth_lora_sd3_checkpointing_checkpoints_total_limit_removes_multiple_checkpoints - test_examples_utils.SubprocessCallException: Command `accelerate launch --config_file /tmp/tmp2yatc1ok/default_config.yml examples/dreamb...
============================================================= 3 failed in 27.89s =============================================================
```

After applying https://github.com/huggingface/diffusers/pull/8743:

```python
============================================================ test session starts =============================================================
platform linux -- Python 3.12.3, pytest-8.2.2, pluggy-1.5.0
configfile: pyproject.toml
plugins: requests-mock-1.10.0, xdist-3.6.1, timeout-2.3.1
collected 3 items                                                                                                                            

examples/dreambooth/test_dreambooth_lora_sd3.py ...                                                                                    [100%]

============================================================= 3 passed in 40.13s =============================================================
```

**Comment by sayakpaul** [comment]
Thanks @asomoza. I have left some comments on https://github.com/huggingface/diffusers/pull/8743. Let's get that merged soon.

**Review by DN6 — APPROVED** [review]
Nice 👍🏽 Good to merge once #8743 is handled.

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by sayakpaul** [comment]
Thanks everyone for chiming in for this PR :)

**Pull request merged**
