### PR TITLE
Support model without vae

### LINKED ISSUE #5429: [Hacktoberfest] Support models without vae in other examples than dreambooth
**Is your feature request related to a problem? Please describe.**
I noticed that some features in dreambooth seem to not be in other examples. The main one I found was supporting models without vae not being there in textual_inversion and text_to_image example.

**Describe the solution you'd like**
Make a pr for it

### PR DESCRIPTION
**Pull request by isamu-isozaki**
# What does this PR do?

Support models without vae in textual inversion and text_to_image examples

Fixes #5429

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by isamu-isozaki** [comment]
I'll do tests tomorrow

**Comment by DN6** [comment]
Hi @isamu-isozaki just following up to see if you were able to run the tests. The Deepfloyd IF model doesn't use a VAE if you were still looking for something to test with.

**Comment by isamu-isozaki** [comment]
@DN6 Oh, sorry, I got a bit distracted. I'll try testing the 64x64 IF with textual inv tonight!

**Comment by isamu-isozaki** [comment]
Slight update: To make it work with IF, I added support for non-clip tokenizers/text encoders exactly like how Dreambooth did it. But it doesn't fit in my GPU card so I will try colab tomorrow.

**Comment by patrickvonplaten** [comment]
Should we maybe create a new script for this? Think this might be better hosted in a new file as it's quite a different use case to SD

**Comment by isamu-isozaki** [comment]
@patrickvonplaten interesting! The main motivation for this script was to make the scripts more general like dreambooth. I think you can still do sd textual inversion etc.

**Comment by isamu-isozaki** [comment]
Ah, I think Deepfloyd IF is a bit too large for colaboratory. I'll search for smaller pixel-based models to test. I will make this PR just for the textual inversion script. But if I can't find a model by tomorrow I'll close this PR for now.

**Pull request closed without merging**
