### PR TITLE
MAINT Permission for GH token in stale.yml

### PR DESCRIPTION
**Pull request by BenjaminBossan**
# What does this PR do?

See https://github.com/huggingface/peft/pull/2061 for the equivalent PR in PEFT.

The stale bot is currently [failing](https://github.com/huggingface/diffusers/actions/workflows/stale.yml). This restores the functionality of the stale bot after permissions for the token have been limited. The action still shows errors for PEFT but the bot appears to work fine.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sayakpaul** [comment]
https://github.com/huggingface/diffusers/pull/9426#

**Comment by BenjaminBossan** [comment]
I added permissions for PRs too.

**Comment by BenjaminBossan** [comment]
@sayakpaul I think this can be merged. The same change restored the stale bot's functionality for PEFT.

**Review by sayakpaul — APPROVED** [review]
Thank you!

**Pull request merged**
