### PR TITLE
Fix StableDiffusionPipeline when `text_encoder=None`

### PR DESCRIPTION
**Pull request by DN6**
# What does this PR do?
FIx for SD Pipeline when `text_encoder=None` and `tokenizer=None`

Fixes # (issue)
#8287

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks. 

We should consider adding tests for this. I think this is a real scenario.

**Comment by sayakpaul** [comment]
Cc: @bghira could you test if this solves the issue you reported?

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by DN6** [comment]
> We should consider adding tests for this. I think this is a real scenario.
@sayakpaul a fast test has been included in the PR.

**Review by sayakpaul — APPROVED** [review]
Thanks!

**Review by bghira — APPROVED** [review]

**Pull request merged**
