### PR TITLE
image_processor.py: Fixed an error in ValueError's message

### PR DESCRIPTION
**Pull request by sirpaddy**
as the string's join method tried to join types, instead of strings

Bug that occurred:

f"Input is in incorrect format. Currently, we only support {', '.join(supported_formats)}" TypeError: sequence item 0: expected str instance, type found

# What does this PR do?

Single bug fix.

Fixes # ```f"Input is in incorrect format. Currently, we only support {', '.join(supported_formats)}" TypeError: sequence item 0: expected str instance, type found```

@sayakpaul

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]
thanks

**Comment by sirpaddy** [comment]
Hi @yiyixuxu, the check_code_quality-check failed (`C417 Unnecessary 'map' usage (rewrite using a generator expression)`). Shall I update my code accordingly and create a new PR, or how does it work?

**Comment by yiyixuxu** [comment]
you can just update on the same PR branch!

**Comment by sirpaddy** [comment]
@yiyixuxu thanks - done!

**Pull request merged**
