### PR TITLE
Replace torchsde dependency with torchsde-brownian

### PR DESCRIPTION
**Pull request by akx**
# What does this PR do?

This PR replaces the [`torchsde`](https://github.com/google-research/torchsde) dependency with my fork [`torchsde-brownian`](https://github.com/akx/torchsde-brownian) that only includes the Brownian motion code that is required by the `dpmpp_sde` sampler (that itself is lifted from [`k-diffusion`](https://github.com/crowsonkb/k-diffusion) (where there is a sibling PR https://github.com/crowsonkb/k-diffusion/pull/82)) that was added in https://github.com/huggingface/diffusers/pull/3020.

The fork also has one dependency less (`boltons`), though that change would also be in a future unreleased version of `torchsde` thanks to my PR over there.

The implementation of this PR here is really just a search-and-replace. 

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Did you make sure to update the documentation with your changes? 
  - No documentation changes, just an internal library switcharoo. 
- [x] Did you write any new necessary tests?
  - No new tests, the brownian code is exactly the same as in the original `torchsde` package.

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

- Pipelines:  @patrickvonplaten and @sayakpaul

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @akx,

Thanks for the PR! Just to better understand is there any functionality that is changed? If the PR stays exactly the same, I don't fully see the advantage of changing the package here tbh

**Comment by akx** [comment]
Anyway, there's also a secondary concern here since #3020 basically just copy-pasted the sampler from `k-diffusion` (which, confusingly, this repo _also_ depends on anyway), and seemingly re-licensed that MIT code as Apache-2.0 here.

**Comment by akx** [comment]
De-staling. WDYT, @patrickvonplaten?

**Comment by patrickvonplaten** [comment]
@akx, I don't feel super comfortable replacing the dependency because torchsde is a robust, well-known library with >1K stars. I don't really mind that it has some additional functionality that we don't need

**Comment by akx** [comment]
@patrickvonplaten Thanks for getting back to me! 

As explained in the PR description and `torchsde-brownian`'s readme, `torchsde-brownian` is a "cropped" version of `torchsde` proper, with no code changes. It's just as robust as `torchsde` itself. (`torchsde`'s authors have noted that they no longer work on the package, for what it's worth: https://github.com/google-research/torchsde/issues/131#issuecomment-1680238316)

Either way, I suppose this PR is no longer quite as required now that torchsde==0.2.6 (likely the final ever version, given the comments above) is out after I fixed torchsde's CI process to let them release with confidence (https://github.com/google-research/torchsde/pull/140).

The secondary concern still stands: the sampler introduced in #3020 (that introduced the `torchsde` requirement) was copy-pasted from the k-diffusion project (which has a different license than this project).

**Pull request closed without merging**
