### PR TITLE
[ldm3d] Update code to be functional with the new checkpoints

### PR DESCRIPTION
**Pull request by estelleafl**
This PR enables the load of the new checkpoints https://huggingface.co/Intel/ldm3d-4c, based on a different way of use the depth

Question: where in the diffusers library should I specify the new model? Should I?

```python

from diffusers import StableDiffusionLDM3DPipeline

pipe = StableDiffusionLDM3DPipeline.from_pretrained("Intel/ldm3d-4c")
pipe.to("cuda")


prompt ="A picture of some lemons on a table"
name = "lemons"

output = pipe(prompt)
rgb_image, depth_image = output.rgb, output.depth
rgb_image[0].save(name+"_ldm3d_rgb.jpg")
depth_image[0].save(name+"_ldm3d_depth.png")
```

### CODE REVIEW

**Comment by estelleafl** [comment]
Hi @sayakpaul and @patrickvonplaten !
Let us know how we can improve :)

**Comment by estelleafl** [comment]
> Hey @estelleafl,
> 
> Happy to merge the code once the fast test passes. Could you maybe adapt the expected values in the integration test so that https://github.com/huggingface/diffusers/actions/runs/5376838568/jobs/9754529527?pr=3875#step:6:6958
> 
> ```
> FAILED tests/pipelines/stable_diffusion/test_stable_diffusion_ldm3d.py::StableDiffusionLDM3DPipelineFastTests::test_stable_diffusion_ddim - AssertionError: assert 0.01909446533203152 < 0.01
>  +  where 0.01909446533203152 = <built-in method max of numpy.ndarray object at 0x7f6daf856d50>()
>  +    where <built-in method max of numpy.ndarray object at 0x7f6daf856d50> = array([0.0050099 , 0.01644091, 0.01909447]).max
>  +      where array([0.0050099 , 0.01644091, 0.01909447]) = <ufunc 'absolute'>((array([103.46727 ,  85.812004,  87.849236], dtype=float32) - array([103.46226 ,  85.828445,  87.86833 ])))
>  +        where <ufunc 'absolute'> = np.abs
>  +        and   array([103.46727 ,  85.812004,  87.849236], dtype=float32) = <built-in method flatten of numpy.ndarray object at 0x7f6daf856a50>()
>  +          where <built-in method flatten of numpy.ndarray object at 0x7f6daf856a50> = array([103.46727 ,  85.812004,  87.849236], dtype=float32).flatten
> ```
> 
> passes?

Thank you!
The issue is that it passes on my computer.. not sure how I can make it work

**Comment by patrickvonplaten** [comment]
Can you make sure to run the test on CPU on your computer and not on GPU? Otherwise maybe increase the tolerance?

**Comment by estelleafl** [comment]
Thank you @patrickvonplaten 
Running it on CPU worked :)
All clear now!

**Comment by patrickvonplaten** [comment]
Super!

**Pull request merged**
