### PR TITLE
Update `CLIPFeatureExtractor` to `CLIPImageProcessor` and `DPTFeatureExtractor` to `DPTImageProcessor`

### PR DESCRIPTION
**Pull request by tolgacangoz**
This pull request updates the usage of `CLIPFeatureExtractor` to `CLIPImageProcessor` in the codebase.
Just to remove this warning message and be ready for the future:
```
/home/.../lib/python3.10/site-packages/transformers/models/clip/feature_extraction_clip.py:28:
FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of
Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
```

@a-r-r-o-w

### CODE REVIEW

**Review by a-r-r-o-w — APPROVED** [review]
awesome, looks good to me! the codebase has CLIPImageProcessor at many places so these might have been overlooked

edit: could you run `make style` :sweat_smile:

**Review by sayakpaul — APPROVED** [review]
Looks like harmless.

**Comment by tolgacangoz** [comment]
> awesome, looks good to me! the codebase has CLIPImageProcessor at many places so these might have been overlooked
> 
> edit: could you run `make style` 😅

How can I forget this, sry 😅.

**Comment by tolgacangoz** [comment]
I also encountered this:
```
/home/.../lib/python3.10/site-packages/transformers/models/dpt/feature_extraction_dpt.py:28:
FutureWarning: The class DPTFeatureExtractor is deprecated and will be removed in version 5
of Transformers. Please use DPTImageProcessor instead.
  warnings.warn(
```

**Comment by a-r-r-o-w** [comment]
> Should this be another PR? I think this PR can be seen for `transformers` deprecation warnings?

i think it should be good here, thanks!

**Comment by a-r-r-o-w** [comment]
cc @yiyixuxu, good to go?

**Comment by tolgacangoz** [comment]
Resolved the merge conflict.

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by tolgacangoz** [comment]
Thanks for merging!

**Pull request merged**
