### PR TITLE
[WIP] Add Latent Consistency Distillation Script

### PR DESCRIPTION
**Pull request by dg845**
# What does this PR do?

This PR adds an example script to perform latent consistency distillation following Algorithm 1 in the [latent consistency models paper](https://arxiv.org/abs/2310.04378). Latent consistency distillation (LCD) distills a latent diffusion model (LDM) such as Stable Diffusion to a latent consistency model (LCM), allowing fast onestep or few-step inference using the LCM while preserving the performance of the LDM.

Follow up to PR #5448 .

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten
@sayakpaul
@luosiallen

### CODE REVIEW

**Comment by Amin456789** [comment]
nice! hope it supports safetensors so we can make low size fp16 like regular models for a better ram and cpu usage

**Comment by DN6** [comment]
@dg845 Could you please run `make style && make quality` on the PR so the code QC checks pass. 
Is it possible to run this script in a Colab notebook to verify that training is working as expected? If so, could you please include a link to the Colab as well.

**Comment by dg845** [comment]
Hi @DN6, the script is not finished yet. I am currently working with @luosiallen and @patrickvonplaten on this.

**Comment by dg845** [comment]
Closing because PR #5727 has been merged.

**Pull request closed without merging**
