### PR TITLE
Controlnet Img2Img with reference

### PR DESCRIPTION
**Pull request by realimposter**
# What does this PR do?

Adds controlnet reference functionality to the controlnet Img2Img pipeline. I created this by combining "stable_diffusion_controlnet_reference.py" into "pipeline_controlnet_img2img.py"

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @realimposter, 

What is a common use case of this? Also how is this different from https://github.com/huggingface/diffusers/pull/3435?

**Comment by patrickvonplaten** [comment]
Also related to: https://github.com/huggingface/diffusers/issues/4257

**Comment by yamkz** [comment]
I really desire the SDXL-supported 'img2img+ControlNet+reference only pipeline' and 'inpainting+ControlNet+reference only pipeline.' I would be very happy if they were available.

**Comment by stilletto** [comment]
> Hey @realimposter,
> 
> What is a common use case of this? Also how is this different from #3435?

It can be usefull with face photo editing on low lavel of noice power.

**Comment by breengles** [comment]
> Hey @realimposter,
> 
> What is a common use case of this? Also how is this different from #3435?

Hey @patrickvonplaten!
I am also trying to get it working (well, i2i adapts actually more or less straightforwardly). The most different feature is that the pipeline you mentioned does not support image input (but as I said it can be readily adapted). 

Currently, I am struggling to adapt reference guidance to the inpaint pipelines for the same reason -- it would allow more ways to edit images. By the way, these combinations of inpainting, reference, and ControlNets work totally fine in A1111 so it might be useful to them in diffusers (perhaps, in the community examples). So, I tried to do the following but haven't got any reasonable result:
```
        # 10. Denoising loop
        num_warmup_steps = len(timesteps) - num_inference_steps * self.scheduler.order
        with self.progress_bar(total=num_inference_steps) as progress_bar:
            for i, t in enumerate(timesteps):
                # expand the latents if we are doing classifier free guidance
                latent_model_input = torch.cat([latents] * 2) if do_classifier_free_guidance else latents
                latent_model_input = self.scheduler.scale_model_input(latent_model_input, t)

                # ref only part
                noise = randn_tensor(
                    ref_image_latents.shape,
                    generator=generator,
                    device=device,
                    dtype=ref_image_latents.dtype,
                )
                ref_xt = self.scheduler.add_noise(
                    ref_image_latents,
                    noise,
                    t.reshape(
                        1,
                    ),
                )
                ref_xt = torch.cat([ref_xt] * 2) if do_classifier_free_guidance else ref_xt
                ref_xt = self.scheduler.scale_model_input(ref_xt, t)

                if num_channels_unet == 9:
                    # concat latents, mask, masked_image_latents in the channel dimension
                    latent_model_input = torch.cat([latent_model_input, mask, masked_image_latents], dim=1)
                    
                    if do_classifier_free_guidance:
                        ref_image_latents_inject = torch.cat([ref_image_latents] * 2)
                    else:
                        ref_image_latents_inject = ref_image_latents

                    ref_xt = torch.cat([ref_xt, empty_mask, ref_image_latents_inject], dim=1)

                MODE = "write"
                self.unet(
                    ref_xt,
                    t,
                    encoder_hidden_states=prompt_embeds,
                    cross_attention_kwargs=cross_attention_kwargs,
                    return_dict=False,
                )

                # predict the noise residual
                MODE = "read"
                noise_pred = self.unet(
                    latent_model_input,
                    t,
                    encoder_hidden_states=prompt_embeds,
                    cross_attention_kwargs=cross_attention_kwargs,
                    return_dict=False,
                )[0]
...
```
closeup-pexels-abed-albaset-alhasan-7814598
closeup-pexels-abed-albaset-alhasan-7814598
closeup-pexels-abed-albaset-alhasan-7814598-prompt=00_00000

I must say that everything works fine with non-inpainting weights with 4-channel input so I think it is smth wrong with how I am trying to prepare `ref_xt` (though, it should follow the A1111's flow).
I would greatly appreciate any advice :hugs:

**Review by patrickvonplaten — COMMENTED** [review]
@DN6 can you take a look here?

**Comment by patrickvonplaten** [comment]
@DN6 gentle ping here

**Comment by DN6** [comment]
@realimposter Could we move this into the community pipelines please?

**Pull request closed without merging**
