### PR TITLE
[CI] Add stalebot

### PR DESCRIPTION
**Pull request by anton-l**
This will run the stale bot at 12:00 CET each day, commenting on issues that were inactive for 23 days, and closing them after another 7 days.

### CODE REVIEW

**Review by pcuenca — APPROVED** [review]
LGTM

**Comment by leszekhanusz** [comment]
Oh no :cry: [stalebot is awful](https://drewdevault.com/2021/10/26/stalebot.html), and 23 days is so little! So many real issues are going to be hidden!

**Comment by anton-l** [comment]
@leszekhanusz fair point! We can disable the auto-closing, so that the bot only acts as a reminder to take another look at the issue and close it manually if the issue is seemingly resolved (for cases like pip install problems, etc.)

**Comment by patrickvonplaten** [comment]
Hmm, we make sure that no issue is closed without answer from us (that's why we have the reminder first).

If we don't have a bot that auto-reminds or auto-closes issues, we have to do it and this is often worse because it doesn't follow a 30 days schedule (so less predictable) and it creates much more overhead for maintainers (since they have to go through open-issues without a reminder to check whether it's resolved or not).

Most contributors opening an issue don't close it themselves after: https://github.com/huggingface/diffusers/issues/193 or things become simply stale because contributors don't answer anymore, e.g. https://github.com/huggingface/diffusers/issues/150

I'm very much in favor of adding a bot here

**Comment by leszekhanusz** [comment]
Please let me propose an alternative: activating **GitHub discussions** on the repo.

You can activate the discussions tab and propose a few categories.

When an issue is posted, if it is not a clear bug or an enhancement well defined, then it should be moved directly to the discussions (like it is done on [graphql-ws](https://github.com/enisdenjo/graphql-ws/issues) for example)

This would already reduce considerably the number of issues left.

For clear enhancement requests, they should be labelled as enhancement and you have to make a decision (it can be difficult, I know) about them:

- either it is something you know already you will never accept in the repo and you close it manually, labelling it as wontfix
- or it is something that could be done. You don't have to implement it but you would accept a PR if someone else did the work. In that case that enhancement request could stay on the issues page, even for years if needed.

I know that triaging issues takes time and sometimes asks for courage when you have to make the decision to decline an issue, I know that you currently have an increase of new issues recently, and thank you again for maintaining this repo, but it's way better in my opinion than to sweep things under the rug by using the stalebot.

#193 could be closed now or moved to discussions. When that happens in the repo I maintain, I close the issue after a few days by labeling it as `waiting for feedback` and ask to reopen if they have more info.
#150 could stay forever unless this is something you know you don't want to add to the repo, in the case it could be closed now.

There is nothing worse than going to GitHub to check for a problem you have and you see that the issue you have was already there 2 years ago, has many "me too" comments, and was closed a long time ago by the stale bot.

You could also ask for volunteers to triage issues if you need some help. Think about it.

**Comment by sgugger** [comment]
The stale-bot has been a very good workflow in Transformers. It does not necessarily suits every maintainer style, but it has worked pretty well with the way we work at Hugging Face. Note @leszekhanusz that we do not use Discussions since we have [our forums](https://discuss.huggingface.co/) and encourage people to post there when they open issues that are not well-defined, so it takes care of the first case you mention.

For the second case, issues with some predefined labels are not closed by the stale-bot (for Transformers we use Good first issues/WiP for instance).

**Comment by LysandreJik** [comment]
I agree that the stale bot only fits certain maintainer styles and is not for every repository. It has been heavily criticized in the past and I can definitely understand why.

We activated it on transformers after the flow of issues was too high and we couldn't spend time properly closing each issue we couldn't address. If there are enough maintainers for diffusers, I don't see a problem with not enabling the stale bot for now!

**Comment by patrickvonplaten** [comment]
Ok - @anton-l should we then maybe just enable a "reminder" bot?

**Comment by patrickvonplaten** [comment]
What is the status here? Should we adapt the config to just a reminder bot and then merge it?

**Comment by patil-suraj** [comment]
Agree with Lysandre's comment here! For now we can just go ahead with "reminder bot, we can activate closing if we see number of stale issues blowing up.

**Comment by anton-l** [comment]
Removed the closing part and added a `stale` label

**Pull request merged**
