### PR TITLE
post release 0.26.2

### PR DESCRIPTION
**Pull request by sayakpaul**

### CODE REVIEW

**Review by regisss — APPROVED** [review]
Thanks!

**Comment by regisss** [comment]
A couple of tests failed, I guess it is not related to this PR?

**Comment by sayakpaul** [comment]
They are very related as they affect the deprecation cycle. Working on fixing them :-)

**Comment by sayakpaul** [comment]
PRs to fix the problems:

* https://github.com/huggingface/diffusers/pull/6886
* https://github.com/huggingface/diffusers/pull/6889 (WIP)

**Pull request merged**
