### PR TITLE
Add an option to use TGATE method to accelerate the inference of PixArt-Alpha.

### PR DESCRIPTION
**Pull request by WentianZhang-ML**
This PR adds a training-free configuration of TGATE  for accelerating the inference of [PixArt-Alpha](https://github.com/PixArt-alpha/PixArt-alpha) and its latent consistency model.  @lawrence-cj 

### Describe the solution you'd like.

In our latest research, "Cross-Attention Makes Inference Cumbersome in Text-to-Image Diffusion Models" [https://arxiv.org/abs/2404.02747](url). We found that cross-attention outputs converge to a fixed point during the initial denoising steps. Consequently, the entire inference process can be divided into two stages: an initial semantics-planning phase, during which the model relies on text to plan visual semantics, and a subsequent fidelity-improving phase, during which the model tries to generate images from previously planned semantics. Surprisingly, ignoring text conditions in the fidelity-improving stage not only reduces computation complexity but also slightly decreases FID score. This yields a simple and training-free method called TGATE for efficient generation, which caches the cross-attention output once it converges and keeps it fixed during the remaining inference steps.

pixart

### 🚀 Major Features 

* Training-Free.
* Easily Integrate into Existing Frameworks.
* Only a few lines of code are required.
* Friendly support CNN-based U-Net, Transformer, and Consistency Model
* 10%-50% speed up for different diffusion models. 

### 📄 Results
| Model                 | MACs     | Param     | Latency | Zero-shot 10K-FID on MS-COCO |
|-----------------------|----------|-----------|---------|---------------------------|
| Pixart-Alpha          | 107.031T | 611.350M  | 61.502s | 38.669                    |
| Pixart-Alpha w/ TGATE | 65.318T  | 462.585M  | 37.867s | 35.825                    |
| LCM (Pixart-Alpha)    | 8.563T   | 611.350M  | 4.733s  | 36.086                    |
| LCM w/ TGATE          | 7.623T   | 462.585M  | 4.543s  | 37.048                    |

### CODE REVIEW

**Comment by lawrence-cj** [comment]
I can help to review this PR. Cc: @sayakpaul

**Comment by sayakpaul** [comment]
@lawrence-cj please do :)

**Comment by WentianZhang-ML** [comment]
> I am okay having this but not likely to the main PixArt-Alpha pipeline. We could have it in the community scripts as a very nice example and we welcome you to write a blog post about it on hf.co/blog as well :) A blog post makes sense to me because the improvements are solid!
> 
> Pinging @yiyixuxu to get her thoughts too.

Hi, thanks for taking your time. I would like to know if it is similar to the scripts, like [deepcache](https://github.com/huggingface/diffusers/blob/main/docs/source/en/optimization/deepcache.md).

**Comment by yiyixuxu** [comment]
agree with @sayakpaul !

**Comment by sayakpaul** [comment]
@WentianZhang-ML any reason for closing the PR?

**Comment by WentianZhang-ML** [comment]
> @WentianZhang-ML any reason for closing the PR?

Hi, we decided not to change the pipeline of PixArt-alpha itself.  We will open a new PR for adding only scripts in the community. @sayakpaul @yiyixuxu @lawrence-cj

**Comment by sayakpaul** [comment]
Sure, thanks for your understanding. Please keep us posted :)

**Pull request closed without merging**
