### PR TITLE
Fix the order of width and height of original size in SDXL training script

### PR DESCRIPTION
**Pull request by linjiapro**
# What does this PR do?

Original size of image will be passed into SDXL pipeline. The order of it should be width, height according to StableDiffusionXLPipeline, but the training script has it in the order of height, width. This PR fixes that. 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by linjiapro** [comment]
cc @siriuscdk

**Review by sayakpaul — APPROVED** [review]
Thanks very much!

Could you maybe propagate this change to the other scripts as well? 

Thanks very much in advance :-)

**Comment by linjiapro** [comment]
@sayakpaul 
I have found another file needs edit, already get it done.

What will be the next step? Do I click "Update branch" button to get it merged into the branch?

**Comment by sayakpaul** [comment]
Thanks for your help. Once the CI is green, I am happy to merge it.

**Comment by gtebbutt** [comment]
I've been chasing down an issue in my own training code and came across this commit - I wanted to double check if there might be an error here, since as far as I can see the [pipeline code](https://github.com/huggingface/diffusers/blob/442017ccc877279bcf24fbe92f92d3d0def191b6/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L789) and [original paper](https://arxiv.org/pdf/2307.01952.pdf) both use `(h, w)` ordering?

**Comment by patrickvonplaten** [comment]
> I've been chasing down an issue in my own training code and came across this commit - I wanted to double check if there might be an error here, since as far as I can see the [pipeline code](https://github.com/huggingface/diffusers/blob/442017ccc877279bcf24fbe92f92d3d0def191b6/src/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl.py#L789) and [original paper](https://arxiv.org/pdf/2307.01952.pdf) both use `(h, w)` ordering?

You're 100% correct! We need to be more careful here going forward and always double-check (cc @sayakpaul )

**Pull request merged**
