### PR TITLE
[Stable Diffusion] Allow users to disable Safety checker if loading model from checkpoint

### LINKED ISSUE #2755: [Bug][StableDiffusion] Allow loading models with Float16 in `load_pipeline_from_original_stable_diffusion_ckpt`
### Describe the bug

Models loaded from .ckpt / .safetensors file are using Float32 automatically, with no obvious way to change this behavior.

### Reproduction

- Import `load_pipeline_from_original_stable_diffusion_ckpt` from `diffusers.pipelines.stable_diffusion.convert_from_ckpt`
- Load model from .ckpt file
- Observe extreme VRAM usage compared to Float16

### Logs

_No response_

### System Info

Diffusers: 0.14.0
OS: Linux (Kubuntu 22.04)
Python 3.10.6

### PR DESCRIPTION
**Pull request by Stax124**
1. Allows users to cast down the pipeline to Float16, even if the checkpoint was saved in Float32 format.
2. Allows users to disable loading the Safety checker and Feature extractor if users opts-out.

**Benefits**: The user will have the option to save both VRAM (safety checker and float16) and disk space (safety checker download)

**Intended use**:
```py
from diffusers.pipelines.stable_diffusion.convert_from_ckpt import (
    download_from_original_stable_diffusion_ckpt,
)

pipe = download_from_original_stable_diffusion_ckpt(
    checkpoint_path="PATH_TO_CKPT",
    from_safetensors=use_safetensors,
    load_safety_checker=False,
    dtype=torch.float16,
)

pipe.to("cuda")
result = pipe("a dog")
```

Closes #2755

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Well done!

**Comment by sayakpaul** [comment]
@patrickvonplaten could you check here?

**Comment by patrickvonplaten** [comment]
I think this is a duplicate of: https://github.com/huggingface/diffusers/pull/2733 no?

**Comment by Stax124** [comment]
I had a look at the stuff you sent and you were correct, thanks for pointing that out - I wasn't aware that this was possible.
With that, I still believe that users should be able to at least disable the safety checker when loading the model - so I purged all the code for dtypes but I left the safety checker code in.

**Comment by Stax124** [comment]
Failed test is not caused by this PR as #2817 is facing the same issue

**Comment by patrickvonplaten** [comment]
Thanks for adapting the PR - think we can merge this one

**Pull request merged**
