### PR TITLE
Add npu support

### PR DESCRIPTION
**Pull request by MengqingCao**
# What does this PR do?
This PR enables users to leverage the Ascend NPU for training and inferencing of Diffusers models.

## Before submitting
- [N/A] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [X] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [N/A] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
maybe @pcuenca
Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

## Example
There is a training and inferencing example as following:

**Training details:**

- **SD Model**: stabilityai/stable-diffusion-xl-base-1.0
- **VAE Model**: madebyollin/sdxl-vae-fp16-fix
- **Dataset**: lambdalabs/pokemon-blip-captions

**Training scripts**:

```shell
export MODEL_NAME="./models_ckpt/stable-diffusion-xl-base-1.0/"
export VAE_NAME="./ckpt/sdxl-vae-fp16-fix"
export TRAIN_DIR="~/diffusers/data/pokemon-blip-captions/pokemon"

python3  ./examples/text_to_image/train_text_to_image_lora_sdxl.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_model_name_or_path=$VAE_NAME \
  --dataset_name=$DATASET_NAME --caption_column="text" \
  --resolution=1024 --random_flip \
  --train_batch_size=1 \
  --num_train_epochs=2 --checkpointing_steps=500 \
  --learning_rate=1e-04 --lr_scheduler="constant" --lr_warmup_steps=0 \
  --mixed_precision="no" \
  --seed=42 \
  --output_dir="sd-pokemon-model-lora-sdxl" \
  --validation_prompt="cute dragon creature"
```

**ScreenShot**：
image-20240229164754929

image-20240229164817299

**Inferencing code**：

```python
from diffusers import DiffusionPipeline
import torch

model_path = "../code/diffusers/sd-pokemon-model-lora-sdxl-txt/checkpoint-800/"
pipe = DiffusionPipeline.from_pretrained("../code/diffusers/models_ckpt/",
                                         torch_dtype=torch.float16)
pipe.to("npu")
pipe.load_lora_weights(model_path)
prompt = "Sylveon Pokemon with elegant features, magical design, \
        light purple aura, extremely detailed and intricate markings, \
        photo realistic, unreal engine, octane render"
image = pipe(prompt, num_inference_steps=30, guidance_scale=7.5).images[0]
image.save("pokemon-fintue-textencoder-UNet.png")
```

**Prompt**:

*"Sylveon Pokemon with elegant features, magical design, light purple aura, extremely detailed and intricate markings, photo realistic, unreal engine, octane render"*

**ScreenShot**：

Terminal output of the inferencing process: 

image-20240226150048689

The generated images:
pokemon-fintue-textencoder-UNet
pokemon-fintue-textencoder-UNet

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
I am okay with this given the changes are this minimal!

@yiyixuxu WDYT?

**Review by pcuenca — COMMENTED** [review]
I'd also be supportive seeing that the changes do not appear to be intrusive. No strong opinion though.

**Comment by sayakpaul** [comment]
Gentle ping here: @yiyixuxu 

@MengqingCao let's resolve the conflicts.

**Comment by MengqingCao** [comment]
> @MengqingCao let's resolve the conflicts.

Thanks for your response. The conflicts have been resolved, retrigger the CI plz : )

**Comment by MengqingCao** [comment]
@sayakpaul sorry to bother you. Please retrigger the CI again, the quality check has passed on my PC now
image

**Comment by pcuenca** [comment]
@MengqingCao let's wait for the other maintainer that Sayak mentioned, if you don't mind.

**Comment by MengqingCao** [comment]
> @MengqingCao let's wait for the other maintainer that Sayak mentioned, if you don't mind.

sure, that's okay

**Comment by yiyixuxu** [comment]
thanks:)

**Pull request merged**
