### PR TITLE
basic hypernetwork support for StableDiffusionPipeline

### PR DESCRIPTION
**Pull request by noskill**
related issue https://github.com/huggingface/diffusers/issues/1140

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
I don't think hypernetworks are used enough to warrant a core integration tbh

**Comment by noskill** [comment]
@patrickvonplaten well i can keep the code in my repo but i saw that issue by @dblunk88  is still open https://github.com/huggingface/diffusers/issues/1140 and no objections there about adding hypernetworks. 
In my experience hypernetworks work very well.

**Comment by noskill** [comment]
What do you think about creating contrib repo, like opencv-contrib for community contributions?

**Comment by patrickvonplaten** [comment]
We can also add it to: https://github.com/huggingface/diffusers/tree/main/examples/research_projects

**Comment by ballenvironment** [comment]
please add this!

**Comment by ballenvironment** [comment]
@noskill this is great, can you also make a training script for hypernetworks? Sorry for the bother

**Comment by noskill** [comment]
@ballenvironment Do you have training script for hypernetworks?

**Comment by ballenvironment** [comment]
@noskill I made a modified version of the [lora script](https://github.com/huggingface/diffusers/blob/main/examples/advanced_diffusion_training/train_dreambooth_lora_sd15_advanced.py), I will just explain the changes I made.

First is to add the create_hypernetwork function to your file (taken from A1111):
```py
def create_hypernetwork(name, enable_sizes=[768, 320, 640, 1280], layer_structure="1,2,1", activation_func="swish", weight_init="Normal", add_layer_norm=False, use_dropout=False, dropout_structure=None):
    if type(layer_structure) == str:
        layer_structure = [float(x.strip()) for x in layer_structure.split(",")]

    if use_dropout and dropout_structure and type(dropout_structure) == str:
        dropout_structure = [float(x.strip()) for x in dropout_structure.split(",")]
    else:
        dropout_structure = [0] * len(layer_structure)

    hypernet = Hypernetwork(
        name=name,
        enable_sizes=[int(x) for x in enable_sizes],
        layer_structure=layer_structure,
        activation_func=activation_func,
        weight_init=weight_init,
        add_layer_norm=add_layer_norm,
        use_dropout=use_dropout,
        dropout_structure=dropout_structure
    )
    return hypernet
```

Disable grad on vae, text encoder, and unet (only training the hypernetwork weights):
```py
vae.requires_grad_(False)
text_encoder.requires_grad_(False)
unet.requires_grad_(False)
```
Create the hypernetwork and add to the unet
```py
# Add Hypernetwork
hypernetwork = create_hypernetwork(name, enable_sizes=args.sizes)
hypernetwork.to(accelerator.device)
add_hypernet(unet, hypernetwork)

hypernetwork.train()
```
Set the optimizer to only train the hypernetwork weights.
```py
optimizer = optimizer_class(
    hypernetwork.weights(),
    betas=(args.adam_beta1, args.adam_beta2),
    weight_decay=args.adam_weight_decay,
    eps=args.adam_epsilon,
)
```

Add it to accelerator.prepare
```py
hypernetwork, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
    hypernetwork,  optimizer, train_dataloader, lr_scheduler
)
```
How to save it
```py
save_path = os.path.join(args.output_dir, f"{name}.pt")
hypernetwork.save(save_path)
```

When running validation prompts I encountered errors loading the unet because of the hypernetwork attn layers so you have to make a deepcopy
```py
v_unet = copy.deepcopy(accelerator.unwrap_model(unet))
hypernetwork = accelerator.unwrap_model(hypernetwork)
# Load the pipeline and then add it
add_hypernet(v_unet, hypernetwork)
```
That's pretty much it.

**Pull request closed without merging**
