### PR TITLE
Benchmarking workflow fix

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Benchmarking workflow is failing:
https://github.com/huggingface/diffusers/actions/runs/9348670151/job/25728280347#step:8:53

So, this PR:

* Changes the Python version to 3.9 from 3.10 of the CUDA compile Docker container (https://github.com/pytorch/pytorch/issues/129351#issuecomment-2190907715) (also discussed internally with @DN6) 
* Implements a simple reporting mechanism to faithfully report the benchmarking status. Example message: https://huggingface.slack.com/archives/C065E480NN9/p1719464587152429.

### CODE REVIEW

**Review by DN6 — APPROVED** [review]

**Comment by sayakpaul** [comment]
Currently manually running the benchmarking workflow here: https://github.com/huggingface/diffusers/actions/runs/9690502132/job/26740442342. Have already pushed the latest Docker container so that it contains Python 3.9 (confirmed from [here](https://github.com/huggingface/diffusers/actions/runs/9690502132/job/26740442342#step:7:11)).

**Comment by sayakpaul** [comment]
`benchmark_ip_adapters.py` is failing: https://github.com/huggingface/diffusers/actions/runs/9690502132/job/26740442342#step:8:55. Will fix.

**Comment by sayakpaul** [comment]
Okay so, it runs on Torch 2.2 but not on Torch 2.3.1.

**Comment by sayakpaul** [comment]
@DN6 I have disabled the IP adapter benchmarks for the moment. Have started a new run here: https://github.com/huggingface/diffusers/actions/runs/9692567539/job/26746155012. Let's see how it goes.

**Pull request merged**
