### PR TITLE
[docs] Other modalities

### PR DESCRIPTION
**Pull request by stevhliu**
This PR updates the other modality section in the docs, most of which are "coming soon" and don't add much content/value right now. We can add them back when we have more substantive content for these topics.

- removes the [Audio](https://huggingface.co/docs/diffusers/main/en/using-diffusers/audio) doc
- moves the [Reinforcement Learning](https://huggingface.co/docs/diffusers/main/en/using-diffusers/rl) into the Pipeline API section and removes the coming soon page [here](https://huggingface.co/docs/diffusers/main/en/api/experimental/rl)

For the [molecular conformation](https://huggingface.co/docs/diffusers/main/en/using-diffusers/other-modalities) example, what do you think about turning it into a blog post? If we include it in the docs (instead of just a link to a notebook), do you think it’ll be too advanced + is there interest in it?

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
💯

**Review by patrickvonplaten — APPROVED** [review]
Thanks!

**Comment by hilookas** [comment]
It seems like the page is still on the huggingface documents, https://huggingface.co/docs/diffusers/main/en/using-diffusers/rl

Maybe we can clean the page cache or redirect this page to https://huggingface.co/docs/diffusers/main/en/api/pipelines/value_guided_sampling ?

**Comment by stevhliu** [comment]
Thanks for reporting, we'll look into this! 

@mishig25, the `rl.md` page should only be accessible on `v18.0` of the docs and I'm not sure why it can be viewed on the `main` version (it doesn't show up in the `main` version's table of contents). I think if you're viewing this page on `v18.0` and try to view it on a newer version of the docs, it redirects to the `main` version where it shouldn't exist. Do you think it'd be possible to add something that says this doc has been removed or that it can be found here instead now?

**Pull request merged**
