### PR TITLE
Skip `test_freeu_enabled ` on MPS

### LINKED ISSUE #7569: `test_freeu_enabled()` fails on Mac
### Describe the bug

The test `test_freeu_enabled` fails on Mac. The underlying issue is this method chain `utils.torch_utils.apply_freeu` -> `utils.torch_utils.fourier_filter` -> `torch.fft.fftn` ultimately tries to convert a `ComplexFloat` to MPS, which MPS doesn't seem to support.

I'll submit a PR to skip this test on Mac

### Reproduction

Run `test_freeu_enabled()`

To repro underlying issue:
```py
import torch
from torch.fft import fftn

x_cpu = torch.rand(16, 16)
x_mps = x_cpu.clone().to('mps')

print(fftn(x_cpu).shape) # works
print(fftn(x_mps).shape) # Fails with "TypeError: Trying to convert ComplexFloat to the MPS backend but it does not have support for that dtype."
```

### Logs

_No response_

### System Info

Copy-and-paste the text below in your GitHub issue and FILL OUT the two last points.

- `diffusers` version: 0.28.0.dev0
- Platform: macOS-14.4.1-arm64-arm-64bit
- Python version: 3.11.8
- PyTorch version (GPU?): 2.1.2 (False)
- Huggingface_hub version: 0.20.2
- Transformers version: 4.36.2
- Accelerate version: 0.26.1
- xFormers version: not installed
- Using GPU in script?: MPS
- Using distributed or parallel set-up in script?: no

### Who can help?

Questions on Tests: @DN6
Questions on JAX- and MPS-related things: @pcuenca

### PR DESCRIPTION
**Pull request by UmerHA**
Skip `test_freeu_enabled ` on MPS

Fixes #7569

## Who can review?

Core library:
- JAX and MPS: @pcuenca
- General functionalities: @sayakpaul @DN6

### CODE REVIEW

**Review by pcuenca — APPROVED** [review]
Yeah, this is an mps limitation as of 14.4 still. Thanks for this!

**Comment by UmerHA** [comment]
@pcuenca sry, I had imported skip_mps wrongly. Should run now. Can you re-run the tests? :)

**Comment by sayakpaul** [comment]
This is very nice. Thank you!

**Comment by sayakpaul** [comment]
An empty commit might help fix the failing test.

**Comment by pcuenca** [comment]
Launched the CI manually

**Pull request merged**
