### PR TITLE
add `noise_sampler_seed` to `StableDiffusionKDiffusionPipeline.__call__`

### PR DESCRIPTION
**Pull request by sunhs**
# What does this PR do?

Currently `StableDiffusionKDiffusionPipeline` uses `k_diffusion.sampling` samplers without providing the `noise_sampler` argument, and thus a noise_sampler with a random seed is created. This makes it not possible to reproduce image generation with a fixed seed, even if `generator` is provided to `__call__`.

Like `DPMSolverSDEScheduler`, this PR adds a `noise_sampler_seed` parameter to `StableDiffusionKDiffusionPipeline.__call__` to address this issue.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Ok for me! Can we also add a test here: https://github.com/huggingface/diffusers/blob/main/tests/pipelines/stable_diffusion/test_stable_diffusion_k_diffusion.py to make sure the new feature works as expected?

**Comment by sunhs** [comment]
@patrickvonplaten please check it out

**Review by patrickvonplaten — APPROVED** [review]

**Comment by patrickvonplaten** [comment]
@yiyixuxu could you check this out?

**Review by yiyixuxu — APPROVED** [review]
great!

**Pull request merged**
