### PR TITLE
Change dreambooth-examples to config base parsing

### LINKED ISSUE #4169: Replace Command-Line Arguments with config.yaml Settings in train.py files
I'm trying to use SDXL Lora and Dreambooth to fine-tuning SDXL.
and, I feel uncomfortable when setting a lot of argparsers in terminal. 
so, I think use config.yaml file and just set this config.yaml file to argparser.
than, when training, py file will read this YAML file and set variables in it.
ex) 
#config.yaml
MODEL_NAME: "stabilityai/stable-diffusion-xl-base-0.9"
... etc

and add train_dreambooth_lora_sdxl.py to
```python
import yaml

def load_config(config_file):
    with open(config_file, "r") as file:
        config = yaml.safe_load(file)
    return config

 parser.add_argument("--config_file", type=str, default="config.yaml",
              help="Path to the config.yaml file.")

config = load_config(args.config_file)
pretrained_model_name_or_path = config.get("MODEL_NAME")
```

like this. Is there any reason that we should use argparsers, just ignore it.
Thank you once again for your hard work and dedication to maintaining this valuable open-source project. I look forward to your feedback on this.

### PR DESCRIPTION
**Pull request by helpmeIamnewbie**
# What does this PR do?

As I suggest in issue #4169 , I change train.py examples in dreambooth work based on config.yaml files with use omega conf library.

Fixes #4169 

```
# Path to pretrained model or model identifier from huggingface.co/models
pretrained_model_name_or_path: CompVis/stable-diffusion-v1-4
# Revision of pretrained model identifier from huggingface.co/models. Trainable model components should be float32 precision
revision: null
# Pretrained tokenizer name or path if not the same as model_name
tokenizer_name: null
# A folder containing the training data of instance images
instance_data_dir: INSTANCE_DIR
# A folder containing the training data of class images
class_data_dir: null
# The prompt with identifier specifying the instance
instance_prompt: A photo of sks dog
.
.
.
```
and just run file by

`
accelerate launch train_dreambooth.py --config="configs/train_dreambooth.yaml"
`

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@shauray8 @patrickvonplaten @sayakpaul @williamberman 
and anyone can review this PR!

### CODE REVIEW

**Comment by sayakpaul** [comment]
Could you maybe take a single example first and then discuss the design? I think that will be easier.

**Comment by patrickvonplaten** [comment]
Do we really want to base everything on configs now? cc @sayakpaul @williamberman @patil-suraj @muellerzr wdyt?

**Comment by muellerzr** [comment]
The configs in accelerate are specifically because there are environmental factors in play, and the behavior as a whole on `accelerate launch` changes based on its config file. And, these are system wide configurations, not model. 

If these proposed configurations are *reusable* and easier to use than just arguments, I could see the benefit there. But the question would be scalability. If it's just one very different config with different keys, etc, for each example... I don't see a benefit from a design perspective abstracting it that far. 

It's clearer without. (And users can do their own flare/handler for that if they want)

**Comment by muellerzr** [comment]
Also, as these just live in the examples, people will look towards these and it adds a level of difficulty when using the framework vs just pulling down the script and running it. I'm not sure this added abstraction is a plus, but interested in everyone else's thoughts :)

**Comment by helpmeIamnewbie** [comment]
Oh, I force-pushed my branch for mistake. after discuss and if concluded to it's necessary, can I re-open PR? or I'll just close my PR.

**Pull request closed without merging**
