### PR TITLE
[JAX] Replace uses of `jnp.array` in types with `jnp.ndarray`.

### PR DESCRIPTION
**Pull request by hvaara**
# What does this PR do?

`jnp.array` is a function, not a type:
https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.array.html so it never makes sense to use `jnp.array` in a type annotation.

Presumably the intent was to write `jnp.ndarray` aka `jax.Array`. Change uses of `jnp.array` to `jnp.ndarray`.

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Nice catch @hvaara - agree with you! cc @pcuenca can you check as well?

**Comment by hvaara** [comment]
@pcuenca Does this LGTY?

**Review by pcuenca — APPROVED** [review]

**Comment by pcuenca** [comment]
@hvaara Yes, sorry! Running tests just in case.

**Comment by hvaara** [comment]
No worries. Yes, please run the tests in case I've missed or broken something 😄  I have a very similar PR incoming to `transformers` soon (ie. minutes).

**Comment by hvaara** [comment]
Thanks for the reviews!

**Pull request merged**
