### PR TITLE
Add Note2audio model 

### PR DESCRIPTION
**Pull request by ArthurZucker**
The note2audio model is pretty complexe, it uses a T5 style EncoderDecoder. During the diffusion process, conditioning can be given to the encoder in two ways, MIDI file and the previous spectrogram. Two seperate network take care of the concatenation and then the Spectrogram Decoder generates a spectrogram. 

Finally, SoundStream is used as a Vocoder to convert the MelSpectrogram to a raw audio. We only need to use the decoder part of SoundStream.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Super cool! 

Note that we should add the vocoder in the very last step (it'll require some tf graph/onnx hacking )

**Comment by ArthurZucker** [comment]
It will require the conversion from TF's SoundStream 😅

I will focus on the T5v1.1 style encoder decoder now.

BTW tell me if the file where I am putting the model is correct or if it needs changing!

**Comment by patil-suraj** [comment]
Very cool! Let me know if you need any help with T5X and weight conversion.

**Comment by patrickvonplaten** [comment]
Closing in favor of #1044

**Pull request closed without merging**
