### PR TITLE
Allow passing non-default modules to pipeline

### PR DESCRIPTION
**Pull request by pcuenca**
Addresses #183.

Override modules are recognized and replaced in the pipeline. However, no check is performed about mismatched classes yet. This is because the override module is already instantiated (see https://github.com/huggingface/diffusers/blob/main/src/diffusers/configuration_utils.py#L223), and `init_dict` in https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipeline_utils.py#L151 no longer has a `library_name` or a `class_name` - just the instantiated module.

I'm looking at a way to detect a class mismatch so we can fail more gracefully.

### CODE REVIEW

**Comment by pcuenca** [comment]
I tried the following (as a quick hack before refactoring):

```python
        for name, module in passed_class_obj.items():
            # TODO: verify that the module class belongs to one of the supported classes
            library_name, class_name = config_dict[name]
            library = importlib.import_module(library_name)
            loadable_classes = LOADABLE_CLASSES[library_name]
            class_candidates = {c: getattr(library, c) for c in loadable_classes.keys()}
            for class_name, class_candidate in class_candidates.items():
                if isinstance(module, class_candidate):
                    init_kwargs[name] = module
            # Remove it even if not found, as it's not appropriate
            init_dict.pop(name)
```

However, if we pass a scheduler instance to `vae`, the `isinstance` check succeeds for class candidate `SchedulerMixin`, because `SchedulerMixin` is part of the supported classes.

If we want to really verify this, I think we should create a mapping from module keys to supported classes, instead of checking all the loadable/importable classes in the library.

**Comment by patrickvonplaten** [comment]
Just added a test, all other tests pass

**Comment by patrickvonplaten** [comment]
@anton-l - feel free to merge and then maybe also add it manually to the release notes quickly :-)

**Comment by patrickvonplaten** [comment]
Merging!

**Pull request merged**
