### PR TITLE
adapt masked im2im pipeline for SDXL

### PR DESCRIPTION
**Pull request by noskill**
Implement sketch inpaint from a1111 for non-inpaint models.

This PR implement the same algorithm as here for https://github.com/huggingface/diffusers/pull/4824
but this pipeline has more parameters

### CODE REVIEW

**Comment by yiyixuxu** [comment]
can you run `make style`?

**Comment by noskill** [comment]
thank you, indeed there were some issues

**Comment by tolgacangoz** [comment]
@noskill Could you run `make style && make quality`( after running `python -m pip install -e ".[quality]"`)?

**Comment by noskill** [comment]
It's not very active i would say.
@tolgacangoz I did run make style and make quality, it complains about lpw_hypernet_diffusion.py

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Pull request merged**
