### PR TITLE
fix: how print training resume logs.

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Addresses #5005 and https://github.com/huggingface/diffusers/issues/5034. 

Incorporates how @williamberman implemented it for ControlNet:
https://github.com/huggingface/diffusers/blob/ed507680e35b7628bc11235255cfc58ad1101626/examples/controlnet/train_controlnet.py#L984-L996

If okay, happy to propagate the changes to the other examples.

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
Nice that's indeed cleaner

**Comment by bghira** [comment]
fwiw you can also use `set_description` to display current / expected num epochs. i really like this change. thank you!

**Comment by sayakpaul** [comment]
Needs to be propagated to:

- [ ] DreamBooth
- [ ] Custom Diffusion
- [ ] Kandinsky 
- [ ] Textual inversion
- [ ] Unconditional generation

**Comment by sayakpaul** [comment]
@patrickvonplaten @yiyixuxu if you could lend your 👁️ here and share your comments, that would be great!

**Review by patrickvonplaten — COMMENTED** [review]
Ok for me!

**Comment by sayakpaul** [comment]
Will fix the failing test (for examples) and then merge.

**Comment by sayakpaul** [comment]
Failing tests are unrelated.

**Pull request merged**
