### PR TITLE
Support LMSDiscreteScheduler in LDMPipeline

### PR DESCRIPTION
**Pull request by mkshing**
Hi, thank you for such a great repo. This is a small change to support all schedulers such as LMSDiscreteScheduler in LDMPipeline.

What's changed
-------
* Add the `scale_model_input` function before `step` to ensure correct denoising (L77)

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
This looks good to me! @anton-l could you also give it a quick review :-)

**Review by patrickvonplaten — APPROVED** [review]

**Review by anton-l — CHANGES_REQUESTED** [review]
Great idea @mkshing, thank you!

You'll just need one more modification to make it work with LMS-like schedulers:
```diff
        latents = torch.randn(
            (batch_size, self.unet.in_channels, self.unet.sample_size, self.unet.sample_size),
            generator=generator,
        )
        latents = latents.to(self.device)
+       # scale the initial noise by the standard deviation required by the scheduler
+       latents = latents * self.scheduler.init_noise_sigma        
```

Happy to merge your PR after that :)

**Comment by mkshing** [comment]
@patrickvonplaten @anton-l Thank you for your review! I added 2 lines as https://github.com/huggingface/diffusers/pull/891#pullrequestreview-1150816675!

**Comment by patrickvonplaten** [comment]
Great PR - thanks @mkshing :-)

**Pull request merged**
