### PR TITLE
add index_counter to DPMSolverMultistepScheduler

### PR DESCRIPTION
**Pull request by yiyixuxu**
fix:https://github.com/huggingface/diffusers/issues/4122

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Looks nice! 

1.) Could you maybe double-check that this is the correct implementation by running `StableDiffusionImg2ImgPipeline` with different strength values for SDv1-5? E.g. can you make sure that this code: https://github.com/huggingface/diffusers/issues/1866#issuecomment-1545578066 works with your fix.
2.) Could you then propagate this fix also to all other schedulers that require this change (probs all k-diffusion ones expect DDIM, PNDM, DDPM)

**Comment by yiyixuxu** [comment]
@patrickvonplaten 

I'm not sure what to do here -

For this scheduler, the "step" calculation is still based on timesteps; it should match up with k-sigmas nicely; However, won't work when there are duplicated timesteps 
https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py#L486

should we update the calculation to be based on k-sigmas?

**Comment by patrickvonplaten** [comment]
Yes I think updating the computation to be based on sigmas is the move here. Let's just make sure our `step(...)` API doesn't change :-) 

Also gently pinging @LuChengTHU here - do you have any thoughts here maybe?

**Comment by LuChengTHU** [comment]
Hi all, it seems that this PR wants to fix the repeated time steps? But I'm not sure why the repeated time steps occurs, could you please explain the reason to me so that I could know the bugs in my code :) Thank you so much!

**Comment by yiyixuxu** [comment]
@LuChengTHU 

The repeated time steps only occurs when we use the sigmas for step size based on the k-diffusion paper. When we convert the sigma to timesteps, sometimes same timestep is mapped to more than one sigmas, hence the repeated timesteps

Basically, this is the part of the code responsible https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_dpmsolver_multistep.py#L269

We currently use a de-duplication logic to address the repeated timesteps, so if you run below code, you will get `95` steps, even though we asked for `100` 

```python
from diffusers import DPMSolverMultistepScheduler

scheduler = DPMSolverMultistepScheduler(
    beta_start=0.00085,
    beta_end=0.012,
    beta_schedule="scaled_linear",
    prediction_type="epsilon",
    num_train_timesteps=1000,
    trained_betas=None,
    thresholding=False,
    algorithm_type="dpmsolver++",
    solver_type="midpoint",
    lower_order_final=True,
    use_karras_sigmas=True,
)

scheduler.set_timesteps(100, device="cuda")
print(len(scheduler.timesteps))
```

**Comment by patrickvonplaten** [comment]
@yiyixuxu let's maybe just give this a try to fix it and see later with design

**Comment by patrickvonplaten** [comment]
@yiyixuxu let me know if you need help to get this one finished

**Comment by yiyixuxu** [comment]
it's been worked on this PR https://github.com/huggingface/diffusers/pull/4986

**Comment by patrickvonplaten** [comment]
Super-seeded by #4986

**Pull request closed without merging**
