### PR TITLE
Fix gradient checkpointing issue for Stable Diffusion 3

### PR DESCRIPTION
**Pull request by Carolinabanana**
When gradient checkpointing is enabled for SD3, in the example dreambooth script with default arguments, various modules fail with "expected Tensor, not tuple". This is because the gradient checkpointing codepath doesn't deconstruct the hidden states tuple. This fixes that issue.

@sayakpaul

### CODE REVIEW

**Comment by darknoon** [comment]
Thank you! Ran into the same issue.

**Comment by s9anus98a** [comment]
can this fix my issue? https://github.com/huggingface/diffusers/issues/8545

**Review by sayakpaul — APPROVED** [review]
Thanks so much!

**Review by yiyixuxu — APPROVED** [review]
thank you!

**Comment by yiyixuxu** [comment]
can you run make style?

**Comment by Carolinabanana** [comment]
> can you run make style?

> All checks passed!

There were no changes from that command to the one file that this modifies.

**Comment by asomoza** [comment]
The failed test it's the same that I have, so need to wait for https://github.com/huggingface/diffusers/pull/8563 to be able to continue with the tests.

**Pull request merged**
