### PR TITLE
Add Singlestep DPM-Solver (singlestep high-order schedulers)

### PR DESCRIPTION
**Pull request by LuChengTHU**
#1308

I've implemented the single-step high-order solvers in an elegant way. It is very similar to the implementations with the multi-step schedulers, and we do not need to modify pipelines. 

If this implementation is fine for you, I will further add the tests and the flax version.

### CODE REVIEW

**Comment by LuChengTHU** [comment]
Emmm, I don't know what happened with the tests...

**Comment by LuChengTHU** [comment]
Here are some of my own suggestions:

1. For few-step guided sampling (such as stable-diffusion), I still recommend using multi-step DPM-Solver++.

2. For unconditional sampling, I recommend using single-step DPM-Solver++.

Nevertheless, for `steps >= 15`, the difference between multi-step DPM-Solver++ and single-step DPM-Solver++ on stable-diffusion seems very small. I don't have much experience with it, and I hope the community can have some more findings.

**Comment by LuChengTHU** [comment]
Here are some examples for comparing multi-step and single-step DPM-Solver++ (2nd order, midpoint):

**Review by patrickvonplaten — APPROVED** [review]
This looks great to me @LuChengTHU - thanks a lot!

Could you maybe add some quick tests to `tests/test_scheduler.py` ?

**Comment by patrickvonplaten** [comment]
Implementation is exactly in line with the current design so that's perfect :-)

**Comment by LuChengTHU** [comment]
No problem. I will add tests and flax version implementations :)

**Comment by patrickvonplaten** [comment]
Cool! Let me know if you need any help :-)

**Pull request merged**
