### PR TITLE
small bugfix at StableDiffusionDepth2ImgPipeline call to check_inputs and batch size calculation

### PR DESCRIPTION
**Pull request by mikegarts**

### CODE REVIEW

**Comment by mikegarts** [comment]
This fixes the use case when one wishes to pass prompt embeddings to the pipeline.

**Review by pcuenca — APPROVED** [review]
I think this makes sense, thanks a lot!

**Comment by sayakpaul** [comment]
Seems to work :) 

https://colab.research.google.com/gist/sayakpaul/0ad064c19ff7cce134028c38f55af81e/scratchpad.ipynb

**Pull request merged**
