### PR TITLE
Add loading ckpt from file for SDXL controlNet

### PR DESCRIPTION
**Pull request by antigp**
# What does this PR do?

Add ability to use checkpoint model when using SDXL ControlNet, like in base SDXL pipeline.
Realized like in other SD Control net pipline.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@patrickvonplaten, i will be glad if you look changes in `convert_from_ckpt.py`
@sayakpaul, i will be glad if you look changes in `pipeline_controlnet_sd_xl.py`

### CODE REVIEW

**Comment by sayakpaul** [comment]
Could we get the CI to be green :) ?

**Comment by antigp** [comment]
Oh, forgot some `import` =(

**Review by patrickvonplaten — APPROVED** [review]
Great thanks! @sayakpaul could you give this a quick look as well?

**Comment by sayakpaul** [comment]
Let's fix the merge conflicts? :)

**Comment by antigp** [comment]
@sayakpaul 
I've fixed. Thanks for review

**Comment by sayakpaul** [comment]
Let's see how the CI run goes this time :-)

**Comment by antigp** [comment]
@sayakpaul Do i need to do something else?

**Comment by sayakpaul** [comment]
We need to make sure the CI is green :-)

**Comment by antigp** [comment]
@sayakpaul i've reformatted the code, please, rerun ci.

**Comment by antigp** [comment]
I've resorted imports =(

**Comment by sayakpaul** [comment]
Thanks for your amazing contributions. 

Could you also leave an example of a checkpoint that would benefit from this example so that users could benefit from that?

**Pull request merged**
