### PR TITLE
fix: enabled num_images_per_prompt>1 for lpw_stable_diffusion_xl (community pipeline)

### PR DESCRIPTION
**Pull request by MilkClouds**
# What does this PR do?

the community lpw_stable_diffusion_xl added by PR https://github.com/huggingface/diffusers/pull/4661 can't handle num_images_per_prompt>1 case. I fixed script to make num_images_per_prompt work well.

Fixes https://github.com/huggingface/diffusers/issues/5081

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [X] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

original PR contributor, @xhinker may review this

### CODE REVIEW

**Comment by yiyixuxu** [comment]
@xhinker does this look good to you?

**Comment by yiyixuxu** [comment]
Hi @MilkClouds :
I'm pretty sure you tested it but can you confirm? :)
maybe provide a test script and results with num_images_per_prompts = 2? will merge once confirm tested 

thanks!
YiYi

**Comment by MilkClouds** [comment]
As long as I tested, it worked well. Is there any other thing I should do for this PR to be merged?

**Review by yiyixuxu — APPROVED** [review]
thank you!

**Pull request merged**
