### PR TITLE
replace references to deprecated KeyArray & PRNGKeyArray

### PR DESCRIPTION
**Pull request by jakevdp**
The correct annotation for PRNG keys is `jax.Array` (see [JEP 9263](https://jax.readthedocs.io/en/latest/jep/9263-typed-keys.html)). Note that `jax.random.KeyArray` has always been effectively aliased to `Any` at type checking time, so changing these to `jax.Array` makes the annotations more specific than they were previously.

I updated the version pinning to `jax>=0.4.1` (released December 2022) because this is the first release where `jax.Array` was available as a type annotation.

### CODE REVIEW

**Comment by hvaara** [comment]
Thanks for proposing this upstream, @jakevdp! 😄

**Review by pcuenca — APPROVED** [review]
Looks good to me, thanks a lot!

Would you recommend to start going over uses of `jax.random.PRNGKey()` and replacing them with `jax.random.key()` now?

**Comment by DN6** [comment]
@pcuenca Good to merge this?

**Comment by pcuenca** [comment]
Yes! Maybe @patrickvonplaten or @yiyixuxu would like to take a quick look.

**Review by patrickvonplaten — APPROVED** [review]
Looks good to me! Happy to bump JAX here to 0.4!

Thanks a lot @jakevdp

**Comment by jakevdp** [comment]
Thanks!

**Pull request merged**
