### PR TITLE
[Single file] fix single file config loading when passing dicts.

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Fixes https://github.com/huggingface/diffusers/actions/runs/9055285304/job/24876182073#step:7:3821

### CODE REVIEW

**Review by yiyixuxu — COMMENTED** [review]
ohh thanks! :) 
looks good to me but I'll wait for @DN6 to comment if there is any reason the dict was not supported here

I think if we decided to accept `config` as a dict we should also update the doc string 
if for some reason, we decide to no longer accept`config` as a dict we should deprecate it

**Comment by yiyixuxu** [comment]
also I thought we are moving all the single-file tests to the same place? are these tests intended to be kept there?

**Comment by sayakpaul** [comment]
Yeah, I think so too. 

https://github.com/huggingface/diffusers/tree/main/tests/single_file has all the tests but I think we need to remove them from `tests/models/unets/` and elsewhere.

**Comment by DN6** [comment]
Actually this test should be removed. We don't support configuring models via dict in `from_pretrained` so `from_single_file` shouldn't support it either.   `config` should be a model repo id or a path to a local model repo. I'll update the test.

**Comment by sayakpaul** [comment]
Closing the PR then :)

**Pull request closed without merging**
