### PR TITLE
[Euler Discrete] do sigmas edits from the pipeline.

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Fixes the issue for which https://github.com/huggingface/diffusers/pull/6078 was made.

### CODE REVIEW

**Comment by DN6** [comment]
Pipeline is breaking with LCM 
https://github.com/huggingface/diffusers/actions/runs/7123821250/job/19397082791?pr=6081#step:11:46

**Comment by sayakpaul** [comment]
@DN6 could you give this another look?

**Comment by sayakpaul** [comment]
@patrickvonplaten @DN6 

Since the concerned change is very specific to the `torch.compile()` performance how about we do from the pipeline calling script?

`pipe.scheduler.sigmas = pipe.scheduler.sigmas.tolist()`

This essentially solves the purpose. In retrospect, I think we shouldn't touch the internals and instead leverage what we can to keep changes more explicit.

**Comment by sayakpaul** [comment]
Closing because we can simply do: `pipeline.scheduler.sigmas = pipeline.scheduler.sigmas.cpu()` from the pipeline calling script.

**Pull request closed without merging**
