### PR TITLE
Fix LLMGroundedDiffusionPipeline super class arguments

### LINKED ISSUE #5992: `llm_guided_diffusion` example code gets `AttributeError: 'bool' object has no attribute '__module__'`
### Describe the bug

I simply followed the instructions [here](https://github.com/huggingface/diffusers/blob/main/examples/community/README.md#llm-grounded-diffusion) to try out the `llm_grounded_diffusion` pipeline and it doesn't work out of the box.

### Reproduction

Started with making sure I'm using main

```
poetry add git+https://github.com/huggingface/diffusers.git
```

Then copied the example code and ran:
```py
import torch
from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained(
    "longlian/lmd_plus", 
    custom_pipeline="llm_grounded_diffusion",
    variant="fp16", torch_dtype=torch.float16
)
pipe.enable_model_cpu_offload()

# Generate directly from a text prompt and an LLM response
prompt = "a waterfall and a modern high speed train in a beautiful forest with fall foliage"
phrases, boxes, bg_prompt, neg_prompt = pipe.parse_llm_response("""
[('a waterfall', [71, 105, 148, 258]), ('a modern high speed train', [255, 223, 181, 149])]
Background prompt: A beautiful forest with fall foliage
Negative prompt:
""")

images = pipe(
    prompt=prompt,
    negative_prompt=neg_prompt,
    phrases=phrases,
    boxes=boxes,
    gligen_scheduled_sampling_beta=0.4,
    output_type="pil",
    num_inference_steps=50,
    lmd_guidance_kwargs={}
).images

images[0].save("./lmd_plus_generation.jpg")
``` 

### Logs

```shell
C:\Users\krist\AppData\Local\pypoetry\Cache\virtualenvs\testproject-cM1rhShM-py3.10\lib\site-packages\huggingface_hub\file_download.py:672: FutureWarning: 'cached_download' is the legacy way to download files from the HF hub, please consider upgrading to 'hf_hub_download'
  warnings.warn(
Loading pipeline components...:  29%|██▊       | 2/7 [00:00<00:00,  6.07it/s]C:\Users\krist\AppData\Local\pypoetry\Cache\virtualenvs\testproject-cM1rhShM-py3.10\lib\site-packages\transformers\models\clip\feature_extraction_clip.py:28: FutureWarning: The class CLIPFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use CLIPImageProcessor instead.
  warnings.warn(
Loading pipeline components...:  86%|████████▌ | 6/7 [00:00<00:00,  9.93it/s]`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["bos_token_id"]` will be overriden.
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["eos_token_id"]` will be overriden.
Loading pipeline components...: 100%|██████████| 7/7 [00:00<00:00,  7.78it/s]
Traceback (most recent call last):
  File "D:\GitHub\testproject\image_gen.py", line 19, in <module>
    pipe = DiffusionPipeline.from_pretrained(
  File "C:\Users\krist\AppData\Local\pypoetry\Cache\virtualenvs\testproject-cM1rhShM-py3.10\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 1357, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "C:\Users\krist\.cache\huggingface\modules\diffusers_modules\git\llm_grounded_diffusion.py", line 277, in __init__
    super().__init__(
  File "C:\Users\krist\AppData\Local\pypoetry\Cache\virtualenvs\testproject-cM1rhShM-py3.10\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py", line 236, in __init__
    self.register_modules(
  File "C:\Users\krist\AppData\Local\pypoetry\Cache\virtualenvs\testproject-cM1rhShM-py3.10\lib\site-packages\diffusers\pipelines\pipeline_utils.py", line 566, in register_modules
    library = not_compiled_module.__module__.split(".")[0]
AttributeError: 'bool' object has no attribute '__module__'. Did you mean: '__mod__'?
```

### System Info

- `diffusers` version: 0.24.0.dev0
- Platform: Windows-10-10.0.22621-SP0
- Python version: 3.10.2
- PyTorch version (GPU?): 1.13.0+cu117 (True)
- Huggingface_hub version: 0.19.4
- Transformers version: 4.35.2
- Accelerate version: 0.23.0
- xFormers version: not installed
- Using GPU in script?: No
- Using distributed or parallel set-up in script?: No

### Who can help?

_No response_

### PR DESCRIPTION
**Pull request by KristianMischke**
# What does this PR do?
This PR makes `requires_safety_checker` a keyword argument so it doesn't collide with `StableDiffusionPipeline.image_encoder` in the parameter order.

Fixes #5992

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@TonyLianLong

### CODE REVIEW

**Comment by TonyLianLong** [comment]
Thanks for the fix. It's interesting that it somehow does not error on my end. Is it a recent change?

**Comment by TonyLianLong** [comment]
After tracing the change, I found #5713 broke the positional argument order. This fix is indeed needed. I also suggest replacing `safety_checker` and `feature_extractor` positionals with keywords in case we have future changes in the order of 
 the arguments.

Thank you!

**Comment by TonyLianLong** [comment]
Just verified on colab and it still gives an error. Tested commit: `git+https://github.com/KristianMischke/diffusers.git@8c07e30`.

The colab: https://colab.research.google.com/drive/1SXzMSeAB-LJYISb2yrUOdypLz4OYWUKj

Steps to reproduce:
1. `!wget https://raw.githubusercontent.com/KristianMischke/diffusers/8c07e30b143938491864607e47aa65955599dad0/examples/community/llm_grounded_diffusion.py -O llm_grounded_diffusion.py`
2. Use local custom pipeline:
```
pipe = DiffusionPipeline.from_pretrained(
    "longlian/lmd_plus",
    custom_pipeline="llm_grounded_diffusion.py",
    variant="fp16", torch_dtype=torch.float16
)
```

The error says `[the pipeline] has been incorrectly initialized or <class 'diffusers_modules.local.llm_grounded_diffusion.LLMGroundedDiffusionPipeline'> is incorrectly implemented. Expected {'tokenizer', 'unet', 'scheduler', 'safety_checker', 'text_encoder', 'feature_extractor', 'vae'} to be defined, but dict_keys(['vae', 'text_encoder', 'tokenizer', 'unet', 'scheduler', 'safety_checker', 'feature_extractor', 'image_encoder']) are defined.`

at 
```
[/usr/local/lib/python3.10/dist-packages/diffusers/pipelines/pipeline_utils.py](https://localhost:8080/#) in components(self)
   1952 
   1953         if set(components.keys()) != expected_modules:
-> 1954             raise ValueError(
   1955                 f"{self} has been incorrectly initialized or {self.__class__} is incorrectly implemented. Expected"
   1956                 f" {expected_modules} to be defined, but {components.keys()} are defined."
```

Somehow the commit #5713 breaks things in a more complicated way than I think it is... It introduces an `image_encoder` that conflicts with the original state design.

The proper way to fix this is to replace the initialization and super call with (i.e., add `image_encoder`):
```
    def __init__(
        self,
        vae: AutoencoderKL,
        text_encoder: CLIPTextModel,
        tokenizer: CLIPTokenizer,
        unet: UNet2DConditionModel,
        scheduler: KarrasDiffusionSchedulers,
        safety_checker: StableDiffusionSafetyChecker,
        feature_extractor: CLIPImageProcessor,
        image_encoder: CLIPVisionModelWithProjection = None,
        requires_safety_checker: bool = True,
    ):
        super().__init__(
            vae,
            text_encoder,
            tokenizer,
            unet,
            scheduler,
            safety_checker=safety_checker,
            feature_extractor=feature_extractor,
            image_encoder=image_encoder,
            requires_safety_checker=requires_safety_checker,
        )
        # other parts of the initialization
```

@KristianMischke could you help add this to the PR and check whether it works on colab?

**Comment by KristianMischke** [comment]
@TonyLianLong Thanks for investigating further! Applied your changes and it's working properly now in the colab notebook with my latest commit

**Review by yiyixuxu — COMMENTED** [review]
ok by me but is there any reason we use `StableDiffusionPipeline` as super class,  instead of `DiffusionPipeline`? if not maybe let's just change the super class to `DiffusionPipeline`? pipelines should not use `StableDiffusionPipeline` as base class at all

**Comment by TonyLianLong** [comment]
I use StableDiffusionPipeline as a superclass because we inherit many methods from it. If we inherit directly from `DiffusionPipeline` we have to copy things over (which we do not change at all, such as `encode_image`). It's hard to say which one will be more compatible. I am ok with both options.

**Comment by yiyixuxu** [comment]
We recommend using the `DiffusionPipeline` and use `#Copy from` statement to copy over methods that are relevant to your pipeline :) We do not expect `StableDiffusionPipeline` to be used as a superclass at all so that's not a use case we maintain at diffusers.

Are you the author of this pipeline? I can merge this quickly for you now if that's what you want.  Let me know:)

**Comment by TonyLianLong** [comment]
Thanks for your suggestions! Yes, I'm the author of this pipeline, and I'd like to make it easier to maintain. Let's inherit from `DiffusionPipeline` then. Do you have a reference of `# Copy from` statement in other pipelines? 

I can take the work to update the inheritance, or before I get some time to do this @KristianMischke you can also help with this if you feel excited about it.

**Comment by yiyixuxu** [comment]
We don't have it in the doc (I think we should, though! cc @sayakpaul @stevhliu what do you think?)

but it's everywhere in our codebase; here is an example
https://github.com/huggingface/diffusers/blob/f72b28c75b2b4b720a5d8de78556694cf4b893fd/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_img2img.py#L323

Once you added this `#Copy from` statement to the `encode_prompt` method of the img2img pipeline and specified where it's copying from, every time you run `make fix-copies` it will automatically update if there is a change in the code it's copying from (i.e., stable diffusion's `encode_prompt` method in this case)

**Comment by KristianMischke** [comment]
@yiyixuxu and @TonyLianLong thanks for the continued correspondence! Given my limited time, I'd say merge and allow @TonyLianLong to adjust the structure later

**Comment by TonyLianLong** [comment]
Somehow the colab still does not work: https://colab.research.google.com/drive/1SXzMSeAB-LJYISb2yrUOdypLz4OYWUKj

Will look into this when I get time.

**Comment by Skquark** [comment]
I'd also like to add another small fix when peft is installed with diffusers, gives the TypeError: Linear.forward() got an unexpected keyword argument 'scale'
On line 168, added this:
    args = () if USE_PEFT_BACKEND else (scale,)
along with importing USE_PEFT_BACKEND at the top.  Simple enough, that patch is probably missing from other pipelines too...

**Comment by TonyLianLong** [comment]
Could you create an issue and assign it to me? @Skquark

**Pull request merged**
