### PR TITLE
Fix incorrect initialization value of guidance_rescale param

### LINKED ISSUE #4553: Incorrect initialization value of guidance_rescale in different pipelines
Hi! I've been trying to understand how SD inference works, and diffusers has been really helpful with that.

As I was going through the code, I found this line of code, which might be a minor bug. The documentation says that it is defaulted to `0.7` but the code has it defaulted to `0.0`. The [arxiv](https://arxiv.org/pdf/2305.08891.pdf) paper states that `0.7` works great as well.

https://github.com/huggingface/diffusers/blob/7b07f9812a58bfa96c06ed8ffe9e6b584286e2fd/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L543

Some of the pipelines with this initialization value issue:
[src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/alt_diffusion/pipeline_alt_diffusion.py)
[src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py](https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py)
[All pipelines in src/diffusers/pipelines/stable_diffusion_xl](https://github.com/huggingface/diffusers/tree/main/src/diffusers/pipelines/stable_diffusion_xl)
[examples/community/stable_diffusion_reference.py](https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_reference.py)

Is this something that needs to be fixed?

### PR DESCRIPTION
**Pull request by a-r-r-o-w**
# What does this PR do?

The `guidance_rescale` parameter is used in different pipelines, inspired from [this](https://arxiv.org/pdf/2305.08891.pdf) paper. A good default value is `0.7` and diffusers documentation says it is set to this. However, it is incorrectly initialized to `0.0`.

Fixes #4553 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@sayakpaul

### CODE REVIEW

**Comment by a-r-r-o-w** [comment]
I anticipated the test to fail since this parameter cause rescaling of the noise predictions from the unet. I am unable to run the test `tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py` locally to find the correct values of `expected_slice` in `test_stable_diffusion_xl_refiner`, because of low compute power which causes my laptop to freeze up.

Could someone look into this?

**Comment by sayakpaul** [comment]
> I anticipated the test to fail since this parameter causes rescaling of the noise predictions from the unet. I am unable to run the test tests/pipelines/stable_diffusion_xl/test_stable_diffusion_xl_inpaint.py locally to find the correct values of expected_slice in test_stable_diffusion_xl_refiner, because of low compute power which causes my laptop to freeze up.

> Could someone look into this?

Could you maybe try on Colab?

**Review by sayakpaul — COMMENTED** [review]
Thanks for the changes. 

Could we also add some before after results with the correct value of this parameter?

@yiyixuxu could you also give this a look?

**Comment by a-r-r-o-w** [comment]
Fixed the test. Will write a small notebook for the before/after results with guidance_rescale set to 0.7 and share in a bit.

**Comment by a-r-r-o-w** [comment]
Here's a before/after of the guidance_rescale parameter:

lion

The prompt used is "A lion in galaxies, spirals, nebulae, stars, smoke, iridescent, intricate detail, octane render, 8k" (from the paper).
The first row has guidance_rescale set to 0.0, which is the current incorrectly set default although the docs say it is 0.7.
The second row has it set to 0.7, as proposed by the paper.
The third row has it set to 1.0.

I see a slight improvement in image quality and details.

**Comment by sayakpaul** [comment]
Can we fix the seeds across the rows?

Also, what about the fourth row?

**Comment by a-r-r-o-w** [comment]
I'm sorry, I'm not sure I follow... Fourth row? Currently, I'm using a fixed seed for each row and increasing the guidance scale from 0 to 0.7 to 1.0 top to bottom.

**Review by sayakpaul — APPROVED** [review]
Sweet. Thanks for answering the questions!

**Review by yiyixuxu — COMMENTED** [review]
I'm not too sure about this. My guess is it was set to `0` because it is something introduced later and we did not want to change the default behavior of the pipelines.

cc @williamberman and @patil-suraj here

**Comment by damian0815** [comment]
> I'm not too sure about this. My guess is it was set to `0` because it is something introduced later and we did not want to change the default behavior of the pipelines.
> 
> cc @williamberman and @patil-suraj here

in this case the documentation should be updated to reflect that the default is 0, not 0.7 (https://huggingface.co/docs/diffusers/v0.19.3/en/api/pipelines/stable_diffusion/text2img#diffusers.StableDiffusionPipeline.__call__)

**Comment by sayakpaul** [comment]
Should we close the PR then? Sorry about the inconvenience.

**Comment by williamberman** [comment]
yeah it's set to zero because that disables it and we don't have it enabled by default

**Comment by sayakpaul** [comment]
Closing the PR then. Sorry about the inconvenience.

**Pull request closed without merging**
