### PR TITLE
[WIP] Force unmasked area to not change

### PR DESCRIPTION
**Pull request by patrickvonplaten**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Draft PR for: https://github.com/huggingface/diffusers/issues/3880

**Comment by AbdallaMohammed** [comment]
Hi,
There's an awesome published paper about this task called "Blended Latent Diffusion"

Project Homepage : [Blended Latent Diffusion](https://omriavrahami.com/blended-latent-diffusion-page/)
Paper : [Arxiv](https://omriavrahami.com/blended-latent-diffusion-page/)
Code : [GitHub](https://github.com/omriav/blended-latent-diffusion)

**Comment by balasuh** [comment]
Hello all,
Is there any completed solution to this issue?
As I understand, the solution needs to achieve the following:

1. Leave the unmasked area unchanged.
2. Handle the transition gracefully.

Could this not be achieved by adding a changeable "halo" of pixels around the mask? Just thinking out loud here..

**Comment by djj0s3** [comment]
Will this PR also apply to StableDiffusionControlNetInpaintPipeline?

**Pull request closed without merging**
