### PR TITLE
[WIP] Retrieval Augmented Diffusion

### PR DESCRIPTION
**Pull request by patil-suraj**
WIP version of pipeline for [Retrieval Augmented Diffusion](https://arxiv.org/abs/2204.11824).

TODO:
- [ ] create a retriever class using `datasets` and `faiss`
- [ ] add script to create/train custom search index
- [ ] tests
- [ ] docs

The mode can be loaded using

```python
from diffusers import RDMPipeline

pipe = RDMPipeline.from_pretrained("fusing/rdm")
pipe.to("cuda")

prompt = "a happy pineapple" 
images = pipe(prompt).images
```

For now to test we can directly pass images for conditioning through the `retrieved_images` argument.

```python
retrieved_images = # a list of PIL images 
images = pipe(prompt, retrieved_images=retrieved_images).images
```

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@patil-suraj - let's open it up for the community maybe no? Wdyt?

**Comment by isamu-isozaki** [comment]
Hello! I can help! I needed this for my personal project anyways.

**Comment by patil-suraj** [comment]
Hey @isamu-isozaki ! Awesome, feel free to take stab it then, I'll be happy to help. Maybe just copy this code in your branch and open a PR. Most of the pieces are already there, big remaining part is to add the retriever, will leave some comments tomorrow about it.

**Comment by isamu-isozaki** [comment]
@patil-suraj thanks! I'm checking out your code now. Will appreciate any help!

**Comment by isamu-isozaki** [comment]
Interesting. I'm just writing here for future reference. 

The Retrieval Augmented Diffusion mainly functions by retrieving images using the text prompt and a database where we find photos via clip similarity with the text.
Now, the practical method of how this is done is the model is conditioned not just on the text clip but also on the retrieved image clip values.
For this pr, the conditioning portion is already done so the main work is making a DB where we can retrieve images based on clip.

**Comment by patrickvonplaten** [comment]
Very cool that you want to give it a try @isamu-isozaki ! 

Think it'd be a very nice addition for the community (especially the research community)

**Comment by patil-suraj** [comment]
closing this in favour of #1846

**Pull request closed without merging**
