### PR TITLE
[Core] Set `weights_only=True` nicely when we use `torch.load()`.

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

See internal discussion: https://pytorch.slack.com/archives/CN963QVJB/p1722612785082449. 

Can propagate this PR to `examples/` and `scripts/` after I have an approval.

### CODE REVIEW

**Comment by sayakpaul** [comment]
@yiyixuxu WDYT?

**Comment by yiyixuxu** [comment]
can we wrap the torch_load + weights_only into a function and use it everywhere?

**Comment by yiyixuxu** [comment]
actually, we already have one, no? https://github.com/huggingface/diffusers/blob/5d476f57c58c3cf7f39e764236c93c267fe83ca1/src/diffusers/models/model_loading_utils.py#L98

**Comment by sayakpaul** [comment]
That could work! Will update the PR.

**Comment by asomoza** [comment]
just want to bring that there some users that even though it's not recommended and risky, still want to load checkpoints with the `weights_only=False` option. For example: https://github.com/huggingface/diffusers/issues/8874 https://github.com/huggingface/diffusers/issues/9154

IMO it should be the default but users should be able to change it, I don't have a strong opinion about this just bringing it up to attention.

**Comment by sayakpaul** [comment]
I think better to wait for Dhruv to come back then.

**Comment by sayakpaul** [comment]
@DN6 cc I think this is relevant.

**Comment by yiyixuxu** [comment]
hi @mikaylagawarecki
I think we've flipped the default long time ago https://github.com/huggingface/diffusers/pull/7393

cc @DN6 to confirm

**Comment by DN6** [comment]
Hi. Yes, we flipped it because of the security issue. We don't allow setting `weights_only=True` when loading Diffusers models anymore. 
https://github.com/huggingface/diffusers/blob/76b7d86a9a5c0c2186efa09c4a67b5f5666ac9e3/src/diffusers/models/model_loading_utils.py#L144

Users would have to either convert to safetensors or deserialise those checkpoints on their own

**Pull request closed without merging**
