### PR TITLE
debug `EMAModel.from_pretrained()`

### PR DESCRIPTION
**Pull request by chenguolin**
# What does this PR do?

`model_cls.load_config()` is modified to **`model_cls.from_config()`**.

When setting `return_unused_kwargs=True`, for `model_cls.load_config()`, the returned unused kwargs are referred to as **unused input args**, instead of unused args for `model_cls` initialization. So the returned `ema_kwargs` are always empty (`{}`).

**`model_cls.from_config()`** will return the real **unused args for model initialization**, which are the expected `ema_kwargs`.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

General functionalities: @sayakpaul @yiyixuxu @DN6

### CODE REVIEW

**Review by sayakpaul — COMMENTED** [review]
Could you add a test for this here? https://github.com/huggingface/diffusers/blob/main/tests/others/test_ema.py

**Comment by chenguolin** [comment]
> Could you add a test for this here? https://github.com/huggingface/diffusers/blob/main/tests/others/test_ema.py

Hi @sayakpaul , how can I add a test here? I'm not familiar with this.

**Comment by sayakpaul** [comment]
Add a test case like 

https://github.com/huggingface/diffusers/blob/9a92b8177cb3f8bf4b095fff55da3b45a3607960/tests/others/test_ema.py#L146 

that accounts for the changes you introduced in this PR?

**Comment by sayakpaul** [comment]
Okay, we can add this as a test case then maybe?

**Comment by chenguolin** [comment]
OK, thank you 😊. You could consider merging this PR then. I have tested it in my own training process, and this bug has confused me for quite some time.

**Comment by sayakpaul** [comment]
Sorry I think you misunderstood. I am suggesting you to add a test case to demonstrate the use case you mentioned in https://github.com/huggingface/diffusers/pull/9809#issuecomment-2447126426.

**Comment by chenguolin** [comment]
OK. I tried.

But I found it's not that easy to write a `test_from_pretrained()` for `EMAModelTests`, as `EMAModel.from_pretrained()` requires loading both a model checkpoint and the corresponding config json file **including EMA args** (such as `decay` and `optimization_step`), which are not available in "[hf-internal-testing/tiny-stable-diffusion-pipe](https://huggingface.co/hf-internal-testing/tiny-stable-diffusion-pipe/blob/main/unet/config.json)".

**Comment by SahilCarterr** [comment]
i already opened a PR for this #9779 with the test case

**Comment by chenguolin** [comment]
> i already opened a PR for this #9779 with the test case @sayakpaul @chenguolin

It looks good :)

**Pull request closed without merging**
