### PR TITLE
[Core] pass revision in the loading_kwargs.

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

No idea why we didn't pass `revision`.

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]

**Comment by sayakpaul** [comment]
You're absolutely right! WDYT about removing `revision` from `load_sub_model()` then? I think we should eliminate the confusion (it's not used in the method).

**Comment by DN6** [comment]
Yes, I think we can remove it from `load_sub_model` if it's not used.

**Comment by yiyixuxu** [comment]
yep on the same page - we can remove it

**Comment by sayakpaul** [comment]
@yiyixuxu requesting for another review.

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Pull request merged**
