### PR TITLE
adding required parameters while calling the get_up_block and get_down_block 

### PR DESCRIPTION
**Pull request by init-22**
add `resnet_skip_time_act`, `resnet_out_scale_factor` and `cross_attention_norm` to `get_up_block` and `get_down_block` function 

this PR fixes a bug in `VersatileDiffusionPipeline` reported in #3178

### CODE REVIEW

**Comment by yiyixuxu** [comment]
oh I think we need to add the arguments to these functions, not removing

**Comment by init-22** [comment]
Hii @yiyixuxu these parameters are not used anywhere in the code, and I also ran the pytest for versatile_diffusion before creating this PR so I thought its not affecting the code. However, are those functions used or going to be used in future with the removed parameters? I'll add them if you think they are necessary.
Also, can you please tell me why 'tests for PRs / Fast PyTorch Pipeline CPU tests (pull_request)' is failing and how I can bypass that?

**Comment by yiyixuxu** [comment]
@init-22 

we like to keep the code consistent with `UNet2DConditionModel` so it is easier for us to maintain (see the `#copy from` statement here) - that's all 

https://github.com/huggingface/diffusers/pull/3210/files#diff-a3697c50cdae2be7e5cf9245ec77b65a81a5eb4ddf1757470c34f4766d7d81faL139

that's also the reason the quality tests failed here

**Comment by init-22** [comment]
@yiyixuxu Made changes as per your suggestion, please check.
Also, the following check is failing, I think it has nothing to do with the current changes.

FAILED tests/pipelines/unclip/test_unclip.py::UnCLIPPipelineFastTests::test_attention_slicing_forward_pass - AssertionError: 0.0039288998 not less than 0.001 : Attention slicing should not affect the inference results

**Review by yiyixuxu — APPROVED** [review]
Thanks!

**Review by sayakpaul — APPROVED** [review]
Thank you!

**Comment by init-22** [comment]
@yiyixuxu I've merged the main branch and checked that this indeed solves the issue after running the pytest separately. Thanks...

since I've already raised this current PR when #3214 wasn't merged this check failed status will remain there, right?

**Comment by sayakpaul** [comment]
And done, merging :)

**Pull request merged**
