### PR TITLE
Add upsample_size to AttnUpBlock2D, AttnDownBlock2D

### PR DESCRIPTION
**Pull request by will-rice**
The argument `upsample_size` needs to be added to these modules to allow compatibility with other blocks that require this argument. Fixes https://github.com/huggingface/diffusers/issues/3249

### CODE REVIEW

**Comment by will-rice** [comment]
Pinning to IPython 8.12 fixed these tests locally.

**Comment by will-rice** [comment]
Fixes #3249

**Review by patrickvonplaten — APPROVED** [review]
Great!

**Review by sayakpaul — APPROVED** [review]
Thank you!

**Comment by bulat15g** [comment]
It seems that the commit I used hasn't been included in the latest pip install update. 
I thought it would be helpful to mention this, as including the commit in the update would benefit other users who might encounter a similar issue.

**Comment by patrickvonplaten** [comment]
Hey @bulat15g,

I don't fully understand - what commit do you mean?

**Pull request merged**
