### PR TITLE
[Examples] use loralinear instead of depecrecated lora attn procs.

### PR DESCRIPTION
**Pull request by sayakpaul**
Fixes: https://github.com/huggingface/diffusers/issues/5133

Colab: https://colab.research.google.com/gist/sayakpaul/4e00a485de92a68b2d5411f090493081/scratchpad.ipynb

WandB: https://wandb.ai/xin-sayak/dreambooth-lora/runs/drwoiw6j

Weights on the Hub: https://huggingface.co/sayakpaul/new-lora-check-v15

### CODE REVIEW

**Comment by sayakpaul** [comment]
@patrickvonplaten did you envision something like this to get rid of the LoRA attention processors from the training examples? If okay I will propagate the changes to the rest of the scripts.

**Review by patrickvonplaten — APPROVED** [review]
Cool that works for me!

**Comment by sayakpaul** [comment]
@patrickvonplaten could you give this another look?

**Review by patrickvonplaten — APPROVED** [review]
Works for me!

**Pull request merged**
