### PR TITLE
[refactor] enhance readability of flux related pipelines

### PR DESCRIPTION
**Pull request by Luciennnnnnn**
# What does this PR do?

This PR refactors the FLUX-related pipelines to improve clarity and consistency, particularly in regards to height and width determination. The changes align the implementation more closely with other pipelines in the library, enhancing overall code coherence and maintainability.

The original code obscured the details of how latents packing affects resolution, but this change makes the process more transparent and easier to understand.

@yiyixuxu  @asomoza

### CODE REVIEW

**Review by DN6 — APPROVED** [review]
Nice clean up! 👍🏽

**Comment by yiyixuxu** [comment]
@Luciennnnnnn can you run `make style` and `make fix-copies`?

**Comment by Luciennnnnnn** [comment]
> @Luciennnnnnn can you run `make style` and `make fix-copies`?

Sure! This is my first contribution to diffusers, i'll try it

**Comment by Luciennnnnnn** [comment]
> @Luciennnnnnn can you run `make style` and `make fix-copies`?

Done!

**Comment by Luciennnnnnn** [comment]
The previous commit is failed on two checks, after modification, how to rerun checks

**Comment by Luciennnnnnn** [comment]
Hi @yiyixuxu , I see checks failed on FLUX training examples, which is not related to my PR. How can I pass it?

**Comment by yiyixuxu** [comment]
Hi @Luciennnnnnn thanks for the PR! It is a really nice PR
you did not "break" the training examples! but because they were using the same logic as in pipelines, we will need to update them too for example here https://github.com/huggingface/diffusers/blob/24c7d578baf6a8b79890101dd280278fff031d12/examples/dreambooth/train_dreambooth_flux.py#L1543

would you be interested in working on that? If not, I can take over when I have a little bit more time:)

**Comment by Luciennnnnnn** [comment]
@yiyixuxu 

> Would you be interested in working on that?
Sure! I have updated training example accordingly.

**Review by yiyixuxu — APPROVED** [review]
Thanks @Luciennnnnnn 
really nice job:) hope to see more of your PRs soon

**Pull request merged**
