### PR TITLE
fix inference in custom diffusion

### PR DESCRIPTION
**Pull request by caopulan**
fix inference in custom diffusion
inference codes should be in the loop of dataloader

### CODE REVIEW

**Comment by pcuenca** [comment]
cc @nupurkmr9, feel free to review if you'd like! :)

**Comment by sayakpaul** [comment]
@caopulan could you run `make style && make quality` so that the quality passes?

**Comment by caopulan** [comment]
> @caopulan could you run `make style && make quality` so that the quality passes?

I will later check the quality passes.

**Comment by caopulan** [comment]
> @caopulan could you run `make style && make quality` so that the quality passes?

I run these commands, which rewrite `train_custom_diffusion.py`.

And there is a nother error `src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py:327:41: E721 Do not compare types, use `isinstance()` but I don't change this file.

**Comment by sayakpaul** [comment]
That seems to be because you probably have a different version of `black` installed than what we use in our CI. You can find these file to know the version we use:
https://github.com/huggingface/diffusers/blob/0513a8cfd8c6a626da0e0bdafc469305a57a723e/setup.py#L95

**Comment by caopulan** [comment]
> That seems to be because you probably have a different version of `black` installed than what we use in our CI. You can find these file to know the version we use:
> 
> https://github.com/huggingface/diffusers/blob/0513a8cfd8c6a626da0e0bdafc469305a57a723e/setup.py#L95

I use `pip install black==23.1` and error still occurs.
```
Successfully uninstalled black-23.9.1
Successfully installed black-23.1.0
WARNING: You are using pip version 21.3.1; however, version 23.2.1 is available.
You should consider upgrading via the '/Users/sariel/opt/anaconda3/bin/python -m pip install --upgrade pip' command.
(base) sariel@MacBook-Pro-3 diffusers % make style
black examples scripts src tests utils
All done! ✨ 🍰 ✨
664 files left unchanged.
ruff examples scripts src tests utils --fix
src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py:327:41: E721 Do not compare types, use `isinstance()`
Found 1 error.
make: *** [style] Error 1
(base) sariel@MacBook-Pro-3 diffusers % make quality
black --check examples scripts src tests utils
All done! ✨ 🍰 ✨
664 files would be left unchanged.
ruff examples scripts src tests utils
src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py:327:41: E721 Do not compare types, use `isinstance()`
Found 1 error.
make: *** [quality] Error 1
```
Could I do anything then? If this error can be ignored, does this pr can be merged in main?

**Comment by sayakpaul** [comment]
The error can not be ignored. I will see if I can do anything.

**Comment by caopulan** [comment]
> The error can not be ignored. I will see if I can do anything.

Thanks a lot!

**Pull request merged**
