### PR TITLE
EMA: fix `state_dict()` and `load_state_dict()` & add `cur_decay_value`

### PR DESCRIPTION
**Pull request by chenguolin**
1. fix the saved value for `min_decay` in EMA `self.state_dict()`.

2. add an interface `self.cur_decay_value` to track the current value for decay.
(as `self.decay` is a constant value meaning "max decay value")

3. track the current EMA decay value by `self.cur_decay_value` in "unconditional image generation" examples, instead of `self.decay`.

### CODE REVIEW

**Comment by chenguolin** [comment]
4. fix a bug in EMA `load_static_dict()`: "AttributeError: 'float' object has no attribute 'get'"

**Comment by patrickvonplaten** [comment]
This looks good to me! @chenguolin could you maybe also check if the EMAModel class is correctly used in: https://github.com/huggingface/diffusers/blob/main/examples/unconditional_image_generation/train_unconditional.py and potentially fix it? :-)

**Comment by chenguolin** [comment]
It looks good. I have changed `logs["ema_decay"]` to the new `ema_model.cur_decay_value` to track the current decay value at: https://github.com/huggingface/diffusers/blob/7d96b38b70407ec69816e71cdcfc4e0b41e26768/examples/unconditional_image_generation/train_unconditional.py#L522

**Review by patrickvonplaten — APPROVED** [review]
This LGTM, @pcuenca @patil-suraj could you take a look?

**Comment by patrickvonplaten** [comment]
Actually we should probably also apply the same changes to: https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image.py 

In case you have 5min it'd be great if you could take a look at applying the same changes to `train_text_to_image` as wel @chenguolin :-) 

cc @patil-suraj wdyt of this PR

**Comment by chenguolin** [comment]
Hi @patrickvonplaten, the only necessary change to example "train_unconditional.py" is `logs["ema_decay"] = ema_model.decay` -> `logs["ema_decay"] = ema_model.cur_decay_value`.

While other examples don't use `ema_model.decay`, maybe there is no need to change them.

**Review by patil-suraj — APPROVED** [review]
Thanks a lot for fixing this!

**Comment by patil-suraj** [comment]
@chenguolin  there's a merge conflict in `train_unconditional_ort.py` could you please fix it? It should be good to merge after that.

**Review by pcuenca — APPROVED** [review]
Thank you!

**Comment by chenguolin** [comment]
Hi @patil-suraj, I have just deleted `train_unconditional_ort.py` ane merged.

**Review by williamberman — APPROVED** [review]
Failing test is un-related :)

**Pull request merged**
