### PR TITLE
Update pipeline_stable_diffusion_sag.py

### PR DESCRIPTION
**Pull request by alexblattner**
fixed a bug in which SAG didn't work with any euler schedulers

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
Thanks a lot for the PR! Could you add one quick test below this one: https://github.com/huggingface/diffusers/blob/342c5c02c0a12f8b0b2b180cea72178f5448b402/tests/pipelines/stable_diffusion/test_stable_diffusion_sag.py#L115 ?

**Comment by patrickvonplaten** [comment]
Yes you can run the fast tests easily on your computer. Could you take a look here: https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md ?

**Comment by bghira** [comment]
have you noticed if the non-square images work on v1.4 and v1.5 with SAG?

**Comment by bghira** [comment]
stable diffusion 1.4 is where SAG was developed for.

stable diffusion 1.4 is the only model where non-square resolutions work with SAG.

v1.5 and newer end up with tensor dimensional issues. imo this should probably  include fixes for the core issues with SAG.

**Comment by alexblattner** [comment]
@bghira thanks for the context. I didn't do anything regarding that issue. I did fix another however

**Pull request closed without merging**
