### PR TITLE
Update IP Adapter implementation to latest

### PR DESCRIPTION
**Pull request by a-r-r-o-w**
# What does this PR do?

After #5915, some pipelines are not yet updated to the latest implementation for IP Adapter Plus.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten @sayakpaul

### CODE REVIEW

**Comment by charchit7** [comment]
LGTM

**Comment by sayakpaul** [comment]
Could you add some results and also update the REAMDEs accordingly?

**Comment by sayakpaul** [comment]
Also ccing @TonyLianLong for the changes introduced in LLM-grounded diffusion.

**Comment by a-r-r-o-w** [comment]
> Could you add some results and also update the REAMDEs accordingly?

@sayakpaul I updated the implementations to match the changes introduced in 5915. However, I can't seem to get IP Adapter Plus to load with LLM Grounded Diffusion due to size mismatch in weights. It's probably just me doing something wrong but would you be willing to take a look as well @TonyLianLong? Thanks. I'll look into it further soon.

**Pull request closed without merging**
