### PR TITLE
fix table formatting for stable diffusion pipeline doc (add blank line)

### PR DESCRIPTION
**Pull request by natolambert**
A quick fix, previously looked like this (and I know this is likely a higher-traffic page!).

Screen Shot 2022-09-11 at 4 05 18 PM

### CODE REVIEW

**Comment by natolambert** [comment]
FYI @patrickvonplaten or @pcuenca this is good to merge, mostly letting one of you do it so we have more knowledge that this page was misformatted.

**Comment by pcuenca** [comment]
Thanks, I just saw it and was going to fix it!

**Review by pcuenca — APPROVED** [review]

**Comment by pcuenca** [comment]
It looks good now if you select `MAIN` in the dropdown.

**Comment by patrickvonplaten** [comment]
Thanks for the fix!

**Pull request merged**
