### PR TITLE
`make  deps_table_update` to fix CI tests

### PR DESCRIPTION
**Pull request by a-r-r-o-w**
# What does this PR do?

We missed this step (I did not know we had to do it) in #9709. Also contains a dummy change for now to trigger CI fast tests

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul @DN6

### CODE REVIEW

**Comment by a-r-r-o-w** [comment]
@sayakpaul, seems like capping the torch version in diffusers to `<2.5.0` does not fix the failing tests, because 2.5 gets installed by peft (see [here](https://github.com/huggingface/diffusers/actions/runs/11420646495/job/31776602477?pr=9720#step:4:76)).

**Comment by sayakpaul** [comment]
I am not sure if that is the case because from the logs of that action, I don't see any reinstallations of PyTorch, though. 

To confirm things, I would try print the PyTorch version just after the container is initialized. After this line:
https://github.com/huggingface/diffusers/blob/56d6d21baeb203a249b3049835916bfb0bfad061/.github/workflows/pr_test_peft_backend.yml#L94

If it's 2.5.0, then there's something wrong.

**Comment by sayakpaul** [comment]
Hmm I am pretty sure that the updated Torch is coming from https://github.com/huggingface/diffusers/blob/56d6d21baeb203a249b3049835916bfb0bfad061/docker/diffusers-pytorch-cpu/Dockerfile#L32

So, we need to:

* Ping torch versions in the Dockerfiles 
* Verify Dockerfiles build 
* Trigger a Docker build and push workflow 

Just pinning in the setup.py file won't cut it and my bad it went unnoticed.

**Comment by sayakpaul** [comment]
PR: https://github.com/huggingface/diffusers/pull/9709

Workflow: https://github.com/huggingface/diffusers/actions/runs/11423669772

**Review by DN6 — APPROVED** [review]

**Pull request merged**
