### PR TITLE
Dreambooth SDXL LoRA - Update PEFT for DoRA

### PR DESCRIPTION
**Pull request by shawnrushefsky**
The sdxl script assumes the presence of a dora related property that does not exist until peft 0.9.0

# What does this PR do?

Recent updates to the sdxl dreambooth lora training script require a newer version of peft to be installed.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul

### CODE REVIEW

**Comment by sayakpaul** [comment]
DoRA can be only used with peft installed from source and we make it clear from the readme. I don’t think this PR is relevant in that case.

**Comment by shawnrushefsky** [comment]
It breaks for non-DoRA training as well, though.

**Comment by sayakpaul** [comment]
Let's just pin the version of PEFT to be at least 0.9.0.

**Comment by sayakpaul** [comment]
Is this still relevant? We could simply remove the version from `peft` no?

**Pull request closed without merging**
