### PR TITLE
Add custom vae (diffusers type) to onnx converter

### PR DESCRIPTION
**Pull request by ForserX**
It is based on the diffuser model conversion algorithm to onnx. 
Tested this: https://github.com/ForserX/StableDiffusionUI

Decoder only.

### CODE REVIEW

**Comment by ForserX** [comment]
Original vae


vae-ft-mse-840000-ema-pruned (ONNX)

**Comment by patrickvonplaten** [comment]
@anton-l can you take a look here?

**Review by anton-l — APPROVED** [review]
Works for me, thank you @ForserX! 

@patrickvonplaten should this rather be in research projects, or is it fine to still merge onnx conversion scripts to the main directory?

**Comment by patrickvonplaten** [comment]
Think it's fine! Thanks a lot @ForserX :-)

**Pull request merged**
