### PR TITLE
[Tests] reduce the model size in the amused fast test

### PR DESCRIPTION
**Pull request by ariG23498**
# What does this PR do?

Reduces the model sizes in the aMUSEd fast tests.

Tagging Issue: https://github.com/huggingface/diffusers/issues/7677

CC: @sayakpaul for visibility.

### CODE REVIEW

**Comment by sayakpaul** [comment]
Let us know when this is ready for review.

**Comment by ariG23498** [comment]
@sayakpaul I am almost ready for reviews. Right now I am trying to estimate whether I could further reduce the size of the architecture. Will surely let the team know when this PR is ready.

**Comment by ariG23498** [comment]
@sayakpaul this is ready for review.

**Comment by ariG23498** [comment]
@sayakpaul I have also pushed the changes for `inpaint` and `img2img` pipelines in this PR.

**Pull request merged**
