### PR TITLE
add stable_diffusion_walk notebook to example/community folder

### PR DESCRIPTION
**Pull request by danielpatrickhug**
Related issue: [205](https://github.com/huggingface/diffusers/issues/205) 

Hello, this pull request is for adding the notebook stable_diffusion_walk to community examples. this notebook is designed to be run on google colab free version.

this notebook is **self contained** to google colab.
this notebook is relatively **easy to tweak** parameters.
this notebook's inference pipeline has **one purpose only** - to create videos.
running this notebook should be relatively **beginner friendly**, tweaking it may not be. 

@anton-l @patil-suraj @pcuenca or @patrickvonplaten may I please get a review?
Please let me know if there are any other changes that can be made for this pull request.

### CODE REVIEW

**Comment by nateraw** [comment]
Hey there, I think we should add a community pipeline before adding the notebook? Idk. WDYT @anton-l - would it be better to add the community pipeline and then add the notebook here?

**Comment by patil-suraj** [comment]
Thanks a lot for the PR @danielpatrickhug ! As @nateraw said we should add a code file for community pipeline here and link to the colab from readme. The notebook can live in your repo, we don't add colab files in the repo because of the file size.

**Comment by danielpatrickhug** [comment]
No worries.

**Comment by patrickvonplaten** [comment]
Hey @danielpatrickhug, 

I think the PR is still very relevant and nice, could I help you out here and make a pipeline that we'll then use from inside your colab?

**Comment by danielpatrickhug** [comment]
Hi, sounds cool, sure what did you have in mind?

**Comment by nateraw** [comment]
@patrickvonplaten is it preferrable to:

1. subclass `StableDiffusionPipeline` and update the `__call__`

or
 
2. copy paste and call it something new, adding functionality within `__call__`

**Comment by danielpatrickhug** [comment]
I've been working on a render, refine and repeat algorithms using SD similar to the one seen [here](https://infinite-nature.github.io/ ) for infinite scene generation. However, its still early in dev and it may be a bit expensive and clunky currently but I think this would be a cool pipeline to set up for future applications, like jumping into and flying through the SD latent in VR. I used a variant of this notebook in colab with my quest and had decent results.

**Comment by patrickvonplaten** [comment]
Hey @nateraw,

It is preferrable to have the file as "independent" as possible meaning there shouldn't be any subclassing

**Comment by nateraw** [comment]
@danielpatrickhug I started working on the pipeline file here: https://huggingface.co/nateraw/stable-diffusion-walk/blob/main/pipeline.py

Pretty hacky version right now...needs some cleanup and maybe should remove some of the features that were in `stable_diffusion_videos` so it's cleaner.

**Comment by allo-** [comment]
Is anyone still interested in developing this?

I have some old code, which would probably need to be adapted to recent diffusers first, that extends stablediffusionwalk with interactive options and more control over, for example, how far the seed travels from a starting point to explore the space around a particular image in detail.

**Pull request closed without merging**
