### PR TITLE
add peft dependency to fast push tests

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Otherwise: https://github.com/huggingface/diffusers/actions/runs/7257347281/job/19771026520

Cc: @younesbelkada

### CODE REVIEW

**Comment by DN6** [comment]
Fine to add. Do we have any LoRA examples that should not use PEFT? Would this affect them?

**Comment by DN6** [comment]
Oh hold on this would affect all fast CPU tests on main. Since they would all use PEFT. We still need to test without PEFT as well.

**Comment by sayakpaul** [comment]
@DN6 you are right. I changed the location as to where `peft` would get installed. 

> Do we have any LoRA examples that should also work without PEFT? Would this affect them?

All the LoRA training examples (that have corresponding tests) should run with PEFT. 

Let me know if that answers your doubts.

**Review by DN6 — APPROVED** [review]
LGTM 👍🏽

**Pull request merged**
