### PR TITLE
Remove code snippets containing `is_safetensors_available()`

### LINKED ISSUE #4243: Remove `use_safetensors` from `diffusers` codebase
`safetensors` is now a required dependency as can be seen here: https://github.com/huggingface/diffusers/pull/4177

This means we can remove all of the following `is_safetensors_available` codesnippets:

```
scripts/convert_original_audioldm_to_diffusers.py
41:from diffusers.utils import is_omegaconf_available, is_safetensors_available
827:        if not is_safetensors_available():

src/diffusers/loaders.py
42:    is_safetensors_available,
48:if is_safetensors_available():
178:        if use_safetensors and not is_safetensors_available():
185:            use_safetensors = is_safetensors_available()
590:        if use_safetensors and not is_safetensors_available():
597:            use_safetensors = is_safetensors_available()
807:        if use_safetensors and not is_safetensors_available():
814:            use_safetensors = is_safetensors_available()
1055:        if use_safetensors and not is_safetensors_available():
1062:            use_safetensors = is_safetensors_available()
1389:        use_safetensors = kwargs.pop("use_safetensors", None if is_safetensors_available() else False)

examples/community/checkpoint_merger.py
7:from diffusers.utils import is_safetensors_available
10:if is_safetensors_available():
232:                        if (is_safetensors_available() and checkpoint_path_1.endswith(".safetensors"))
239:                            if (is_safetensors_available() and checkpoint_path_2.endswith(".safetensors"))

src/diffusers/utils/import_utils.py
302:def is_safetensors_available():

src/diffusers/utils/__init__.py
67:    is_safetensors_available,

src/diffusers/pipelines/pipeline_utils.py
55:    is_safetensors_available,
877:        use_safetensors = kwargs.pop("use_safetensors", None if is_safetensors_available() else False)
1169:        if use_safetensors and not is_safetensors_available():
1176:            use_safetensors = is_safetensors_available()

src/diffusers/models/modeling_utils.py
39:    is_safetensors_available,
59:if is_safetensors_available():
303:        if safe_serialization and not is_safetensors_available():
460:        if use_safetensors and not is_safetensors_available():
467:            use_safetensors = is_safetensors_available()

src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py
51:from ...utils import is_omegaconf_available, is_safetensors_available, logging
1100:        if not is_safetensors_available():
1388:        if not is_safetensors_available():
```

### PR DESCRIPTION
**Pull request by chiral-carbon**
# What does this PR do?
Fixes #4243 

Some tests failing on running `make test`, since I did not add my own tests. 
`make test` summary:
```
================================================== 116 failed, 1941 passed, 1145 skipped, 1098 warnings in 1420.89s (0:23:40) ===================================================
```

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@patrickvonplaten @DN6

### CODE REVIEW

**Comment by chiral-carbon** [comment]
The summary in the PR description above is the summary from `make test` that I run on my local machine. 
I use a MacBook Pro 2019 and many of the above errors are MPS device errors, so I assume it is because I don't have GPU on my local machine that I see so many errors.

Need some help understanding the current `AssertionErrors` that you can see in the summary.

**Comment by DN6** [comment]
Hi @chiral-carbon PR looks good. I'd like to update/add some tests to this PR. Can add me as a collaborator to your fork so that I can commit them? Alternatively, I can create another with the test changes that you can merge into your branch. LMK what works for you 👍🏽

**Comment by chiral-carbon** [comment]
Thanks @DN6! Added you as collaborator.

**Comment by chiral-carbon** [comment]
Thanks @DN6! I think I would like to merge your test commits from your own fork. If that is a longer process though I will directly add you as collaborator.

**Comment by DN6** [comment]
@chiral-carbon Could you merge the commits from `safetensors-default` into your branch.

**Comment by chiral-carbon** [comment]
it works @DN6, thanks! I was stuck on the logic in the last test so this helps me understand too

**Comment by DN6** [comment]
Hi @chiral-carbon requesting one last small change. I think we can get rid of these lines in the test. We don't need them anymore. 
https://github.com/huggingface/diffusers/blob/ac1580a48d9ab6d8d9841e70d8d35735f1603609/tests/models/test_modeling_common.py#L63-L65

**Review by DN6 — APPROVED** [review]

**Comment by DN6** [comment]
Great job @chiral-carbon 🙌🏽

**Pull request merged**
