### PR TITLE
Multiprompt dreambooth

### PR DESCRIPTION
**Pull request by klopsahlong**
**Purpose of multi-prompting**
This pull request implements the ability to train a single model with multiple new concepts using dreambooth. This can be used for rendering multiple new concepts in a single generated image.

**A few things to note:**
- This implements multi-prompting for train_dreambooth.py only (not train_dreambooth_flax.py). Assuming this PR looks good, I can also implement multi-prompting for train_dreambooth_flax.py.
- This implementation does not include any unit tests, largely because I could not find any existing test for the dreambooth code. If this is not the case or there is a test suite that I should add to, please let me know.

Comments & edits are appreciated!

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
cc @patil-suraj @williamberman

Thanks a lot for the PR @klopsahlong :-) 

This seems a bit researchy and might be a bit too specific for the highly used dreambooth example script - should we maybe add it under: https://github.com/huggingface/diffusers/tree/main/examples/research_projects ?

**Comment by williamberman** [comment]
+1 to @patrickvonplaten 

There's definitely interest in multiple subject dreambooth. See longer discussion here: https://github.com/huggingface/diffusers/issues/1475 . I haven't done much testing myself but we would need high confidence we can do multiple subjects with a reasonable degree of quality before adding to the main script. 

Would love to see example multiple subject scripts (like yours, @klopsahlong !) merged into `research_projects`! Would certainly help us having examples to look at when we get time to look more into multi-subject dreambooth :)

**Comment by klopsahlong** [comment]
Okay great that makes a lot of sense! Thanks for the feedback - will look to merge some example multiple subject scripts into `research_projects` soon :)

**Comment by abhishekkrthakur** [comment]
@klopsahlong do you have any examples of end-results using this?

**Pull request closed without merging**
