### PR TITLE
[Pipeline Docs] Unconditional Latent Diffusion

### PR DESCRIPTION
**Pull request by satpalsr**
Part of #293

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Very cool @satpalsr !

If you want you could also start adding the docstring to the code as shown here: https://github.com/huggingface/diffusers/pull/377/files#r964672207 (feel free to copy) - we can also do this in a follow-up PR though :-)

**Comment by patrickvonplaten** [comment]
Here a complete example you could more or less copy everything from :-) https://github.com/huggingface/diffusers/pull/377#pullrequestreview-1098963887

**Comment by satpalsr** [comment]
Thanks, @patrickvonplaten Added the docstrings.

**Comment by patrickvonplaten** [comment]
That's great thanks a lot @satpalsr

**Pull request merged**
