### PR TITLE
Research project multi subject dreambooth

### PR DESCRIPTION
**Pull request by klopsahlong**
This pull request implements the ability to train a single model to learn multiple new subjects using dreambooth. This can be used for rendering multiple new subjects in a single generated image.

Note also that this is a follow up from the original multi subject dreambooth PR ([here](https://github.com/huggingface/diffusers/pull/1893)), where it was recommended that the multi subject dreambooth code be added to the `research_projects` folder, rather than the main `dreambooth` folder.

### CODE REVIEW

**Comment by klopsahlong** [comment]
tagging @williamberman @patrickvonplaten as an fyi

**Review by patrickvonplaten — APPROVED** [review]
Thanks a lot!

**Comment by abhishekkrthakur** [comment]
@klopsahlong do you have any examples of end-results using this?

**Comment by qq110146** [comment]
Hi @klopsahlong  I finetuned from stable diffusion v1.5 with [train_multi_subject_dreambooth.py](https://github.com/huggingface/diffusers/blob/main/examples/research_projects/multi_subject_dreambooth/train_multi_subject_dreambooth.py). it worked fine when I trained single subject: car/dog. But the results quality decreased when I trained both categories at the same time.

Details: https://github.com/huggingface/diffusers/issues/2599

Are there any examples of two-subjects training results?

**Pull request merged**
