### PR TITLE
[dreambooth] Add --hflip flag

### PR DESCRIPTION
**Pull request by nickkolok**
# What does this PR do?

Add `--hflip` flag for DreamBooth (SD1.5). The feature is being backported from ShivamShrirao's fork

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

Tagging: @sayakpaul and @patrickvonplaten (following the guide from template)

About a year ago, @ShivamShrirao released a fork of Dreambooth script (along with a Colab Notebook!)
(see also  #3461 ). That is a really good tool to fine-tune models, but there is also a really big problem behind it: the community. As for now, ShivamShrirao's tool is (almost) not being maintaining. It is not being developed - and that's discouraging.

I've been using the ShivamShrirao's notebook (with my own improvements) since Dec 2022; now, I'm trying to switch to the main, `diffusers` edition... with no success yet. So, I'm going to try to backport some features from ShivamShrirao's fork to the upstream. 

At least one of them :)

Also, is there an official **free** Colab notebook to test the script? I have only 512MB VRAM locally :)

### CODE REVIEW

**Comment by sayakpaul** [comment]
Hi there!

Thanks for your PR. Our training examples are for folks to build on top of. So, you are free to customize the scripts to suit your needs. But we keep the PRs related to changes to our scripts to a bare minimum.

**Comment by patrickvonplaten** [comment]
@nickkolok can you explain what `hflip` does exactly and why it should help?

**Comment by nickkolok** [comment]
The purpose of `--hflip` is to virtually double the variety of the concept dataset, which is said to be expecially useful on small datasets. Before each training step, every image is randomly flipped horizontally (the left side becomes the right one and vice versa) - or not flipped. Thus, a dataset of $n$ images becomes a dataset of $2n$ images. They say that this trick can improve the quality of training.

However, we cannot enable this behaviour by default, because some concepts do not allow arbitrary mirroring.

**Comment by patrickvonplaten** [comment]
@sayakpaul wdyt? I'm ok with the change, but also ok to ask users to tweak it

**Pull request closed without merging**
