### PR TITLE
[New Pipeline] Add Grad TTS

### PR DESCRIPTION
**Pull request by Vaibhavs10**
Note: This is still WIP

So far I've added all the text and model utils to two separate files in the GradTTS pipeline folder.
I've also added the `LinearAttention` function in the `attention.py` file.

I am confused about adding GradTTS-specific Resnet blocks to `resnet.py` or directly using the `ResNet2D` block.

Next, I'll focus on adding the model and then the pipeline, any suggestions/ feedback is welcome.

cc: @patil-suraj & @patrickvonplaten

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @Vaibhavs10 , 

Do you need a review here?

**Comment by Vaibhavs10** [comment]
Hi @patrickvonplaten - I am struggling a bit about splitting the Resnet blocks into a diffusers friendly format. So any quick pointers on that would be pretty helpful. after that, can we do a full review?

**Comment by patrickvonplaten** [comment]
Hey @Vaibhavs10 :-) 

Yes I think grad-tts had some weird unet/resnet blocks. Could you for now just add something that works from where we can start iterating? Essentially try to build a very hacky block in `unet_block` and a completely new `ResnetBlock` (I think we should actually create a new resnet block here) 

Once that's in the PR, I'm more than happy to help :-)

**Comment by Vaibhavs10** [comment]
Hey hey Patrick & team - sorry for the delay on this. Got pulled in different directions with work stuff.
This is next on my priority list and will have some updates on this in the next couple days!

**Comment by patrickvonplaten** [comment]
Cool!

**Pull request closed without merging**
