### PR TITLE
Stable diffusion text2img conversion script.

### PR DESCRIPTION
**Pull request by patil-suraj**
This PR adds conversion script for text2img stable diffusion models from CompVis.

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]

**Comment by kabachuha** [comment]
@patil-suraj Do you have any plans for reverse functionality? I.e. diffusers .bin -> original .ckpt? Your knowledge would help us greatly

**Comment by pcuenca** [comment]
Hi @kabachuha! Work towards that goal is being coordinated in issue #672, where you have participated :) It looks like @rashmimarganiatgithub is taking a go at it!

**Comment by NicholasKao1029** [comment]
Are there docs for this?

**Comment by patil-suraj** [comment]
Hi @NicholasKao1029  you can check the docstring here, the script can now be called as a function https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L778

**Comment by NicholasKao1029** [comment]
Thanks @patil-suraj is it correct to say that this conversion is a perfect 1:1.

As in 
ckpt 1 -> diffusers -> ckpt 2
`ckpt 1 == ckpt2`

**Comment by patil-suraj** [comment]
Yes, it should be 1:1

**Comment by NicholasKao1029** [comment]
Very nice thanks, can I also confirm that safetensors transformation is the same way (also outputting to a safetensors)

**Comment by patil-suraj** [comment]
The script convert ckpt safetensors to diffusers but with native torch doesn't output safetensors yet

**Pull request merged**
