### PR TITLE
Fix SDXL Inpainting from single file with Refiner Model

### PR DESCRIPTION
**Pull request by DN6**
# What does this PR do?
Some refinements to `from_single_file` for the SDXL Inpainting model that allows it to work with the SDXL Refiner checkpoint. 

Also cleans up a lot of redundant checks and object creation in the `download_from_original_stable_diffusion_ckpt` function.

Fixes # (issue)
https://github.com/huggingface/diffusers/issues/6001

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by standardAI** [comment]
Hi @DN6. I am new to open-source software. What should I do in the case of [similar PRs](https://github.com/huggingface/diffusers/pull/6138), what are your suggestions to me?
Wouldn't this be possible: You would have forked my branch and would have continued to study on it. I did this at [this PR](https://github.com/huggingface/diffusers/pull/6144).

**Comment by DN6** [comment]
Hi @standardAI. In this particular case, I was removing a chunk of redundant code in order to keep the `covnvert_from_ckpt` function from growing more. If it were just a few small changes I would have pushed to your PR.

**Comment by standardAI** [comment]
> Hi @standardAI. In this particular case, I was removing a chunk of redundant code in order to keep the `covnvert_from_ckpt` function from growing more. If it were just a few small changes I would have pushed to your PR.

OK, all fine!

**Review by sayakpaul — COMMENTED** [review]
Cool! Can we add some tests here or modify the `single_file` tests to include assertions to ensure that the correct pipeline classes are returned from these utilities?

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by patrickvonplaten** [comment]
Let's merge this for now and then start the bigger refactor of `from_single_file` . 

It's actually a bit tricky to add tests here since it's really difficult to create dummy models.

**Pull request merged**
