### PR TITLE
[LoRA test suite] refactor the test suite and cleanse it

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Currently, we have a giant `test_lora_layers_peft.py` script, which makes it quite difficult for us, as well as the contributors, to understand how LoRA-related stuff is tested. Moreover, we have SDv1.5 tests within `LoraSDXLIntegrationTests`:

https://github.com/huggingface/diffusers/blob/53e9aacc1087bc1d6cf9a1c0d243e82ffd56e925/tests/lora/test_lora_layers_peft.py#L1935

To mitigate that, this PR proposes to do the following:

* Create two test files corresponding to SD and SDXL. 
* Move the tests that are of type "integration" (i.e., value assertions for pre-trained checkpoints) in nature to their appropriate classes. 
* Maintains a utility module to have `PeftLoraLoaderMixinTests` and other util functionalities. 

Additionally, it makes use of `numpy_cosine_similarity_distance()` wherever possible to relax the assertions on absolute value slices. This makes it easier to run the test suite on different GPU cards. 

@DN6 I have already run the entire testing suite on the DGX and everything passes. Feel free to do so yourself as well.

### CODE REVIEW

**Review by younesbelkada — APPROVED** [review]
Thanks for the cleanup Sayak !

**Review by DN6 — APPROVED** [review]
LGTM 👍🏽

**Comment by sayakpaul** [comment]
@DN6 could you check if running `make style && make quality` incurs any changes on your end?

**Comment by sayakpaul** [comment]
Failing test is because of https://github.com/huggingface/diffusers/pull/7304/#issuecomment-2008575998.

**Pull request merged**
