### PR TITLE
Community pipeline img2img inpainting

### LINKED ISSUE #905: [Community Pipeline] image2image inpainting?
**Is your feature request related to a problem? Please describe.**
Imagine you have two images defined, a logo and a t-shirt. we want to apply the logo to the t-shirt in such a way that it matches the physical surface of the t-shirt and the logo deforms correctly.

**Describe the solution you'd like**
How it should look like can be viewed in the images:
https://ibb.co/HtGGsC2 +  https://ibb.co/6mFc8QL -> https://ibb.co/Y7h2t8b

**Describe alternatives you've considered**
I was trying to predict the surface of the t-shirt with pose predictor and place the logo onto it via affine transformation.
Results are questionable and in the end it is not scalable to other objects

**Additional context**

### PR DESCRIPTION
**Pull request by vvvm23**
Resolves #905

However, it would see the base implementation doesn't actually support Tensor input (only PIL image).

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @vvvm23 ,

Could you also add a section to the Examples README and a entry to the table: https://github.com/huggingface/diffusers/blob/main/examples/community/README.md#example-usages ? 

This would be very nice :-)

**Comment by vvvm23** [comment]
Sure, I can do that tomorrow for you ~ I'll also try and fix the bug with tensor inputs, but that may come later.

**Comment by vvvm23** [comment]
Done, I can't fix the other issues today though, doing this PR from the airport 😅

**Comment by socathie** [comment]
Hi @vvvm23 , thanks for the custom pipeline! It was very useful for my application - just wondering if the example usage script is accurate though? In particular, this line:

```
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "runwayml/stable-diffusion-inpainting",
    revision="fp16",
    torch_dtype=torch.float16,
)
```

seems like this just calls the regular inpaint pipeline and disregard the inner image argument?

**Comment by vvvm23** [comment]
Good catch, just goes to show you shouldn't write PRs in an airport :sweat_smile: I'll change that tomorrow + adds some example results. Likely in a separate PR that I will link to this one.

**Comment by vvvm23** [comment]
@socathie how does #1370 look to you?

**Comment by socathie** [comment]
> @socathie how does #1370 look to you?

Look good. Works on my end as well.

**Pull request merged**
