### PR TITLE
Added Community pipeline for comparing Stable Diffusion v1.1-4 checkpoints

### LINKED ISSUE #873: [Community Pipelines] SD v1-v4 compare
## Intro

Community Pipelines are introduced in `diffusers==0.4.0` with the idea of allowing the community to quickly add, integrate, and share their custom pipelines on top of `diffusers`. 

You can find a guide about Community Pipelines [here](https://github.com/huggingface/diffusers/issues/841). You can also find all the community examples under [`examples/community/`](https://github.com/huggingface/diffusers/tree/main/examples/community). If you have questions about the Community Pipelines feature, please head to the [parent issue](https://github.com/huggingface/diffusers/issues/841).

## Idea: SD v1-v4 compare

The idea of this pipeline is to run all 4 checkpoints in parallel to compare the outputs

* https://huggingface.co/CompVis/stable-diffusion-v1-4
* https://huggingface.co/CompVis/stable-diffusion-v1-1
* https://huggingface.co/CompVis/stable-diffusion-v1-2
* https://huggingface.co/CompVis/stable-diffusion-v1-3

### PR DESCRIPTION
**Pull request by suvadityamuk**
Fixes #873  to add a Community pipeline that will perform a comparison between the Stable Diffusion v1.1-v1.4 checkpoints parallely. 
Takes a general prompt as input and returns a formatted `StableDiffusionPipelineOutput` with the result of each of the four checkpoints.

Signed-off-by: Suvaditya Mukherjee <suvadityamuk@gmail.com>

### CODE REVIEW

**Comment by suvadityamuk** [comment]
Hi, @patrickvonplaten!

Could you possibly guide me on this issue and let me know if my approach towards solving #873 is correct or are we looking for something else altogether?

**Comment by patrickvonplaten** [comment]
Thanks for the PR - could you also add an example here: https://github.com/huggingface/diffusers/blob/main/examples/community/README.md :-)

**Comment by suvadityamuk** [comment]
Sure thing, will do in a while!

**Comment by suvadityamuk** [comment]
It seems that `DiffusionPipeline.from_pretrained()` only accepts one string for the pretrained-model path, but here we need 4. What should I do in this case, in your opinion?

**Comment by suvadityamuk** [comment]
One possible solution is to accept only the v1.4 model string while using the v1.1-3 models internally. Should I do that instead?

**Comment by suvadityamuk** [comment]
Have added the code example and the updated file for the Pipeline where it accepts the v1.4 checkpoint and installs the v1.1-3 checkpoints internally. Is that fine?

**Comment by suvadityamuk** [comment]
Hi, @patrickvonplaten!

Any updates on whether this is fine?

**Review by patrickvonplaten — APPROVED** [review]
Great!

**Comment by patrickvonplaten** [comment]
Thanks a lot for adding this!

**Pull request merged**
