### PR TITLE
[Core] Refactor `IPAdapterPlusImageProjection` a bit

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Refer to https://github.com/huggingface/diffusers/pull/7988/#issuecomment-2120785867, thanks to @fabiorigano for the suggestion. Even though Fabio mentioned working on a PR for this, I had some free-time and thought I would do it. I hope that's okay with you, @fabiorigano? 

In any case, would really appreciate your reviews here and if you could test this if you find some time, that would be of great help. 

@rootonchair feel free to give it a look as well.

### CODE REVIEW

**Comment by fabiorigano** [comment]
@sayakpaul no problem, it looks really good and neat to me now!
I will do some testing as soon as I can, but maybe https://github.com/huggingface/diffusers/blob/e1df77ee1ec0400195ad8dcb2099d137b34c9b9f/tests/models/unets/test_models_unet_2d_condition.py#L114 should be updated too, right?

**Comment by fabiorigano** [comment]
@sayakpaul I tested both simple inference and the `test_ip_adapter_plus` function in the test suite with the command `python -m pytest -s -v tests/models -k test_ip_adapter_plus`. Everything works as expected, even the test because some keys are not updated and the loading process doesn't fail. The following conditions are never true because of the new architecture of the class: 
https://github.com/huggingface/diffusers/blob/e1df77ee1ec0400195ad8dcb2099d137b34c9b9f/tests/models/unets/test_models_unet_2d_condition.py#L162-L175

IMO they should be either removed or updated. WDYT?

**Comment by sayakpaul** [comment]
Thanks for catching this, @fabiorigano! I just updated it in [9ebacf3](https://github.com/huggingface/diffusers/pull/7994/commits/9ebacf3f6d77f6aad251a2a38628a7026aaf96ba). WDYT?

**Comment by fabiorigano** [comment]
Looks great! @sayakpaul

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Pull request merged**
