### PR TITLE
upgrade to python 3.10 in the Dockerfiles

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Check here: https://github.com/huggingface/diffusers/pull/7703#discussion_r1584501268.

### CODE REVIEW

**Comment by sayakpaul** [comment]
Hmm our base image Ubuntu makes it a little difficult to install Python 3.10. Any other ideas @DN6?

**Comment by sayakpaul** [comment]
Or we could follow this approach: https://github.com/huggingface/trl/blob/main/docker/trl-source-gpu/Dockerfile. I don't really mind. Let me know and I will use this PR to do that.

**Review by DN6 — APPROVED** [review]
Nice.  Thanks 👍🏽

**Comment by sayakpaul** [comment]
Please see the comments first:

* https://github.com/huggingface/diffusers/pull/7893#issuecomment-2101501844
* https://github.com/huggingface/diffusers/pull/7893#issuecomment-2101505786

**Pull request merged**
