### PR TITLE
update runway repo for single_file

### PR DESCRIPTION
**Pull request by yiyixuxu**
use `Lykon/dreamshaper-8` for now - will update once we made a decision
for https://github.com/huggingface/diffusers/issues/9322#issuecomment-2319165753

### CODE REVIEW

**Comment by crapthings** [comment]
i still get error

```
pip install git+https://github.com/huggingface/diffusers@46e47c9
```

```
 > [19/21] RUN python cache.py:                                                                                                                                                                                                                                               
2.165 The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.                                 
0it [00:00, ?it/s]                                                                                                                                                                                                                                                            
3.648 /opt/conda/lib/python3.10/site-packages/controlnet_aux/mediapipe_face/mediapipe_face_common.py:7: UserWarning: The module 'mediapipe' is not installed. The package will have limited functionality. Please install it using the command: pip install 'mediapipe'       
3.648   warnings.warn(                                                                                                                                                                                                                                                        
3.649 /opt/conda/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_5m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_5m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
3.649   return register_model(fn_wrapper)
3.649 /opt/conda/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_11m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_11m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
3.649   return register_model(fn_wrapper)
3.649 /opt/conda/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_224 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_224. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
3.649   return register_model(fn_wrapper)
3.649 /opt/conda/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_384 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_384. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
3.649   return register_model(fn_wrapper)
3.649 /opt/conda/lib/python3.10/site-packages/controlnet_aux/segment_anything/modeling/tiny_vit_sam.py:654: UserWarning: Overwriting tiny_vit_21m_512 in registry with controlnet_aux.segment_anything.modeling.tiny_vit_sam.tiny_vit_21m_512. This is because the name being registered conflicts with an existing name. Please check if this is not expected.
3.649   return register_model(fn_wrapper)
40.53 cache model
40.53 Traceback (most recent call last):
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
40.53     response.raise_for_status()
40.53   File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
40.53     raise HTTPError(http_error_msg, response=self)
40.53 requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main
40.53 
40.53 The above exception was the direct cause of the following exception:
40.53 
40.53 Traceback (most recent call last):
40.53   File "/workspace/cache.py", line 21, in <module>
40.53     pipe = StableDiffusionControlNetPipeline.from_single_file(
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
40.53     return fn(*args, **kwargs)
40.53   File "/opt/conda/lib/python3.10/site-packages/diffusers/loaders/single_file.py", line 403, in from_single_file
40.53     cached_model_config_path = _download_diffusers_model_config_from_hub(
40.53   File "/opt/conda/lib/python3.10/site-packages/diffusers/loaders/single_file.py", line 249, in _download_diffusers_model_config_from_hub
40.53     cached_model_path = snapshot_download(
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
40.53     return fn(*args, **kwargs)
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 238, in snapshot_download
40.53     raise api_call_error
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/_snapshot_download.py", line 169, in snapshot_download
40.53     repo_info = api.repo_info(repo_id=repo_id, repo_type=repo_type, revision=revision, token=token)
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
40.53     return fn(*args, **kwargs)
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2588, in repo_info
40.53     return method(
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
40.53     return fn(*args, **kwargs)
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/hf_api.py", line 2373, in model_info
40.53     hf_raise_for_status(r)
40.53   File "/opt/conda/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 352, in hf_raise_for_status
40.53     raise RepositoryNotFoundError(message, response) from e
40.53 huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-66d13ade-2e6d8a523b2f4328430f7bda;8a18eda1-eba2-4fbb-b665-97bccb17f32f)
40.53 
40.53 Repository Not Found for url: https://huggingface.co/api/models/runwayml/stable-diffusion-v1-5/revision/main.
40.53 Please make sure you specified the correct `repo_id` and `repo_type`.
40.53 If you are trying to access a private or gated repo, make sure you are authenticated.
40.53 Invalid username or password.
```

**Review by pcuenca — APPROVED** [review]

**Comment by yiyixuxu** [comment]
@crapthings can you share your code?

**Comment by missionfloyd** [comment]
All the old versions will remain broken unless their respective wheels are updated with this as well, or the repo is replaced (or perhaps huggingface_hub can be updated). There's still a reason to use old versions, as generations can and often do change between releases.

These files are tiny; why not bundle them?

**Comment by crapthings** [comment]
0.30.2 works

**Pull request merged**
