### PR TITLE
Make safety_checker optional in more pipelines

### LINKED ISSUE #1792: Img2Img pipeline initialization fails on SD variants with no feature extractor/safety checker
### Describe the bug

The SD2.1 base repo didn't have the safety checker components. It still loaded fine in a normal StableDiffusionPipeline, but failed when using the StableDiffusionImg2ImgPipeline since that requires a safety checker. Initializing it with the components of the base StableDiffusionPipeline worked but gave a warning since the safety checker is None for v2.1. 

The issue with v2.1 specifically should now be fixed thanks to 
- https://huggingface.co/stabilityai/stable-diffusion-2-1-base/commit/826d6be1b25b06a83b5250146b926ca9276bb944
- https://huggingface.co/stabilityai/stable-diffusion-2-1-base/commit/88bb1a46821197d1ac0cb54d1d09fb6e70b171bc

but more generally this is likely to crop up any time someone tries to load a variant with no safety checker into the Img2Img pipeline, so @patrickvonplaten suggested I open an issue anyway for others who might face the same bug.

### Reproduction

`pipe = StableDiffusionImg2ImgPipeline.from_pretrained( "stabilityai/stable-diffusion-2-1-base").to(device)`

This fails with an error: 
ValueError: Pipeline <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion_img2img.StableDiffusionImg2ImgPipeline'> expected {'text_encoder', 'safety_checker', 'feature_extractor', 'vae', 'scheduler', 'unet', 'tokenizer'}, but only {'text_encoder', 'vae', 'scheduler', 'unet', 'tokenizer'} were passed.

### Logs

_No response_

### System Info

diffusers 0.11 on Google colab IIRC

### PR DESCRIPTION
**Pull request by pcuenca**
Fixes #1792.

Note that some pipelines (paint by example, image variations) do require a `feature_extractor`. We should at least display a clear error message if the loaded checkpoint doesn't have one. Or should we automatically instantiate one in those cases?

### CODE REVIEW

**Review by patil-suraj — APPROVED** [review]
Thanks for fixing this! Also, since the `feature_extractor` is a required argument for those pipelines, it should already display a nice error message about that no ? And think we can-not load `feature_extractor` automatically because those are associated with specific image models and might not be the same for all.

**Comment by pcuenca** [comment]
> since the `feature_extractor` is a required argument for those pipelines, it should already display a nice error message about that no ? 

This is what it gives right now:

> /home/pedro/.cache/huggingface/diffusers/models--pcuenq--tmp-variations/snapshots/09d9d929c0c58a2ae7a96b7b371e9e91c834e821 does not appear to have a file named preprocessor_config.json. Checkout 'https://huggingface.co//home/pedro/.cache/huggingface/diffusers/models--pcuenq--tmp-variations/snapshots/09d9d929c0c58a2ae7a96b7b371e9e91c834e821/None' for available files.

I think we could maybe improve it in a new PR. Merging this because I think fixing the issue is more important than the error message for those other pipelines :)

**Comment by pcuenca** [comment]
Actually, taking a look at the test failures.

**Comment by pcuenca** [comment]
Tests now pass, cc @anton-l for the changes and merging to fix the issue.

**Pull request merged**
