### PR TITLE
Add support for XFormers in SD3

### PR DESCRIPTION
**Pull request by CanvaChen**
# What does this PR do?

Add support for XFormers in SD3 (#8535)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul @yiyixuxu

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by sayakpaul** [comment]
Thanks!

Could you also provide a test script for this so that we can run some tests?

**Comment by sayakpaul** [comment]
@DN6 how should this test set be added?

**Comment by DN6** [comment]
Pipeline tests for xformers is handled via the `PipelineTesterMixin`, so a pipeline test is not needed. It would be nice to add a test in for the SD3 Transformer though. Similar to how we have it here
https://github.com/huggingface/diffusers/blob/c1dc2ae61968cccc3924784e4ed65ccfcd5c86eb/tests/models/unets/test_models_unet_2d_condition.py#L398

**Comment by DN6** [comment]
@CanvaChen Could you please run `make style && make quality` for the QC checks to pass?

**Comment by sayakpaul** [comment]
Apologies for this delay. @DN6 could you give this a review?

**Comment by sayakpaul** [comment]
@CanvaChen I think this is still quite relevant. Would you maybe like to resolve the conflicts so that we can attempt a merge?

**Comment by sayakpaul** [comment]
@DN6 could you please give this a review?

**Review by DN6 — APPROVED** [review]

**Comment by sayakpaul** [comment]
Failing tests are unrelated.

**Pull request merged**
