### PR TITLE
ControlNet from_single_file when already converted

### LINKED ISSUE #9976: ControlNet broken from_single_file
### Describe the bug

controlnet loader from_single_file was originally added via #4084
and method `ControlNet.from_single_file()` works for non-converted controlnets.

but for controlnets in safetensors format that contain already converted state_dict, it errors out.

its not reasonable to expect from user to know what is the internal dict structure of the controlnet safetensors file  
before he can use it.

even worse, some of the newer controlnets are distributed as single-file-only and are already in diffusers format  
which makes them impossible to load in difufsers.
for example: <https://huggingface.co/Laxhar/noob_openpose/tree/main>

this issue was already mentioned several times, each time closed as "works as designed"  
when in reality its just a failure that should be addressed as an issue.  
see #8474 #9208 #8614 as examples of previous issues

### Reproduction

scenario-1: works with non-converted controlnet
```python
import torch
from diffusers import ControlNetModel
from huggingface_hub import hf_hub_download
local_path = hf_hub_download(repo_id='Aptronym/SDNext', filename='ControlNet11/controlnet11Models_canny.safetensors')
cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16)
print(cn.__class__)
```

scenario-1: fails for majority of controlnets available on huggingface
```python
import torch
from diffusers import ControlNetModel
from huggingface_hub import hf_hub_download
local_path = hf_hub_download(repo_id='lllyasviel/sd_control_collection', filename='diffusers_xl_canny_small.safetensors')
cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16)
print(cn.__class__)
```
initial failure is nonsense
> OSError: stable-diffusion-v1-5/stable-diffusion-v1-5 does not appear to have a file named config.json.

whats making this worse is that SD15 and SDXL share the same `ControlNet` class which causes some
confusion on the base repo where to lookup config.
e.g,, here we're loading SDXL controlnet and error referrs to SD15 repo.

anyhow, trying to force correct config:
```py
cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16, config='diffusers/controlnet-canny-sdxl-1.0-small')
```

results in even worse nonsense failure during loading of state_dict:
> TypeError: is_floating_point(): argument 'input' (position 1) must be Tensor, not NoneType

### System Info

diffusers=0.32.0.dev0
python==3.12.3
torch==2.5.1+cu124

### Who can help?

@yiyixuxu @sayakpaul @DN6 @asomoza

### PR DESCRIPTION
**Pull request by hlky**
# What does this PR do?

This PR fixes #9976

ControlNet `from_single_file` is broken when used with a checkpoint that has already been converted:

```python
import torch
from diffusers import ControlNetModel
from huggingface_hub import hf_hub_download
local_path = hf_hub_download(repo_id='lllyasviel/sd_control_collection', filename='diffusers_xl_canny_small.safetensors')
cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16)
```

```python
OSError: stable-diffusion-v1-5/stable-diffusion-v1-5 does not appear to have a file named config.json.
```

https://github.com/huggingface/diffusers/blob/f6f7afa1d7c6f45f8568c5603b1e6300d4583f04/src/diffusers/loaders/single_file_utils.py#L457

https://github.com/huggingface/diffusers/blob/f6f7afa1d7c6f45f8568c5603b1e6300d4583f04/src/diffusers/loaders/single_file_utils.py#L65

The state dict is incorrectly being detected as `v1` Stable Diffusion because the checked keys for `controlnet` are for non-Diffusers format.

We add to checked keys for `controlnet` and add `controlnet_xl_large`, `controlnet_xl_mid` and `controlnet_xl_small` as the final types with `controlnet_xl` being used internally as a key to check for XL vs v1.

`controlnet_xl` keys are for Diffusers type checkpoints and need equivalents for non-converted checkpoints.

When fixed, or if we provide the correct config:

```python
cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16, config='diffusers/controlnet-canny-sdxl-1.0-small')
```

```python
TypeError: is_floating_point(): argument 'input' (position 1) must be Tensor, not NoneType
```

`convert_controlnet_checkpoint` called as part of `from_single_file` expects non-Diffusers type, the conversion function runs without error and returns an unusable state dict.

`convert_controlnet_checkpoint` is modified to return the checkpoint if it's already been converted.

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul @vladmandic

### CODE REVIEW

**Comment by vladmandic** [comment]
nice! did a quick test and seems fine.

**Comment by yiyixuxu** [comment]
thanks @hlky !
can you take a look here? @DN6

**Review by DN6 — APPROVED** [review]

**Comment by DN6** [comment]
Thanks @hlky. Would it be possible to do a follow up for the ControlNetXL small version?

**Comment by hlky** [comment]
Small, mid and large/full versions of ControlNet XL should all be covered, I've tested a couple checkpoints for each. I haven't found any ControlNet XL checkpoints that aren't already in Diffusers format but I'll add non-Diffusers keys to check in a follow up, and I'll check for something specific to detect small version - currently small is selected if known keys in medium and large versions aren't detected.

```python
import torch
from diffusers import ControlNetModel
from huggingface_hub import hf_hub_download

small = 'diffusers/controlnet-canny-sdxl-1.0-small'
mid = 'diffusers/controlnet-canny-sdxl-1.0-mid'
large = 'diffusers/controlnet-canny-sdxl-1.0'

for size in {small, mid, large}:
    local_path = hf_hub_download(repo_id=size, filename='diffusion_pytorch_model.fp16.safetensors')
    cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16)
    print(cn.__class__)

small = 'diffusers_xl_canny_small.safetensors'
mid = 'diffusers_xl_canny_mid.safetensors'
large = 'diffusers_xl_canny_full.safetensors'

for size in {small, mid, large}:
    local_path = hf_hub_download(repo_id="lllyasviel/sd_control_collection", filename=size)
    cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16)
    print(cn.__class__)

# xl large/full
local_path = hf_hub_download(repo_id="Laxhar/noob_openpose", filename="openpose_pre.safetensors")
cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16)
print(cn.__class__)

# v1
local_path = hf_hub_download(repo_id="lllyasviel/sd-controlnet-canny", filename="diffusion_pytorch_model.safetensors")
cn = ControlNetModel.from_single_file(local_path, torch_dtype=torch.float16)
print(cn.__class__)
```

**Pull request merged**
