### PR TITLE
Clear `ruff` Configuration

### PR DESCRIPTION
**Pull request by standardAI**
### Update
1. `C` in the select list includes only complex-structure (C901), so it is not meaningful to select `C` and ignore complex-structure (C901) at the same time, thus removing both.
2. When I remove import-shadowed-by-loop-var (F402) and undefined-local (F823) from the ignore list, `make style && make quality` shows nothing, also IMHO they can be useful, so they can be removed.
3. When I remove module-import-not-at-top-of-file (E402) and redefined-while-unused (F811) from the `__init__.py` files' ignore list, no error except one which I proposed to resolve at [my previous PR](https://github.com/huggingface/diffusers/pull/7720); so removed them.
4. `src/diffusers/utils/dummy_*.py` files don't need to ignore unused-import (F401), so removed that line.
5. `[tool.ruff.format]` section includes [generic default values](https://docs.astral.sh/ruff/configuration/#configuring-ruff), so removed.

### ~Upgrade~
~1. IMHO, [ambiguous-variable-name (E741)](https://docs.astral.sh/ruff/rules/ambiguous-variable-name/) might be very useful in terms of readability, why ignoring?
2. Setting `line-length = 119` and ignoring line-too-long (E501) applies on all codes but length of imports. I mean that ignoring line-too-long (E501) doesn't apply to the length of imports, so `line-length = 119` holds for imports. When I remove `line-length = 119`, because I thought it was unnecessary due to ignoring line-too-long (E501); then unsorted-imports (I001) applies for "larger" imports because the default is 88. [It seems that this is still being discussed](https://github.com/astral-sh/ruff/issues/3206). What to do here?
3. Why don't we benefit from all the power of `ruff` with its latest version? [It was pinned to `v0.1.5`](https://github.com/huggingface/diffusers/pull/6059), and [`v0.4.2` has just been announced](https://twitter.com/charliermarsh/status/1781051101661245483)! IMHO, there are [many more fun and beneficial rules](https://docs.astral.sh/ruff/rules/).~

@sayakpaul @yiyixuxu @DN6

### CODE REVIEW

**Comment by yiyixuxu** [comment]
can you take a look here? @sayakpaul

**Comment by sayakpaul** [comment]
Thanks for your proposal, but we don't want to make code styling ultra-sophisticated, to be honest. So, the simplest reasonable alternative works. Our efforts are better spent in improving the library design and then maintaining the things that come with it, TBH.

**Comment by standardAI** [comment]
OK, understood :+1:. I am withdrawing the upgrade part. What about the update part?

**Comment by standardAI** [comment]
I think this was a useless PR :smiling_face_with_tear:; thus, closing.

**Comment by tolgacangoz** [comment]
FYI: https://github.com/huggingface/transformers/pull/30932

**Pull request closed without merging**
