### PR TITLE
Add Pytorch 2.0 Efficient Attention Processors to some SD Pipelines

### PR DESCRIPTION
**Pull request by clarencechen**
Simplify implementation of Attend and Excite AttentionStore class

# What does this PR do?

This PR updates existing and adds new Attention Processors with Pytorch 2.0 Efficient Attention to several Stable Diffusion-based pipelines that implement custom Attention Processors in order to store and manipulate hidden attention maps inside the UNet. Despite the fused Pytorch 2.0 Efficient Attention kernel not directly exposing the Query-Key attention map, the required attention maps are extracted through substituting dummy value matrices to the fused function call, requiring at most one more Efficient Attention function call.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

@patrickvonplaten @sayakpaul

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
cc @yiyixuxu wdyt ?

**Comment by yiyixuxu** [comment]
@clarencechen 

thanks for adding the 2.0 processors! also, I think this PR cleaned up the code quite a bit 👍👍👍

@patrickvonplaten 

should we introduce a callback mechanism to attention processors so that people can get the attention maps out and do whatever they want with it? was this discussed somewhere?

**Comment by patrickvonplaten** [comment]
I don't think adding a callback mechanism to attention layers is a good idea this sounds very hacky :sweat_smile: or maybe I'm not 100% following what is meant here

**Comment by clarencechen** [comment]
@patrickvonplaten @yiyixuxu @sayakpaul I updated the expected slow test output for Attend-and-Excite at https://huggingface.co/datasets/hf-internal-testing/diffusers-images/discussions/22, as it is currently failing with the same output on both main and this branch. The images are perceptually very similar, with a few minor texture and edge discrepancies.

**Comment by yiyixuxu** [comment]
@clarencechen,

 oh thanks!
Can you share the comparison images?

**Comment by clarencechen** [comment]
old
new
Here are the two images, side by side.

**Comment by clarencechen** [comment]
@yiyixuxu At this point I'm just rebasing this PR on changes that are getting merged into main. I'll run the examples from the Gradio demo you mentioned and post the results here.

**Comment by yiyixuxu** [comment]
@clarencechen
 
ohhh!!!!! thanks so much 😇😇😇😇

sorry, I have been so slow on this PR 😣😣😣😣 will do a review today and merge ASAP if the examples match

**Comment by yiyixuxu** [comment]
@clarencechen 
let's make sure all the tests pass too! otherwise, it looks good I think :)

**Comment by clarencechen** [comment]
@yiyixuxu 

When running this snippet of code:
```
import torch
from PIL import Image

from diffusers import StableDiffusionAttendAndExcitePipeline

attend_and_excite_test_inputs = [
    {"prompt": "A mouse and a red car", "token_indices": [2, 6], "seed": 2098},
    {"prompt": "A horse and a dog", "token_indices": [2, 5], "seed": 123},
    {"prompt": "A painting of an elephant with glasses", "token_indices": [5, 7], "seed": 123},
    {"prompt": "A playful kitten chasing a butterfly in a wildflower meadow", "token_indices": [3, 6, 10], "seed": 123},
    {"prompt": "A grizzly bear catching a salmon in a crystal clear river surrounded by a forest", "token_indices": [2, 6, 15], "seed": 123},
    {"prompt": "A pod of dolphins leaping out of the water in an ocean with a ship on the background", "token_indices": [4, 16], "seed": 123}
]


pipe = StableDiffusionAttendAndExcitePipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4", safety_checker=None, torch_dtype=torch.float16
)
pipe.to("cuda")

def run(
    prompt: str,
    token_indices: list[int],
    seed: int = 0,
    num_inference_steps: int = 50,
    guidance_scale: float = 7.5,
    scale_factor: int = 20,
    thresholds: dict[int, float] = {
        10: 0.5,
        20: 0.8,
    },
    max_iter_to_alter: int = 25,
) -> Image.Image:
    generator = torch.Generator(device="cpu").manual_seed(seed)
    return pipe(
        prompt=prompt,
        token_indices=token_indices,
        guidance_scale=guidance_scale,
        generator=generator,
        num_inference_steps=num_inference_steps,
        max_iter_to_alter=max_iter_to_alter,
        thresholds=thresholds,
        scale_factor=scale_factor,
    ).images[0]

output_images = [run(**args) for args in attend_and_excite_test_inputs]
```
I get the following outputs on my PR branch:
attend_and_excite_samples_0
attend_and_excite_samples_1
attend_and_excite_samples_2
attend_and_excite_samples_3
attend_and_excite_samples_4
attend_and_excite_samples_5
Compared to the following outputs on main:
main_attend_and_excite_samples_0
main_attend_and_excite_samples_1
main_attend_and_excite_samples_2
main_attend_and_excite_samples_3
main_attend_and_excite_samples_4
main_attend_and_excite_samples_5

**Comment by clarencechen** [comment]
@yiyixuxu I also ran the following tests, returning zero failures:
```
RUN_SLOW=1 python -m pytest tests/pipelines/stable_diffusion_2/test_stable_diffusion_attend_and_excite.py
RUN_SLOW=1 python -m pytest tests/pipelines/stable_diffusion/test_stable_diffusion_sag.py
```

**Comment by yiyixuxu** [comment]
@clarencechen, 
do you have any idea why the results are not identical?

**Comment by clarencechen** [comment]
@yiyixuxu My first suspicion is that these differences are due to numerical discrepancies introduced by vectorizing and moving operations to use fp16 Tensors in the GPU. I'll rerun the examples again without the Attend-and-Excite refactoring commit and post the results again later today.

**Comment by clarencechen** [comment]
@yiyixuxu Sorry for the long wait, but here are the results after reverting the Attend-and-Excite refactoring commit:

main_attend_and_excite_samples_0
main_attend_and_excite_samples_1
main_attend_and_excite_samples_2
main_attend_and_excite_samples_3
main_attend_and_excite_samples_4
main_attend_and_excite_samples_5

**Pull request closed without merging**
