### PR TITLE
Multi controlnet draft

### PR DESCRIPTION
**Pull request by patrickvonplaten**
The following draft works with the following code:

```py
from diffusers import (
    ControlNetModel,
    StableDiffusionControlNetPipeline,
    UniPCMultistepScheduler,
)


controlnet_canny = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-canny", torch_dtype=torch.float16)
controlnet_normal = ControlNetModel.from_pretrained("lllyasviel/sd-controlnet-normal", torch_dtype=torch.float16)
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5", controlnet=[controlnet_canny, controlnet_normal], torch_dtype=torch.float16
)
pipe.to("cuda")
pipe.to("cpu")
print(pipe.device)
```

### CODE REVIEW

**Comment by sayakpaul** [comment]
Closing in favor of https://github.com/huggingface/diffusers/pull/2627

Follow the discussion here: https://github.com/huggingface/diffusers/issues/2556#issuecomment-1461879052

**Comment by HyeonHo99** [comment]
Hi, @patrickvonplaten can you check if pipe.enable_xformers_memory_efficient_attention() is supported in the above code you wrote? Thank you

**Comment by sayakpaul** [comment]
@HyeonHo99 it should be possible. We recently merged https://github.com/huggingface/diffusers/pull/2627 which used the design introduced by @patrickvonplaten in this PR. 

Could you check if you can enable it? Be sure to install `diffusers` from source: `pip install git+https://github.com/huggingface/diffusers`.

Here you can find an example of MultiControlNet.

**Comment by patrickvonplaten** [comment]
@HyeonHo99 ,

Yes it's enabled :-) You should be able to follow the guides here: https://huggingface.co/docs/diffusers/optimization/fp16#memory-efficient-attention

**Comment by HyeonHo99** [comment]
Thanks a lot, @sayakpaul , @patrickvonplaten .
I checked that it works without problems.

**Pull request closed without merging**
