### PR TITLE
Don't call the Hub if `local_files_only` is specifiied

### PR DESCRIPTION
**Pull request by patrickvonplaten**
Fixes: https://github.com/huggingface/diffusers/issues/1970

cc @lstein @keturn

### CODE REVIEW

**Comment by lstein** [comment]
This is good news. Thanks. Too late to get into 0.12, I guess?

**Comment by patrickvonplaten** [comment]
> This is good news. Thanks. Too late to get into 0.12, I guess?

Actually, ok for me make a patch release for 0.12.1 since we kind of introduced this bug ourselves. cc @patil-suraj @pcuenca wdyt?

**Comment by lstein** [comment]
> > This is good news. Thanks. Too late to get into 0.12, I guess?
> 
> Actually, ok for me make a patch release for 0.12.1 since we kind of introduced this bug ourselves. cc @patil-suraj @pcuenca wdyt?

Much obliged. This is allow me to run textual inversion on my multi-GPU, but firewalled, machine.

**Comment by patrickvonplaten** [comment]
Patch release is out: https://github.com/huggingface/diffusers/releases/tag/v0.12.1

**Comment by pcuenca** [comment]
@patrickvonplaten Awesome, thanks!

**Comment by lstein** [comment]
Thanks so much!

**Pull request merged**
