### PR TITLE
support v prediction in other schedulers

### PR DESCRIPTION
**Pull request by patil-suraj**
This PR adds v-prediction support to `PNDMScheduler`, `LMSDiscreteScheduler` and `EulerAncestralDiscreteScheduler`.

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
Could we use this PR to also add tests to all the schedulers?

**Comment by natolambert** [comment]
The simple test I had from the original v-prediction pr
```
def test_prediction_type(self):
        for prediction_type in ["epsilon", "sample", "velocity"]:
            self.check_over_configs(prediction_type=prediction_type)
```

I can add ddpm to this or in another pr if it's not done yet.

**Review by patrickvonplaten — APPROVED** [review]
Nice!

**Comment by alexisrolland** [comment]
Hi, is there a documentation somewhere describing what it is / how to use v-prediction? Or is this automatically used?

**Comment by patil-suraj** [comment]
It's automatically used based on the value in the `scheduler_config` file, cf https://huggingface.co/stabilityai/stable-diffusion-2-1/blob/main/scheduler/scheduler_config.json#L9

You can also pass `prediction_type="v_prediction` when instantiating/loading the scheduler.

**Pull request merged**
