### PR TITLE
[PNDM Scheduler] format timesteps attrs to np arrays

### PR DESCRIPTION
**Pull request by NouamaneTazi**
Before this fix, the concerned attributes were lists, and lists don't get formatted in `self.set_format`

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Very cool PR @NouamaneTazi - thanks a lot! 

This looks good to me - what do you think @anton-l @patil-suraj ? :-)

**Comment by patrickvonplaten** [comment]
@NouamaneTazi - do you think we could also add a test to https://github.com/huggingface/diffusers/blob/eb64e201b8cf69bb009783057327b4122ec53224/tests/test_scheduler.py#L368 that showcases what didn't work before but works now? :-)

**Review by patil-suraj — APPROVED** [review]
Great catch @NouamaneTazi , thanks for the fix!
As Patrick said, would be nice to add a test for this!

**Comment by patil-suraj** [comment]
@patrickvonplaten this is exactly what I had to modify for the JAX PNDM, had to convert all lists to arrays.

**Comment by NouamaneTazi** [comment]
I tried to add a test for the scheduler formatting. Lmk if it's good enough for you @patrickvonplaten @patil-suraj

**Comment by NouamaneTazi** [comment]
Also should I run `black` to fix the styling? Because `make fixup` doesn't work and `make style` formats 15 files 😅

**Comment by patrickvonplaten** [comment]
Regarding `make style` which version of isort and black do you have?

**Comment by patrickvonplaten** [comment]
Just ran `make style` with `black 22.3.0` and `isort 5.10.1`. Could you check whether you have the same versions? :-) This should only have re-styled two files :-) 

Thanks for the amazing PR anyways! This is super helpful :heart:

**Comment by NouamaneTazi** [comment]
It seems an issue with `black`'s version. Indeed when I tried `make style` with the `black 22.3.0` it formats the files correctly. But when I use `black 22.6.0` it formats 14 files:
```
black --preview examples scripts src tests utils
reformatted src/diffusers/schedulers/scheduling_sde_vp.py
reformatted src/diffusers/pipelines/ddim/pipeline_ddim.py
reformatted src/diffusers/schedulers/scheduling_utils.py
reformatted src/diffusers/schedulers/scheduling_ddim.py
reformatted src/diffusers/models/unet_2d_condition.py
reformatted src/diffusers/schedulers/scheduling_ddpm.py
reformatted src/diffusers/models/unet_2d.py
reformatted src/diffusers/utils/logging.py
reformatted examples/inference/image_to_image.py
reformatted examples/inference/inpainting.py
reformatted src/diffusers/pipeline_utils.py
reformatted src/diffusers/schedulers/scheduling_pndm.py
reformatted src/diffusers/pipelines/latent_diffusion/pipeline_latent_diffusion.py
reformatted src/diffusers/models/unet_blocks.py

All done! ✨ 🍰 ✨
14 files reformatted, 67 files left unchanged.
```

**Comment by patrickvonplaten** [comment]
Ah we should then update black overall in the repo I think -> @anton-l let's maybe move to `black=22.6.0` no?

**Pull request merged**
