### PR TITLE
Use `torch` in `get_2d_rotary_pos_embed`

### PR DESCRIPTION
**Pull request by hlky**
# What does this PR do?

Refactors `get_2d_rotary_pos_embed` to use `torch` instead of `numpy`, and adds `device` argument so that tensors can be created on e.g. `cuda`.

Usage of `get_2d_rotary_pos_embed` in HunyuanDiT pipelines is updated to pass `device`.

`torch` and `numpy` versions match numerically.

<details>
  <summary>Reproduction</summary>

  ```python
from diffusers.models.embeddings import get_2d_rotary_pos_embed
import torch


def get_resize_crop_region_for_grid(src, tgt_size):
    th = tw = tgt_size
    h, w = src

    r = h / w

    # resize
    if r > 1:
        resize_height = th
        resize_width = int(round(th / h * w))
    else:
        resize_width = tw
        resize_height = int(round(tw / w * h))

    crop_top = int(round((th - resize_height) / 2.0))
    crop_left = int(round((tw - resize_width) / 2.0))

    return (crop_top, crop_left), (crop_top + resize_height, crop_left + resize_width)


height, width = 1024, 1024
height = int((height // 16) * 16)
width = int((width // 16) * 16)
num_attention_heads = 16
attention_head_dim = 88
patch_size = 2
inner_dim = num_attention_heads * attention_head_dim
grid_height = height // 8 // patch_size
grid_width = width // 8 // patch_size
base_size = 512 // 8 // patch_size
grid_crops_coords = get_resize_crop_region_for_grid(
    (grid_height, grid_width), base_size
)
image_rotary_emb_np = get_2d_rotary_pos_embed(
    inner_dim // num_attention_heads,
    grid_crops_coords,
    (grid_height, grid_width),
    output_type="np",
)

image_rotary_emb = get_2d_rotary_pos_embed(
    inner_dim // num_attention_heads,
    grid_crops_coords,
    (grid_height, grid_width),
    output_type="pt",
)

torch.testing.assert_close(image_rotary_emb[0], image_rotary_emb_np[0])
torch.testing.assert_close(image_rotary_emb[1], image_rotary_emb_np[1])
```

</details>

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul @yiyixuxu

### CODE REVIEW

**Comment by hlky** [comment]
[Downstream usage](https://github.com/search?q=%22from+diffusers.models.embeddings+import+get_2d_rotary_pos_embed%22&type=code) - should be ok, this was already returning `torch.Tensor` and integrations are handling device casting

**Comment by yiyixuxu** [comment]
did we run hunyuan test?

**Comment by hlky** [comment]
Running now 
https://github.com/huggingface/diffusers/actions/runs/12262870196/job/34213155782

**Comment by hlky** [comment]
Checkpoint used in the slow test is 404

https://github.com/huggingface/diffusers/blob/49a914347974abbc21cffd3580680485194783f7/tests/pipelines/hunyuan_dit/test_hunyuan_dit.py#L320

https://huggingface.co/XCLiu/HunyuanDiT-0523

**Comment by hlky** [comment]
There a slight change to the image.

```python
import torch
from diffusers import HunyuanDiTPipeline
pipe = HunyuanDiTPipeline.from_pretrained(
    "Tencent-Hunyuan/HunyuanDiT-Diffusers", torch_dtype=torch.float16
)
pipe.to("cuda")
prompt = "An astronaut riding a horse"
image = pipe(prompt, generator=torch.Generator("cuda").manual_seed(0)).images[0]
```

Main:
main

PR:
pr

**Comment by hlky** [comment]
Unclear why though, I'll run the test again.

```python
>>> torch.abs(image_rotary_emb[0].flatten() - image_rotary_emb_np[0].flatten()).max()
tensor(0.)
>>> torch.abs(image_rotary_emb[1].flatten() - image_rotary_emb_np[1].flatten()).max()
tensor(0.)
```

**Comment by hlky** [comment]
Yes there's a very minor difference when we create the tensors on CUDA.

```
>>> torch.abs(image_rotary_emb[0].cpu().flatten() - image_rotary_emb_np[0].flatten()).max()
tensor(1.7881e-07)
>>> torch.abs(image_rotary_emb[1].cpu().flatten() - image_rotary_emb_np[1].flatten()).max()
tensor(1.7881e-07)
```

It's below PyTorch's tolerance for float32 though https://pytorch.org/docs/stable/testing.html

cc @yiyixuxu

**Comment by hlky** [comment]
I've added `output_type` and a deprecation message as in #10156

**Review by yiyixuxu — APPROVED** [review]
thanks @hlky !

**Comment by yiyixuxu** [comment]
It's a bit of a surprise that something numerically < 1e-7 would cause a visual difference like this, but it is not worse, is it? my eyes are not very good with it

**Comment by hlky** [comment]
It is surprising, we can run more tests before merge if you want, the visual difference is acceptable imo.

**Comment by yiyixuxu** [comment]
thanks @hlky great work as always:) 
I think this pipeline might not be completely deterministic to begin with (but don't have time to look into now)

**Pull request merged**
