### PR TITLE
fix: Fixed a wrong decorator by modifying it to `@classmethod`

### PR DESCRIPTION
**Pull request by Sai-Suraj-27**
# What does this PR do?
Fixes a wrong decorator.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@sayakpaul

### CODE REVIEW

**Comment by DN6** [comment]
Hi @Sai-Suraj-27 this affects a lot of the loading logic in diffusers which assumes the method is a static method.

**Comment by Sai-Suraj-27** [comment]
> Hi @Sai-Suraj-27 this affects a lot of the loading logic in diffusers which assumes the method is a static method.

Hey, @DN6. Thanks for the review. After looking into the code further, I understood that it is supposed to be a `staticmethod`, but the argument name `cls`, we are now using makes it very confusing and even `Pylint` that I am using is also showing warnings for that line. So, i think the best thing here would be to change the argument name from `cls` to something else like `input_class` or may be `target_class`?

```Python
@staticmethod
def _get_init_keys(input_class):
    return set(dict(inspect.signature(input_class.__init__).parameters).keys())
```
Please let me know your opinion, I will update with a new commit. Thank you.

**Comment by DN6** [comment]
@Sai-Suraj-27 Sure we can change that to be more clear.

**Review by DN6 — APPROVED** [review]
Thanks

**Pull request merged**
