### PR TITLE
multi-subject-dreambooth-inpainting with 🤗  datasets

### PR DESCRIPTION
**Pull request by gzguevara**
# What does this PR do?

This PR is a training example. It shows how to implement Dreambooth for multiple subjects for inpainting models. Moreover, the project shows how to  create 🤗 datasets for inpainting with custom masks, which is a feature that has often been requested in the forum. The README.md includes a link to a w&b report to show training results.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@patrickvonplaten and @sayakpaul

### CODE REVIEW

**Comment by sayakpaul** [comment]
Thanks so much for your contributions. Could you please run the quality checks so that the CI is green?

**Comment by gzguevara** [comment]
@sayakpaul Thanks! Unfortunately, I cannot figure locate the error. I have ordered my imports as required. I have followed the example training scripts. However, it keeps failing. Do you have any suggestion?

**Comment by gzguevara** [comment]
@sayakpaul CI is green is green now! Thanks!

**Comment by sayakpaul** [comment]
Thanks much for your valuable contributions.

**Pull request merged**
