### PR TITLE
[WIP] Testing rc1.

### PR DESCRIPTION
**Pull request by Narsil**

### CODE REVIEW

**Comment by Narsil** [comment]
@patrickvonplaten

**Comment by patrickvonplaten** [comment]
Awesome! No problems on the diffusers side then with the new safetensors release

**Comment by patrickvonplaten** [comment]
Can we do these changes here as well: https://github.com/huggingface/diffusers/pull/2046/files#r1123384186 so that this PR triggers the slow tests as well

**Comment by Narsil** [comment]
Are those errors worrying ?

**Comment by Narsil** [comment]
Something must be off in the CI, test is green on regular safetensors==0.2.8 and 0.3.0rc1  on my machine..

**Comment by patrickvonplaten** [comment]
Closing as testing worked!

**Pull request closed without merging**
