### PR TITLE
IP-Adapter support for StableDiffusionXLControlNetInpaintPipeline

### LINKED ISSUE #6866: IP-Adapter support for StableDiffusionXLControlNetInpaintPipeline
Hello 👋 

**Is your feature request related to a problem? Please describe.**
`StableDiffusionXLControlNetPipeline` and `StableDiffusionXLControlNetImg2ImgPipeline` support IP-Adapter thanks to https://github.com/huggingface/diffusers/pull/6573. However, it is not added for `StableDiffusionXLControlNetInpaintPipeline` pipeline as I see. It would be very useful to have ControlNet inpainting pipeline support IP-Adapters.

**Describe the solution you'd like.**
IP-Adapter support for `StableDiffusionXLControlNetInpaintPipeline` as in `StableDiffusionXLControlNetPipeline` and `StableDiffusionXLControlNetImg2ImgPipeline`

### PR DESCRIPTION
**Pull request by rootonchair**
# What does this PR do?

Fixes #6866 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by yiyixuxu** [comment]
thanks for the PR!
I think we need to make updates based on https://github.com/huggingface/diffusers/pull/6868

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Review by sayakpaul — APPROVED** [review]
Lovely! Do we have any example code snippet that shows the results with this modification?

**Comment by tontan2545** [comment]
Hi, I would like to request to extend `IPAdapterMixin` to the `StableDiffusionXLControlNetInpaintPipeline` class so it could inherit `load_ip_adapter` property

```python
class StableDiffusionXLControlNetInpaintPipeline(
    DiffusionPipeline, 
    StableDiffusionXLLoraLoaderMixin, 
    FromSingleFileMixin, 
+    IPAdapterMixin
):

r"""
    Pipeline for text-to-image generation using Stable Diffusion XL.

    This model inherits from [`DiffusionPipeline`]. Check the superclass documentation for the generic methods the
    library implements for all the pipelines (such as downloading or saving, running on a particular device, etc.)

    The pipeline also inherits the following loading methods:
        - [`~loaders.StableDiffusionXLLoraLoaderMixin.load_lora_weights`] for loading LoRA weights
        - [`~loaders.StableDiffusionXLLoraLoaderMixin.save_lora_weights`] for saving LoRA weights
        - [`~loaders.FromSingleFileMixin.from_single_file`] for loading `.ckpt` files
+        - [`~loaders.IPAdapterMixin.load_ip_adapter`] for loading IP Adapters
...
"""
```

For code snippet that shows the result as @sayakpaul requested, it looks kinda like this after the modification.

```python
image_encoder = CLIPVisionModelWithProjection.from_pretrained(
            "h94/IP-Adapter",
            subfolder="models/image_encoder",
            torch_dtype=torch.float16,
            cache_dir=CACHE_DIR
).to(device)


pipe = StableDiffusionXLControlNetInpaintPipeline.from_pretrained(
            weight_path,
            cache_dir=CACHE_DIR,
            vae=sd_vae,
            controlnet=controlnet, 
            image_encoder=image_encoder,
            torch_dtype=torch.float16
).to(device)
        
pipe.load_ip_adapter("h94/IP-Adapter", subfolder="sdxl_models", weight_name="ip-adapter-plus_sdxl_vit-h.safetensors", cache_dir=CACHE_DIR)

images = pipe(
            image=room_image,
            ip_adapter_image=style_image, 
            control_image=control_image, 
            mask_image=mask_image,
            ...other-params
).images
```

**Comment by yiyixuxu** [comment]
oh thanks!! @tontan2545 
I read your comment too fast and I thought it was a code example provided by the OP

thanks for opening a PR to fix this!

**Pull request merged**
