### PR TITLE
Update pipeline_animatediff_video2video.py

### PR DESCRIPTION
**Pull request by AbhinavGopal**
# What does this PR do?

In AnimatediffVideoToVideoPipeline, video might be none because of latents getting passed in. In this case, we should check if video is none before indexing inside it in prepare_latents.

## Before submitting
- [X] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [X] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@sayakpaul @yiyixuxu @DN6

### CODE REVIEW

**Comment by AbhinavGopal** [comment]
@a-r-r-o-w might have context as well

**Comment by a-r-r-o-w** [comment]
Thanks for the PR. I just tested and it does fix the issue where previously it was not possible to use latents as input. I think it might help to add a test for this as well. @DN6

**Comment by DN6** [comment]
Thanks! Yes agree with @a-r-r-o-w  could we add a test as well.

**Comment by AbhinavGopal** [comment]
done, @DN6 and @a-r-r-o-w

**Review by a-r-r-o-w — APPROVED** [review]
Looks good, LGTM! Thanks for reporting the error

**Comment by a-r-r-o-w** [comment]
cc @DN6

Failing test seems unrelated. As it is a problem with core diffusers, speedy merge would be appreciated :)

**Review by DN6 — APPROVED** [review]

**Pull request merged**
