### PR TITLE
Ensure the `temb` kwarg is not passed unexpectedly to attn

### PR DESCRIPTION
**Pull request by lsb**
WIP.

Token embeddings can be passed to attention processors. *Some* attention processors expect this. In Python, an unexpected keyword causes an error. Using a sliced attention processor instead of the default, in SD, reveals this bug.

For example, note this call to the attention processor: https://github.com/huggingface/diffusers/blob/v0.25.0/src/diffusers/models/unet_2d_blocks.py#L624

This PR fixes one instance of one attention processor getting passed a token_embedding, by declaring an unused parameter that gets ignored. This was a temporary band-aid I made.

TODO: (patches welcome!)

[] Check all of the other attention processors for this same problem (a few other attention processors might have this bug, from a quick visual scan)
[] Throw an error in each attention processor that gets a non-None `temb` that wasn't expecting it (maybe? open to other design ideas)

# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by lsb** [comment]
TODO: put this failing code into a test

```
from diffusers import DiffusionPipeline
from diffusers.models.attention_processor import SlicedAttnProcessor

pipe = DiffusionPipeline.from_pretrained(
    "hf-internal-testing/tiny-stable-diffusion-torch",
)

pipe(prompt="a trout", num_inference_steps=1).images[0].save("trout1.png")

pipe.vae.set_attn_processor(SlicedAttnProcessor(1))

pipe(prompt="a trout", num_inference_steps=1).images[0].save("trout2.png")
```

**Comment by lsb** [comment]
The error message:

```
Traceback (most recent call last):
  File "/Users/lsb/jupyterlab/sliced-attention-temb.py", line 12, in <module>
    pipe(prompt="a trout", num_inference_steps=1).images[0].save("trout2.png")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 1042, in __call__
    image = self.vae.decode(latents / self.vae.config.scaling_factor, return_dict=False, generator=generator)[
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 304, in decode
    decoded = self._decode(z).sample
              ^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 275, in _decode
    dec = self.decoder(z)
          ^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/diffusers/models/autoencoders/vae.py", line 333, in forward
    sample = self.mid_block(sample, latent_embeds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/diffusers/models/unet_2d_blocks.py", line 624, in forward
    hidden_states = attn(hidden_states, temb=temb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lsb/jupyterlab/.direnv/python-3.11.7/lib/python3.11/site-packages/diffusers/models/attention_processor.py", line 527, in forward
    return self.processor(
           ^^^^^^^^^^^^^^^
TypeError: SlicedAttnProcessor.__call__() got an unexpected keyword argument 'temb'
```

**Comment by yiyixuxu** [comment]
should have already fixed here https://github.com/huggingface/diffusers/pull/6915

**Comment by lsb** [comment]
It is! Thanks for landing this

**Pull request closed without merging**
