### PR TITLE
Init for korean docs

### PR DESCRIPTION
**Pull request by seriousran**
As explained by @patrickvonplaten the docs are divided into en and ko like transformer docs. https://github.com/huggingface/diffusers/issues/1779

I started by translating the first few pages.
Thank you for reviewing and commenting.

### CODE REVIEW

**Comment by ymjoo827-neubla** [comment]
If you add [TRANSLATING.md](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md) like transformers to docs/, it would be helpful for other translators to refer to.

**Comment by patrickvonplaten** [comment]
Hey @ymjoo827-neubla,

You're 100% right, would you like to open a PR to add this doc to `diffusers` as well? :-)

**Comment by patrickvonplaten** [comment]
Great job @seriousran! 

Let's merge this now and then the docs could be further improved in a follow-up PR I think? :-)

**Comment by patrickvonplaten** [comment]
Also cc @yiyixuxu FYI

**Comment by seriousran** [comment]
Surely I'm going to improve docs with people who can translate and verify. And I've opened the PR for [TRANSLATING.md](https://github.com/huggingface/transformers/blob/main/docs/TRANSLATING.md).

**Pull request merged**
