### PR TITLE
Better attn op for SD v2.0 - hardcoded - don't merge

### PR DESCRIPTION
**Pull request by Dango233**
Some of the xformers versions will dispatch the memory attention to `MemoryEfficientAttentionFlashAttentionOp`, which is significantly slower than `MemoryEfficientAttentionCutlassOp` on SD 2.0/2.1.

I observe following performance increases by forcing the use ofMemoryEfficientAttentionCutlassOp.

A 15%~100% increase in performance is observed depending on the precision, resolution, and the GPU architecture the code is running on.

### CODE REVIEW

**Review by patil-suraj — COMMENTED** [review]
Thanks a lot for the PR, this looks good! Going to test it now :) 

Also think we can make this an argument of `set_use_memory_efficient_attention_xformers` method, so users can choose the op, instead of always fixing it.

**Comment by kashif** [comment]
BTW xformers comes with a nice helper which selects the best one: https://github.com/facebookresearch/xformers/blob/189828ce12de9bff807a15134a53c48a7f2da3fe/xformers/ops/memory_efficient_attention.py#L954

my understanding was they might remove the cutlas based methods once the triton ones are faster...

**Comment by blefaudeux** [comment]
@Dango233 I would not hardcode anything here based on anecdata, your results prove that the heuristics in xformers are not perfect (@fmassa @danthe3rd) but in general the mechanism is sound, and by bypassing it you open up for a lot of issues (for instance not all kernels are compatible with all matrix dimensions, somebody will have to debug that one day).

At the very least I would use a sane default in diffusers (ie: default to xformers choosing the op), so that people who don't want to dive in there are sparred

**Comment by Dango233** [comment]
Makes sense! I'll turn this into a draft :D

**Pull request closed without merging**
