### PR TITLE
aura: add lora loading support via peft, copied from SD3

### PR DESCRIPTION
**Pull request by bghira**
# What does this PR do?

This is a barebones PR to add LoRA loading support for AuraFlow models.

cc @sayakpaul i know there's no unit tests added etc but wanted to get some eyes on it since it's currently in use by users for training.

### CODE REVIEW

**Comment by sayakpaul** [comment]
This is looking nice. Thank you. 

Going to keep it open till https://github.com/huggingface/diffusers/pull/8774 is merged because it will help it make unified much. 

One #8774 is merged will update here.

**Comment by sayakpaul** [comment]
@bghira you didn’t really have to close it. #8774 is going to be merged very soon pending another review from @DN6 and then this could have rebased more easily.

**Comment by bghira** [comment]
it actually never really panned out to make the model trainable due to issues embedded into it during pretraining. there is no need to have LoRAs loadable since they cannot be trained.

**Comment by sayakpaul** [comment]
Oh thanks for explaining.

**Comment by bghira** [comment]
it might come back in weeks at which point i can reopen

**Pull request closed without merging**
