### PR TITLE
add torch_xla support in pipeline_stable_audio.py

### PR DESCRIPTION
**Pull request by fancy45daddy**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [x] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by hlky — APPROVED** [review]
Thanks! 🤗

**Comment by hlky** [comment]
@fancy45daddy It's an indicator for other reviewers that this PR is close to being merged, someone else will take a look then we'll get it in!

**Comment by fancy45daddy** [comment]
@hlky Do you have the ability to merge? I try to submit a lot of pr. But none of them are actually merge. How to accelerate the merge process? I need the code for my torch_xla project.

**Comment by hlky** [comment]
@fancy45daddy You can ping me on your other PRs for review if you like 🤗

**Pull request merged**
