### PR TITLE
Adding TextualInversionLoaderMixin for the controlnet_inpaint_sd_xl pipeline 

### PR DESCRIPTION
**Pull request by jschoormans**
# What does this PR do?
The pipeline controlnet_inpaint_sd_xl pipeline contained the textual_inversion loading logic, but did not load the TextualInversionLoaderMixin yet. 

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by sayakpaul** [comment]
Thanks for the PR. Could you share some code and results where this is beneficial?

**Comment by jschoormans** [comment]
Hi Sayak, 

When using this pipeline with a textual inversion (and without this commit):

`self.pipe.load_textual_inversion()`

I have this error: 

`AttributeError: 'StableDiffusionXLControlNetInpaintPipeline' object has no attribute 'load_textual_inversion'`


Adding TextualInversionMixIn fixes this - and this seems in line with the other controlnet and sdxl pipelines.

**Comment by sayakpaul** [comment]
Yes, that is fine. I was curious see the results with that i.e., Textual Inversion + SDXL ControlNet Inpainting (with your fix)

**Comment by yiyixuxu** [comment]
can we fix the tests?

**Comment by jschoormans** [comment]
Hi yiyixuxu, 
I think there was a formatting error, (extra newline) but I am not sure. I have made a new commit which fixes that. I don't really know what else would be wrong. 
I use this pipeline to do inpainting with loras I have trained, and for that I also add the textual inversion part. It seems to be the only pipeline that was missing this part.

**Comment by yiyixuxu** [comment]
hi:
can you run `make fix-copies` and `make style`?

**Comment by yiyixuxu** [comment]
looks like `make style` made changes to files that you did not touch in this PR
can you update the quality dependency? `pip install -e ".[quality]"`

**Comment by jschoormans** [comment]
hmm I tried to checkout the previous commit, did the pip install and ran the make again.

**Comment by yiyixuxu** [comment]
@jschoormans 
thanks for your contribution! and sorry for the inconvenience

**Comment by jschoormans** [comment]
Thank you!!!

**Pull request merged**
