### PR TITLE
split tests_modeling_utils

### LINKED ISSUE #184: Split `tests_modeling_utils`
The function https://github.com/huggingface/diffusers/blob/main/tests/test_modeling_utils.py becomes too long which makes it a bit cumbersome to only test part of the code. 

We should at least move all the pipeline tests into a new class and probably also also move the individual model testing classes, such as https://github.com/huggingface/diffusers/blob/051b34635fda2fc310898a6a602c89be8663b77f/tests/test_modeling_utils.py#L539 into their own files.

### PR DESCRIPTION
**Pull request by kashif**
Fixes #184

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Thanks a lot @kashif - this looks nice!

**Comment by kashif** [comment]
Thanks! Let me double check if I didnt screw anything up in the merge... give me a minute!

**Comment by kashif** [comment]
ok fixed the merge! all good from my end too!

**Comment by patrickvonplaten** [comment]
@anton-l can you check and then merge?

**Review by anton-l — APPROVED** [review]
Thanks a lot @kashif, looks very clean!

**Pull request merged**
