### PR TITLE
[Pipeline] Adding BoxDiff to community examples

### PR DESCRIPTION
**Pull request by zjysteven**
# What does this PR do?

This PR adds a pipeline for [BoxDiff](https://github.com/showlab/BoxDiff) (ICCV'23), a training-free controlled generation technique with bounding boxes. The pipeline is implemented in the self-contained `examples/community/pipeline_stable_diffusion_boxdiff.py`, meaning that this is the only change and no code in `scr/diffusers/` is ever modified by this PR.

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation). **Yes I updated the README for community examples to showcase the usage.**
- [ ] Did you write any new necessary tests? **Tests aren't necessary here since it's just a self-contained community pipeline.**

## Who can review?

Since this is a pipeline contribution I'm tagging @sayakpaul @yiyixuxu @DN6 for review

### CODE REVIEW

**Comment by yiyixuxu** [comment]
thank you!

**Comment by KeyaoZhao** [comment]
Hello，I tried the BoxDiff with SDXL model, but got:
Traceback (most recent call last):
  File "/workspace/diffusers/examples/inference/box.py", line 42, in <module>
    images = pipe(
             ^^^^^
  File "/opt/conda/envs/main/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/diffusers/examples/inference/pipeline_stable_diffusion_boxdiff.py", line 1569, in __call__
    noise_pred_text = self.unet(
                      ^^^^^^^^^^
  File "/opt/conda/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/main/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1156, in forward
    aug_emb = self.get_aug_embed(
              ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/main/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 977, in get_aug_embed
    if "text_embeds" not in added_cond_kwargs:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
Do you have any solution?

**Comment by zjysteven** [comment]
> Hello，I tried the BoxDiff with SDXL model, but got: Traceback (most recent call last): File "/workspace/diffusers/examples/inference/box.py", line 42, in images = pipe( ^^^^^ File "/opt/conda/envs/main/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/workspace/diffusers/examples/inference/pipeline_stable_diffusion_boxdiff.py", line 1569, in **call** noise_pred_text = self.unet( ^^^^^^^^^^ File "/opt/conda/envs/main/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/opt/conda/envs/main/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1156, in forward aug_emb = self.get_aug_embed( ^^^^^^^^^^^^^^^^^^^ File "/opt/conda/envs/main/lib/python3.11/site-packages/diffusers/models/unets/unet_2d_condition.py", line 977, in get_aug_embed if "text_embeds" not in added_cond_kwargs: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: argument of type 'NoneType' is not iterable Do you have any solution?

As the name suggests, `pipeline_stable_diffusion_boxdiff.py` only supports SD models rather than SDXL. You will need to adapt the code to make it work with SDXL, which I imagine wouldn't be too difficult.

**Comment by yiyixuxu** [comment]
@zjysteven @zjysteven 
welcome to send a PR!

**Pull request merged**
