### PR TITLE
[docs]add coreml.mdx

### PR DESCRIPTION
**Pull request by yiyixuxu**
porting this post to doc https://huggingface.co/blog/diffusers-coreml

### CODE REVIEW

**Review by pcuenca — COMMENTED** [review]
This is something I've been wanting to do, thanks a lot @yiyixuxu for starting the process!

That post was focused on Apple's conversion library, but a few things have happened since then that we could mention:
- The DPM-Solver++ scheduler was ported to Swift, so it can be used on Apple hardware too (Inference is twice as fast as it takes half the number of steps).
- Other features now supported by Apple's library: negative prompts, image-to-image.
- The community converted several Dreambooth models to Core ML.
- We now have https://github.com/huggingface/swift-coreml-diffusers as a technology demo that people can use easily and programmers can extend.

I wouldn't make a long and comprehensive post about all this, but maybe we can rework this one to focus more on diffusers or diffusers-like features rather than just on the conversion library.

I can prepare a first draft and send it to you, would that be ok? I'll also update the blog post itself when the documentation is out.

**Comment by yiyixuxu** [comment]
@pcuenca sounds great! thanks!

**Comment by patrickvonplaten** [comment]
Gentle ping here

**Comment by yiyixuxu** [comment]
closing since we now have this  #2987

**Pull request closed without merging**
