### PR TITLE
Refac training utils.py

### PR DESCRIPTION
**Pull request by RogerSinghChugh**
# What does this PR do?

Fixes #9567 

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@a-r-r-o-w @stevhliu

### CODE REVIEW

**Comment by stevhliu** [comment]
@sayakpaul do you happen to know why these specific tests are failing? We've tried troubleshooting (`make style`, `make quality`, push changes) in https://github.com/huggingface/diffusers/pull/9724 but nothing seems to be working.

**Comment by sayakpaul** [comment]
> @sayakpaul do you happen to know why these specific tests are failing? We've tried troubleshooting (`make style`, `make quality`, push changes) in #9724 but nothing seems to be working.

Could be because of the versioning problems locally. I have just pushed the changed with "make style && make quality". Hopefully, that cuts it.

**Comment by RogerSinghChugh** [comment]
> > @sayakpaul do you happen to know why these specific tests are failing? We've tried troubleshooting (`make style`, `make quality`, push changes) in #9724 but nothing seems to be working.
> 
> Could be because of the versioning problems locally. I have just pushed the changed with "make style && make quality". Hopefully, that cuts it.

Hi @sayakpaul 
Thank you doing that. What do you mean by versioning changes? Do you mean the versions of the library ruff and isort I have installed?
I installed ruff 0.1.5 and the latest one for isort.
Can you let me know what versions are you running?
Also if the versioning is an issue, then can we add version requirements somewhere in the guides? Could be really helpful for beginners looking to contribute.

Once again thanks @stevhliu @sayakpaul

**Review by stevhliu — APPROVED** [review]
Thanks so much @sayakpaul, and thanks for your patience @RogerSinghChugh! 🤗

**Pull request merged**
