### PR TITLE
[Community Pipeline] Unclip Image Interpolation

### PR DESCRIPTION
**Pull request by Abhinay1997**
Added the code sample in the README.md

### CODE REVIEW

**Comment by Abhinay1997** [comment]
@williamberman , could you review this when you have time ?

**Comment by Abhinay1997** [comment]
@williamberman, @patrickvonplaten, can you have a look at the PR and let me know if it’s good to merge ?

**Comment by patrickvonplaten** [comment]
Very sorry for being so late here :cry: 

@williamberman do you mind taking a look?

**Review by patrickvonplaten — APPROVED** [review]
Looks nice to me!

**Comment by Abhinay1997** [comment]
No worries Patrick ! :)

**Review by williamberman — APPROVED** [review]

**Comment by williamberman** [comment]
nice :)

**Comment by williamberman** [comment]
Sorry for the delay @Abhinay1997 things have been a bit hectic, looks great!

**Comment by Abhinay1997** [comment]
Thanks for the merge @williamberman ! Good news on a Monday morning :) 

No worries. I get it. :)

**Pull request merged**
