### PR TITLE
Allow passing a checkpoint state_dict to convert_from_ckpt (instead of just a string path)

### PR DESCRIPTION
**Pull request by cmdr2**
This allows passing either a string path or a state_dict to the `download_from_original_stable_diffusion_ckpt()` method.

This makes it a bit more consistent with other model loading functions in diffusers, as well as allows external management and inspection of the state_dict (for e.g. Easy Diffusion analyzes the state dict for a few more things to determine the correct config file).

In general, it just provides a lot more flexibility to the users of this function, without any real downside.

Thanks!

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
Ok for me once tests are all green. @sayakpaul wdyt?

**Comment by cmdr2** [comment]
@patrickvonplaten I don't think the failing tests are from this PR.

Looking at the code of these tests, they don't use anything from the ckpt loader.

```
FAILED tests/models/test_lora_layers.py::SDXLLoraLoaderMixinTests::test_load_lora_locally - AssertionError: False is not true
```
```
FAILED tests/pipelines/paint_by_example/test_paint_by_example.py::PaintByExamplePipelineFastTests::test_save_load_local - ValueError: Trying to set a tensor of shape torch.Size([1, 1, 32]) in "uncond_vector" (which has shape torch.Size([1, 1, 768])), this look incorrect.
FAILED tests/pipelines/paint_by_example/test_paint_by_example.py::PaintByExamplePipelineFastTests::test_save_load_optional_components - ValueError: Trying to set a tensor of shape torch.Size([1, 1, 32]) in "uncond_vector" (which has shape torch.Size([1, 1, 768])), this look incorrect.
```

**Comment by patrickvonplaten** [comment]
You're right @cmdr2 :-) Updating this PR to "main"

**Comment by cmdr2** [comment]
Thanks @patrickvonplaten ! :)

**Comment by xhinker** [comment]
@cmdr2  Man, this parameter change from "checkpoint_path" to "checkpoint_path_or_dict" break everything, why not add a new parameter? 

@patrickvonplaten I believe this PR break the fundamental open-close development rules, and Diffusers's guidelines too

**Comment by cmdr2** [comment]
@xhinker I'm sorry, yes this was a mistake on my part. I assumed that the first argument wouldn't work with named parameters, since it was a mandatory argument (i.e. no default value). Clearly that was a mistake on my part.

Unfortunately, I see a few other scripts have started using the new variable name now (after it was checked-in on Aug 26). So reverting this change would break someone else again.

Again, my apologies for not checking all my assumptions.

**Comment by xhinker** [comment]
> @xhinker I'm sorry, yes this was a mistake on my part. I assumed that the first argument wouldn't work with named parameters, since it was a mandatory argument (i.e. no default value). Clearly that was a mistake on my part.
> 
> Unfortunately, I see a few other scripts have started using the new variable name now (after it was checked-in on Aug 26). So reverting this change would break someone else again.
> 
> Again, my apologies for not checking all my assumptions.

Hi, @cmdr2 thank you for the response, agree we should keep it as it is now. I will need to update all code in my part to reflect the change. but please, add new changes, instead of changing the existing input output, or dependance logic. Thank you.

**Comment by patrickvonplaten** [comment]
Yeah going forward now that `from_single_file` is used much more we should be more careful and make sure we cleanly deprecate arguments that change names.

**Pull request merged**
