### PR TITLE
[LoRA] Make sure validation works in multi GPU setup

### PR DESCRIPTION
**Pull request by patrickvonplaten**
Fixes: https://github.com/huggingface/diffusers/issues/2132

### CODE REVIEW

**Review by patil-suraj — APPROVED** [review]
Looks good!

**Review by pcuenca — APPROVED** [review]
Oops, thanks a lot!

**Comment by patil-suraj** [comment]
Should be changed in the [train_text_to_image_lora.py](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora.py) too

**Comment by teaguexiao** [comment]
not working, still having same errors..

**Comment by patrickvonplaten** [comment]
Hey @teaguexiao could you open a new issue with a reproducible code snippet please? :-)

**Pull request merged**
