### PR TITLE
Modify example with intel optimization

### PR DESCRIPTION
**Pull request by mengfei25**
Modify example with intel optimization

### CODE REVIEW

**Comment by hshen14** [comment]
Thanks @mengfei25 for creating the PR. You may consider 1) removing the constraints of grid image 2x4 with batch size 8, instead you can use batch size 1; 2) enabling steps as a parameter.

**Comment by hshen14** [comment]
Thanks @mengfei25 for creating the PR. You may consider 1) removing the constraints of grid image 2x4 with batch size 8, instead you can use batch size 1; 2) enabling steps as a parameter.

**Comment by mengfei25** [comment]
@hshen14 updated and fix format issues, please help have a review

**Review by hshen14 — APPROVED** [review]
LGTM

**Comment by hshen14** [comment]
@patrickvonplaten The PR looks good to me. Please help review. Thanks. 
One thing is about the failure of fast tests which seems not related with this PR.

**Comment by patrickvonplaten** [comment]
Good to merge for me!

**Pull request merged**
