### PR TITLE
[docs] Add controlnet example to marigold

### PR DESCRIPTION
**Pull request by asomoza**
# What does this PR do?

Add an example for using marigold depth prediction with controlnet.

Note: I only added  the `Depth Prediction with Controlnet` section, the rest of the changes were made with the `make style` automatically.

@toshas Feel free to add or change any text that you think will match better the overall style of the documentation.

## Who can review?
@yiyixuxu @stevhliu @toshas

### CODE REVIEW

**Comment by toshas** [comment]
@asomoza Thanks for proposing this! Can you please kick off the doc builder workflow to see how it looks now? I'm shooting in the dark with the CSS..

**Comment by toshas** [comment]
What do you think about this? 
https://x.com/bdsqlsz/status/1793988792086598114
https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite

**Comment by toshas** [comment]
LGTM otherwise

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by yiyixuxu** [comment]
feel free to merge! @asomoza

**Pull request merged**
