### PR TITLE
Simplify `platform_info` assignment in `diffusers-cli env`

### PR DESCRIPTION
**Pull request by tolgacangoz**
Fixes https://github.com/huggingface/diffusers/issues/8264#issuecomment-2134604783

Does simplifying/reverting `platform_info` more generalizable?

@sayakpaul @DN6

### CODE REVIEW

**Comment by yiyixuxu** [comment]
cc @DN6 here
just saw this https://github.com/huggingface/diffusers/pull/8235 - seem to cause error?

**Comment by DN6** [comment]
We just added the check for python 3.10 to so that the `PRETTY_NAME` for the platform can also be printed on supported python versions. I think it's fine to leave as is.

**Comment by tolgacangoz** [comment]
In the first comment of this PR, I referenced to a comment in an Issue. Could you look at there?
`platform.freedesktop_os_release()` is [under the Linux Platforms](https://docs.python.org/3/library/platform.html#linux-platforms) and `platform.platform()` is [under the Cross Platform](https://docs.python.org/3/library/platform.html#cross-platform).

**Comment by DN6** [comment]
@tolgacangoz Oh I see. Yeah makes sense then to just remove it.

**Comment by DN6** [comment]
@tolgacangoz Oh I see. Yeah makes sense then to just remove it.

**Pull request merged**
