### PR TITLE
Add attentionless VAE support

### PR DESCRIPTION
**Pull request by Gothos**
# What does this PR do?
Exposes the ```mid_block_add_attention``` parameter in Encoder and Decoder to enable attentionless VAEs using AutoencoderKL config .

## Before submitting
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?

This PR aims to integrate the [AuraDiffusion 16-channel VAE](https://huggingface.co/AuraDiffusion/16ch-vae) into diffusers. Integration requires minimal changes, requiring just an exposure of the Encoder and Decoder  (from models/autoencoders/autoencoder_kl.py) classes'  ```mid_block_add_attention``` parameter to the AutoencoderKL class and thus the VAE config.

Examples of image/reconstructed image pairs are below:

image
image

Some metrics:
image

``` make style && make quality``` fails due to some unrelated changes elsewhere in controlnets, hence this has not been done.
 I didn't think any new tests were required as this is a minor change, however more than happy to write any if required.

### CODE REVIEW

**Comment by haofanwang** [comment]
Looking forward to it!

**Review by isidentical — APPROVED** [review]

**Comment by bghira** [comment]
@yiyixuxu  for #8796

**Comment by bghira** [comment]
can confirm this works correctly, thank you!

**Comment by sayakpaul** [comment]
@Gothos can you follow https://github.com/huggingface/diffusers/actions/runs/9824367283/job/27123254814?pr=8769#step:6:1 to resolve the code quality failures?

**Comment by Gothos** [comment]
Will do!

**Comment by Gothos** [comment]
Should be done now.

**Comment by donthomasitos** [comment]
Would be great to see this PR merged!

**Comment by sayakpaul** [comment]
@yiyixuxu @DN6 a friendly ping here.

**Review by DN6 — APPROVED** [review]

**Pull request merged**
