### PR TITLE
Fixed Nits in Docs and Example Script

### PR DESCRIPTION
**Pull request by ParagEkbote**
# What does this PR do?
 
Closes the PR [#9087](https://github.com/huggingface/diffusers/pull/9087) and Issue [#9027](https://github.com/huggingface/diffusers/issues/9027). I've only updated the docstrings to not break anything. Please let me know if any improvements are needed and I will make the necessary changes.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).

## Who can review?

 cc: @yiyixuxu

### CODE REVIEW

**Review by a-r-r-o-w — APPROVED** [review]
Thank you, this looks like the correct thing to do since we can't change argument names without breaking backwards compatibility!

**Review by stevhliu — APPROVED** [review]
Thanks for the fixes!

**Comment by ParagEkbote** [comment]
Could you please see that #9087 and the issue #9027 gets closed to declutter?

cc: @stevhliu

**Comment by a-r-r-o-w** [comment]
Thanks for the fix and notifying! Marked those as closed

**Pull request merged**
