### PR TITLE
Add guidance start/stop

### PR DESCRIPTION
**Pull request by holwech**
Adds guidance start/stop to the img2img and text2img Stable Diffusion pipeline classe. This is a setting that is available in automatic1111. This PR is heavily inspired by this [community pipeline](https://github.com/huggingface/diffusers/blob/main/examples/community/stable_diffusion_controlnet_img2img.py) that implements the same functionality.

I've used and tested the PR on my own project and it seems to work fine.

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
Looks like a nice addition to me ,could we add some tests and also add it to the controlnet inpainting pipeline? 

Tests should be added here: 
https://github.com/huggingface/diffusers/tree/main/tests/pipelines/controlnet
Inpainting pipeline is here:
https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet_inpaint.py

**Comment by julien-blanchon** [comment]
`controlnet_guidance_start` and `controlnet_guidance_end` don't work for MultiControlnet. It should accept list/tuple for each controlnet

**Comment by holwech** [comment]
Thanks for the feedback. Seems like implementing this is slightly more complex than I anticipated, but I will try to look at this in the coming weeks. If anyone wants this implemented asap, feel free to take it over.

Todos
- [ ] Write tests
- [ ] Add guidance start/end to inpainting
- [ ] Add guidance start/end to MultiControlNet

**Comment by holwech** [comment]
Here is a before and after example:

```
modern apartment, grass, rocks, mountains, norway, summer, vray, hyper-realistic, high resolution, highly detailed
 Negative prompt: ugly, bad, jpeg artifacts, vignette
 Steps: 40, Sampler: DPM++ 2M, CFG scale: 7, Seed: 3313150245, Size: 896x512, Model: v1_realisticVisionV20_v20, ControlNet 0: "preprocessor: lineart_standard (from white bg & black line), model: control_v11p_sd15_lineart [43d4be0d], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: False, control mode: Balanced, preprocessor params: (512, 64, 64)", ControlNet 1: "preprocessor: depth_midas, model: control_v11f1p_sd15_depth [cfd03158], weight: 0.1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: False, control mode: Balanced, preprocessor params: (512, 64, 64)", Version: v1.3.2
```
image

```
modern apartment, grass, rocks, mountains, norway, summer, vray, hyper-realistic, high resolution, highly detailed
 Negative prompt: ugly, bad, jpeg artifacts, vignette
 Steps: 40, Sampler: DPM++ 2M, CFG scale: 7, Seed: 1996722551, Size: 896x512, Model: v1_realisticVisionV20_v20, ControlNet 0: "preprocessor: lineart_standard (from white bg & black line), model: control_v11p_sd15_lineart [43d4be0d], weight: 1, starting/ending: (0.05, 0.7), resize mode: Crop and Resize, pixel perfect: False, control mode: Balanced, preprocessor params: (512, 64, 64)", ControlNet 1: "preprocessor: depth_midas, model: control_v11f1p_sd15_depth [cfd03158], weight: 0.1, starting/ending: (0.05, 0.7), resize mode: Crop and Resize, pixel perfect: False, control mode: Balanced, preprocessor params: (512, 64, 64)", Version: v1.3.2
```
image


I find it's quite useful to set guidance end to a number lower than 1. This allows the model to clean up any artifacts caused by controlnet in the last steps of the process. By setting guidance start larger than 0, details that don't exist in the input images are added.

**Comment by holwech** [comment]
I've updated the PR to support multicontrolnet, can someone have a look at the changes and let me know if you are fine with the changes? I will add some tests afterwards if we agree to proceed.

**Comment by cylwin** [comment]
We need this for our qrcode controlnet demo.

**Comment by PhilSad** [comment]
Thanks for your PR! Here is a [demo colab](https://colab.research.google.com/github/koll-ai/stable-difusion-qrcode/blob/master/colabs/diffusers_qrcode_test_multicontrolnet_guidance_start_end.ipynb) that shows how to use it to generate qrcodes.

I also made the lib [sdqrcode](https://github.com/koll-ai/stable-diffusion-qrcode) to generate ai qrcodes with this method with a simple one-liner ([colab](https://colab.research.google.com/github/koll-ai/stable-diffusion-qrcode/blob/master/colabs/demo_sdqrcode_diffusers.ipynb))

Dalmatian qrcode

**Comment by patrickvonplaten** [comment]
Hey @holwech,

Sorry for fiddling soo much with your PR. Some tests were missing and I think it's better if we try to not change the controlnet files. Here I just take advantage of the fact that zero'ing out the controlnet result is the same as skipping it. The gain we might get from skipping on controlnet is negligible IMO so design-wise I think it's cleaner to just zero it out.

**Pull request merged**
