### PR TITLE
Timestep bias for fine-tuning (Dreambooth)

### PR DESCRIPTION
**Pull request by bghira**
# What does this PR do?

Implements #5094 for Dreambooth.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Cool, let's maybe discuss here: https://github.com/huggingface/diffusers/pull/5094#issuecomment-1728286546 a bit first.

**Comment by bghira** [comment]
:recycle:

**Comment by patrickvonplaten** [comment]
cc @sayakpaul IMO we should make sure to not add too many such features to keep the examples readable. The same note as mentioned here: https://github.com/huggingface/diffusers/pull/5508#issuecomment-1785213259 applies to this PR as well IMO.

**Comment by sayakpaul** [comment]
I agree. Let's maybe just include a note in the README. Should apply to https://github.com/huggingface/diffusers/pull/5104 as well.

**Pull request closed without merging**
