### PR TITLE
fix bug for multiple prompts inputs

### PR DESCRIPTION
**Pull request by xiaohu2015**
fig bugs for multiple prompts, for examples: 
```
prompt = [
    "a cat sitting on a bench",
    "a dog sitting on a bench",
    "a man sitting on a bench"
]
```

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@patil-suraj could you review here for in-paint?

**Comment by patrickvonplaten** [comment]
We should also add a test for this please :-)

**Comment by xiaohu2015** [comment]
> We should also add a test for this please :-)

I think we don't have to add a test, since I only fix a small bug.

**Review by patil-suraj — APPROVED** [review]
Good catch and thanks a lot for the fix @xiaohu2015 ! This works perfectly.

@patrickvonplaten I will add a test for this in follow-up a PR, I tried manually and works well

**Comment by patrickvonplaten** [comment]
Cool thanks for checking! Let's maybe also add a test here :-)

**Pull request merged**
