### PR TITLE
[Official callbacks] SDXL Controlnet CFG Cutoff

### LINKED ISSUE #8686: `SDXLCFGCutoffCallback` does not work with `StableDiffusionXLControlNetPipeline`
### Describe the bug

Running CFGCutoffCallback with ControlNet SDXL will raise following error
````
diffusers/src/diffusers/models/attention.py:372, in BasicTransformerBlock.forward(self, hidden_states, attention_mask, encoder_hidden_states, encoder_attention_mask, timestep, cross_attention_kwargs, class_labels, added_cond_kwargs)
    364         norm_hidden_states = self.pos_embed(norm_hidden_states)
    366     attn_output = self.attn2(
    367         norm_hidden_states,
    368         encoder_hidden_states=encoder_hidden_states,
    369         attention_mask=encoder_attention_mask,
    370         **cross_attention_kwargs,
    371     )
--> 372     hidden_states = attn_output + hidden_states
    374 # 4. Feed-forward
    375 # i2vgen doesn't have this norm 🤷‍♂️
    376 if self.norm_type == "ada_norm_continuous":

RuntimeError: The size of tensor a (8192) must match the size of tensor b (4096) at non-singleton dimension 1
````

which occurs due to conditional `image` (https://github.com/huggingface/diffusers/blob/main/src/diffusers/pipelines/controlnet/pipeline_controlnet_sd_xl.py#L1488) is not converted back to batch 1.

So the solution would be either adding new Callback for ControlNet or fixing current Callback to convert `image` back to shape 1

### Reproduction

````python
from diffusers import StableDiffusionXLControlNetPipeline, ControlNetModel, AutoencoderKL
from diffusers.callbacks import SDXLCFGCutoffCallback
from diffusers.utils import load_image, make_image_grid
from PIL import Image
import cv2
import numpy as np
import torch

original_image = load_image(
    "https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd_controlnet/hf-logo.png"
)

image = np.array(original_image)

low_threshold = 100
high_threshold = 200

image = cv2.Canny(image, low_threshold, high_threshold)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
canny_image = Image.fromarray(image)

controlnet = ControlNetModel.from_pretrained(
    "diffusers/controlnet-canny-sdxl-1.0",
    torch_dtype=torch.float16,
    use_safetensors=True
)
vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16, use_safetensors=True)
pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=controlnet,
    vae=vae,
    torch_dtype=torch.float16,
    use_safetensors=True
)
pipe.enable_model_cpu_offload()

prompt = "aerial view, a futuristic research complex in a bright foggy jungle, hard lighting"
negative_prompt = 'low quality, bad quality, sketches'
callback = SDXLCFGCutoffCallback(cutoff_step_ratio=0.4)
image = pipe(
    prompt,
    negative_prompt=negative_prompt,
    image=canny_image,
    controlnet_conditioning_scale=0.5,
    callback_on_step_end=callback,
).images[0]
make_image_grid([original_image, canny_image, image], rows=1, cols=3)
````

### Logs

_No response_

### System Info

- 🤗 Diffusers version: 0.29.0.dev0
- Platform: Linux-4.18.0-408.el8.x86_64-x86_64-with-glibc2.17
- Running on a notebook?: No
- Running on Google Colab?: No
- Python version: 3.8.13
- PyTorch version (GPU?): 2.1.0+cu121 (True)
- Flax version (CPU?/GPU?/TPU?): not installed (NA)
- Jax version: not installed
- JaxLib version: not installed
- Huggingface_hub version: 0.23.4
- Transformers version: 4.40.0.dev0
- Accelerate version: 0.28.0
- PEFT version: 0.11.1
- Bitsandbytes version: 0.43.1
- Safetensors version: 0.4.2
- xFormers version: 0.0.22.post7
- Accelerator: NVIDIA GeForce RTX 4090, 24564 MiB
- Using GPU in script?: Yes
- Using distributed or parallel set-up in script?: No

### Who can help?

@sayakpaul @yiyixuxu

### PR DESCRIPTION
**Pull request by asomoza**
# What does this PR do?

Adds a new official callback for the SDXL Controlnet pipeline.

After testing with different alternatives, I found that just adding a new callback for this specific pipeline was the best and simpler solution. 

Fixes #8686

## How to test

```python
import random
from datetime import datetime

import torch

from diffusers import AutoencoderKL, ControlNetModel, StableDiffusionXLControlNetPipeline
from diffusers.callbacks import SDXLControlnetCFGCutoffCallback
from diffusers.utils import load_image


anyline = load_image(
    "https://huggingface.co/datasets/OzzyGT/testing-resources/resolve/main/callbacks/20240829020431.png"
)

controlnet = ControlNetModel.from_pretrained("TheMistoAI/MistoLine", torch_dtype=torch.float16, variant="fp16")
vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)
pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    controlnet=controlnet,
    vae=vae,
    torch_dtype=torch.float16,
    variant="fp16",
).to("cuda")

prompt = "high quality photo of a yellow plastic huggingface emoji toy, white background"
callback = SDXLControlnetCFGCutoffCallback(cutoff_step_ratio=0.3)

image = pipe(
    prompt,
    num_inference_steps=25,
    image=anyline,
    controlnet_conditioning_scale=0.6,
    controlnet_guidance_end=0.9,
    callback_on_step_end=callback,
).images[0]

image.save("cnet_callback.png")
```

|anyine|Normal|Callback|
|---|---|---|
||||

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@rootonchair @juancopi81

### CODE REVIEW

**Comment by rootonchair** [comment]
LGTM. Just one concern if this issue exists in other callbacks

**Comment by asomoza** [comment]
yeah, this was discussed in the original PR, we probably need to do this kind of callbacks to all the different pipelines, so this means inpaint, img2img and for different model archs. 

But this is the only one so far that someone asked for it, so maybe lets evaluate to do them when someone asks for an official callback, also the community is open to do PRs with them.

Also probably we need to start naming the args more consistently, for this pipeline the controlnet image is `image` but for the `inpaint` and `img2img` pipelines this is for the source image and this one is named `control_image`.

**Comment by juancopi81** [comment]
Thanks @asomoza!!

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by kunc01** [comment]
> yeah, this was discussed in the original PR, we probably need to do this kind of callbacks to all the different pipelines, so this means inpaint, img2img and for different model archs.
> 
> But this is the only one so far that someone asked for it, so maybe lets evaluate to do them when someone asks for an official callback, also the community is open to do PRs with them.
> 
> Also probably we need to start naming the args more consistently, for this pipeline the controlnet image is `image` but for the `inpaint` and `img2img` pipelines this is for the source image and this one is named `control_image`.

@asomoza Hello, I'm trying SDXL with multicontrolnets, using the code in this PR leads to the same error as [#8686](https://github.com/huggingface/diffusers/issues/8686). I've tried replace [this line](https://github.com/huggingface/diffusers/pull/9311/files#diff-da47e27d2e11dfb926e05e4f6710dda730b05f18e258e3017235a95f51070bd2R176) with 
`image = image[-1].chunk(2)`
`image = [image[0] + image[1]]`
but the result is poor with cutoff_step_ratio=0.4. Any help is appreciated!

**Comment by rootonchair** [comment]
@kunc01 you should open a new issue and provide example code

**Pull request merged**
