### PR TITLE
[Scheduler] DPM-Solver (++) Inverse Scheduler

### PR DESCRIPTION
**Pull request by clarencechen**
Implements a higher-order inverse scheduler for the latent inversion process found in a number of diffusion-based image-editing pipelines. Please see #3336 for more information.

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
In general, I'm totally fine with adding a new scheduler for this, but would love to also hear what @LuChengTHU thinks as the author of the DPM-Solver. Also cc @sayakpaul

**Comment by LuChengTHU** [comment]
Thank you for your hard work! @clarencechen 

However, I don't fully understand why we need an additional "inverse" scheduler..? In my opinion, the "inverse" procedure can be directly implemented by setting the `timesteps` as a reverse order. As far as I remembered, my implemented scheduler for dpmsolver can work for both forward (sampling) and reverse ("inverses") order. Could you please give me more explanations why not directly use the current scheduler?

**Comment by clarencechen** [comment]
@LuChengTHU @patrickvonplaten I implemented a separate scheduler in order to retain code architecture consistency with the existing `DDIMInverseScheduler`. Implementing inversion with the existing deterministic denoising samplers will probably require a `self.set_reverse_timesteps()` function, and refactoring `self.step()` in order to enforce a uniform dependency on `self.timesteps` across schedulers.

**Comment by patrickvonplaten** [comment]
Ok for me to have a seperate scheduler here - think I'd even prefer it to not make the original DPMScheduler implementation too complicated - ok for you @LuChengTHU ?

**Comment by LuChengTHU** [comment]
No problem :) @patrickvonplaten 

A small reminder: could you please add the newest dpmsolver in the inverse version to include the SDE variant? @clarencechen

**Comment by patrickvonplaten** [comment]
Still some test failures here it seems, after that we can merge :-)

**Comment by patrickvonplaten** [comment]
Thanks for fixing the failures

**Pull request merged**
