### PR TITLE
[Type hint] PNDM pipeline

### PR DESCRIPTION
**Pull request by daspartho**
Based on 35. and 36. of issue https://github.com/huggingface/diffusers/issues/287

@anton-l would you mind checking it? Thanks : )

### CODE REVIEW

**Comment by anton-l** [comment]
Hi @daspartho, thanks for the contribution! 
Looks like your `make style` command made some extra changes to unrelated files due to a wrong `black` version. We use `black==22.3` which is installed if you run `pip install -e ".[dev]"` from the cloned repo :) 

Could you please revert those changes? It's as simple as running `git restore --source origin/main src/diffusers/models/*.py` on every directory where you see the unexpectedly deleted lines here: https://github.com/huggingface/diffusers/pull/327/files
(make sure not to run it on `pipelines/pndm/*.py` though! :smile:)

After that we're good to merge! :hugs:

**Comment by daspartho** [comment]
Hi @anton-l 
I reverted the unexpected changes, could you check it? 
Thanks : )

**Review by anton-l — APPROVED** [review]
Perfect, thank you @daspartho!

**Comment by danielpatrickhug** [comment]
Hi, added a pull request for 27 - 29 https://github.com/huggingface/diffusers/pull/412

**Pull request merged**
