### PR TITLE
[Refactor autoencoders] feat: introduce autoencoders module

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Give them their separate module. Happy life.

### CODE REVIEW

**Comment by charchit7** [comment]
LGTM!

**Comment by sayakpaul** [comment]
@DN6 a gentle ping here.

**Review by patrickvonplaten — APPROVED** [review]
Agree this is cleaner! Think "autoencoder" also works as a name!

**Comment by sayakpaul** [comment]
@DN6 a gentle ping here.

**Review by DN6 — APPROVED** [review]
LGTM

**Pull request merged**
