### PR TITLE
Add variant argument to dreambooth lora sdxl advanced

### PR DESCRIPTION
**Pull request by levi**
# What does this PR do?

Adds variant argument to the advanced script to support loading fp16 SDXL.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@linoytsaban @sayakpaul

### CODE REVIEW

**Comment by levi** [comment]
Unable to run the `make style` command locally. Getting this error:

```
→ make style && make quality
ruff check examples scripts src tests utils setup.py --fix
ruff failed
  Cause: TOML parse error at line 16, column 1
   |
16 | [tool.ruff.format]
   | ^^^^^^^^^^^^^^^^^^
wanted exactly 1 element, more than 1 element

make: *** [style] Error 2
```

**Comment by sayakpaul** [comment]
I suggest you do the following:

* Create a new Python virtual environment. 
* `cd` into `diffusers`, ensuring it's rebased with the updated `main`. 
* Then do `pip install -e ".[quality]".
* Then run `make style && make quality`.

**Comment by sayakpaul** [comment]
@linoytsaban could you give this a look?

**Comment by patrickvonplaten** [comment]
PR looks good to go for me, thanks for adding the `variant=...` argument. @apolinario @linoytsaban wdyt?

**Pull request merged**
