### PR TITLE
post release v0.28.0

### PR DESCRIPTION
**Pull request by sayakpaul**

### CODE REVIEW

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by yiyixuxu** [comment]
oh I think there are a couple things to deprecate still

**Comment by sayakpaul** [comment]
@yiyixuxu since https://github.com/huggingface/diffusers/pull/8291 has been merged, could I merge it once the CI is green?

**Comment by Z30G0D** [comment]
This PR is prevented from running `scripts/train_text_to_image.py` using the current `requirements.txt` file.
specifcally Line 60:
`check_min_version("0.29.0.dev0")`
I could not find this version anywhere.

**Comment by asomoza** [comment]
the `0.29.0.dev0` version is the current one in the main branch, you get that version when you install from source:

image

You probably have a version installed from source and updated the git, but you'll need to reinstall again to update the version.

**Pull request merged**
