### PR TITLE
Update lora_conversion_utils.py

### PR DESCRIPTION
**Pull request by zhaowendao30**
x-flux single-blocks lora load

# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by zhaowendao30** [comment]
I check the x-flux code, the single block lora should load after qkv attention，not norm,they are just has the same shape
image
image

**Comment by sayakpaul** [comment]
@raulmosa could you give this a look?

**Comment by raulmosa** [comment]
I've checked it and it's right, it shouldn't be norm. Looks good to me @sayakpaul .
Nice catch @zhaowendao30 , thanks! =)

**Comment by sayakpaul** [comment]
@zhaowendao30 thanks for your contribnutions!

Could you also do a side-by-side comparison of your changes applied and without your changes in the outputs? That would be very much appreciated.

**Comment by zhaowendao30** [comment]
> I've checked it and it's right, it shouldn't be norm. Looks good to me @sayakpaul . Nice catch @zhaowendao30 , thanks! =)

No thanks =)

**Comment by zhaowendao30** [comment]
> @zhaowendao30 thanks for your contribnutions!
> 
> Could you also do a side-by-side comparison of your changes applied and without your changes in the outputs? That would be very much appreciated.

OK, the single block i just trained index 1,2,3,4, and the first image is load in qkv, the second is load in norm, the last is no lora
image
image
image

**Comment by sayakpaul** [comment]
@zhaowendao30 thanks, but please prefer not using human subjects in the public forums. 

I will run the tests today and update the slices as needed because of the change.

**Comment by zhaowendao30** [comment]
> @zhaowendao30 thanks, but please prefer not using human subjects in the public forums.
> 
> I will run the tests today and update the slices as needed because of the change.

OK, I've uploaded it again. However, this is a LoRA about people, and the panda looks a bit strange. =）

**Review by sayakpaul — APPROVED** [review]
Thanks!

**Comment by sayakpaul** [comment]
@yiyixuxu a gentle ping.

**Pull request merged**
