### PR TITLE
mps & onnx tests rework

### PR DESCRIPTION
**Pull request by pcuenca**

### CODE REVIEW

**Comment by pcuenca** [comment]
This is now ready for review. ONNX and mps tests now run on push rather than pr. I increased tolerance for a single mps test that failed on CI hardware (perhaps because of the macOS version), and ensured installed dependencies are the latest stable ones.

As discussed internally, I also set up a new `mps` CI runner as the old one died.

**Review by williamberman — APPROVED** [review]
Nice!

**Review by sayakpaul — APPROVED** [review]
["thank you"] * 300!

**Review by patrickvonplaten — APPROVED** [review]
Cool, much cleaner!

**Pull request merged**
