### PR TITLE
SDXL microconditioning documentation should indicate the correct default order of parameters, so that developers know

### PR DESCRIPTION
**Pull request by bghira**
# What does this PR do?

Corrects the SDXL pipeline documentation to indicate the correct order of parameters for `original_size` and `target_size`.

I don't know if anyone else has been confused by this yet, but this led me astray for a while, training incorrectly on these values.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by bghira** [comment]
@sayakpaul @patrickvonplaten just a quick typo fix in the documentation

**Comment by sayakpaul** [comment]
@bghira could you push an empty commit?

**Review by patrickvonplaten — APPROVED** [review]
Very cool! Thanks a lot :-)

**Comment by patrickvonplaten** [comment]
Failing test is unrelated - merging

**Pull request merged**
