### PR TITLE
Move ControlNetXS into Community Folder

### PR DESCRIPTION
**Pull request by DN6**
# What does this PR do?
I don't think we can currently support the implementation of ControlNetXS  as is in the release version of diffusers. 

This PR:
1. Moves it into the community folder so that an implementation is still available to the community. 
2. Adds an example inference script that users can use to test the model. 

We can revisit this design and adding it into source based on community interest.     

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
We need to delete these tests after ControlNetXS has been moved to community.

**Review by sayakpaul — APPROVED** [review]
This works for me. It would make sense to also remove the documentation and add a note about ControlNetXS from the community README. Let's also have Umer as a co-author since they contributed the pipeline initially. WDYT?

**Comment by patrickvonplaten** [comment]
Can we instead move all the code to the research folder? We should only add code to `examples/community` that works with `from_pretrained(custom_pipeline="...")`

**Comment by sayakpaul** [comment]
@patrickvonplaten done.

**Pull request merged**
