### PR TITLE
Draft PR: [Flux ControlNet] Support Xlabs ControlNet in diffusers

### LINKED ISSUE #9378: [Flux ControlNet] Support Xlabs ControlNet in diffusers
It'd be great to have XLabs ControlNets supported in `diffusers`. We already support their LoRAs. 

Code: https://github.com/XLabs-AI/x-flux/
Checkpoint: https://huggingface.co/XLabs-AI/flux-controlnet-depth-v3

Related issue: https://github.com/huggingface/diffusers/issues/9301

Pinging @chenbinghui1 in case you're interested in contributing this.

### PR DESCRIPTION
**Pull request by caoandong**
# What does this PR do?

Fixes #9378 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by Adenialzz** [comment]
hi, is this finished ?

**Comment by chuck-ma** [comment]
It seems that it's a breaking change.

**Comment by chuck-ma** [comment]
Can you share your full script including how to convert xlab controlnet and an example of how to run? I'm trying your branch, but I get an error in the following codes.

```python
            if controlnet_block_samples is not None:
                interval_control = len(self.transformer_blocks) / len(
                    controlnet_block_samples
                )
                interval_control = int(np.ceil(interval_control))
                # print(interval_control, len(controlnet_block_samples))
                hidden_states = (
                    hidden_states
                    + controlnet_block_samples[index_block // interval_control]
                )
```

The length of controlnet_block_samples is 3. Index_block can be 17. It will throw an error definitely. @sayakpaul @caoandong

**Comment by sayakpaul** [comment]
Closing in favor of https://github.com/huggingface/diffusers/pull/9638. Thanks for your interest!

**Pull request closed without merging**
