### PR TITLE
[Community] Differential Diffusion

### LINKED ISSUE #7038: Differential Diffusion: Giving Each Pixel Its Strength
### Model/Pipeline/Scheduler description

Hello,
I would like to suggest merging my paper: Differential Diffusion: Giving Each Pixel Its Strength.
The paper allows a user to edit a picture by a change map that describes how much each region should change.
The editing process is typically guided by textual instructions, although it can also be applied without guidance.
We support both continuous and discrete editing.
Our framework is training and fine tuning free! And has negligible penalty of the inference time.
Our implementation is diffusers-based.
 We already tested it on 4 different diffusion models (Kadinsky, DeepFloyd IF, SD, SD XL).
We are confident that the framework can also be ported to other diffusion models, such as SD Turbo, Stable Cascade, and amused.
I notice that you usually stick to white==change convention, which is opposite to the convention we used in the paper.
The paper can be thought of as a generalization to some of the existing techniques.
A black map is just regular txt2img ("0"),
A map of one color (which isn't black) can be thought as img2img,
A map of two colors which one color is white can be thought as inpaint.
And the rest? It's completely new!
In the paper, we suggest some further applications such as soft inpainting and strength visualization.

### Open source status

- [X] The model implementation is available.

### Provide useful links for the implementation

Site:
https://differential-diffusion.github.io/
Paper:
https://differential-diffusion.github.io/paper.pdf
Repo:
https://github.com/exx8/differential-diffusion

### PR DESCRIPTION
**Pull request by a-r-r-o-w**
# What does this PR do?

Adds support for differential diffusion in a somewhat easy way to be usable by any img2img pipeline. There is an example with SDXL.

Fixes #7038.

Paper: https://differential-diffusion.github.io/paper.pdf
Project site: https://differential-diffusion.github.io/
Code: https://github.com/exx8/differential-diffusion

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul @yiyixuxu @exx8 @asomoza @vladmandic

### CODE REVIEW

**Comment by noskill** [comment]
there is already the same pipeline in examples https://github.com/huggingface/diffusers/blob/main/examples/community/masked_stable_diffusion_img2img.py

**Comment by exx8** [comment]
> there is already a pipeline that implements the same method in examples https://github.com/huggingface/diffusers/blob/main/examples/community/masked_stable_diffusion_img2img.py

Hi,
I understand the confusion,
Differential Diffusion can be thought as generalization of this approach:
Diff Diff allows for non binary masks (allowing editing different parts by different amount of change).
This pipeline implements only the case where a binary mask is given (some kind of traditional inpaint).

**Comment by noskill** [comment]
No, the mask is not binary, nor it is binarized at some point.

**Comment by noskill** [comment]
@exx8 here in diff diff at line 86 there is interpolation between two latents:

```
latents = original_with_noise[i] * mask + latents * (1 - mask)
```
the same as in [masked_stable_diffusion_img2img.py](https://github.com/huggingface/diffusers/blob/main/examples/community/masked_stable_diffusion_img2img.py) at line 212

**Comment by exx8** [comment]
> @exx8 here in diff diff at line 86 there is interpolation between two latents:
> 
> ```
> latents = original_with_noise[i] * mask + latents * (1 - mask)
> ```
> 
> the same as in [masked_stable_diffusion_img2img.py](https://github.com/huggingface/diffusers/blob/main/examples/community/masked_stable_diffusion_img2img.py) at line 212

Please notice that the mask is **dynamic**:
https://github.com/exx8/differential-diffusion/blob/d78f3f3f5181d319c8a96234393d545cec7eba11/SD2/diff_pipe.py#L696
https://github.com/exx8/differential-diffusion/blob/d78f3f3f5181d319c8a96234393d545cec7eba11/SD2/diff_pipe.py#L706
It changes at every for step.  While in the current pipeline it is static, and effectively interpolate the two latents.

**Comment by noskill** [comment]
Ok, what you implemented looks somewhat similar to interpolation with *latent noise* in automatic111

image

while i ported *fill* part in masked_stable_diffusion_img2img.py. *fill* is the color of the mask. It indeed interpolates latents. It is also useful, for example if you paint a green mask on an image then diffusion will generates something greenish.

Do you guys have good test images + masks?

**Comment by a-r-r-o-w** [comment]
Few results to show the pipeline works via diffusers.

<table>
<tr>
<td align=center>Input</td>
<td align=center>Mask</td>
</tr>
<tr>
<td align=center></td>
<td align=center></td>
</tr>
<tr>
<td align=center colspan=2>base + refiner at denoising_end = 0.8</td>
</tr>
<tr>
<td align=center>strength = 0.7</td>
<td align=center>strength = 1</td>
<tr>
<tr>
<td align=center></td>
<td align=center></td>
</tr>
<tr>
<td align=center colspan=2>base</td>
</tr>
<tr>
<td align=center></td>
<td align=center></td>
</tr>
</table>

I'll try and look into what noskill mentioned but I haven't had time to compare against A1111 or the community pipeline, which needs setting up on my end, after having moved to Comfy a while back.

**Comment by yiyixuxu** [comment]
so all we need is to use a callback with img2img pipeline? I think we can either:
1. add the usage example and callback function to community script 
2. just add as regular community pipelines (what's the advantage of this design, compared with normal community pipeline?)

**Comment by a-r-r-o-w** [comment]
> so all we need is to use a callback with img2img pipeline? I think we can either:
> 
> 1. add the usage example and callback function to community script
> 2. just add as regular community pipelines (what's the advantage of this design, compared with normal community pipeline?)

1. Initially, I wanted to propose this as a demonstration of callback usage in a slightly complex example. See https://github.com/huggingface/diffusers/issues/7038#issuecomment-1960700209. Some time after that, there was a community section added on community tips/tricks and callback usage examples, and targeted this PR for that.
2. The main benefit of this mixin is that it can be used with any img2img pipeline (currently sd and sdxl). I wrote it this way, with other modifications, for a library I use that has over 20 different implementations of sdxl img2img. Testing differential diffusion with any of those implementations becomes as simple as creating a new child class of the pipeline and this mixin, thus saving much time. This is just a copy of that version and I'm okay with changing the design to a normal community pipeline if you'd like that. I stick to implementing new changes as separate classes because writing a custom pipeline for testing an idea requires just opt-in inheriting and little to no modifications - something I took from working on diffusers for a bit :)

**Comment by yiyixuxu** [comment]
@a-r-r-o-w 
ohh nice! 
for the differential diffusion, let's do it as normal community pipelines so that it will be easier for us to integrate into diffusers later when it gains more usage

we could do that in a separate PR and keep this PR as it is, as it can serve as a good example for those who want to do similar kind experiments with diffusers in the future. Feel free to share more results and write about diff-diff experiments too!

**Comment by a-r-r-o-w** [comment]
I'm on a bit of a vacation and did not carry my personal laptop, so converting to community pipeline is going to take a while :( Since @exx8's repository already contains the implementation of the different versions, anyone can feel free to take up the addition to community pipelines. Apologies for the inconvenience

> You could maybe post something about your testing process in the [forum](https://github.com/huggingface/diffusers/discussions/categories/show-and-tell) and link it to this PR

Thanks, I would love to share something soon when I'm more free

**Pull request closed without merging**
