### PR TITLE
[Community Pipeline] Support for Zero123 

### PR DESCRIPTION
**Pull request by bennyguo**
# What does this PR do?

This PR addresses https://github.com/huggingface/diffusers/issues/4096.

- Support [Zero123](https://zero123.cs.columbia.edu/) as a community pipeline.
- A conversion script to convert to original Zero123 checkpoint to diffusers format. I've uploaded the converted weights to https://huggingface.co/bennyguo/zero123-diffusers.

TODO

- [ ] Add a snippet to test the pipeline.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by bennyguo** [comment]
@sayakpaul Any suggestions on how to incorporate extra modules in this community pipeline? I have a CLIPCameraProjection module which is basically a linear layer:
https://github.com/huggingface/diffusers/blob/bc691231360a4cbc7d19a58742ebb8ed0f05e027/examples/community/zero123.py#L40-L81

I've tried putting this module in the pipeline file (as in this PR) or putting it under the same folder as the pipeline file, but neither allows me to correctly load pipeline weights using `from_pretrain`. It always raises a `ModuleNotFoundError` indicating that the CLIPCameraProjection module cannot be found.

**Comment by sayakpaul** [comment]
Cc: @yiyixuxu  for https://github.com/huggingface/diffusers/pull/4417#issuecomment-1661485436

**Comment by patrickvonplaten** [comment]
It seems like this PR got borked sadly - any chance to fix the commit history or open a new one? :-)

**Comment by bennyguo** [comment]
@patrickvonplaten Closing.

**Pull request closed without merging**
