### PR TITLE
Update LCMScheduler Inference Timesteps to be More Evenly Spaced

### LINKED ISSUE #5815: LCM Scheduler's isn't perfect in uniformly spreading the timesteps across the full range
### Describe the bug

Timesteps for nSteps=26 using the current scheduler
> [999, 979, 959, 939, 919, 899, 879, 859, 839, 819, 799, 779, 759,
    739, 719, 699, 679, 659, 639, 619, 599, 579, 559, 539, 519, 499]
Notice that it comes up short of coming near zero.
My modification is still linear but across the full range and still keeping the individual timesteps as multiples of 20 away from 999:
> [999, 959, 919, 879, 839, 799, 759, 739, 699, 659, 619, 579, 539,
    499, 459, 419, 379, 339, 299, 259, 239, 199, 159, 119,  79,  39]

Note that at 25 steps and at a few other step values both schedules result in the same timesteps and same image.  In the "Asian woman with fancy bikini" image below with the old scheduler it loses the sky, clouds and sand/sea edge when going from 25 steps to 26 steps.  Perhaps due to the lopsided schedule???

Screenshot from 2023-11-15 21-23-18

### Reproduction

For a hack to test my modified scheduler I took:
> diffusers/schedulers/scheduling_lcm.py:set_timesteps()
and after the old scheduler created the self.timesteps tensor I just overrode it with:
```
    nSteps = len(self.timesteps)
    delta = 999. / nSteps
    for i in range(nSteps):
        self.timesteps[i] = 999 - 20 * int((i * delta + 10) / 20)
```
Obviously this is hard code for the 20 increment delta requirement Simian told me of when I reported this to him.

### Logs

_No response_

### System Info

This is the diffusers version with LCM now integrated fully.

### Who can help?

_No response_

### PR DESCRIPTION
**Pull request by dg845**
# What does this PR do?

This PR modifies `LCMScheduler.set_timesteps` to produce `timesteps` which are more evenly spaced across the range of candidate timesteps, which should lead to better sample quality.

Fixes #5815.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@patrickvonplaten
@patil-suraj
@aifartist
@luosiallen

### CODE REVIEW

**Comment by dg845** [comment]
The solution I have currently implemented differs from the solution suggested in https://github.com/huggingface/diffusers/issues/5815#issue-1996137525 as follows:

- Instead of generating timesteps directly, we select indices from the training/distillation schedule `lcm_origin_timesteps`. This should ensure that we always end up with timesteps that we saw during training/distillation.
- Because `np.linspace(0, len(lcm_origin_timesteps) - 1, num=num_inference_steps)` is used to generate the indices, the first and last timesteps in the final inference timestep schedule are always anchored to the first and last timesteps in `lcm_origin_timesteps`. (Under default settings, this would be `999` and `19` respectively.)

**Comment by dg845** [comment]
(Also, note that the timestep schedule produced by `LCMScheduler.set_timesteps` will in general be different after the change, so any test that uses `LCMScheduler` with `num_inference_steps > 1` will probably need to be fixed.)

**Comment by luosiallen** [comment]
I think we want to avoid the cases that 3-step sampling is very similar to 2-step sampling, which means that we don't want setting anchor for the first timesteps 19.  For example, i think the schedule of 2-step [999, 499] is better than [999, 19].

**Review by patil-suraj — APPROVED** [review]
Thanks a lot for fixing this @dg845 , lgtm!

Will run some tests then we can merge.

**Review by patrickvonplaten — APPROVED** [review]
I trust you here @patil-suraj

**Review by patrickvonplaten — COMMENTED** [review]
If you consider the previous timestep spacing a bug, I'm ok with the PR. If not and it's just a "different way" of doing timestep spacing, we should probably be careful about backwards breaking

**Comment by luosiallen** [comment]
Should we do more test? or just like @patrickvonplaten suggestion. We can just add `timestep [list]` input in the` __call__`, so the users can figure out what's the best for them.

**Comment by patil-suraj** [comment]
I'm currently running the slow tests that we have. All the fast tests are passing. 
This timestep schedule is correct, as it matches the schedule during training, so it should be the default IMO. We could add the `timestep` argument to `__call__` for additional schedules.

**Comment by luosiallen** [comment]
> I'm currently running the slow tests that we have. All the fast tests are passing.
> This timestep schedule is correct, as it matches the schedule during training, so it should be the default IMO. We could add the `timestep` argument to `__call__` for additional schedules.

Thanks @patil-suraj !

**Comment by patil-suraj** [comment]
Some slow tests are failing,

- `pytest tests/lora/test_lora_layers_peft.py::LoraSDXLIntegrationTests::test_sdxl_lcm_lora`
- `pytest tests/lora/test_lora_layers_peft.py::LoraSDXLIntegrationTests::test_sdv1_5_lcm_lora`
- `pytest tests/lora/test_lora_layers_peft.py::LoraSDXLIntegrationTests::test_sdv1_5_lcm_lora_img2img`

@patrickvonplaten  would it be okay to adjust the tests in this case ?

**Comment by patil-suraj** [comment]
All slow LCM tests are now passing, I updated the images here https://huggingface.co/datasets/hf-internal-testing/diffusers-images/tree/main/lcm_lora

**Review by Empty-Huanaco38 — APPROVED** [review]

**Pull request merged**
