### PR TITLE
Replaced optimizer.zero_grad() with param.grad = None

### PR DESCRIPTION
**Pull request by shirayu**
Followed PyTorch Performance Tuning Guide.

> Use parameter.grad = None instead of model.zero_grad() or optimizer.zero_grad()

https://pytorch.org/tutorials/recipes/recipes/tuning_guide.html#use-parameter-grad-none-instead-of-model-zero-grad-or-optimizer-zero-grad

Other reference:
https://nvlabs.github.io/eccv2020-mixed-precision-tutorial/files/szymon_migacz-pytorch-performance-tuning-guide.pdf#page=7

### CODE REVIEW

**Comment by lukovnikov** [comment]
Personally, I would be more in favour of  `optimizer.zero_grad(set_to_none=True)` and changing torch version to 1.7, or keeping it as-is.

Also, the behavior may not be exactly the same, as elaborated here: https://pytorch.org/docs/master/generated/torch.optim.Optimizer.zero_grad.html#torch.optim.Optimizer.zero_grad

**Comment by anton-l** [comment]
As suggested by @lukovnikov, `optimizer.zero_grad(set_to_none=True)` looks cleaner.
@shirayu have you noticed a significant speedup with `parameter.grad = None`? Could you benchmark it for one of the scripts please?

**Comment by shirayu** [comment]
@lukovnikov @anton-l 
Yes, if the minimum requirement of torch can be updated to 1.7, that makes more readable.

No, I haven't tested it, but I read that it saved VRAM in training of dreambooth.
https://note.com/kohya_ss/n/nee3ed1649fb6 (In Japanese, they say `set_to_none=True` saved VRAM)

I would like to benchmark this, but I'm not sure when I can make time for it.
(Benchmarks by others are welcome)

**Review by patil-suraj — CHANGES_REQUESTED** [review]
Thanks a lot for the PR. Agree with @lukovnikov and @anton-l . I would keep the script simple and just use `optimizer.zero_grad(set_to_none=True)`.

I would be happy to test the script to see if it gives any speed-up or saves VRAM.

**Comment by patrickvonplaten** [comment]
I think we should indeed keep `.zero_grad()` here - closing for now

**Pull request closed without merging**
