### PR TITLE
Google drive backup support for checkpoints

### PR DESCRIPTION
**Pull request by rohitdavas**
Problem : 

The problem with runtime training on colab is that when runtime expires, everything gets deleted. I added the support for the controlnet training such that user can enable the backup to the drive.

Another issue is user having low storage google drive : 15GB

Solution: 
i) copying the folder to the drive for backup at the checkpointing and logs at validation. 
ii) controlling how much checkpoints in order from latest to oldest are saved to drive. since each checkpoint is quite large, drive fills quite fast. --drive_n_keep flag to keep the last [0, n] checkpoints. when it is 0, only the latest one is kept. 

Shortcomings :
- runs in the the main thread, so slows down training a bit. 

Better versions :
- running the backup in a seperate thread such that it doesn't block training. Still in todo.

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
cc @williamberman @yiyixuxu here. We should not upload to Google drive but to the Hub, it's much better integrated. Think periodically uploading to the Hub makes a lot of sense though

**Comment by rohitdavas** [comment]
the particular use case is for people that are not using hub for any number of reason. e.g the commercial training.

**Comment by williamberman** [comment]
hey @rohitdavas when I've used google drive for backups when working on colab, I've just set the directory to be written into as a subfolder of where the google drive is mounted so I don't think we need to make any changes to support this?

The saving 1 out of every n checkpoints to a different place is a bit of a specific use case and I'm not sure if we could merge without seeing more demand for it 

lmk if I missed something :)

**Comment by patrickvonplaten** [comment]
> the particular use case of google drive is for people that are not using hub for any number of reason. e.g the commercial training.
> 
> Also to support the familiar interface for people who use google colab and drive extensively, and might not want to make their results public.

You can very easily upload your results privately to the Hub btw

**Pull request closed without merging**
