### PR TITLE
[training] CogVideoX-I2V LoRA

### PR DESCRIPTION
**Pull request by a-r-r-o-w**
# What does this PR do?

Image-to-Video LoRA finetuning for CogVideoX

<details>
<summary> bash script </summary>

```bash
#!/bin/bash

export TORCH_LOGS="+dynamo,recompiles,graph_breaks"
export TORCHDYNAMO_VERBOSE=1
export TORCH_NCCL_ENABLE_MONITORING=0
export WANDB_MODE="offline"

GPU_IDS="2,3"
LEARNING_RATES=("1e-3" "1e-4")
LR_SCHEDULES=("constant" "cosine_with_restarts")
OPTIMIZERS=("adam" "adamw")
EPOCHS=("30")

for learning_rate in "${LEARNING_RATES[@]}"; do
  for lr_schedule in "${LR_SCHEDULES[@]}"; do
    for optimizer in "${OPTIMIZERS[@]}"; do
      for epochs in "${EPOCHS[@]}"; do
        cache_dir="/raid/aryan/cogvideox-lora/"
        output_dir="/raid/aryan/cogvideox-lora__optimizer_${optimizer}__epochs_${epochs}__lr-schedule_${lr_schedule}__learning-rate_${learning_rate}/"

        cmd="accelerate launch --gpu_ids $GPU_IDS --config_file accelerate_configs/simple_uncompiled_v2.yaml examples/cogvideo/train_cogvideox_image_to_video_lora.py \
          --pretrained_model_name_or_path /raid/aryan/CogVideoX-5b-I2V/ \
          --cache_dir $cache_dir \
          --instance_data_root /raid/aryan/dataset-cogvideox/ \
          --caption_column <CAPTION_FILENAME> \
          --video_column <VIDEOS_FILENAME> \
          --validation_prompt \"A black and white animated scene unfolds with an anthropomorphic goat surrounded by musical notes and symbols, suggesting a playful environment. Mickey Mouse appears, leaning forward in curiosity as the goat remains still. The goat then engages with Mickey, who bends down to converse or react. The dynamics shift as Mickey grabs the goat, potentially in surprise or playfulness, amidst a minimalistic background. The scene captures the evolving relationship between the two characters in a whimsical, animated setting, emphasizing their interactions and emotions:::A panda, dressed in a small, red jacket and a tiny hat, sits on a wooden stool in a serene bamboo forest. The panda's fluffy paws strum a miniature acoustic guitar, producing soft, melodic tunes. Nearby, a few other pandas gather, watching curiously and some clapping in rhythm. Sunlight filters through the tall bamboo, casting a gentle glow on the scene. The panda's face is expressive, showing concentration and joy as it plays. The background includes a small, flowing stream and vibrant green foliage, enhancing the peaceful and magical atmosphere of this unique musical performance\" \
          --validation_images \"/raid/aryan/dataset-cogvideox/videos/frames_1_00.png:::/raid/aryan/dataset-cogvideox/videos/frames_2_00.png\" \
          --validation_prompt_separator ::: \
          --num_validation_videos 1 \
          --validation_epochs 10 \
          --seed 42 \
          --rank 64 \
          --lora_alpha 64 \
          --mixed_precision bf16 \
          --output_dir $output_dir \
          --height 480 --width 720 --fps 8 --max_num_frames 49 --skip_frames_start 0 --skip_frames_end 0 \
          --train_batch_size 1 \
          --num_train_epochs $epochs \
          --checkpointing_steps 10000 \
          --gradient_accumulation_steps 1 \
          --learning_rate $learning_rate \
          --lr_scheduler $lr_schedule \
          --lr_warmup_steps 200 \
          --lr_num_cycles 1 \
          --enable_slicing \
          --enable_tiling \
          --gradient_checkpointing \
          --optimizer $optimizer \
          --adam_beta1 0.9 \
          --adam_beta2 0.95 \
          --max_grad_norm 1.0 \
          --report_to wandb \
          --nccl_timeout 1800"
        
        echo "Running command: $cmd"
        eval $cmd
        echo -ne "-------------------- Finished executing script --------------------"
      done
    done
  done
done
```

</details>

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by SHYuanBest** [comment]
When will the SFT version of CogVideoX-5B T2V be available?

**Comment by a-r-r-o-w** [comment]
> When will the SFT version of CogVideoX-5B T2V be available?

We can add support for it soon. The changes to make CogVideoX T2V LoRA to full SFT should be very simple actually - you will have to remove all the lora related parts and make the transformer require gradients, and instead of saving lora weights, you can save the full model with `pipe.save_pretrained()`

**Comment by 963658029** [comment]
Why didn't you run the following two lines of code after calculating the loss?
avg_loss = accelerator.gather(loss.repeat(args.train_batch_size)).mean()
train_loss += avg_loss.item() / args.gradient_accumulation_steps

**Comment by a-r-r-o-w** [comment]
Gradient accumulation is handled by `accelerate` (you can see that we pass `gradient_accumulation_steps` when initializing `Accelerator`). We don't need to maintain total train loss because accelerator.backward(loss) implicitly maintains it for N - 1 gradient steps and performs averaging at N'th gradient accumulation step. [Here's](https://huggingface.co/docs/accelerate/en/usage_guides/gradient_accumulation) a helpful reference.

**Comment by 963658029** [comment]
I'm not sure, but I've seen other models' training scripts run these two lines of code.

**Comment by a-r-r-o-w** [comment]
Hmm, I'm not too sure either what the case for distributed training should be. It seems like you might be right because I took a look at a few code bases and found this used too.

Just for a sanity check, pinging @SunMarc here. Do we need an `accelerator.gather(loss)` when using distributed training or is it handled internally? In the script, I only have a call to `accelerator.backward(loss)` and, as far as I've understood from the accelerate codebase, it looks like gradient accumulation in distributed settings is already considered

**Comment by 963658029** [comment]
any update?

**Comment by lclichen** [comment]
As far as I know, the `gather` function in torch only collects the numerical results of loss (excluding gradients) for logging, and the accumulation of gradients is done automatically in the `backward` function.

I am not sure if I am right, if there is a mistake please help me correct it.

**Comment by 963658029** [comment]
but if `accelerator.gather(loss)` (e.g., loss) is incorrect, will `accelerator.backward(loss)` (e.g., backword) correct?

**Comment by 963658029** [comment]
any update?

**Comment by a-r-r-o-w** [comment]
We're working on a separate repository for memory-efficient and multiresolution finetuning of CogVideoX that will be open-sourced soon. This PR will probably not receive any further updates at the moment.

I think `accelerator.backward(loss)` is correct, and I think what @lclichen said makes the most sense to me but please correct me if I'm wrong so I can make all the necessary changes. Pinging @muellerzr, @SunMarc from the accelerate team and @sayakpaul to verify this.

**Comment by 963658029** [comment]
Can the code of this PR run normally to fine-tune i2v (consistent with the official effect of CogVideoX)?

**Comment by 963658029** [comment]
No need for multi-resolution and memory-efficient, is this code now the same as `sat`?

**Comment by Florenyci** [comment]
> The changes for I2V LoRA are as follows (in SAT):
> 
> * Adding small amounts of noise to image before VAE encode: [here](https://github.com/THUDM/CogVideo/blob/a9a55462f363a9f7ef2ba0364ba08a87a7c439bc/sat/diffusion_video.py#L151). This is supported in current training script
> * Noised image dropout (replacing image condition with zeros): [here](https://github.com/THUDM/CogVideo/blob/a9a55462f363a9f7ef2ba0364ba08a87a7c439bc/sat/diffusion_video.py#L164). This is supported too
> * Loss with denoised video latent (image latent is never considered in loss, nor while adding initial noise): [here](https://github.com/THUDM/CogVideo/blob/a9a55462f363a9f7ef2ba0364ba08a87a7c439bc/sat/sgm/modules/diffusionmodules/loss.py#L98). This is considered too in the script.
> 
> Apart from these, if I'm missing anything, please let me know or feel free to open a PR for improvements. Maybe I can merge this as it is for now, and we can work on the others improvements later (it will be released as a separate repository in the near future).
> 
> Here are my training runs: [wandb](https://wandb.ai/aryanvs/cogvideox-i2v-lora?nw=nwuseraryanvs)
> 
>  Accelerate Config
>  Launch script

@a-r-r-o-w Great work! I also want to fine-tune VAE model, is there any code pointer to do it?

**Comment by 963658029** [comment]
I found a big problem, you missed this line of code `image = image + image_noise` in `def encode_video()`

**Comment by 963658029** [comment]
> u missed this line of code `image = image + image_noise` in `def encode_video()`



> The changes for I2V LoRA are as follows (in SAT):
> 
> * Adding small amounts of noise to image before VAE encode: [here](https://github.com/THUDM/CogVideo/blob/a9a55462f363a9f7ef2ba0364ba08a87a7c439bc/sat/diffusion_video.py#L151). This is supported in current training script
> * Noised image dropout (replacing image condition with zeros): [here](https://github.com/THUDM/CogVideo/blob/a9a55462f363a9f7ef2ba0364ba08a87a7c439bc/sat/diffusion_video.py#L164). This is supported too
> * Loss with denoised video latent (image latent is never considered in loss, nor while adding initial noise): [here](https://github.com/THUDM/CogVideo/blob/a9a55462f363a9f7ef2ba0364ba08a87a7c439bc/sat/sgm/modules/diffusionmodules/loss.py#L98). This is considered too in the script.
> 
> Apart from these, if I'm missing anything, please let me know or feel free to open a PR for improvements. Maybe I can merge this as it is for now, and we can work on the others improvements later (it will be released as a separate repository in the near future).
> 
> Here are my training runs: [wandb](https://wandb.ai/aryanvs/cogvideox-i2v-lora?nw=nwuseraryanvs)
> 
> Accelerate Config
> Launch script

I found a big problem, you missed this line of code `image = image + image_noise` in `def encode_video()`

**Comment by a-r-r-o-w** [comment]
> I found a big problem, you missed this line of code image = image + image_noise in def encode_video()

I'm extremely sorry for the time this would have cost you! I actually have this fixed in the latest repository that we will be releasing for finetuning cogvideox (hopefully this week as only some final tests are remaining), but I completely forgot to push the latest changes here :melting_face: Thank you so much for reporting this though! Would you be okay if I added you as a co-author when pushing the fix here?

> Great work! I also want to fine-tune VAE model, is there any code pointer to do it?

We haven't looked into yet but since there have been many requests (on the original CogVideo repo), we might consider providing a script for finetuning VAE too soon. cc @zRzRzRzRzRzRzR

**Comment by 963658029** [comment]
Thanks for your reply. @SHYuanBest informed me about this bug, and I would be delighted if he could also be listed as a co-author when you push the fix.

**Comment by 963658029** [comment]
It seems that deepspeed cannot run normally: 
1. 
`use_deepspeed_scheduler = ( accelerator.state.deepspeed_plugin is not None and "scheduler" not in accelerator.state.deepspeed_plugin.deepspeed_config )` needs to be modified to 
`use_deepspeed_scheduler = ( accelerator.state.deepspeed_plugin is not None and "scheduler" in accelerator.state.deepspeed_plugin.deepspeed_config )` 
2. 
`if accelerator.is_main_process: if global_step % args.checkpointing_steps == 0`: needs to be modified to
`if accelerator.distributed_type == DistributedType.DEEPSPEED or accelerator.is_main_process : if global_step % args.checkpointing_steps == 0:`

**Comment by a-r-r-o-w** [comment]
> And we also found that the effect of the diffuser version of cogvideox is slightly worse than that of SAT, I don't know why. Any other bugs you have fixed expect these?

Nope, the only bug we had fixed was the `image + noisy_image` part in our other repository too. Thanks for the DeepSpeed fixes! I'll try to investigate the SAT training run to see why the quality is slightly poorer in comparison

**Comment by a-r-r-o-w** [comment]
Are you sure that `if accelerator.distributed_type == DistributedType.DEEPSPEED or accelerator.is_main_process` is correct? This would mean that other processes will also be performing validation/inference instead of the just the main, when using DeepSpeed? I've pushed it for now, but can try and verify later as I'm occupied with a few other things

**Comment by 963658029** [comment]
> Are you sure that `if accelerator.distributed_type == DistributedType.DEEPSPEED or accelerator.is_main_process` is correct? This would mean that other processes will also be performing validation/inference instead of the just the main, when using DeepSpeed? I've pushed it for now, but can try and verify later as I'm occupied with a few other things
`if accelerator.distributed_type == DistributedType.DEEPSPEED or accelerator.is_main_process` should be used to save weights (line 1464), and line1497only needs  `if accelerator.is_main_process`.

**Comment by a-r-r-o-w** [comment]
Oh, I see what you mean, sorry! Will fix

**Comment by 963658029** [comment]
> > And we also found that the effect of the diffuser version of cogvideox is slightly worse than that of SAT, I don't know why. Any other bugs you have fixed expect these?
> 
> Nope, the only bug we had fixed was the `image + noisy_image` part in our other repository too. Thanks for the DeepSpeed fixes! I'll try to investigate the SAT training run to see why the quality is slightly poorer in comparison

I have located the problem. I seriously suspect that there is a problem in the implementation of `rescale_betas_zero_snr` in the `diffusers scheduler`. This leads to the following abnormal phenomenon: the inference of `cogvideox-diffusers` gradually gets worse with the increase of steps, while the inference of `cogvideox-sat` gradually gets better with the increase of steps. I think this may also lead to the training effect being worse than that of `sat`?

**Comment by SunMarc** [comment]
> Just for a sanity check, pinging @SunMarc here. Do we need an accelerator.gather(loss) when using distributed training or is it handled internally? In the script, I only have a call to accelerator.backward(loss) and, as far as I've understood from the accelerate codebase, it looks like gradient accumulation in distributed settings is already considered

Sorry for the wait ! I see that you are going to merge this soon. You don't have to gather the loss before calling `accelerator.backward(loss)`. As you said gradient accumulation is already considered and we don't really want to gather the loss actually. More explanation on DDP particular case [here](https://discuss.pytorch.org/t/way-to-aggregate-loss-in-ddp-training/176929#:~:text=Apr%202023-,No%2C%20DDP%20would%20not%20aggregate%20the%20losses%20from%20different%20ranks%20as%20each%20rank%20gets%20an%20independent%20input%20and%20calculates%20%E2%80%9Cits%20own%E2%80%9D%20gradients.,-The%20gradients%20are).

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by scarbain** [comment]
Hi everyone. I just trained a LoRA for I2V thanks to all your work but now I'm having trouble using it for inference. 
What should I use to add the LoRA to my I2V pipeline ? I saw the readme for inferencing a LoRA on T2V but it doesn't work on I2V, I get the error "AttributeError: 'CogVideoXImageToVideoPipeline' object has no attribute 'load_lora_weights'"

**Comment by a-r-r-o-w** [comment]
You will have to install the latest diffusers release with `pip install -U diffusers`, or the `main` branch for being able to use `load_lora_weights`

**Comment by a-r-r-o-w** [comment]
You could do it in less than 24gb for batch_size=1. More details available here: https://github.com/a-r-r-o-w/cogvideox-factory

**Comment by SHYuanBest** [comment]
@a-r-r-o-w hi, we just develope a identity-preserving text-to-video generation model, ConsisID, which can keep human-identity consistent in the generated video. Can you help us to intergrate it into diffusers? Thanks.

https://github.com/PKU-YuanGroup/ConsisID

**Comment by a-r-r-o-w** [comment]
Ofcourse, I would love to! For this week, I'm quite busy but I will take a good look and start testing it this weekend. Thanks for the awesome work!

**Comment by SHYuanBest** [comment]
@a-r-r-o-w hi arrow, if you need any help, just feel free to let me know

**Comment by a-r-r-o-w** [comment]
@SHYuanBest Sorry, I was not able to find the time yet to try and integrate this. But I did try it out on ComfyUI and the results were very cool! If you could open a PR, we could help with reviews and try to integrate it faster. If that works, we can set up a communication channel on Slack with your team (cc @sayakpaul)

**Comment by SHYuanBest** [comment]
sure, i have create a PR here https://github.com/huggingface/diffusers/pull/10140

**Pull request merged**
