### PR TITLE
Saving Image Locally

### PR DESCRIPTION
**Pull request by hi-sushanta**
I've expanded the Stable Diffusion pipeline's capabilities by introducing a new parameter that empowers you to preserve generated output locally, precisely where you wish.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [x] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sayakpaul** [comment]
We don't need this parameter as saving an image is just a one-liner.

**Comment by hi-sushanta** [comment]
But it's usefull to save generated output locally.
Example:
```
import torch
from diffusers import StableDiffusionPipeline

pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
pipe = pipe.to("cuda")
prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt,save_img_path="marse-with-horse.png")
```

**Comment by hi-sushanta** [comment]
And also it's small line of code.

**Comment by sayakpaul** [comment]
That is exactly the point. 

```python
prompt = "a photo of an astronaut riding a horse on mars"
image = pipe(prompt).images[0]
image.save("name.jpeg")
```

Does the job.

**Comment by patrickvonplaten** [comment]
Strongly agree with @sayakpaul here. Let's try to not bloat the pipelines too much

**Pull request closed without merging**
