### PR TITLE
[docs] Clean up toctree

### PR DESCRIPTION
**Pull request by stevhliu**
Refactors the toctree to reduce navigational complexity and improve section/subsection titles. Changes include:
 
- remove "Other modalities" section and move molecule generation notebook to the research projects folder
- remove section overviews (except for "Training") in favor of streamlining the docs
- un-nest the "Using Diffusers" section to avoid too many nested sections and because this is a rather vague title
- move IP-Adapter/Textual Inversion to the "Specific pipeline examples" section
- move pipeline callbacks to "Techniques" section
- move Distilled SD Inference to "Optimization" section
- collapse models/methods subsections in "Training"
- collapse all subsections in "API"

This is just a first draft to see what everything looks like when they're moved around. Some docs will be merged later after everything has been moved to make the docs even easier to navigate.

### CODE REVIEW

**Comment by stevhliu** [comment]
Comments and feedback welcome @yiyixuxu @sayakpaul @pcuenca @DN6 @asomoza! 🤗

**Review by sayakpaul — COMMENTED** [review]
The proposal looks good to me. It's much more concise without losing any info. 

But I think having overview pages in some sections could be useful as they serve as friendly introductions to the users about what's to come.

**Comment by stevhliu** [comment]
Yeah, I left an overview page for the "Training" section, which has install instructions and an overview of what to expect since that section is so extensive. What other sections do you think could benefit from an overview?

I think, for the most part, the "Load pipelines and adapters," "Generative tasks," "Specific pipeline examples," and "Accelerate inference and reduce memory" sections are pretty self-explanatory about what's to come. The "Techniques" section is a bit more vague and I think an overview there could indeed be useful!

**Comment by sayakpaul** [comment]
Agreed.

**Review by yiyixuxu — APPROVED** [review]
very nice!

**Review by sayakpaul — APPROVED** [review]
Very organized!

**Pull request merged**
