### PR TITLE
Fix typo in StableDiffusionInpaintPipeline

### PR DESCRIPTION
**Pull request by hutec**

### CODE REVIEW

**Review by pcuenca — COMMENTED** [review]
Good catch!

**Comment by hutec** [comment]
> Would you be up for fixing it too? 😄 (It's totally ok if you can't)

I can give it a try. Can this be done in this PR or should I open a separate one?

**Comment by pcuenca** [comment]
I think it can be done here as it's related, but up to you!

And thanks a lot :)

**Comment by patrickvonplaten** [comment]
Very cool @hutec ,

This looks good to me! The failing tests don't seem to be related.

@pcuenca I let you merge if you're happy with it

**Review by patrickvonplaten — APPROVED** [review]

**Review by pcuenca — APPROVED** [review]
Looks great, thanks a lot!

**Pull request merged**
