### PR TITLE
fix xlabs FLUX lora conversion typo

### PR DESCRIPTION
**Pull request by Clement-Lelievre**
# What does this PR do?

Typo fixing for XLab FLUX LoRA conversion to diffusers.
In [its current version](https://github.com/huggingface/diffusers/blob/99f608218caa069a2f16dcf9efab46959b15aec0/src/diffusers/loaders/lora_conversion_utils.py#L635), this raises: `TypeError: slice indices must be integers or None or have an __index__ method` because `str.startswith` expects a tuple of strs or a single str.
(Unless I've missed an issue on this topic, I'm a bit surprised this typo has been here for over a month without anyone complaining)

Repro steps:

1. instanciate a flux pipeline
2. get a xlab lora safetensors
3. run `pipe.load_lora_weights(xlab_lora)` , passing the lora from step 2

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@sayakpaul , @yiyixuxu

### CODE REVIEW

**Comment by sayakpaul** [comment]
Thank you for this. The reason why, it was not brought up because we don't test for an Xlabs LoRA that has `single_block` components:
https://github.com/huggingface/diffusers/blob/99f608218caa069a2f16dcf9efab46959b15aec0/tests/lora/test_lora_layers_flux.py#L252

**Review by sayakpaul — APPROVED** [review]

**Comment by Clement-Lelievre** [comment]
@sayakpaul from a cursory glance from my phone it seems the failed test is unrelated to the diff of this PR

**Comment by sayakpaul** [comment]
@Clement-Lelievre possible to push an empty commit?

**Comment by Clement-Lelievre** [comment]
> @Clement-Lelievre possible to push an empty commit?

done

**Comment by sayakpaul** [comment]
Failing test is completely unrelated.

**Comment by sayakpaul** [comment]
Thank you for the PR!

**Comment by Clement-Lelievre** [comment]
@sayakpaul as follow-up, using the same xlabs lora the conversion now works, however I now get the error: `Adapter name(s) {'<my_adapter_name>'} not in the list of present adapters: set().` raised [here](https://github.com/huggingface/diffusers/blob/3159e60d59819ae874ea3cdbd28e02d9e6c57321/src/diffusers/loaders/lora_base.py#L539) since [this PR](https://github.com/huggingface/diffusers/pull/9535)

Possibly because `get_list_adapters` fails to add a component?

**Comment by sayakpaul** [comment]
Can you open a new issue with a reproducible snippet?

**Pull request merged**
