### PR TITLE
[SD3 Training] T5 token limit 

### PR DESCRIPTION
**Pull request by asomoza**
# What does this PR do?
Adds a command line argument `max_sequence_length` for the SD3 training scripts to change the token limit for the T5 text encoder.

I left it at 256 to be consistent with the inference token limit.

Fixes https://github.com/huggingface/diffusers/issues/8557

## Who can review?

@sayakpaul @AmericanPresidentJimmyCarter

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks a bunch here :) 

Not a blocker to merge the PR but did you notice any substantial qualitative differences after increasing the maximum sequence length during training? 

It will also increase the training memory requirements a bit I'd assume.

**Comment by bghira** [comment]
it also increases disk space requirements and the time to compute the text embeds

it may be better not to implement this for SD3 yet, as we don't really have a handle on all of the variables impacting training

**Comment by sayakpaul** [comment]
My personal thought is that it's still okay to have this argument exposed and explicitly documented about the ramifications of using increased token lengths.

**Comment by asomoza** [comment]
> Thanks a bunch here :)
> 
> Not a blocker to merge the PR but did you notice any substantial qualitative differences after increasing the maximum sequence length during training?
> 
> It will also increase the training memory requirements a bit I'd assume.

Personally no, because I don't have any training dataset with this kind of big prompts, more than 77 is more than enough for me. But I see the benefit here because with the T5 we can now train with detailed spatial composition and not just a description of it.

CC: @AmericanPresidentJimmyCarter said that tested it and had those kind of datasets.

**Comment by asomoza** [comment]
Also maybe it will be best if I set it to a default of 77 and people who want more than that can set the token limit higher? that way people won't get the higher resource consumption unless they really want it.

**Comment by sayakpaul** [comment]
That makes sense to me. Feel free to add a note about this in the README and merge afterward.

**Pull request merged**
