### PR TITLE
Add docstring for the AutoencoderKL's decode

### LINKED ISSUE #5230: [HacktoberFest][Missing Docstrings] Autoencoder `decode`
This feature request is included in this years Diffusers' Hacktoberfest 👨‍💻! 

Hacktoberfest's purpose is to give upcoming open-source developers the opportunity to learn about open-source and programming by fixes simple issues (like this one).

**How to solve the issue**:

- 1. Every issue has a description further below explaining the problem. First, you should try to understand the issue.
- 2. Second, follow the [contribution guide](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md) to learn how to contribute to Diffusers.\
- 3. Claim this issue for you by opening a PR that links to this issue and writing "I am solving this issue in `<link-to-pr>`"

**Issue**

The [decode method of AutoencoderKL](https://github.com/huggingface/diffusers/blob/78a78515d64736469742e5081337dbcf60482750/src/diffusers/models/autoencoder_kl.py#L283) is completely missing docstrings, can you add them?

### PR DESCRIPTION
**Pull request by freespirit**
Fixes #5230

### CODE REVIEW

**Comment by freespirit** [comment]
Similar to #5239 I tried to stick to the style of `tiled_decode`'s docstring for consistency

**Review by patrickvonplaten — APPROVED** [review]
Thanks!

**Review by yiyixuxu — APPROVED** [review]
thank you!

**Review by sayakpaul — APPROVED** [review]
Thanks for adding it!

**Comment by freespirit** [comment]
Ran `make style` & `make quality`. Thank you all for the support!

**Comment by patrickvonplaten** [comment]
Failing tests are unrelated => merging

**Pull request merged**
