### PR TITLE
fix the add_noise function for dpm-multi et al 

### PR DESCRIPTION
**Pull request by yiyixuxu**
My PR to refactor schedulers https://github.com/huggingface/diffusers/pull/4986 broke img2img pipelines :(
I updated the `add_noise` incorrectly and never tested it with img2img and it was not caught by our current tests 

this PR update`add_noise` to use `sigmas`

# testing 

I compared outputs from this branch vs the output from a branch where I reverted the commit that introduced this bug https://github.com/huggingface/diffusers/pull/4986

I used a single strength value `0.8`, and I tested both `use_karras_sigma=True` and `use_karras_sigma=False` config. The results are identical. 

## testing `use_karras_sigma=True` 
```python
import requests
import numpy as np
from PIL import Image
from io import BytesIO
import torch

from diffusers import (
    StableDiffusionImg2ImgPipeline,
    DPMSolverSinglestepScheduler,
    DPMSolverMultistepScheduler,
    UniPCMultistepScheduler,
    DEISMultistepScheduler,
)

url = "https://raw.githubusercontent.com/CompVis/stable-diffusion/main/assets/stable-samples/img2img/sketch-mountains-input.jpg"
response = requests.get(url)
init_image = Image.open(BytesIO(response.content)).convert("RGB")
init_image = init_image.resize((768, 512))

device = "cuda"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
).to(device)

scheduler_config = dict(pipe.scheduler.config)

seed = 33
strength = 0.8
#branch = "current"
branch = "revert-dpm-refactor"

# DPMSolverMultistepScheduler
sched_name = "dpm_miulti"
pipe.scheduler = DPMSolverMultistepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True, algorithm_type="dpmsolver++")

generator = torch.Generator(device="cuda").manual_seed(seed)
images = pipe(
    prompt="a fantasy landscape",
    negative_prompt=None,
    image=init_image,
    strength=strength,
    num_inference_steps=15,
    generator=generator,
    guidance_scale=10,
    num_images_per_prompt=1
).images
image = images[0].save(f"test_5_out/[{sched_name}]_{strength:.2f}_[{branch}].png")

# DPMSolverMultistepScheduler(sde) 
sched_name = "dpm_miulti_sde"
pipe.scheduler = DPMSolverMultistepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True, algorithm_type="sde-dpmsolver++")

generator = torch.Generator(device="cuda").manual_seed(seed)
images = pipe(
    prompt="a fantasy landscape",
    negative_prompt=None,
    image=init_image,
    strength=strength,
    num_inference_steps=15,
    guidance_scale=10,
    generator=generator,
    num_images_per_prompt=1
).images
image = images[0].save(f"test_5_out/[{sched_name}]_{strength:.2f}_[{branch}].png")

# DPMSolverSingleScheduler
sched_name = "dpm_single"
pipe.scheduler = DPMSolverSinglestepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True)

generator = torch.Generator(device="cuda").manual_seed(seed)
images = pipe(
    prompt="a fantasy landscape",
    negative_prompt=None,
    image=init_image,
    strength=strength,
    num_inference_steps=15,
    guidance_scale=10,
    generator=generator,
    num_images_per_prompt=1
).images
image = images[0].save(f"test_5_out/[{sched_name}]_{strength:.2f}_[{branch}].png")

# UniPCMultistepScheduler
sched_name = "unipc"
pipe.scheduler = UniPCMultistepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True)

generator = torch.Generator(device="cuda").manual_seed(seed)
images = pipe(
    prompt="a fantasy landscape",
    negative_prompt=None,
    image=init_image,
    strength=strength,
    num_inference_steps=15,
    guidance_scale=10,
    generator=generator,
    num_images_per_prompt=1
).images
image = images[0].save(f"test_5_out/[{sched_name}]_{strength:.2f}_[{branch}].png")

# DEISMultistepScheduler
sched_name = "deis"
pipe.scheduler = DEISMultistepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True)

generator = torch.Generator(device="cuda").manual_seed(seed)
images = pipe(
    prompt="a fantasy landscape",
    negative_prompt=None,
    image=init_image,
    strength=strength,
    num_inference_steps=15,
    generator=generator,
    guidance_scale=10,
    num_images_per_prompt=1
).images
image = images[0].save(f"test_5_out/[{sched_name}]_{strength:.2f}_[{branch}].png")
```
#### DEISMultistepScheduler
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
deis _0 80_ current | deis _0 80_ revert-dpm-refactor

#### DPMSolverMultistepScheduler(sde) 
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
dpm_miulti_sde _0 80_ current | dpm_miulti_sde _0 80_ revert-dpm-refactor

#### DPMSolverMultistepScheduler
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
dpm_miulti _0 80_ current | dpm_miulti _0 80_ revert-dpm-refactor

#### DPMSolverSingleScheduler
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
dpm_single _0 80_ current | dpm_single _0 80_ revert-dpm-refactor

#### UniPCMultistepScheduler
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
unipc _0 80_ current | unipc _0 80_ revert-dpm-refactor

#### DEISMultistepScheduler
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
deis _0 80_ current | deis _0 80_ revert-dpm-refactor

#### DPMSolverMultistepScheduler(sde) 
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
dpm_miulti_sde _0 80_ current | dpm_miulti_sde _0 80_ revert-dpm-refactor

#### DPMSolverMultistepScheduler
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
dpm_miulti _0 80_ current | dpm_miulti _0 80_ revert-dpm-refactor

#### DPMSolverSingleScheduler
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
dpm_single _0 80_ current | dpm_single _0 80_ revert-dpm-refactor

#### UniPCMultistepScheduler
this PR           |  revert dpm-refactor PR
:-------------------------:|:-------------------------:
unipc _0 80_ current | unipc _0 80_ revert-dpm-refactor

### CODE REVIEW

**Comment by yiyixuxu** [comment]
# testing 

## script
```python
import requests
import numpy as np
from PIL import Image
from io import BytesIO
import torch

from diffusers import (
    StableDiffusionImg2ImgPipeline,
    DPMSolverSinglestepScheduler,
    DPMSolverMultistepScheduler,
    UniPCMultistepScheduler,
    DPMSolverMultistepInverseScheduler,
    DEISMultistepScheduler,
)

url = "https://raw.githubusercontent.com/CompVis/stable-diffusion/main/assets/stable-samples/img2img/sketch-mountains-input.jpg"
response = requests.get(url)
init_image = Image.open(BytesIO(response.content)).convert("RGB")
init_image = init_image.resize((768, 512))

device = "cuda"
pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
).to(device)

scheduler_config = dict(pipe.scheduler.config)


# DPMSolverMultistepScheduler
sched_name = "dpm_miulti"
pipe.scheduler = DPMSolverMultistepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True, algorithm_type="dpmsolver++")


for strength in torch.linspace(0.1,0.95,18):
    images = pipe(
        prompt="a fantasy landscape",
        negative_prompt=None,
        image=init_image,
        strength=strength,
        num_inference_steps=15,
        guidance_scale=10,
        num_images_per_prompt=1
    ).images
    image = images[0].save(f"test_2_out/[{sched_name}]_{strength:.2f}.png")

# DPMSolverMultistepScheduler(sde) 
sched_name = "dpm_miulti_sde"
pipe.scheduler = DPMSolverMultistepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True, algorithm_type="sde-dpmsolver++")


for strength in torch.linspace(0.1,0.95,18):
    images = pipe(
        prompt="a fantasy landscape",
        negative_prompt=None,
        image=init_image,
        strength=strength,
        num_inference_steps=15,
        guidance_scale=10,
        num_images_per_prompt=1
    ).images
    image = images[0].save(f"test_2_out/[{sched_name}]_{strength:.2f}.png")

# DPMSolverSingleScheduler
sched_name = "dpm_single"
pipe.scheduler = DPMSolverSinglestepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True)


for strength in torch.linspace(0.1,0.95,18):
    images = pipe(
        prompt="a fantasy landscape",
        negative_prompt=None,
        image=init_image,
        strength=strength,
        num_inference_steps=15,
        guidance_scale=10,
        num_images_per_prompt=1
    ).images
    image = images[0].save(f"test_2_out/[{sched_name}]_{strength:.2f}.png")

# UniPCMultistepScheduler
sched_name = "unipc"
pipe.scheduler = UniPCMultistepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True)


for strength in torch.linspace(0.1,0.95,18):
    images = pipe(
        prompt="a fantasy landscape",
        negative_prompt=None,
        image=init_image,
        strength=strength,
        num_inference_steps=15,
        guidance_scale=10,
        num_images_per_prompt=1
    ).images
    image = images[0].save(f"test_2_out/[{sched_name}]_{strength:.2f}.png")

# DEISMultistepScheduler
sched_name = "deis"
pipe.scheduler = DEISMultistepScheduler.from_config(
    scheduler_config, use_karras_sigmas=True)

for strength in torch.linspace(0.1,0.95,18):
    images = pipe(
        prompt="a fantasy landscape",
        negative_prompt=None,
        image=init_image,
        strength=strength,
        num_inference_steps=15,
        guidance_scale=10,
        num_images_per_prompt=1
    ).images
    image = images[0].save(f"test_2_out/[{sched_name}]_{strength:.2f}.png")
```
## results
### DPMSolverMultistepScheduler (strength 0.1 ~ 0.95)
dpm_miulti _0 10
dpm_miulti _0 15
dpm_miulti _0 20
dpm_miulti _0 25
dpm_miulti _0 30
dpm_miulti _0 35
dpm_miulti _0 40
dpm_miulti _0 45
dpm_miulti _0 50
dpm_miulti _0 55
dpm_miulti _0 60
dpm_miulti _0 65
dpm_miulti _0 70
dpm_miulti _0 75
dpm_miulti _0 80
dpm_miulti _0 85
dpm_miulti _0 90
dpm_miulti _0 95

### DPMSolverMultistepScheduler SDE (strength 0.1 ~ 0.95)
dpm_miulti_sde _0 10
dpm_miulti_sde _0 15
dpm_miulti_sde _0 20
dpm_miulti_sde _0 25
dpm_miulti_sde _0 30
dpm_miulti_sde _0 35
dpm_miulti_sde _0 40
dpm_miulti_sde _0 45
dpm_miulti_sde _0 50
dpm_miulti_sde _0 55
dpm_miulti_sde _0 60
dpm_miulti_sde _0 65
dpm_miulti_sde _0 70
dpm_miulti_sde _0 75
dpm_miulti_sde _0 80
dpm_miulti_sde _0 85
dpm_miulti_sde _0 90
dpm_miulti_sde _0 95

### DPMSolverSingleScheduler (strength 0.1 ~ 0.95)
dpm_single _0 10
dpm_single _0 15
dpm_single _0 20
dpm_single _0 25
dpm_single _0 30
dpm_single _0 35
dpm_single _0 40
dpm_single _0 45
dpm_single _0 50
dpm_single _0 55
dpm_single _0 60
dpm_single _0 65
dpm_single _0 70
dpm_single _0 75
dpm_single _0 80
dpm_single _0 85
dpm_single _0 90
dpm_single _0 95

### UniPCMultistepScheduler (strength 0.1 ~ 0.95)
unipc _0 10
unipc _0 15
unipc _0 20
unipc _0 25
unipc _0 30
unipc _0 35
unipc _0 40
unipc _0 45
unipc _0 50
unipc _0 55
unipc _0 60
unipc _0 65
unipc _0 70
unipc _0 75
unipc _0 80
unipc _0 85
unipc _0 90
unipc _0 95

### DEISMultistepScheduler (strength 0.1 ~ 0.95)
deis _0 10
deis _0 15
deis _0 20
deis _0 25
deis _0 30
deis _0 35
deis _0 40
deis _0 45
deis _0 50
deis _0 55
deis _0 60
deis _0 65
deis _0 70
deis _0 75
deis _0 80
deis _0 85
deis _0 90
deis _0 95

**Comment by yiyixuxu** [comment]
ohh actually I think I have to update `add_noise` using sigmas too .... I don't know what I was thinking....
working on it now

**Review by pcuenca — APPROVED** [review]
Works for me (tested DPMSolverMultistepScheduler). The SDXL refiner step was broken, wasn't it? Did we receive any reports?

I'd suggest we merge this soon but then create tests (or fix them) as a followup, to ensure we catch similar problems in the future.

**Comment by rvorias** [comment]
Thanks for fixing this so fast!

**Pull request merged**
