### PR TITLE
add data_dir parameter when calling load_dataset

### PR DESCRIPTION
**Pull request by aihao2000**
# What does this PR do?
Similar to https://github.com/huggingface/diffusers/pull/4482. Adding the data_dir parameter makes it easy to use personal local datasets

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.
@sayakpaul and @patrickvonplaten @yiyixuxu

### CODE REVIEW

**Comment by yiyixuxu** [comment]
thanks - could you provide an example when we pass`args.train_data_dir`? 
I looked at https://github.com/huggingface/diffusers/pull/4482 and it wasn't clear to me

**Comment by AisingioroHao0** [comment]
@yiyixuxu If I implement as [#4482](https://github.com/huggingface/diffusers/pull/4482) and use my local dataset. I used data_dir to determine the location of the local dataset.Assuming that the current implementation of the training script does not have the data_dir parameter, it will go to "None/..." Finding files

**Comment by AisingioroHao0** [comment]
@yiyixuxu 
```shell
accelerate launch --mixed_precision=fp16 /home/aihao/workspace/diffusers/examples/text_to_image/train_text_to_image.py \
    --pretrained_model_name_or_path="/home/aihao/workspace/DeepLearningContent/models/sd/AnythingV5Ink_v5PrtRE" \
    --dataset_name="/home/aihao/workspace/DeepLearningContent/datasets/images" \
    --dataset_config_name='style_learn_torino' \
    --train_data_dir="/home/aihao/workspace/DeepLearningContent/datasets/images" \
    --image_column="image" \
    --caption_column="prompt" \
    --resolution=512 \
    --report_to="wandb" \
    --train_batch_size=4 \
    --gradient_accumulation_steps=1 \
    --max_train_steps=20000 \
    --learning_rate=5e-6 \
    --output_dir="/home/aihao/workspace/DeepLearningContent/models/sd/torino_style" \
    --checkpointing_steps=1000 \
    --validation_epochs=10 --validation_prompt="a painting in the style of torino,one anime girl,original, masterpiece, illustration,detailed beautiful eyes,cat ear and cat tail,silver hair, silver ear,long hair, coat, short skirt, hair blowing with the wind,casual,""a painting in the style of torino,one anime girl,(masterpiece, best quality), solo, twintails, shirt, skirt, petals, bowtie, earrings, jewelry, bangs, black hair, hair ornament, hair ribbon, red ribbon, red eyes, long hair, open mouth, white shirt, multicolored hair, black skirt, red hair, long sleeves, pink bowtie, hair between eyes, looking at viewer, collared shirt" \
    --use_8bit_adam \
    --gradient_checkpointing \
    --enable_xformers_memory_efficient_attention \
    --mixed_precision="fp16" \
    --seed=2221101
```

**Comment by yiyixuxu** [comment]
It's the same as https://github.com/huggingface/diffusers/pull/4482, I'm not super familiar with these training scripts but I don’t think it is a common use case we need to enable - no? 

I think the logic is strange that we pass both `args.dataset_name` and `args.train_data_dir` to `load_dataset`

cc @sayakpaul @patrickvonplaten - let me know what you guys think!

**Comment by sayakpaul** [comment]
> It's the same as https://github.com/huggingface/diffusers/pull/4482, I'm not super familiar with these training scripts but I don’t think it is a common use case we need to enable - no?

Agreed.

**Comment by AisingioroHao0** [comment]
@yiyixuxu  dataset_name sometimes does not represent a local dir, but may be a remote name for a huggingfacehub dataset. So the dataset library adds data_dir. I personally think so. The official example is to use a path returned by a downloader as the location, but my local data does not need to be downloaded so I have been using data_dir to locate the local path of the dataset.

**Review by patrickvonplaten — APPROVED** [review]
Looks good to me! @sayakpaul wdyt?

**Comment by patrickvonplaten** [comment]
@yiyixuxu @sayakpaul this PR is good to go I think. We allow local dataset loading so why shouldn't we merge this PR ?

**Comment by yiyixuxu** [comment]
@patrickvonplaten 
because based on my understanding,  `args.train_data_dir` should be a local directory and should be used when we load a dataset from local (i.e. used in the `else...` part of the code below)

it is very confusing to me that we also use it when we load the dataset from hub and give it a completely different meaning (i.e. we use in the `if...` part of the code below, I also made a comment at the line it was used) 

the contributor explained their particular use case here https://github.com/huggingface/diffusers/pull/4655#issuecomment-1689267458 and here https://github.com/huggingface/diffusers/pull/4655#issuecomment-1689586181. I don't think it is a user case we need to support - if they want to load local dataset, they can use `args.train_data_dir` instead of `args.dataset_name`

I'm not 100% against merge this PR as I don't think it'll cause any issues. But I really don't like how we just give (very arbitrary) second meaning to an existing argument. 
 

```python
    if args.dataset_name is not None:
        # Downloading and loading a dataset from the hub.
        dataset = load_dataset(
            args.dataset_name,
            args.dataset_config_name,
            cache_dir=args.cache_dir,
      # yiyi comments: here for some reason this PR we pass train_data_dir 
      # (which for our user, means the local directory that contains your data) as `data_dir` when load a dataset from hub 
            data_dir=args.train_data_dir,
    else:
        data_files = {}
        if args.train_data_dir is not None:
          # yiyi comments: this is how `train_data_dir` is normally used - it is the local directory that contains your data
            data_files["train"] = os.path.join(args.train_data_dir, "**")
        dataset = load_dataset(
            "imagefolder",
            data_files=data_files,
            cache_dir=args.cache_dir,
        )
```

**Comment by aihao2000** [comment]
@yiyixuxu I have not used the data_files parameter. However, the prefabricated dataset configuration of "imagefolder" does not feel like it will meet my expectations. My dataset is relatively complex.

**Comment by yiyixuxu** [comment]
@aihao2000 

our training scripts serves as examples, we want to keep it simple, clear and general  - you're very welcomed to make any modifications on your copy to suit your need! :) 

Thanks!
YiYi

**Comment by aihao2000** [comment]
@yiyixuxu With this parameter, we can customize the data processing process in the script file under our own data set folder. The training script does not need to be changed, it is still very simple, and I feel it does not affect the generality. It can still handle all previous situations.

**Comment by patrickvonplaten** [comment]
@yiyixuxu I'm still in favor of merging this PR because:
- 1. It's a very simple change
- 2. It can solve a use case that can currently not be solved, which is that the user wants to load a dataset script from the Hub via a name and "fill" this script with local data. This is something that can happen quite often actually. E.g. you want to use this dataset: https://huggingface.co/datasets/poloclub/diffusiondb/blob/main/diffusiondb.py , but **not** this https://huggingface.co/datasets/poloclub/diffusiondb/tree/main/diffusiondb-large-part-1 data. In this case it makes a lot of sense to overwrite the Hub data with custom local data while still downloading the dataset script `diffusiondb.py`

**Comment by yiyixuxu** [comment]
@patrickvonplaten oh yes of course if you think it makes sense to support this use case :)

in this example you mentioned, do we still pass `--dataset_name = poloclub/diffusiondb` and then then pass the local directory as `--train_data_dir`?

**Comment by aihao2000** [comment]
@yiyixuxu If I did, I would download dataset.py into data dir and then use the local path. That way I can use the official script directly on the local custom dataset.

**Comment by yiyixuxu** [comment]
@aihao2000 

I think it might work without the downloading it, otherwise maybe we should consider change `args.dataset_name` to `args.dataset_name_or_path`

```python
load_dataset(
            args.dataset_name,
            args.dataset_config_name,
            cache_dir=args.cache_dir,
            data_dir=args.train_data_dir,
)
```

**Comment by yiyixuxu** [comment]
hey @aihao2000 
really sorry I think we decided to merge this one. I just forgot about it
would you be kind enough to re-open it? 

Thanks a lot
YiYi

**Comment by aihao2000** [comment]
@yiyixuxu Oh, it doesn’t matter, I also forgot about it and deleted the branch directly. I will reopen a PR later.

**Pull request closed without merging**
