### PR TITLE
fix: remove duplicated code in TemporalBasicTransformerBlock.

### PR DESCRIPTION
**Pull request by AsakusaRinne**
# What does this PR do?

Fixes the duplication of the layernorm definition in TemporalBasicTransformerBlock.

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Review
@sayakpaul @yiyixuxu @DN6 I wonder if you'd like to review it though it's just a simple fix. :)

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thanks!

**Comment by AsakusaRinne** [comment]
Seems that the ci needs approval, could you please help?

**Comment by sayakpaul** [comment]
Please ping me once the CI workflow is complete. Will merge :)

**Comment by AsakusaRinne** [comment]
@sayakpaul All the ci has passed. :)

**Pull request merged**
