### PR TITLE
fix dreambooth attention mask

### PR DESCRIPTION
**Pull request by linbo0518**
Convert attention mask to torch tensor to fix attention mask bug

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @linbo0518,

Can you give a bit more background to how this issue is arising?

**Comment by linbo0518** [comment]
Hello @patrickvonplaten ,

To fine-tune Dreambooth, utilize the `--text_encoder_use_attention_mask` flag. Be aware that this may lead to an `AttributeError: 'list' object has no attribute 'to'`. This occurs because the attention mask obtained from the dataloader is of list type rather than a torch tensor, and therefore lacks the 'to' function.

image

**Comment by patrickvonplaten** [comment]
cc @williamberman can you take a look here?

**Comment by williamberman** [comment]
Nice, makes sense!

**Review by williamberman — APPROVED** [review]

**Pull request merged**
