### PR TITLE
Integration tests precision improvement for inpainting

### LINKED ISSUE #914: Improve the precision of our integration tests
We currently have a rather low precision when testing our pipeline due to due reasons. 
1. - Our reference is an image and not a numpy array. This means that when we created our reference image we lost float precision which is unnecessary
2. - We only test for `.max() < 1e-2` . IMO we should test for `.max() < 1e-4` with the numpy arrays. In my experiements across multiple devices I have **not** seen differences bigger than `.max() < 1e-4` when using full precision.

IMO this could have also prevented: https://github.com/huggingface/diffusers/issues/902

### PR DESCRIPTION
**Pull request by Lewington-pitsos**
closes #914 

Currently all 11 related tests pass with `pytest tests\pipelines\stable_diffusion\test_stable_diffusion_inpaint.py tests\pipelines\stable_diffusion\test_stable_diffusion_inpaint_legacy.py -k test_stable_diffusion_inpaint` however they use my own huggingface dataset.

Waiting on [this dataset PR](https://huggingface.co/datasets/hf-internal-testing/diffusers-images/discussions/2) to be merged before we can update the URLs and merge this one.

Once this is merged I intend to apply the same strategy to improve other tests.

### CODE REVIEW

**Comment by Lewington-pitsos** [comment]
@patrickvonplaten I'm submitting this PR a little early, as I am not sure if anyone generally checks dataset PRs on huggingface, and I wanted to get your attention since at the moment you're still assigned to the issue.

**Comment by patrickvonplaten** [comment]
Hey @Lewington-pitsos this is a great PR! I'll accepted the change on https://huggingface.co/datasets/hf-internal-testing/diffusers-images/discussions/2 - thanks a mille for adding the datasets directly there. 

Also, sadly we cannot guarantee a precision of 1e-4 across devices, the best we can do seems to be 1e-3 as pointed out here:
https://github.com/huggingface/diffusers/issues/902#issuecomment-1297019244

**Comment by patrickvonplaten** [comment]
@Lewington-pitsos, if you're interesting we still need to change the integration tests for text2image and img2img from PIL images to numpy just like you've done here. Leaving https://github.com/huggingface/diffusers/issues/914 open for this

**Comment by Lewington-pitsos** [comment]
On it like a bonnet!

**Comment by patrickvonplaten** [comment]
Very cool - it's merged :-)

**Pull request merged**
