### PR TITLE
Add AuraFlowPipeline and KolorsPipeline to auto map

### PR DESCRIPTION
**Pull request by Beinsezii**
Just T2I. Validated using `quickdif`

Maybe we should sort the k/v list like the imports are?

### CODE REVIEW

**Comment by Skquark** [comment]
You forgot to add KolorsImg2ImgPipeline to the AutoPipelineForImage2Image... Also could add StableDiffusion3InpaintPipeline to AutoPipelineForInpainting while you're at it.  I did it in my fork since it was easy and needed for my personal implementation, but might as well make it official.  I could PR if needed, but was an easy one to include.

**Comment by yiyixuxu** [comment]
yes, can we add KolorsImg2ImgPipeline and StableDiffusion3Inpaint too? 🤗

**Comment by Beinsezii** [comment]
Kolors I2I and SD3 Inpaint added.

Runs well enough in my app.
demo using my pfp

**Comment by yiyixuxu** [comment]
thank you!

**Pull request merged**
