### PR TITLE
Add missing restore() EMA call in train SDXL script

### LINKED ISSUE #7549: Potential UNet EMA bug in `train_text_to_image_sdxl`
### Describe the bug

Hi, 

Am I seeing a bug here? https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py#L1198-L1201

At the end of each epoch we perform a validation step which involves having `ema_unet` store `unet`'s params temporarily, and then loading `ema_unet`'s params into `unet` since the latter is what is used in the `pipeline` class to perform validation. However, when that is done there is no call to `ema_unet.restore(unet.parameters())` in order to restore the original UNet's parameters. I would have expected that method call to be made at the end of this if block: 

https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_sdxl.py#L1192-L1253

Does that sound about right?

Thanks,
Chris

### Reproduction

N/A

### Logs

```shell
N/A
```

### System Info

N/A (reading off Github code here)

### Who can help?

_No response_

### PR DESCRIPTION
**Pull request by christopher-beckham**
# What does this PR do?

Super simple fix, train script for SDXL forgets to restore original U-Net parameters after each intermediate validation step.

Fixes #7549

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

@bghira

### CODE REVIEW

**Comment by bghira** [comment]
cc @sayakpaul @patil-suraj

**Comment by sayakpaul** [comment]
Thank you! Will merge after the CI is green.

**Comment by sayakpaul** [comment]
Could you pass an empty commit to retrigger the CI?

**Comment by christopher-beckham** [comment]
@sayakpaul fyi :) thanks

**Comment by sayakpaul** [comment]
The failing test is unrelated. So this PR is safe to be merged (cc: @yiyixuxu as we discussed this internally).

**Pull request merged**
