### PR TITLE
[ldm3d] Ldm3d-sr - upscaler

### PR DESCRIPTION
**Pull request by estelleafl**
We integrated ldm3d-sr, the upscaler of ldm3d
Thank your in advance for your reviews

### CODE REVIEW

**Comment by estelleafl** [comment]
Hi @sayakpaul, @patrickvonplaten,

Could you help me with this PR ? :) I would really appreciate your comments and advice.

I see that the check copy test is not passing but relates to files I didnt change. Could you help me to understand why?
Exception: Found the following copy inconsistencies:
- src/diffusers/pipelines/stable_diffusion/pipeline_stable_unclip.py: copy does not match pipelines.unclip.pipeline_unclip.UnCLIPPipeline._encode_prompt at line 170
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py: copy does not match models.unet_2d_blocks.DownBlock2D at line 1498
- src/diffusers/pipelines/versatile_diffusion/modeling_text_unet.py: copy does not match models.unet_2d_blocks.CrossAttnDownBlock2D at line 1587
Run `make fix-copies` or `python utils/check_copies.py --fix_and_overwrite` to fix them.

**Review by patrickvonplaten — COMMENTED** [review]
Hey @estelleafl,

Thanks a lot for the PR! Would it maybe be possible to instead move the PR to be used as a community pipeline: https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md#6-contribute-a-community-pipeline

We're currently not able to keep up with all the maintenance and our tests are getting too expensive. It might be easiest here to just add it as a single file community pipeline I think :-) 

Would this be ok for you?

**Comment by estelleafl** [comment]
Sounds good
Quick question: does it mean removing the documentation as well? Or just move the pipeline script and update the example/community readme?
Thanks

**Comment by patrickvonplaten** [comment]
> Hi @patrickvonplaten ! Thanks for your answer Quick questions: does it mean removing the documentation as well? Or just move the pipeline script and update the example/community readme? And then I remove the tests as well right? And dont you think it might be weird to have the ldm3d pipeline in the src and the ldm3d-sr in the example? Thanks

Yes I think we can remove the tests for now. The documentation should ideally be moved directly into the README here: https://github.com/huggingface/diffusers/blob/main/examples/community/README.md

I think it's fine to have one in src and the other one in community. We sadly have to limit the number of pipeline additions at the moment because tests and maintenance is exploding

**Comment by estelleafl** [comment]
Yes of course, I understand
Can we leave this PR open? Ill push the modifications here

**Comment by estelleafl** [comment]
I actually created a new PR https://github.com/huggingface/diffusers/pull/5870
I think we can close this one :)

**Pull request closed without merging**
