### PR TITLE
refactor onnxruntime integration

### PR DESCRIPTION
**Pull request by prathikr**
Moving all onnxruntime related code into examples/research_projects/onnxruntime

### CODE REVIEW

**Comment by prathikr** [comment]
@patrickvonplaten @anton-l can I please get reviews on this?

**Comment by prathikr** [comment]
@anton-l I ran `make style` and all my files were unchanged, some other files not authored by me were affected. Could you please take a look on your end and let me know if there is any other linting I need to do? Thanks

**Comment by patrickvonplaten** [comment]
cc @anton-l

**Comment by prathikr** [comment]
@patrickvonplaten @anton-l any updates?

**Comment by patrickvonplaten** [comment]
cc @anton-l @echarlaix

**Comment by prathikr** [comment]
@patrickvonplaten is there an ETA to get this reviewed/merged?

**Review by anton-l — APPROVED** [review]
The refactor looks great, thank you @prathikr!
The `black` version changed in the library dependencies, I've ran the style script with a newer one

**Pull request merged**
