### PR TITLE
adding more typehints to DDIM scheduler

### PR DESCRIPTION
**Pull request by vishnu-anirudh**
Adding more type hints to DDIM scheduler to make readability better.

### CODE REVIEW

**Comment by natolambert** [comment]
Hey @vishnu-anirudh, this looks great. Can you run `make quality` to get the last check to pass, then we should be good to merge this!

**Comment by vishnu-anirudh** [comment]
> 

Thank you @natolambert, yes `isort` did the trick.

**Review by patrickvonplaten — APPROVED** [review]
Thanks a lot!

**Comment by patrickvonplaten** [comment]
Hey @vishnu-anirudh,

Super sorry, I just noticed that we actually are making our schedulers framework-specific now (cc @kashif ) so that all arrays should not get a numpy type hint anymore. 

Very sorry :pray: 

@kashif could you maybe link your PR here so that maybe we can improve the type hints there once it's ready? :-)

**Comment by kashif** [comment]
Apologies! Please continue to check in to PR #534

**Comment by vishnu-anirudh** [comment]
Hello @patrickvonplaten 

That's not a problem. I am happy to fill in the gaps wherever required after this commit is merged.

**Pull request merged**
