### PR TITLE
[ONNX] Add additional inputs to OnnxStableDiffusionPipeline

### PR DESCRIPTION
**Pull request by PatriceVignola**
# What does this PR do?

This change adds additional inputs to `OnnxStableDiffusionPipeline` to support Stable Diffusion models that have additional inputs meant to override initializers (e.g. LoRA weights). It allows the user to change the weights without having to re-export the model or reloading the session.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@anton-l

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hmm I think this would break optimum at the moment, cc @echarlaix do you think this could make sense?

**Comment by PatriceVignola** [comment]
Would it? The new parameters are optional and the default value is the same behavior as the previous one (empty kwargs). Presumably it shouldn't change anything on the optimum side if they just don't use it.

**Comment by patrickvonplaten** [comment]
I'm not too sure how happy optimum would be with passing dicts around

**Comment by PatriceVignola** [comment]
They don't need to pass anything around though. This is an opt-in optional feature that users of the pipeline can use if they want to override initializers in their model. I didn't even use optimum to generate the model that I'm using for this pipeline, I'm not sure how it affects them.

**Comment by echarlaix** [comment]
> Hmm I think this would break optimum at the moment, cc @echarlaix do you think this could make sense?

Thanks a lot for letting me know @patrickvonplaten ! The issue I see here is that if users provide a non empty `text_encoder_additional_inputs`, inference will fail with the model exported with `optimum` (or [`diffusers`](https://github.com/huggingface/diffusers/blob/6b1abba18dce2eb169b6363ea5f626e7cd87cf21/scripts/convert_stable_diffusion_checkpoint_to_onnx.py#L95)) as the text encoder will only expect [`input_ids`](https://github.com/huggingface/optimum/blob/958fa661c930b3f23ff709407309863875878a8c/optimum/exporters/onnx/model_configs.py#L676) as inputs. Also not sure to understand what are the additional inputs concerned here (I only see [`attention_mask`](https://github.com/huggingface/diffusers/blob/v0.18.2/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L384) in the default pipeline which seems unrelated)

Also adding new dictionaries such as [`added_cond_kwargs`](https://github.com/huggingface/diffusers/blob/v0.18.2/src/diffusers/models/unet_2d_condition.py#L843) containing inputs needed during inference in the forward of components that needs to be traced could potentially break the optimum ONNX export (worth to be mentioned even though not related here)

**Comment by PatriceVignola** [comment]
Thanks for explaining. I understand that it would throw an error if the user somehow provides `text_encoder_additional_inputs` with a model that hasn't been post processed yet, but why would they? I thought this pipeline could be used for more than just models that come right out of Optimum.

For example, with [Olive](https://github.com/microsoft/Olive), we convert and optimize models that are meant to run the best they can on a multitude of execution providers. One pass that we plan to add is the possibility to supply LoRA weights at runtime without having to re-export the model or without hack into the model and overwrite the initializers. Having additional inputs allows us to do just that.

Would it be better to spin up another pipeline (e.g. `OnnxStableDiffusionWithLoraWeightsPipeline` or something else) that explicitly specifies what it's meant to be used for.

Either way, I appreciate the feedback!

**Comment by echarlaix** [comment]
> I thought this pipeline could be used for more than just models that come right out of Optimum.

Yes no needs for `diffusers` to only support ONNX models obtained through `optimum`, but because we want to ensure compatibility between `optimum.exporters.onnx` and `optimum.onnxruntime`, it's a non-negligeable possibility that these changes will not be applied in the `optimum` [pipelines](https://github.com/huggingface/optimum/blob/21943aa305c64c6db79af440b4a1152b64cad38b/optimum/onnxruntime/modeling_diffusion.py#L534) which could become default depending on whether it will be deprecated in `diffusers` in the future (cc @patrickvonplaten for that point)

**Comment by echarlaix** [comment]
> Would it be better to spin up another pipeline (e.g. OnnxStableDiffusionWithLoraWeightsPipeline or something else) that explicitly specifies what it's meant to be used for.

An option could be to check whether the corresponding inputs are expected by the ONNX model in case we want to avoid the case where unexpected inputs are given during inference. If it's not something we expect users to do, we can keep it as it is, I don't think it's worth adding a new pipeline for this.  I'll let the diffusers team decide the option they prefer.

**Pull request closed without merging**
