### PR TITLE
Fix slow tests

### PR DESCRIPTION
**Pull request by NouamaneTazi**
Fixes slow tests after the PR https://github.com/huggingface/diffusers/pull/371

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]

**Review by patil-suraj — APPROVED** [review]

**Comment by Birch-san** [comment]
@NouamaneTazi @patrickvonplaten, do you remember any details about why this needed to be reverted?

by my measurements (admittedly on CompVis): reintroducing `baddbmm` would make inference 19% faster on MPS:  
https://twitter.com/Birchlabs/status/1588703520433541120

was it the case that `tests/test_pipelines.py::PipelineTesterMixin::test_stable_diffusion_memory_chunking` went slower? did it do so on all platforms, or just on certain hardware (e.g. CUDA vs MPS, high vs low VRAM)? or this is only a problem when sliced attention is used, and we should prefer to use `baddbmm` for unsliced attention?

**Comment by patrickvonplaten** [comment]
Hey @Birch-san,

Good question! Now that we have strong unet testing we could maybe re-open this PR to see if it improves overall performance. 
However we need to be sure that it doesn't slow down any other use case such as ONNX, FP16 Torch, ...

What are your thoughts here @anton-l @pcuenca ?

**Comment by patrickvonplaten** [comment]
And @NouamaneTazi ?

**Comment by Birch-san** [comment]
Ah, lemme correct myself. the 19% speed increase was the outcome of **2** changes:

- changing the (q,k) matmul to baddbmm (as shown in this PR)
- changing the (attn, v) matmul below to a bmm(). not featured in this PR. the batched matmul was way faster than regular matmul on MPS.

**Comment by patil-suraj** [comment]
Think we could open a PR and do through tests for other cases as well. @NouamaneTazi would you like to tackle this ?

**Comment by pcuenca** [comment]
I agree we should open a new PR and explore this again :)

**Comment by Birch-san** [comment]
@patrickvonplaten @pcuenca @patil-suraj @NouamaneTazi  
I've restored the original `baddbmm`, added a new `bmm`, implemented for sliced attention, added fast-path to Decoder:  
https://github.com/huggingface/diffusers/pull/1203

**Pull request merged**
