### PR TITLE
scheduler timesteps as float32 instead of float64

### PR DESCRIPTION
**Pull request by drscotthawley**
Having the scheduler timesteps default to float64 type, when all other variables are float32, is unecessary. More importantly, it causes problems when running on Apple Silicon, since float64 is not implemented in MPS but float32 is.  

Changing "float" -> "np.float32" in one location is all I did.  This makes it consistent with the use of float32 in the rest of the code. 

# What does this PR do?

Fixes # (issue)

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a Github issue or the [forum](https://discuss.huggingface.co/)? Please add a link to it if that's the case.
No. This is a minor change.

- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/transformers/tree/main/docs#writing-source-documentation).
No, it's not that kind of change. 

- [ ] Did you write any new necessary tests?
No, it's not that kind of change. 

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

### CODE REVIEW

**Comment by drscotthawley** [comment]
About the first failed test:  
How can changing "float" to "np.float32" possibly cause the code formatter to fail??

**Comment by patrickvonplaten** [comment]
Yeah I tend to agree here. @pcuenca @sayakpaul @yiyixuxu any objections to changing everything to float32? Think we kept float64 at due to precision, but given the random results depending on which hardware is used, I doubt that float32 vs. float64 really makes a difference. 

If you agree, I think we change all float64 to float32

**Comment by sayakpaul** [comment]
Okay for me.

**Comment by bghira** [comment]
the extra precision is nice for terminal SNR with SNR gamma, otherwise you hit a divide by zero.

**Comment by patrickvonplaten** [comment]
@yiyixuxu can we maybe test here whether fp32 and fp64 give more or less the same results?

**Comment by yiyixuxu** [comment]
@drscotthawley 

it works mysteriously 
can we try `make style`?

**Comment by yiyixuxu** [comment]
added a test - seems ok 

Should we also update for `EulerAncestralDiscreteScheduler`, and `EulerDiscreteScheduler` ?

**Pull request closed without merging**
