### PR TITLE
Adding logging images to textual inversion. Issue 1837

### PR DESCRIPTION
**Pull request by isamu-isozaki**
This is the implementation of the idea of [this issue](https://github.com/huggingface/diffusers/issues/1837)
I added support for wandb if it is installed but will otherwise just log the images to args.output_dir/imgs/

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@patil-suraj @williamberman could you take a look here?

**Comment by isamu-isozaki** [comment]
sry, I'll fix the quality check in a bit

**Comment by patrickvonplaten** [comment]
Re-ping @patil-suraj @williamberman here

**Comment by isamu-isozaki** [comment]
Quality checks for the files inside examples/textual_inversion passed so I'm done with what I wanted to do I think.

**Comment by patrickvonplaten** [comment]
@patil-suraj can you check please?

**Review by patil-suraj — COMMENTED** [review]
Thanks a lot for the PR! Sorry to only come back to it now. The logic can be simplified a lot, for reference see 
https://github.com/huggingface/diffusers/blob/a66f2baeb782e091dde4e1e6394e46f169e5ba58/examples/dreambooth/train_dreambooth_lora.py#L910-L944

Could you please update the PR with a similar logic as above. Thanks :)

**Comment by isamu-isozaki** [comment]
@patil-suraj Thanks for the review! And will do

**Comment by isamu-isozaki** [comment]
@patil-suraj Should be fixed now! Tested with command
```
accelerate launch textual_inversion.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --train_data_dir='frida' --learnable_property="object" --placeholder_token="<frida>" --initializer_token="dog" --resolution=512 --train_batch_size=1 --gradient_accumulation_steps=4 --max_train_steps=3000 --learning_rate=5.0e-04 --scale_lr --lr_scheduler="constant" --lr_warmup_steps=0 --output_dir="textual_inversion_frida" --report_to="wandb" --validation_prompt="A photo of <frida>" --log_frequency=1 --revision="fp16" --mixed_precision="fp16" --enable_xformers_memory_efficient_attention
```
I needed to modify 1 line of StableDiffusionPipeline so that text_encoder's dtype is fine even with mixed_precision

**Pull request closed without merging**
