### PR TITLE
Fix DDIM on Windows not using int64 for timesteps

### PR DESCRIPTION
**Pull request by hafriedlander**
Same fix as already in pndm - https://github.com/huggingface/diffusers/blob/main/src/diffusers/schedulers/scheduling_pndm.py#L190

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Hey @hafriedlander,

Thanks a lot for the issue. In general, we tend to check the library much more with Linux or Mac, but we want to be better at providing full support for Windows as well. 

Just to understand better, do you know why we need to cast the int values to 64. 

In general this change seems fine to me though - what do you think @anton-l ?

**Comment by hafriedlander** [comment]
Windows numpy uses int32 values as the standard integer, regardless of platform. So timesteps becomes an array of int32.

We pass in individual timestep member into add_noise, and index alphas_cumprod with it. But you can't use an int32 as a tensor index in PyTorch, it complains. 

Linux defaults to int64 so you don't see it there. (This would probably also break on i386 Linux, just that there aren't many of those around any more :) )

**Comment by patrickvonplaten** [comment]
Thanks a lot for the explanation! Just wondering - isn't int32 the better dtype here? I cannot really think of a case where we would need a number higher than 2**31 for time steps ? Does this PR solve a use case that currently doesn't work?

**Comment by patrickvonplaten** [comment]
Also cc @anton-l

**Comment by hafriedlander** [comment]
This line fails with int32 https://github.com/huggingface/diffusers/blob/870878d24372b04a8e262f3ab2a9564e9691b7fd/src/diffusers/schedulers/scheduling_ddim.py#L308

PyTorch requires index tensors to be Long

**Comment by anton-l** [comment]
Makes sense @hafriedlander, thanks for checking!

**Pull request merged**
