### PR TITLE
Wider support for gelu. Remove unused activation. Use same torch layer for silu and swish

### PR DESCRIPTION
**Pull request by hypnopump**
Adds support for GeLU in modules where only `silu/swish` and `mish` were supported. Uses the same layer for `silu` and `swish` instead of a `lambda` definition for `swish` and the layer for `silu`

### CODE REVIEW

**Review by patrickvonplaten — COMMENTED** [review]
I think we should create a simple `activations.py` file as is done here: https://github.com/huggingface/transformers/blob/main/src/transformers/activations.py and import from there

**Comment by hypnopump** [comment]
Probably @patrickvonplaten but that would be more of a design choice, whereas this is a path to fix a current bug.

**Comment by patrickvonplaten** [comment]
cc @williamberman let's move all those activation functions into their own file

**Comment by patrickvonplaten** [comment]
@williamberman could you try to help move all the activation functions to their own filesL

**Comment by williamberman** [comment]
hey @hypnopump sorry for the delay! I put up a PR here just since this branch is a bit behind tip and has some failing ci. Happy to merge this PR as well if you want to rebase and cherry pick the commit from my branch or what not. Up to you! :) 

https://github.com/huggingface/diffusers/pull/3656

**Comment by hypnopump** [comment]
makes sense. im closing this then as functionality is implemented in your newer PR (left a review btw :)).

**Pull request closed without merging**
