### PR TITLE
[Core] fuse_qkv_projection() to Flux

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

Adds `fuse_qkv_projection()` support Flux. 

Will report the performance improvements soon. 

Batch size 1 (see footnote):

With fusion: 8.456 seconds (memory 25.25 GB)
Without fusion: 11.492 seconds (35.455 GB)

As a reminder, refer to [this comment](https://github.com/huggingface/diffusers/pull/8829/#issuecomment-2236254834) to understand the scope of when fusion is ideal. 

**Footnote**:

This was run on an A100. For quantization, we use "autoquant" from [`torchao`](https://github.com/pytorch/ao/). We are working on a repository to show the full-blown recipes. It will be made open in a day's time.

### CODE REVIEW

**Comment by yiyixuxu** [comment]
awesome, but I think we will have to update once the refactor PR is in since I combined the attention processors there https://github.com/huggingface/diffusers/pull/9074

**Comment by sayakpaul** [comment]
100 percent right. I will repurpose once your PR is in :)

**Comment by sayakpaul** [comment]
@yiyixuxu could you give this a look? I face adjusted it accordingly with https://github.com/huggingface/diffusers/pull/9074.

**Review by yiyixuxu — APPROVED** [review]
PR looks good to me
Can we run a actual test to see the improvement before merge? feel free to merge once that's done

**Comment by sayakpaul** [comment]
Check the PR [description](https://github.com/huggingface/diffusers/pull/9185#issue-2467883991):

```
Batch size 1 (see footnote):

With fusion: 8.456 seconds (memory 25.25 GB)
Without fusion: 11.492 seconds (35.455 GB)

As a reminder, refer to https://github.com/huggingface/diffusers/pull/8829/#issuecomment-2236254834 to understand the scope of when fusion is ideal.

Footnote:

This was run on an A100. For quantization, we use "autoquant" from [torchao](https://github.com/pytorch/ao/). We are working on a repository to show the full-blown recipes. It will be made open in a day's time.
```

**Comment by yiyixuxu** [comment]
@sayakpaul ahh I missed it! sorry! very nice!

**Comment by ngaloppo** [comment]
@sayakpaul This feature doesn't seem to work together with torchao quantization. Is that expected?

**Comment by sayakpaul** [comment]
Please redirect the issue to https://github.com/sayakpaul/diffusers-torchao

**Pull request merged**
