### PR TITLE
add sample_mode argument to prepare_latens in SD and SDXL img2img pipelines

### PR DESCRIPTION
**Pull request by noskill**
# What does this PR do?

add sample_mode argument to prepare_latens in SD and SDXL

prepare_latens calls retrieve_latents function which already has this argument

## Who can review?

 @sayakpaul @DN6

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Works for me. Thanks!

**Comment by noskill** [comment]
@sayakpaul i also added add_noise to prepare_latents in SD pipeline to make it match SDXL one

**Review by yiyixuxu — COMMENTED** [review]
why is this needed?
these methods are only meant to be called in the pipeline, and these particular pipelines do not need to set a special value for sample_mode or add_noise

**Comment by noskill** [comment]
Actually it makes sense to pass different sample modes to this particular pipelines. It will produce valid images with latents initialised from mode or mean instead of sampling from distribution.

Also i am refactoring this pipeline and making SDXL version https://github.com/huggingface/diffusers/blob/main/examples/community/masked_stable_diffusion_img2img.py

For example this code can be replaced with call to prepare_latents https://github.com/huggingface/diffusers/blob/ae05050db9d37d5af48a6cd0d6510a5ffb1c1cd4/examples/community/masked_stable_diffusion_img2img.py#L160C1-L163C10

**Comment by noskill** [comment]
Is it possible that mode of distribution in vae is not equal to mean btw?

**Comment by noskill** [comment]
With copy-pasting there is no code reuse, for example all the pipelines have to be updated when someone implemented clip_skip or any other bugfix. I would really prefer such changes to be automatically applied to any pipeline i implement.

**Comment by yiyixuxu** [comment]
you can read our design philosophy here https://huggingface.co/docs/diffusers/v0.27.2/en/conceptual/philosophy#design-philosophy-in-details

You are the owner of the community pipeline and we will let you make your design decisions :) but it will be harder to maintain this way, that's all 

for this PR we cannot accept since it is not aligned with our design principles

**Comment by noskill** [comment]
I have read that page, but it's a bit vague tbh. For example there is "Pipelines follow the single-file policy." but clearly all the pipelines use a lot of imported code.

**Pull request closed without merging**
