### PR TITLE
Fix running LoRA with xformers

### PR DESCRIPTION
**Pull request by bddppq**
#2247 
#2124 

```python
from diffusers import DiffusionPipeline

pipe = DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-2-1")
pipe.unet.load_attn_procs(lora_dir)
pipe.to('cuda:2')

prompt = 'a cute cat'

image = pipe(prompt, guidance_scale=9, num_inference_steps=25).images[0]
image.save('1.png')

pipe.enable_xformers_memory_efficient_attention()
image = pipe(prompt, guidance_scale=9, num_inference_steps=25).images[0]
image.save('2.png')

pipe.disable_xformers_memory_efficient_attention()
image = pipe(prompt, guidance_scale=9, num_inference_steps=25).images[0]
image.save('3.png')
```

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
Great job @bddppq ! This looks exactly like it should :-)

**Comment by patrickvonplaten** [comment]
Could we maybe add one quick tests that ensures that the two implementations are identical. It should be pretty easy to add as this test:
1. Copy-paste this test: https://github.com/huggingface/diffusers/blob/fd5c3c09afe29cbbde42cfa791ca598a07d94da9/tests/models/test_models_unet_2d_condition.py#L388 and give it a new name with "xformers" in it
2. Verify that xformers on/off gives same results 

That would be amazing!

Also happy to do it if you're too busy #1877

**Comment by patrickvonplaten** [comment]
Thanks a lot!

**Comment by juancopi81** [comment]
I found this issue while noticing that my inference times also increased after loading a LoRA. I am using a LoRA from civitai:

`pipe.load_lora_weights("/path/to/lora/", weight_name = 'add_detail.safetensors')`

Is it normal that now inference takes longer? Should I load the model differently? It is not clear for me from the example if I should first run the model without xformers and then activate it.

Thank you very much!

**Comment by juancopi81** [comment]
Nevermind! I found 

`pipe.fuse_lora()` 

and this worked!

**Pull request merged**
