### PR TITLE
[Test] Add DeepCache support for Stable Diffusion Pipeline.

### PR DESCRIPTION
**Pull request by kadirnar**
Code:

```python
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    'SG161222/Realistic_Vision_V5.1_noVAE',
    custom_pipeline="deepcache_stable_diffusion",
    torch_dtype=torch.float16
)
pipe=pipe.to("cuda")
``` 

Error Message:
```bash
HfHubHTTPError: 404 Client Error: Not Found for url: https://raw.githubusercontent.com/huggingface/diffusers/main/examples/community/deepcache_stable_diffusion.py
```

@patrickvonplaten , @sayakpaul ,[yiyixuxu](https://github.com/yiyixuxu)

Why am I getting this error? How can I solve it?

### CODE REVIEW

**Comment by sayakpaul** [comment]
That is because "https://raw.githubusercontent.com/huggingface/diffusers/main/examples/community/deepcache_stable_diffusion.py" doesn't exist in reality. You will need to pass a local path here.

**Comment by kadirnar** [comment]
> That is because "https://raw.githubusercontent.com/huggingface/diffusers/main/examples/community/deepcache_stable_diffusion.py" doesn't exist in reality. You will need to pass a local path here.

Can you share sample code? I couldn't run the code.

Testv1:
Code:
```python
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    pretrained_model_name_or_path='SG161222/Realistic_Vision_V5.1_noVAE',
    custom_pipeline="examples/community/deepcache/deepcache_stable_diffusion",
    torch_dtype=torch.float16
)
pipe=pipe.to("cuda")
print("Loaded model")
```
Error Message:
```
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'examples/community/deepcache/deepcache_stable_diffusion'. Use `repo_type` argument if needed.
```

Testv2:

HF Model Link: https://huggingface.co/kadirnar/deepcache_stable_diffusion
```python
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    pretrained_model_name_or_path='SG161222/Realistic_Vision_V5.1_noVAE',
    custom_pipeline="kadirnar/deepcache_stable_diffusion",
    torch_dtype=torch.float16
)
pipe=pipe.to("cuda")
print("Loaded model")
```
Error Message:
```
Entry Not Found for url: https://huggingface.co/kadirnar/deepcache_stable_diffusion/resolve/main/auto_pipeline.py.
```

**Comment by patrickvonplaten** [comment]
Hey @kadirnar,

Can we for now add DeepCache just as a research project? Adding it to "src/diffusers" will require too many file changes

**Comment by kadirnar** [comment]
> Hey @kadirnar,
> 
> Can we for now add DeepCache just as a research project? Adding it to "src/diffusers" will require too many file changes

I think you should look into this. DeepCache could be a great feature.
https://github.com/huggingface/diffusers/issues/6193#issuecomment-1859571170

**Pull request closed without merging**
