### PR TITLE
Harmonize HF environment variables + deprecate use_auth_token

### PR DESCRIPTION
**Pull request by Wauplin**
(Similar to https://github.com/huggingface/transformers/pull/27564. Sorry in advance for the size of the diff, I hope it'll be ok :) )

This PR aims at harmonizing environment variables in the HF ecosystem (following up on https://github.com/huggingface/huggingface_hub/pull/1786). I also took the time to review the integration of `huggingface_hub` into `diffusers` to update to latest "standard". I tried to break nothing -staying at iso-feature- but the review will be much appreciated :smile:. The overall goal is simply to have less duplication in the codebase.

List of changes:
1. Remove usage of `use_auth_token` in favor of `token` everywhere and in a backward-compatible way. To do do I used the [`@validate_hf_hub_args`](https://huggingface.co/docs/huggingface_hub/v0.19.3/en/package_reference/utilities#generic-decorator) decorator that checks which of `use_auth_token` and/or `token` are passed. For now using `use_auth_token` do not raise a warning but it will in the future. The goal is to slowly adapt scripts before deprecating officially. And the deprecation will only have to happen in `huggingface_hub` thanks to the decorator.
2. Remove references to `use_auth_token=True`. This is not necessary anymore since the token is always passed to the server by default (already the case since ~1y ago).
3. Do not set `local_files_only` to `HF_HUB_OFFLINE` by default. This is already done in `huggingface_hub` (less duplicated code)
4. Do not set `cache_dir` to `DIFFUSERS_CACHE` by default. This is already done in `huggingface_hub` (less duplicated code)
5. Remove `DIFFUSERS_CACHE` which is strictly equal to `HF_HUB_CACHE` (shared with other libraries)
6. Do not parse constant values `HF_HUB_OFFLINE` and `DISABLE_TELEMETRY` from environment variables but use `huggingface_hub` values instead
7. Use `huggingface_hub.constants.HF_HOME` instead of `huggingface_hub.constants.hf_cache_home`
8. Use `huggingface_hub.get_full_repo_name` (instead of defining it in diffusers)
9. Add static typing to `_get_model_file` (that one was for myself - it looks like a heavily used method)

 
And that's it. Mostly cleaning some stuff in a backward-compatible way to remove duplicated work. Sorry in advance for the tedious review :see_no_evil:

### CODE REVIEW

**Comment by kopyl** [comment]
Why did you think that removing this arg is a good idea?

**Review by patrickvonplaten — APPROVED** [review]
That looks great - thanks for all the effort!

**Comment by kopyl** [comment]
@patrickvonplaten Why do you think that removing use_auth_token arg is a good idea?

**Comment by kopyl** [comment]
@patrickvonplaten also why do you approve this commit with not all checks passed?

**Comment by Wauplin** [comment]
@kopyl Argument `use_auth_token` will still work normally on all diffusers methods and will have the exact same behavior as before. So don't expect any breaking changes in the short-term. On the long term it will be deprecated and then completely removed in favor of `token` that has the exact same behavior. The goal is to harmonize parameter names across our libraries which should benefit users in the long run.

Regarding CI checks I guess the failing error was unrelated to this PR.

**Pull request merged**
