### PR TITLE
Set main_input_name in StableDiffusionSafetyChecker to "clip_input"

### PR DESCRIPTION
**Pull request by clinty**
FlaxStableDiffusionSafetyChecker sets main_input_name to "clip_input". This makes StableDiffusionSafetyChecker consistent.

### CODE REVIEW

**Comment by pcuenca** [comment]
Hi @clinty! Thanks for the contribution. However, I'd like to understand what purpose it serves or how you expect this to be used. Unlike in the `transformers` codebase, `main_input_name` is not used in `diffusers` (except for some tests). Are you experiencing any shortcomings because it's not defined in `StableDiffusionSafetyChecker`?

**Comment by clinty** [comment]
@pcuenca only confusion on my part when I checked the value and found it to be `input_ids` and not one of the two valid inputs.  I am not aware of any code which is using this.

**Comment by pcuenca** [comment]
Ah, it's set to a default value. In that case I'd support changing it to avoid confusion. I triggered a CI run, copying  @sayakpaul as this affects the PyTorch implementation

**Review by pcuenca — APPROVED** [review]
LGTM as long as tests pass.

**Comment by clinty** [comment]
The test failure has the appearance of something transient.

**Pull request merged**
