### PR TITLE
[SDXL-IP2P] Add gif for demonstrating training processes

### PR DESCRIPTION
**Pull request by harutatsuakiyama**
Previously was asked to provide more information about the findings when training the Instruct Pix2Pix SDXL version, which has now been updated in the README_sdxl.md document.

### CODE REVIEW

**Comment by harutatsuakiyama** [comment]
@sayakpaul More training details of IP2P SDXL. Let me know if more contents are required.

**Review by sayakpaul — APPROVED** [review]
Thank you! We would still need a good checkpoint for InstructPix2Pix (SDXL compatible) for folks to try things out. 

Also, for assets, please create a PR to https://huggingface.co/datasets/huggingface/documentation-images.

**Comment by harutatsuakiyama** [comment]
@sayakpaul Thank you! The assets have been uploaded to https://huggingface.co/datasets/huggingface/documentation-images/discussions/144/files. Once merged, I will update the two gifs with the hosted links. 

Can you give me a location to upload the checkpoint?

**Comment by sayakpaul** [comment]
We can do something similar to https://huggingface.co/timbrooks/instruct-pix2pix

**Comment by harutatsuakiyama** [comment]
It seems that the GIF cannot be showed here. What can be the reason? https://github.com/harutatsuakiyama/diffusers/blob/06816a8cdde7bd0fb25a8bbeb1ebe0a4b987db30/examples/instruct_pix2pix/README_sdxl.md

**Comment by sayakpaul** [comment]
Probably because they're too big (22 MBs). Could we optimize the GIFs a bit?

**Comment by harutatsuakiyama** [comment]
> Probably because they're too big (22 MBs). Could we optimize the GIFs a bit?

Compressed the GIFs: https://huggingface.co/datasets/huggingface/documentation-images/discussions/145

If still don't work, will reduce the number of images in GIF

**Comment by harutatsuakiyama** [comment]
Still not show GIFs. Make them even smaller (2 MB): https://huggingface.co/datasets/huggingface/documentation-images/discussions/146

If still not work, will use images rather than GIFs.

**Comment by harutatsuakiyama** [comment]
The URL seems to work :-) If possible, please merge this PR.

**Comment by sayakpaul** [comment]
Thank you for your work!

**Pull request merged**
