### PR TITLE
Handle batches and Tensors in `pipeline_stable_diffusion_inpaint.py:prepare_mask_and_masked_image`

### PR DESCRIPTION
**Pull request by vict0rsch**
Addresses #1000 

Not sure what your code conventions are, I've been quite verbose in comments

### CODE REVIEW

**Comment by vict0rsch** [comment]
Not sure why `black` isn't happy. Locally I see:

```
~/Documents/Github/vict0rsch/diffusers on  main ⌚ 15:42:20
$ black  --check --preview examples tests src utils scripts
All done! ✨ 🍰 ✨
174 files would be left unchanged.
```

**Comment by patrickvonplaten** [comment]
In general this is ok for me! @patil-suraj could you also take a look?

**Comment by patrickvonplaten** [comment]
Regarding the `black` failure, could you maybe update your black version:
```
pip install --upgrade black
```

and then run `make black` again?

**Comment by patrickvonplaten** [comment]
Regarding the `black` failure, could you maybe update your black version:
```
pip install --upgrade black
```

and then run `make black` again?

Also could we add one test that shows how the code changes now work? You can add a test under tests/pipelines/stable_diffusion/pipeline_inpaint.py

**Comment by patrickvonplaten** [comment]
Hey @vict0rsch, 

We can fix `black` if you want :-) 

Could you maybe add a test that show-cases how this PR fixes something that currently doesn't work?

**Comment by patrickvonplaten** [comment]
We already allow to pass images at pytorch tensors I think so I'm wondering whether we need to take care of this here

**Comment by vict0rsch** [comment]
Hey sorry I got busy and forgot because I have a cloned and patched local version. I'm going to work on this

**Comment by vict0rsch** [comment]
@patrickvonplaten do you mean a new `tests/pipelines/stable_diffusion/pipeline_inpaint.py` or do you refer to the existing `tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py` ?

**Comment by vict0rsch** [comment]
I'm assuming you'll resolve conflicts?

**Comment by vict0rsch** [comment]
Actually I see tests are still not happy with `black` it's very weird because after upgrading to the latest `black` I continue to see

```
$ black  --check --preview examples tests src utils scripts
All done! ✨ 🍰 ✨
174 files would be left unchanged.
```

But the tests expect something different, on files I have not touched...

```
Run black  --check --preview examples tests src utils scripts
  black  --check --preview examples tests src utils scripts
  isort --check-only examples tests src utils scripts
  flake8 examples tests src utils scripts
  doc-builder style src/diffusers docs/source --max_len 119 --check_only --path_to_docs docs/source
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.7.15/x64
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.7.15/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.15/x64
    Python[2](https://github.com/huggingface/diffusers/actions/runs/3483685264/jobs/5827440704#step:5:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/huggingface/diffusers/actions/runs/3483685264/jobs/5827440704#step:5:3).7.15/x6[4](https://github.com/huggingface/diffusers/actions/runs/3483685264/jobs/5827440704#step:5:4)
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.7.1[5](https://github.com/huggingface/diffusers/actions/runs/3483685264/jobs/5827440704#step:5:5)/x[6](https://github.com/huggingface/diffusers/actions/runs/3483685264/jobs/5827440704#step:5:6)4
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.[7](https://github.com/huggingface/diffusers/actions/runs/3483685264/jobs/5827440704#step:5:7).15/x64/lib
would reformat examples/community/imagic_stable_diffusion.py
would reformat examples/community/lpw_stable_diffusion.py
would reformat examples/community/lpw_stable_diffusion_onnx.py
would reformat examples/textual_inversion/textual_inversion.py
would reformat examples/textual_inversion/textual_inversion_flax.py

Oh no! 💥 💔 💥
5 files would be reformatted, 2[11](https://github.com/huggingface/diffusers/actions/runs/3483685264/jobs/5827440704#step:5:11) files would be left unchanged.
Error: Process completed with exit code 1.
```

**Comment by vict0rsch** [comment]
Couple remarks:

* may want to use it in `pipeline_onnx_stable_diffusion_inpaint.py` too
* it's confusing that the input is `(image, mask)` but the output is `(mask, masked_input)`

**Comment by vict0rsch** [comment]
13 tests pass with 

```
pytest tests/pipelines/stable_diffusion/test_stable_diffusion_inpaint.py -k "StableDiffusionInpaintingPrepareMaskAndMaskedImageTests"
```

**Comment by patrickvonplaten** [comment]
Thanks @vict0rsch - cool that you added all these tests

**Pull request merged**
