### PR TITLE
[Core] remove `resume_download` from Hub related stuff

### PR DESCRIPTION
**Pull request by sayakpaul**
# What does this PR do?

To not have to incur:

```bash
huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
```

### CODE REVIEW

**Review by Wauplin — COMMENTED** [review]
Thanks for taking care of removing those @sayakpaul. I'm linking https://github.com/huggingface/diffusers/pull/7843 and https://github.com/huggingface/diffusers/pull/8267 which are related PRs (the ones that should have already removed the deprecation warnings). Removing `resume_download` altogether is even better since it'll also us to remove it from `huggingface_hub` in the future.

Last thing: do you want to remove `resume_download` mention from docstrings as well? We have [this message](https://github.com/huggingface/diffusers/blob/fa2abfdb0387fe090f21f40f800ffcb9d28278ad/src/diffusers/configuration_utils.py#L313) for now but if we remove them already, then let's remove the docs as well?

**Review by Wauplin — APPROVED** [review]
Thanks for taking care of removing those @sayakpaul. I'm linking https://github.com/huggingface/diffusers/pull/7843 and https://github.com/huggingface/diffusers/pull/8267 which are related PRs (the ones that should have already removed the deprecation warnings). Removing `resume_download` altogether is even better since it'll also us to remove it from `huggingface_hub` in the future.

Last thing: do you want to remove `resume_download` mention from docstrings as well? We have [this message](https://github.com/huggingface/diffusers/blob/fa2abfdb0387fe090f21f40f800ffcb9d28278ad/src/diffusers/configuration_utils.py#L313) for now but if we remove them already, then let's remove the docs as well?

**Comment by DN6** [comment]
@sayakpaul  We can merge once the conflicts are resolved here

**Comment by sayakpaul** [comment]
Failing tests are unrelated.

**Pull request merged**
