### PR TITLE
Fix broken controlnet loading from checkpoints (after the SD XL change), by accepting extra args in a kwargs dict

### PR DESCRIPTION
**Pull request by cmdr2**
Fixes the `__init__() got an unexpected keyword argument 'addition_embed_type'` error when loading a controlnet from a checkpoint. E.g.

```py
from diffusers.pipelines.stable_diffusion.convert_from_ckpt import download_controlnet_from_original_ckpt

controlnet = download_controlnet_from_original_ckpt(
    "models/controlnet/control_v11p_sd15_canny.pth", "models/controlnet/control_v11p_sd15_canny.yaml", device="cpu"
)
```

This is because `addition_embed_type` and `addition_time_embed_dim` aren't known to the constructor of `ControlNetModel`. These two fields were added in the recent SD XL change:  https://github.com/huggingface/diffusers/commit/bc9a8cef6f258aafcd43ef64ac161218a7eae43a#diff-0613bbbcc958a37615e7638e09307201784c90c2661611f745fe4f67f68f51efR314-R315

Constructor call for `ControlNetModel`: https://github.com/huggingface/diffusers/blob/bfe8b4131505d4ee722276abfe1d752234ffd465/src/diffusers/pipelines/stable_diffusion/convert_from_ckpt.py#L1058

I don't know if these fields should be implemented in the ControlNetModel (not knowledgeable-enough about this topic). So I propose that we catch extra args from the unet config in a `kwargs` in the meanwhile. This will help unblock loading controlnets from checkpoints in diffusers 0.18.2

@patrickvonplaten @sayakpaul 

Thanks!

### CODE REVIEW

**Comment by cmdr2** [comment]
Or we could delete the unsupported fields in the dict before calling the constructor.

**Review by sayakpaul — COMMENTED** [review]
Works for me. 

Actually, we're working on adding ControlNet support for SDXL here: https://github.com/huggingface/diffusers/pull/4038. So, maybe let's hold off until it gets merged? 

Would be great if you could do a conversion test basing your code from that above-mentioned PR. 

Let us know :)

**Comment by patrickvonplaten** [comment]
> Or we could delete the unsupported fields in the dict before calling the constructor.

I think this solution would be a bit better actually

**Comment by cmdr2** [comment]
@patrickvonplaten Made the change as you suggested. This might also fix #4101 , but not sure if this bug has already been fixed.

Thanks!

**Review by patrickvonplaten — APPROVED** [review]
Great!

**Review by sayakpaul — COMMENTED** [review]
Thanks for this work but we recently added these arguments in `ControlNetModel`: https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/controlnet.py

Does installing from source help resolve the issue? :)

**Comment by cmdr2** [comment]
Ah nice! That's even better.

I had a feeling that this got resolved (looking at the comment in other issue), but no harm done (just a few lines of code in this PR) :)

Thanks for the quick resolution! Closing this PR.

**Comment by sayakpaul** [comment]
> Ah nice! That's even better.
> 
> I had a feeling that this got resolved (looking at the comment in other issue), but no harm done (just a few lines of code in this PR) :)
> 
> Thanks for the quick resolution! Closing this PR.

Appreciate your understanding :)

**Pull request closed without merging**
