### PR TITLE
Animatediff Controlnet Community Pipeline IP Adapter Fix

### PR DESCRIPTION
**Pull request by AbhinavGopal**
# What does this PR do?
The animatediff controlnet community pipeline had a small bug that supplied an incorrect parameter to encode_image. I pushed the fix for it.

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [X] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [X] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?
@sayakpaul @yiyixuxu @DN6 @a-r-r-o-w

### CODE REVIEW

**Comment by sayakpaul** [comment]
Could you also tag the author who contributed the pipeline for a review?

**Comment by a-r-r-o-w** [comment]
This is bizarre, I'm not sure how it even passed locally in the other PR! The issue comes from encode_image not being the latest implementation. It seems like `# Copied from` has no effect for community pipelines.

The changes in this PR are incorrect btw. For both AnimateDiff controlnet/img2vid, could you update the encode_image function to this:

https://github.com/huggingface/diffusers/blob/3e1097cb63c724f5f063704df5ede8a18f472f29/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py#L468

**Comment by a-r-r-o-w** [comment]
@sayakpaul @yiyixuxu From a quick look at the `utils/check_copies.py` script, it does not seem like the community folder falls in the "Copied From" checks. Could you verify if that's the case, and if yes, may I open a PR adding community folder to it? I believe some things might break and need fixing due to overlaps with the latest implementations.

**Comment by sayakpaul** [comment]
Yeah we don't don't copy checks on community pipelines.

**Comment by AbhinavGopal** [comment]
Fixed as requested above. It's a bit weird though, as this optional variable is never used in the encode_image function.

**Comment by a-r-r-o-w** [comment]
> Fixed as requested above. It's a bit weird though, as this optional variable is never used in the encode_image function.

Please copy the entire function body of encode_image. Please also do it from animatediff img2vid in this PR if possible as both pipelines suffer from common issue.

**Comment by AbhinavGopal** [comment]
Gotcha! And the error doesn't seem to be there for the img2video pipeline

**Comment by a-r-r-o-w** [comment]
> Gotcha! And the error doesn't seem to be there for the img2video pipeline

Oh I see, I'm looking at my local branches that were not synced and comparing against here. Looks good to go now! Thanks

Would be great if you could run the example code and verify if everything's working again

**Comment by AbhinavGopal** [comment]
Seems to work!

**Comment by a-r-r-o-w** [comment]
cc @DN6

**Pull request merged**
