### PR TITLE
Fix several imports

### PR DESCRIPTION
**Pull request by standardAI**
This pull request fixes several imports in the codebase. Specifically, it removes unnecessary `StableDiffusionSafetyChecker` import and updates the import path for `dummy_pt_objects`.
@sayakpaul @yiyixuxu @DN6

### CODE REVIEW

**Comment by sayakpaul** [comment]
> Specifically, it removes unnecessary StableDiffusionSafetyChecker import

Why is it an unnecessary import?

**Comment by standardAI** [comment]
Because I saw that [it is imported from its file](https://github.com/standardAI/diffusers/blob/e23c27e90524c3c3e93525d03f18408b84372012/src/diffusers/pipelines/stable_diffusion/__init__.py#L129) as well.

**Comment by standardAI** [comment]
@sayakpaul, wasn't it?

**Review by yiyixuxu — APPROVED** [review]
thanks!

**Comment by standardAI** [comment]
Thanks for merging!

**Pull request merged**
