### PR TITLE
[WIP] [Core] Add support for ControlNet LoRA 

### LINKED ISSUE #5800: [Control-LoRA] Picking Control-LoRA up again
Stability AI's Control LoRA has been around for a while: https://huggingface.co/stabilityai/control-lora. 

We also have had requests for it, e.g., https://github.com/huggingface/diffusers/issues/4679. 

I even started working on it: https://github.com/huggingface/diffusers/pull/4899, but I couldn't reproduce the results. I have tried debugging it from the ComfyUI codebase, too, but couldn't actually find any non-trivial differences. 

Would be great if someone from the community picked it up. Especially cc: @HighCWu (because of https://github.com/HighCWu/control-lora-v2).

### PR DESCRIPTION
**Pull request by shauray8**
# What does this PR do?

Adds support for ControlNet LoRA. continuing on @sayakpaul design #4899 

Fixes #5800

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## The current design
Load things 

```py
from diffusers import (
    StableDiffusionXLControlNetPipeline, 
    ControlNetModel, 
    UNet2DConditionModel
)
import torch

pipe_id = "stabilityai/stable-diffusion-xl-base-1.0"
lora_id = "stabilityai/control-lora"
lora_filename = "control-LoRAs-rank128/control-lora-canny-rank128.safetensors"


unet = UNet2DConditionModel.from_pretrained(pipe_id, subfolder="unet", torch_dtype=torch.float16).to("cuda")
controlnet = ControlNetModel.from_unet(unet).to(device="cuda", dtype=torch.float16)
controlnet.load_lora_weights(lora_id, weight_name=lora_filename, controlnet_config=controlnet.config)
```
Infer
```py
from diffusers import AutoencoderKL
from diffusers.utils import load_image, make_image_grid
from PIL import Image
import numpy as np
import cv2

prompt = "aerial view, a futuristic research complex in a bright foggy jungle, hard lighting"
negative_prompt = "low quality, bad quality, sketches"

image = load_image("https://huggingface.co/datasets/hf-internal-testing/diffusers-images/resolve/main/sd_controlnet/hf-logo.png")

controlnet_conditioning_scale = 0.5  # recommended for good generalization

vae = AutoencoderKL.from_pretrained("madebyollin/sdxl-vae-fp16-fix", torch_dtype=torch.float16)
pipe = StableDiffusionXLControlNetPipeline.from_pretrained(
    pipe_id,
    unet=unet,
    controlnet=controlnet,
    vae=vae,
    torch_dtype=torch.float16,
).to("cuda")

image = np.array(image)
image = cv2.Canny(image, 100, 200)
image = image[:, :, None]
image = np.concatenate([image, image, image], axis=2)
image = Image.fromarray(image)

images = pipe(
    prompt, negative_prompt=negative_prompt, image=image,
    controlnet_conditioning_scale=controlnet_conditioning_scale,
    num_images_per_prompt=4
).images

final_image = [image] + images
grid = make_image_grid(final_image, 1, 5)
grid
```

## Who can review?
@sayakpaul can you provide me with access to [the notebook you mentioned](https://colab.research.google.com/drive/1S-NDshYL7N4S1ugF9Y86d3SRY-Fe0Qe-?usp=sharing)

### CODE REVIEW

**Comment by sayakpaul** [comment]
Here you go: https://colab.research.google.com/drive/1S-NDshYL7N4S1ugF9Y86d3SRY-Fe0Qe-?usp=sharing

**Comment by George0726** [comment]
Hi folks, are there any other updates on the PR?

**Comment by andypotato** [comment]
+1 for this

**Comment by sayakpaul** [comment]
We don't have the bandwidth for this at the moment and hence https://github.com/huggingface/diffusers/pull/4899

**Comment by AbnerCSZ** [comment]
controlnet = ControlNetModel.from_unet(unet).to(device="cuda", dtype=torch.float16)
controlnet.load_lora_weights(lora_id, weight_name=lora_filename, controlnet_config=controlnet.config)

The following error occurred during runtime: 
**AttributeError: 'ControlNetModel' object has no attribute 'load_lora_weights'**
Is this due to a version issue? May I know which version you are using? My running version is as follows:
diffusers                     0.27.0.dev0
transformers                  4.35.2

**Comment by sayakpaul** [comment]
This feature hasn't been shipped yet.

**Comment by AbnerCSZ** [comment]
> This feature hasn't been shipped yet.

Is there a test version that has been implemented that can be used? thanks！

**Comment by bghira** [comment]
@sayakpaul maybe this can come back sometime

**Comment by a-r-r-o-w** [comment]
Thanks for reminding about this @bghira! I'm going to take a look at this soon considering we now are working on adding support for Flux Control LoRA

**Comment by sayakpaul** [comment]
Just flagging some differences so that we don't conflate ControlNet LoRA (from SAI) and what BFL has released (Flux Control LoRA):

1. SAI's version is like so:
   a. Initialize a ControlNet from the weights of the denoiser. 
   b. Add LoRA layers.
   c. Train the LoRA layers. 
   d. Their pipeline is actually a ControlNet pipeline i.e., during denoising we leverage two things: the ControlNet (with LoRA added) module as well as the denoiser.

2. OTOH, BFL is doing something different (it's more akin to how regular img2img is done but with differences) 
   a. Expand the input dimension of the denoiser. First half is pre-trained weights and the rest is initialized to zeros. 
   b. Add LoRA layers to the attention layers (and others) including the input embedding layer (`img_in`) and train them. 
   c. During inference, compute the condition of a given image (depth condition, for example), encode it with the VAE's encoder, and then do regular img2img. There is NO separate ControlNet module involved. 

Hope that helps clear out the differences a bit.

**Pull request closed without merging**
