### PR TITLE
Update PEFT requirement to 0.9.0 with DoRA implementation.

### LINKED ISSUE #7296: Update PEFT required version for advaced_diffusion_training to 0.9.0 to fix DoRA dependency
### Describe the bug

DoRA, which was implemented quite recently, breaks runtime by calling itself into PEFT class LoraConfig, which incorporates DoRA only from 0.9.0 version.

I will submit a PR to fix it and fix documentation.

### Reproduction

Every time.

### Logs

_No response_

### System Info

PEFT 0.7.0 version.

### Who can help?

_No response_

### PR DESCRIPTION
**Pull request by NorilskMajor**
# What does this PR do?

Update required PEFT version to make DoRA work (specifically LoraConfig class call).

Fixes #7296 

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [x] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ ] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by NorilskMajor** [comment]
@sayakpaul

**Comment by NorilskMajor** [comment]
My first PR here, please feel free to tell me if anything is wrong with it!

**Comment by sayakpaul** [comment]
We already specify that `peft` needs to be installed from the source for using DoRA. Cc: @linoytsaban

**Comment by NorilskMajor** [comment]
I see now! However one need to install from source regardless if they want DoRA or not with the current implementation as it will try to push DoRA value anyway. What do you think about protecting PEFT from DoRA setting then? Or maybe push the PEFT requirement up.

**Comment by NorilskMajor** [comment]
Created 5a52a63afd5675e4ed60cba35e5091e123109b23 commit for demonstation of version checking error throw.

**Comment by sayakpaul** [comment]
Since it's a very simple option (just install `peft` from the `main`) I don't think we should complicate it any further.

**Comment by NorilskMajor** [comment]
Alright, I'll close the PR!

**Pull request closed without merging**
