### PR TITLE
improve setup.py

### PR DESCRIPTION
**Pull request by sayakpaul**

### CODE REVIEW

**Review by patrickvonplaten — APPROVED** [review]
Cool!

**Comment by sayakpaul** [comment]
What's wrong with the failing test? :o

**Comment by patrickvonplaten** [comment]
Seemed to have started here: https://github.com/huggingface/diffusers/actions/runs/5958506576/job/16162831889 but the merged PR was surely not the problem. Could you maybe try to figure out how to fix it? (happy to do it otherwise)

**Comment by sayakpaul** [comment]
Working on https://github.com/huggingface/diffusers/issues/4208.

**Comment by sayakpaul** [comment]
Wait. Just ran the failing tests locally and they passed. Looking into. Probably some versioning stuff.

**Comment by sayakpaul** [comment]
Seems like an accelerate version problem, @patrickvonplaten. Works with `accelerate==0.21.0`.

**Pull request merged**
