### PR TITLE
Fix Wrong Text-encoder Grad Setting in Custom_Diffusion Training

### LINKED ISSUE #7294: Wrong Text-encoder Grad Setting in Custom_Diffusion
### Describe the bug

According to [Custom Diffusion](https://arxiv.org/pdf/2212.04488.pdf), It only trains modified tokens. In implementation, it set the grad of non-modified tokens to zero. But there is a bug in this implementation.

https://github.com/huggingface/diffusers/blob/531e719163d2d7cf0d725bb685c1e8fe3393b9da/examples/custom_diffusion/train_custom_diffusion.py#L1180-L1187

In 

https://github.com/huggingface/diffusers/blob/531e719163d2d7cf0d725bb685c1e8fe3393b9da/examples/custom_diffusion/train_custom_diffusion.py#L1183

it should be 

`torch.arange(len(tokenizer)) != modifier_token_id[i + 1]`

as the variant 'i' starts from 0.

Consequently, the last concept would not be trained if you want to train multiple concepts(It works well when single concept training).

Should I open a PR to fix that? 

### Reproduction

export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export OUTPUT_DIR="./ckpt"

accelerate launch train_custom_diffusion.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --output_dir=$OUTPUT_DIR \
  --concepts_list=./concept.json \
  --resolution=512  \
  --train_batch_size=2  \
  --learning_rate=1e-5  \
  --lr_warmup_steps=0 \
  --max_train_steps=500 \
  --scale_lr \
  --hflip  \
  --modifier_token "<new1>+<new2>" \
  --no_safe_serialization \

### Logs

_No response_

### System Info

diffusers :0.27.0.dev0

### Who can help?

@sayakpaul @DN6 @yiyixuxu

### PR DESCRIPTION
**Pull request by Rbrq03**
# What does this PR do?

This PR fixs the wrong text-encoder grad setting in custom diffusion training

Fixes #7294  (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [x] Did you read the [contributor guideline](https://github.com/huggingface/diffusers/blob/main/CONTRIBUTING.md)?
- [ ] Did you read our [philosophy doc](https://github.com/huggingface/diffusers/blob/main/PHILOSOPHY.md) (important for complex PRs)?
- [ x] Was this discussed/approved via a GitHub issue or the [forum](https://discuss.huggingface.co/c/discussion-related-to-httpsgithubcomhuggingfacediffusers/63)? Please add a link to it if that's the case.
- [ ] Did you make sure to update the documentation with your changes? Here are the
      [documentation guidelines](https://github.com/huggingface/diffusers/tree/main/docs), and
      [here are tips on formatting docstrings](https://github.com/huggingface/diffusers/tree/main/docs#writing-source-documentation).
- [ ] Did you write any new necessary tests?

## Who can review?

Anyone in the community is free to review the PR once the tests have passed. Feel free to tag
members/contributors who may be interested in your PR.

@sayakpaul

### CODE REVIEW

**Review by sayakpaul — APPROVED** [review]
Thank you!

**Comment by sayakpaul** [comment]
Please ping me once the CI suite is complete.

**Comment by Rbrq03** [comment]
@sayakpaul hey saya, CI suite is complete.

**Comment by sayakpaul** [comment]
Thank you!

**Pull request merged**
